### ISSUE TITLE
Travis doesn't always recognise PRs which leaves them blocked and unmergable

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#1002]
### Summary

Travis doesn't always pick up when new PRs have been opened on the repo, this leaves the PR unmergeable since the test never runs/passes. I think this is more to do with GitHub not sending the correct notification to Travis as per this issue: https://github.com/travis-ci/travis-ci/issues/7643

We are seeing this a lot with PRs opened by the all-contributors bot, for example #1001 

I've notified @ots22 as our Researcher Tool Management Service Area contact.

### What needs to be done?

**EITHER:**
- [x] Follow up with GitHub Support, see if the `alan-turing-institute` org or `the-turing-way` repo is blocked in anyway

**OR:**
- [ ] Consider a different CI vendor to Travis
  - https://github.com/netlify/actions

### Who can help?

* @ots22 

---

**Comment by ots22** [comment]
Support request sent

**Comment by ots22** [comment]
> Hi there Oliver,
> 
> Thanks for writing in and I'm sorry for the time taken for us to get back to you!
> 
> Hmm, I had a look at https://github.com/alan-turing-institute/the-turing-way/pull/1001, the pull request linked in @sgibson91's issue. Our logs show that the webhook did trigger and send the payload to Travis CI.
> 
> I suspect the issue is 
> [skip ci] in all the commit messages. Looking at Travis CI's documentation, this will cause them to skip the build:
> 
> https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
> 
> If that's not the reason, can you try speaking to Travis CI's support team? As I mentioned, the webhooks are being triggered, and hopefully Travis CI would see those in their logs and be able to explain why these aren't triggering a build.
> 
> Let me know how you get on and don't hesitate to ask if you have any questions.
> 
> Thanks,
> Steve

**Comment by sgibson91** [comment]
Thanks @ots22! Looks like there's something in our all-contributors config that has defaulted the commits to skip-ci. Something to investigate!

**Comment by sgibson91** [comment]
This looks like a default setting https://github.com/all-contributors/all-contributors-bot/pull/216

**Comment by sgibson91** [comment]
This line implies that we have the feature turned off though? https://github.com/alan-turing-institute/the-turing-way/blob/d6fac9f55e610c1a5fb0201240a12c57c43d8a9d/.all-contributorsrc#L8 I think we may need to move this question to the all-contributors repo
