### ISSUE TITLE
Governance: Create policy for authorship and contribution credits

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1034]
### Summary

* How can we fairly recognise contributions of people?

### What needs to be done?

- [x] Compile the scenario where this idea is applicable and what rewards can we think of
- [ ] Invite different solutions from the community
- [ ] Create a policy that aligns with the values of team and community members

### Who can help?

* @KirstieJane 
* Community members

**Comment by malvikasharan** [comment]
### Scenarios

- Bug and typo fixes
- Chapter review
- Chapter Contribution
- A team effort on subprojects (translation, multiple chapters, contributions from the workshop)
- Advisory or maintenance roles
- representing Turing Way at an event or community

**Comment by malvikasharan** [comment]
## Types of Rewards

- Designated roles within the community leadership
  - To be defined within the governance
- Acknowledgement for their work
  - A dedicated area in the repo for acknowledgement and fair credits 
  - All contributors bot badging for different writing/editing contributions 
- If funding can be allocated - access to small support grant
- If intending to represent Turing Way at an event - travel cost

**Comment by malvikasharan** [comment]
### General Governance

- How people join the community (Roles: Who welcomes them, where?)
  - How: Chapter related contributions - Author, reviewers, bug and typo reporter, bug and typo fixer, issue raiser, idea contributors, idea realiser/leader, sustained contributor
  - Who welcomes them? - Core members, existing members
  - Where? - Gitter, Book Dash, Collaboration Cafe, Twitter, personal interaction with other members, event talks, conferences, media resources

- How do they access infrastructure (Roles: What are the infrastructure? Who helps them learn? Who helps them troubleshoot?)
  - What infrastructures?: GitHub, JupyterHub, Netlify design, CI, Transfex, Gitter, Twitter
  - Who helps them: Core members, existing members, new members - no roles designated so far except for self-assumed task leadership
 
- What are community-wide policies? (Roles: Who proposes, writes and approves them?)
  - Current policies: CoC, Contributing guideline, governance, License
  - Who proposes and writes: Core members, existing members, new members - no roles designated so far
  - Approval: Core team

**Comment by malvikasharan** [comment]
## Steering and direction of the project

- decisions about goals, ambition and focus of the project and community
  - leadership - the core team members
  - ideas for designated members: (Will brainstorm with @KirstieJane)

### Next steps and priorities
- How are they decided? 
- Who decides them? 
- How can we involve community members? (e.g. Community leadership, steering or technical advisory committee, Code of Conduct or community policy committee, task leads, subproject leads, maintainers, etc.)

**Comment by KirstieJane** [comment]
Thanks @malvikasharan - and most importantly - I'm sorry that it has taken me so long to add my thoughts on this point. I spend a lot of my time frustrated about the lack of attention that other projects spend on governance & appreciating their community members so it's super hypocritical for me to not have put this in the [GOVERNANCE.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/GOVERNANCE.md) document already. Sorry folks 😩 

---

In GOVERNANCE.md at the moment we have a good policy for covering contribututions and individual authorship I think. What we *haven't* done - which is honestly something I wake up in the night feeling terrible about - is uploaded the versions of the book to zenodo to actually *implement* the policy.

In short: substantial contributions make you an author, I decide what substantial means (we can adapt that to a governance team in the future..... or now?) and literally anything at all (above zero) where you consent to being acknowledged in the repository makes you a contributor.

What we're missing though is a way to disagregate all the authors and all the contributors - not all authors have contributed the same amount to the project and it would be good to highlight their work much better than we are doing at the moment.

We're also missing ways to acknowledge teams.

The idea I've always had is that each *author* - and each team / organisation has a paragraph about their contributions to the project in a file called community members. 

Let me do a few examples here (all names taken from [Quick Name Generator](https://www.name-generator.org.uk/quick/))

### Bug and typo fixes

Fraya found a typo and fixed it. She is acknowledged in the Contributors table with a 🐛 emoji.

Amalie has found multiple typos on multiple visits to the project and contributes to conversations in issues about where these typos cause confusion or need additional input to fix. She has had sustained engagement with the community and are acknowledged in the Contributors table with a 🐛 and a 🤔 emoji, and she is named as an author on the last 2 releases of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Amalie Fenton has participated in the Turing Way community since December 2019. She has fixed typos and identified sections of the book that are unclear.
> * Key contributions: `#555` `#556` `#557` (list of PRs) 
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

### Chapter review

Tashan has reviewed a pull request that contributed one additional paragraph to an already existing chapter. They approved the pull request after catching two typos and giving a suggestion for a clearer phrasing of one sentence. They are acknowledged in the Contributors table with the :eyes: emoji.

Hareem has reviewed a new chapter on "Secure communication for distributed teams". She gave critical feedback on the structure of the proposed text and suggested a new format. She was engaged for multiple reviews of the same pull request and engaged closely with the community member who wrote the chapter. She is acknowledged in the Contributors table with the :eyes: and :thinking_face: emojis, and she is named as an author on the last release of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Hareem Mustafa has participated in the Turing Way community since February 2020. She reviewed and contributed to the structure and content of the "Secure communication for distributed teams" chapter.
> * Key contributions: `#555` (the PR in which the review happened)
>   * https://the-turing-way.netlify.com/collaboration/secure-comms (published chapter)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

### Chapter contribution

Jordon has written a chapter on "Setting expectations across academia and industry". He started writing the chapter at a Turing Way Book Dash event, based on an idea he had developed in advance of the event. At the event he collaborated with Ishan and they brainstormed the chapter together. After the event Jordan completed the chapter and submitted it as a pull request to the Turing Way. Jordan responded to review comments and iteratively improved the chapter until the pull request was merged. Ishan didn't have time to continue working on the chapter and so was not part of the review process.

Jordon is acknowledged in the Contributors table with the 🖊️ and :thinking_face: emojis, and he is named as an author on the last release of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Jordon Evans has participated in the Turing Way community since February 2020. He participated in the Turing Way Book Dash event in London in February 2020. Jordon designed and wrote a chapter on "Setting expectations across academia and industry". 
> * Key contributions: `#555` `#556` (the issue where the chapter was designed and PR where the chapter was added)
>   * https://the-turing-way.netlify.com/project-design/expectations-academia-industry (published chapter)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

Ishan is acknowledged in the Contributors table with the :thinking_face: emoji, and he is named as an author on the last release of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Ishan Wolfe has participated in the Turing Way community since February 2020. He participated in the Turing Way Book Dash event in London in February 2020. Ishan contributed to the design of the chapter on "Setting expectations across academia and industry" at the Book Dash event. 
> * Key contributions: `#555` `#556` (the issue where the chapter was designed and PR where the chapter was added)
>   * https://the-turing-way.netlify.com/project-design/expectations-academia-industry (published chapter)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

### Translation

Anika has translated 3 paragraphs of the version control chapter into Swedish following the standard process defined in The Turing Way repository. She is acknowledged in the Contributors table with the :earth_africa: emoji.

Jamil has translated the version control chapter into Arabic following the standard process defined in The Turing Way repository. He is acknowledged in the Contributors table with the :earth_africa: emoji, and he is named as an author on the last release of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Jamil Huff has participated in the Turing Way community since March 2020. He has translated the chapter on "Version control" into Arabic.
> * Key contributions: `#555` (the PR in which translated chapter was added)
>   * https://the-turing-way.netlify.com/ara/reproducibility/version-control (published chapter)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

Zavier has designed the process for managing translation of The Turing Way into multiple languages. They have worked closely with a core team of contributors who are translating the book into multiple languages and have mentored their contributions. Zavier has translated three chapters into Spanish. He is acknowledged in the Contributors table with the :earth_africa:, :thinking_face: and :metro: emojis, and he is named as an author on the last two releases of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Zavier Hopkins has participated in the Turing Way community since December 2019. He designed and implemented a process to translate the book into multiple languages. Zavier has mentored multiple contributors within the community and has translated chapters of The Turing Way into Spanish. 
> * Key contributions: `#555` `#556` `#557`  (issues and PRs where translations and details of how to translate are added)
>   * https://the-turing-way.netlify.com/handbook/translation (guide for translation)
>   * https://the-turing-way.netlify.com/esp/reproducibility/testing (translated chapter)
>   * https://the-turing-way.netlify.com/esp/reproducibility/version-control (translated chapter)
>   * https://the-turing-way.netlify.com/esp/reproducibility/continuous-integration (translated chapter)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

### Organisational support

The Narnia National AI Institute (NNAII) has shared their internal guidance on communicating safe and ethical artificial intelligence to The Turing Way. The chapters were written by a team of people within NNAII and converted into pull requests that fit The Turing Way style guide. the NNAII is acknowledged as a "Collaborating organisations" in the README file of The Turing Way repository and there is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) that describes how and why the NNAII has supported The Turing Way.

Abby is one of the members of the NNAII who contributed to the guidance before she left to join a non-profit last year. The NNAII team got in touch with her to ask her permission to be named and when she said yes she was added to the Contributors table with the 🖊️ emoji.

Eric still works at the NNAII and worked to reformat the guidance into The Turing Way book structure. He is acknowledged in the Contributors table with the 🖊️ and :thinking_face: emojis, and he is named as an author on the last release of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Eric Prentice has participated in the Turing Way community since November 2019. He worked with a team at the Narnia National AI Institute to convert their internal guidance on communicating safe and ethical AI into three chapters within The Turing Way. 
> * Key contributions: `#555` `#556` `#557`  (issues and PRs where chapters were added)
>   * https://the-turing-way.netlify.com/comms/citizen-juries 
>   * https://the-turing-way.netlify.com/comms/ethics-vs-justice
>   * https://the-turing-way.netlify.com/comms/inclusive-design-workshops
> * Collaborating organisations: Narnia National AI Institute
>   * https://the-turing-way.netlify.com/handbook/collaborating-organisations
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

Kadie is a programme director at the NNAII who manages the team that wrote the guidance that has been incorporated into The Turing Way. She is acknowledged in the Contributors table with the :dollar: emoji. Kadie was asked if she would like to be an author on the most recent release of the Turing Way book but declined as she did not personally feel that she had contributed enough to be named as an author.

### Maintenance

Neve has helped two contributors on two individual occasions by responding to a question on the Turing Way gitter channel and a question on one of the issues in the Turing Way GitHub repository. He is acknowledged in the Contributors table with the :speech_balloon: emoji.

Ursula regularly answers questions on Gitter and in the Turing Way issues. She points new contributors to documentation and submits pull requests to improve the guidance when she sees areas that are unclear. She reviews pull requests from others working to make the process of contributing smoother. She is acknowledged in the Contributors table with the :speech_balloon:, :thinking_face:, :eyes: and :construction: emojis, and she is named as an author on the last two releases of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Ursula Farrell has participated in the Turing Way community since December 2019. She regularly answers questions and updates the contributing guidelines to ensure it is easy for new community members to get involved. Ursula has mentored multiple contributors within the community and has reviewed pull requests to fix typos in the book. 
> * Key contributions: `#555` `#556` `#557`  (issues and PRs where major work has been contributed)
>   * https://the-turing-way.netlify.com/handbook/contributing (contributing guidelines)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

### Representing the Turing Way

Yehuda used one of the Scriberia and The Turing Way illustrations in a recent talk they gave at a open source workshop that was hosted by their company. They included links to The Turing Way book, GitHub repository and twitter handle. Their slides available under a CC-BY license and are linked from a page in the community handbook. They are acknowledged in the Contributors table with the :loudspeaker: emoji.

Noah is a long time contributor to The Turing Way, they answer questions and review pull requests on a regular basis. In March 2020, Kirstie - lead developer of The Turing Way - recommended Noah as a suggested speaker to give a talk about the Project Design section of The Turing Way at a conference on open source community management. She worked with Noah to practice his presentation in advance of the talk. Noah's slides are available under a CC-BY license and are linked from a page in the community handbook. They are acknowledged in the Contributors table with the :loudspeaker:, :construction:, :eyes:, :thinking_face: and :speech_balloon: emojis, and they will be named as an author on the next release of the book. There is a section of the `CONTRIBUTORS` file (or a chapter in the community handbook?) saying:

> Noah Vo has participated in the Turing Way community since October 2019. They regularly answer questions and submit and review pull requests to fix broken links or make sure the book remains coherent as the content expands. Noah has mentored multiple contributors within the community and has given talks on behalf of the community. 
> * Key contributions: `#555` `#556` `#557`  (issues and PRs major work has been contributed)
>   * https://the-turing-way.netlify.com/handbook/talks (list of talks about The Turing Way)
> * ORCID: 1234-1234-1234-1234
> * More information: `personal-website-goes-here`

---

There's one hill that I'll almost certainly die on - it would take a very concerted effort from the community to have me shift on this - which is that I don't want authorship (including organisational) on individual chapters. Here's a paragraph about that to go in the governance doc (or at least to start us off!)

> _The Turing Way_ is a _lightly opinionated_ handbook for data science. There are a lot of points that are open for discussion and we will embrace nuance and context as best we can. There is one point however that Kirstie - the lead developer of _The Turing Way_ - feels very strongly about: no individual authorship on chapters.
>
> Her opinion is that individual authorship - even if we employ a very inclusive policy - puts boundaries around ownership of the text. It psychologically breaks up the book and makes it much harder for content to be edited, moved and otherwise adapted as the book grows. Authorship implies ownership and has historically missed important work around answering questions, representating the project, infrastructure and all those nurturing roles that make The Turing Way community so special. Individual or organisational authorship doesn't scale - the decisions around who to add to each chapter and when will - in the limit - converge to the answer we have now: everyone who contributes substantially are all authors on the book as a whole.
>
> We hope that the authors page where individuals can identify the work they've done allows people to show the work that they have completed, without trying to fit _The Turing Way_ into a traditional credit system. If you'd like to talk more with Kirstie about this please get in touch. She is firm on this point but not immovable, and she is very interested in recognising the contributions from _Turing Way_ community members and the organisations who support them. Just not in the traditional author-list format.
