### ISSUE TITLE
Collect items for June newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#1037]
### Summary

This is an issue to capture any updates for the June newsletter

### What needs to be done?

- [x] Share your updates! Events, celebrations, other opportunities, merged PRs etc!

### Who can help?

* Anyone 💖 
* Anyone who wants to promote their event
* Anyone who has included material from The Turing Way in a talk / presentation / project etc

**Comment by KirstieJane** [comment]
Really nice link to Mozilla Open Leadership and highlighting lovely use of scriberia images by @EstherPlomp: https://openworking.wordpress.com/2020/05/20/movement-building-from-home-a-participant-view/

**Comment by malvikasharan** [comment]
Share this preprint: WORCS: A Workflow for Open Reproducible Code in Science: 
https://psyarxiv.com/k4wde

**Comment by pherterich** [comment]
@nadiasoliman is giving a shoutout again (I think - I'm not watching this one...) https://twitter.com/riotscienceclub/status/1268506427355734016
