### ISSUE TITLE
Update storage and backup section in RDM chapter

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1039]
# Summary

I'm trying to add some more examples for data organisation in this section to make it even more practical. 

Additionally, the title storage and backup doesn't cover the data organisation/file naming, so it could probably use an update. 

And I would like to refer to another section in this chapter, but that should probably be done after the massive changes in the structure of the book.

### What needs to be done?

- [ ] If you have any clear data management organisation examples that people can just copy, hop on!
- [ ] 

### Who can help?

* *Anyone willing to share their examples or their own data folder structures
* *

---

**Comment by malvikasharan** [comment]
Thank you for the issue @EstherPlomp. We have a file here: https://deploy-preview-977--the-turing-way.netlify.app/communication/filenaming.html. We will be able to link to this in the RDM chapter as soon as we have upgraded to the new format.
