### ISSUE TITLE
Standard way to link to sections/chapters in the book

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1040]
### Summary

To prevent duplication and dead links it would be very helpful to have a standardised way to link to sections in the book.

This should probably be established after the major changes in the structure of the book.

### What needs to be done?

- [ ] Define a standard way to link to sections/chapters in the book after the restructuring of the book
- [ ] Implement this throughout the book

### Who can help?

* *Anyone that has more knowledge on how to implement relative/dynamic links in the book. 

---

**Comment by malvikasharan** [comment]
I am gonna look into it now. We can add this in the ocntributing guideline.

**Comment by malvikasharan** [comment]
We can keep it open after the next update is done.

**Comment by EstherPlomp** [comment]
No that was exactly what I was looking for! Looking forward to try it out :) I think we can close the issue now.

**Comment by malvikasharan** [comment]
@EstherPlomp: Please check out the Style guide in the community handbook for details: https://the-turing-way.netlify.app/community-handbook/style/style-citing.html
