### ISSUE TITLE
New chapter/section on Data Management Plans (Project Design chapter or RDM section)

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1043]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter or section on data management plans, as part of a separate chapter for Project Design or part of the Research Data Management chapter. 
 * This chapter is being written in https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/rym-ZyrO8/edit, please join in if you love or hate data management plans :) 

## Current status
This chapter is still empty. You can contribute by:

 - [x] Write chapter outline
 - [x] Add material to the chapter
 - [x] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by growupboron** [comment]
@EstherPlomp If you can have a look of PR #1076, where I expanded the ` ` `Checklist for managing and participating in a distributed team` ` `
