### ISSUE TITLE
Community: The Turing Way coworking hours: Dates and time added weekly

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1049]
### Summary

* Short coworking hours each day 11:00 - 12:00 BST

### What needs to be done?

- [x] Assess by running each day of this week and assess interest from the community
- [ ] Please respond below if you are interested to join!

### Who can help?

* Anyone interested in joining to work together
* Collaborative document: https://hackmd.io/@malvikasharan/TW-coworking

---

### Updates

* We will update!

**Comment by sgibson91** [comment]
This works for 3/5 days for me next week

**Comment by adswa** [comment]
I would like to join, this would work Tue and Wed next week for me. :)

**Comment by martinagvilas** [comment]
it would be awesome to join as well 💻  not sure about the days yet though!

**Comment by malvikasharan** [comment]
Great! I will ping a document to add your names and get the Zoom link :)

**Comment by malvikasharan** [comment]
Here is the shared document: https://hackmd.io/@malvikasharan/TW-coworking
Go ahead an add your name under the dates that work for you.

**Comment by adswa** [comment]
I think I'm confused, I *thought* it is today, at this time, in the zoom conference room shared in the hackMD? If something is happening at the moment, could someone send me the correct Zoom link? :)

**Comment by sgibson91** [comment]
From the looks of the hackmd, I think you were the only person available to participate today @adswa. Sorry about that :(

**Comment by malvikasharan** [comment]
That's strange. I was online at the hour.

**Comment by adswa** [comment]
I'm still online in the call, so maybe in a wrong zoom room?

**Comment by malvikasharan** [comment]
@all-contributors please add @adswa for content.

**Comment by malvikasharan** [comment]
Updated the notes with today's discussion. Thank you @adswa and @tonyyzy 🎉🙌

**Comment by martinagvilas** [comment]
Hi, I won't be able to join today unfortunately, but will keep you posted with the jupyter-book update and the redirect issue 🚀

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
