### ISSUE TITLE
Global issue search for distributed issue repos

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/the-turing-way#1065]
### Summary

The [issue tracking](https://github.com/alan-turing-institute/the-turing-way/edit/master/book/content/open-source-comms/issue-tracking.md) table shows that "Global issue search" isn't possible for distributed issue repos:

| Feature | Centralised Issue Repo | Distributed Issue Repos |
| :--- | :---: | :---: |
| Global issue search | ✅ | |
| Hosted by the same platform as the code | ❓(not guaranteed) | ✅ |
| Filter by repository | ❓(power users*) | ✅ |
| Suscribe to relevant updates | ❓(power users) | ✅ |
| Easy to Discover | | ✅ |
| Connected to the Codebase | | ✅ |
| Appears active to community | | ✅ |
| Manageable volume | | ✅ |

We might be missing the case where you have an umbrella group then many child repositories, each child with its own issue set. I can't speak for github, but for gitlab this definitely is possible. You can have a structure like:

```
Group/
  repo-a
  repo-b
```

When you go the board for `Group` you can search through issues from both `repo-a` and `repo-b`.

### What needs to be done?

1. Check whether github has this feature
2. If so, think about updating to 

| Feature | Centralised Issue Repo | Distributed Issue Repos |
| :--- | :---: | :---: |
| Global issue search | ✅ | ✅** |

** With use of repository groups (or a similar explanation)

### Who can help?

* @masonlr 

---

**Comment by growupboron** [comment]
@masonlr Yes it is quite possible. Going to [Github Issues](https://github.com/issues) **the user must be logged into Github to access Github Issues. Searching ```is:open is:issue org:alan-turing-institute``` in the Gihub Issues yields all the open issues in "The Alan Turing Institute".
 
![Screenshot from 2020-05-12 15-45-32](https://user-images.githubusercontent.com/41593068/81672400-b9ebc480-9467-11ea-99bf-ba3c472915d0.png)

**References : [Search within a user's or organization's repositories](https://help.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-within-a-users-or-organizations-repositories)**

**Comment by sgibson91** [comment]
Hey @masonlr, the point of this chapter isn't a how-to but rather exploring how easy it is for new contributors to onboard themselves to a project, and the fact that using a different platform can be an unexpected roadblock in this process. @growupboron is right that globally searching issues on orgs (distributed repos) is possible, but I would consider this, and your GitLab example, a power-user method. Such that, the users have to be familiar enough with the platform to know that that is a method they could use, which just reinforces the point that using a different platform for issue tracking versus code storage is detrimental to building a healthy community.

Would you rather suggest a question emoji in that space?

**Comment by masonlr** [comment]
@sgibson91 are you okay with "❓(power users)" ?

Some of this confusion might be because "using a different platform" is a different concept to "Centralised Issue Repo". For example Asana isn't really a "Repo" but is discussed in the "Centralised Issue Repository" section and implied in the "Centralised Issue Repo" table column.

The "different platform" concept means that there are more options:

1. A project could have centralised issues on a different platform (eg. Asana).
2. A project could have centralised issues on the same platform (eg. https://github.com/typora/typora-issues is a centralised issue-only respository for the Typora project).
3. A project could use a decentralised system with issues posted directly to sub-project repositories.

If a project chooses option 3, organic/bottom-up discoverability is maintained and global/top-down issue search is still possible without leaving the GitHub platform (assuming that the project is a GitHub organisation).

It's not intended but "If your issues are elsewhere" sounds decentralised. Could we make this clearer by changing

> However in terms of engaging your community, such a centralised system can be problematic. If your issues are elsewhere this can create a lot of barriers to entry for community members, such as:

to:

> However in terms of engaging your community, such a centralised system can be problematic. If your issues are centralised this can create a lot of barriers to entry for community members, such as:

**Comment by sgibson91** [comment]
> @sgibson91 are you okay with "❓(power users)" ?

Yep! 👍 

> The "different platform" concept means that there are more options:
> 
> 1. A project could have centralised issues on a different platform (eg. Asana).
> 2. A project could have centralised issues on the same platform (eg. https://github.com/typora/typora-issues is a centralised issue-only respository for the Typora project).
> 3. A project could use a decentralised system with issues posted directly to sub-project repositories.

Yes, option 1 is what I had come across and found it particularly uninviting.

> > However in terms of engaging your community, such a centralised system can be problematic. If your issues are centralised this can create a lot of barriers to entry for community members, such as:

Yes, I like this. Thank you for your time thinking about this! 😊

**Comment by malvikasharan** [comment]
This has been sorted.
