### ISSUE TITLE
A better position for Acronyms

### ISSUE THREAD

**Issue by iiitmjay** [alan-turing-institute/the-turing-way#1086]
**Acronyms** are used to eradicate the overburden problem of writing the full forms repetitively. But at the same time we should not forget to mention their full forms at one location when we are using more number of acronyms.  
## Issue: ( also discussed in #1085 )
*  Misunderstanding with some other full forms with same acronyms.
*  Mentioning the full form as a footnote for the same acronym again and again
*  Hectic work for reader to search if not found at one centralized location 

## What needs to be done?
All the acronyms used in the book should have their full forms at one centralized location so that it will be esier for maintainers as well as readers too.

**Comment by malvikasharan** [comment]
@iiitmjay I am repeating myself from the last issue: 

> Hi @IIITM-Jay, Thanks for opening an issue.
> 
> A standard way of using acronym is "Always write out the first in-text reference to an acronym, followed by the acronym itself written in capital letters." ([see reference](https://www.e-education.psu.edu/styleforstudents/c2_p9.html)). This is what we use in most scientific writing and hence in the book. Therefore I don't agree that we need to get rid of the acronyms.
> 
> Regarding a central location for the acronyms, I think that's a good idea and can be potentially added in a new section within the glossary chapter: https://the-turing-way.netlify.app/glossary/glossary.html. Would you like to give it a go?
