### ISSUE TITLE
Adding an "Average Time Read" tag in all chapters.

### ISSUE THREAD

**Issue by Yash-Varshney** [alan-turing-institute/the-turing-way#1090]
### Summary
Instead of scrolling through the whole page to look out for the length of the chapter, a tag should be created just below every chapter's title to tell the amount of time it takes to read the whole chapter.
It should look like `10 min read`.

### What needs to be done?

- Related article to read - [Read Time and You](https://blog.medium.com/read-time-and-you-bc2048ab620c)

- Calculating the word count of the whole chapter and dividing it by average read time and adding 12 seconds for every image should work.

- Also, adding it to the chapter template so that writers can tell the audience beforehand about the length of the chapter.

**Comment by erictleung** [comment]
Here's a quick rough bash script to find total minutes based on words. 275 came from that blog you linked.

```shell
function esttime() {
  wc -w $1 | awk '{ printf "%.0f min read\n", $1/275 }'
}
```

So to estimate time for a file `example.md`, you'd run the following

```shell
$ esttime example.md
14 min read
```

This could also help as a GUI http://www.niram.org/read/

**Comment by malvikasharan** [comment]
Thanks @Yash-Varshney and @erictleung. Where do you this step can be suggested in the writing process? Also, I think this might need to rerun after each edit/review process.  Is there an idea of if this can be automated in the CI or would this be something an author would need to do manually?

**Comment by Yash-Varshney** [comment]
@malvikasharan, the cmd code by @erictleung looks perfect to use. This step should be just below the main heading of the article. Also, another thing to look up is that we have subsections in a chapter, so should the `average read time` be of every sub-section specifically or of the whole chapter only? 
Regarding the automation of CI, I am not well aware of that now but there has to be some way to do it automatically but the task of doing it manually isn't that long, and easily doable. But automation should be the first priority :)

**Comment by harisood** [comment]
Hello from 2023 @Yash-Varshney! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to the chapter template issue (#1243) referenced in our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
