### ISSUE TITLE
Broken links in README.md inside the /book directory

### ISSUE THREAD

**Issue by IIITM-Jay** [alan-turing-institute/the-turing-way#1092]
## Bug description
- [ ] The link under the subsection **Configuration** under *README.md* file inside `/book` is not turning up
- [ ] Incorrect path for searching out figures written on the top as `website/assets/figures/`

## Expected behaviour
- [ ] The link should be redirected to correct web page
- [ ] The path for figures should be corrected

##  personal set up
- OS:
- [x] Linux

- Browser:
- [x] Chrome
- [x] Firefox

**Comment by IIITM-Jay** [comment]
Fixed. @malvikasharan .

**Comment by malvikasharan** [comment]
Thanks for the PR @IIITM-Jay. I have approved your PR with some suggestions. Is it safe to close this issue?

**Comment by IIITM-Jay** [comment]
Ok, no problem @malvikasharan . I will submit a new PR with the new changes so proposed.

**Comment by IIITM-Jay** [comment]
@malvikasharan this issue still require something and if so then please let me know.
