### ISSUE TITLE
Include citation to "10 Simple Rules" paper for Dockerfiles in the Comp Env/Docker chapter

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#1095]
### Summary

@nuest, @betatim and friends have a pre-print of a 10 simple rules for Dockerfiles for reproducible research that we should cite somewhere in our computational environments/docker chapter

### What needs to be done?

- [ ] Add reference to the below paper

> Nüst, D., Sochat, V., Marwick, B., Eglen, S., Head, T., & Hirst, T. (2020, April 17). Ten Simple Rules for Writing Dockerfiles for Reproducible Data Science. https://doi.org/10.31219/osf.io/fsd7t

### Who can help?

* Anybody!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by Sylfrena** [comment]
Hi,

I would love to make a PR for this. Can I go ahead?

**Comment by sgibson91** [comment]
Hey @Sylfrena! Go ahead!
