### ISSUE TITLE
Decide what material to include in Reproducibility vs Open Science chapters

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#110]
The Reproducibility and Open Science chapters have the potential to cross over. We need to decide which topics will be covered  in which chapter in order to write them as efficiently as possible. This crosses over with #101 and #73.

**Comment by r-j-arnold** [comment]
Hi @pherterich! Here's my thoughts on this.

I was thinking the reproducibulity chapter should be the first chapter in the book and act as a kind of preface/introduction just defining what reproducibility is and why it's important. I'm thinking we keep the "how to do it" and best practise information very light because the textbook's "the how to guide for reproducible data science" after all, everything in it could be put there.

One thing we could do is:

- This is what reproducibility is
- This is why it's important
- "Things that can improve the reprocucibility of your work include" and then follow this up with a list of the chapter topics and a single sentence summary of what they are and how they improve reproducibility, e.g
  - Version Control: Keep track of all past versions of your project so past results can be recovered and checked.
  - Open science: Make your research publicly available so it can be checked and re-used by others.

Now obviously this is your chapter so feel free to overrule me on this, but does this sound ok to you?

**Comment by pherterich** [comment]
With both drafts being available now, do you think we managed @r-j-arnold ? Maybe close this one and open separate issue(s) for just the Open Science chapter or subcategories depending on how you feel comments on #140 are best addressed?

**Comment by r-j-arnold** [comment]
Hey, yep, good to close, I'll do that now. I think if we decide to move stuff between the chapters later we can open issues about that then.
