### ISSUE TITLE
Writing the subchapter "Data Licenses"

### ISSUE THREAD

**Issue by IIITM-Jay** [alan-turing-institute/the-turing-way#1107]
## Summary
As I have started writing on the subchapter *"Data Licenses"*, want the valuable feedbacks and suggestions. I am thinking to include the following subsections under it.
## Subsections:
 1.**Intoduction**(_a type of short summary within 5-6 lines and a flow chart to be more clear_) that discusses the following:
 * Why to use Data Licenses
 * What are Data Licenses
 * A flow chart to describe various scenarios where these are applicable
 
 2. **License Creation,Adaptation and Termination** that discusses the following:
 * How to use these licenses in your own document
 * How to use other's licensed material
 * What are the consequences of termination and violating the laws abide by them
 
 3.**An extensive use of Data Licenses in Aritificial intelligence(AI)**
 
 4.**An extension to "BIG DATA SCIENCES"**
 
 5.**A Case Study**
 
 ## Work done so far
 - [x] **Intoduction**
 - [x] **License Creation,Adaptation and Termination**
 - [ ] **An extensive use of Data Licenses in Aritificial intelligence(AI)**
 - [ ] **An extension to "BIG DATA SCIENCES"**
 - [ ] **A Case Study**
 
 ## Updates (Work done can be viewed on the following subsection links)
 * [Introduction](https://github.com/IIITM-Jay/Data-Licenses/blob/master/introduction.md)
 * [License Creation,Adaptation and Termination](https://github.com/IIITM-Jay/Data-Licenses/blob/master/branches.md)
 * Working on remaing three subsections **[WIP]**

**Comment by IIITM-Jay** [comment]
@malvikasharan I have started writing. Waiting for your valuable guidance and suggestions.

**Comment by malvikasharan** [comment]
Hi @IIITM-Jay, I don't have any comment on this. Please go ahead and add your content which I will ask other members to review.

**Comment by IIITM-Jay** [comment]
@malvikasharan can you please share the branch for Data Licenses

**Comment by IIITM-Jay** [comment]
@malvikasharan it's fine if will do the PR in a day or two as I have to add case studies also. sorry for inconvenience.

**Comment by malvikasharan** [comment]
Hey @IIITM-Jay, there is no hurry and so no need to be sorry (also no inconvenience caused).

**Comment by IIITM-Jay** [comment]
@malvikasharan done the PR at #1168 .

**Comment by IIITM-Jay** [comment]
@malvikasharan the reason behind closing the PR is the issue of images I have included in my content. Although I am done with my content but the images are not visible in netlify but though the tables are. This is so because I have to first do a PR of all images which should get merged first only then I can able to link those with correct path and can be viewed on netlify.
For the time being it can only be viewed when we click on `view file` with all the images and associated contents but it doesn't make any sense to do the PR of images prior it gets finalized to be included in the book.
Need help on the same.
