### ISSUE TITLE
[BUG] Placeholder text for search bar on website contains an extra apostrophe

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#1114]
### Bug description

- At [the search page on the website](https://the-turing-way.netlify.app/search.html) the placeholder text currently reads: ``` 'Enter your search term.```
- I suspect that the apostrophe at the start is unintended.
- Looking at the [code which generates this text](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/assets/html/search_form.html) there seems to be multiple apostrophes at the end of the search term, and I do not understand the functional role of them, which makes me nervous about delving in and editting.
- Would someone with more html confidence please take a look?

**Comment by malvikasharan** [comment]
Thanks, @da5nsy for the issue. I have created a PR #1117 that should fix this. Can you please give that PR a review? you can test it in this preview: https://deploy-preview-1117--the-turing-way.netlify.app/search.html
