### ISSUE TITLE
Developing section for "Leadership and Management" under Remote Collaboration

### ISSUE THREAD

**Issue by IIITM-Jay** [alan-turing-institute/the-turing-way#1116]
## Summary:
Added Contents to "Leadership and Management" for Remote Collaboration with reference to discussion in #942 
## What it contains:
- [x] Elaborated the Classifications of management
- [x] Discussed the problems faced when remotely located
- [x] Discussed the solution for the proposed problems
- [x] Focused on representing the contents in a pictorial way
- [x] Key points are well explained diagrammatically
## What should a reviewer concentrate their feedback on?
- [ ] Feedback on the contents to be incorporated
- [ ] The positioning of images
- [ ] Images and corresponding contents are well established
## work done
Done a PR #1115

**Comment by IIITM-Jay** [comment]
@malvikasharan I hope you will find it more interesting. Waiting for your valuable suggestions and feedback on the same so that I can incorporate those. #1115

**Comment by malvikasharan** [comment]
Hi @IIITM-Jay, Thank you for the #1115 PR. You current content is not placed correctly in the designated directory and doesn't sync with the branch you are working on (#962).

More specifically, the content you have created is great but doesn't address the remote collaboration aspect. You can think about editing it for project design of collaboration section - that can be linked to the remote collaboration chapter for which more specific content might be needed.

**Comment by malvikasharan** [comment]
Hey @IIITM-Jay, I saw that you closed your PR without any comment. Is there is reason for closing that or will you add that in a different PR?

**Comment by IIITM-Jay** [comment]
@malvikasharan yeah, I am thinking to do in another PR. I have one thing to discuss that you have mentioned something about project design. Is it something a new section that I should edit and you think that it should be added as an important aspect i.e., Project Design.
Because as you said I also thought the same way the contents which I have might be somewhat to be good to include in the new section which can be called as "Project Design".
Will think and do something interesting the next week because this week I have decided to complete the chapter "Data Licences" which only remains with the case study. Is it okay that I will do the PR on Data Licences in a day or two.?

**Comment by IIITM-Jay** [comment]
@malvikasharan What do you say about my above comment? Is it okay to open up new issue regarding Project Design subsection...
More respectively, if you had viewed my PR on "Leadership and Management", it contained a section called **Task Management** in which I had mentioned 10 P's practices ***(Participate ,Produce,Progress......Publish)*** , I think that such kind of content really fits for the topic "Project Design" and on which I can think to edit upon. What do you say?

**Comment by IIITM-Jay** [comment]
@malvikasharan might be busy with schedule!!! I must guess....

**Comment by malvikasharan** [comment]
Hi Jay, yes! It's busy on most days. 

The project will upgrade to the new version of Jupyterbook and transfer to this format: https://deploy-preview-977--the-turing-way.netlify.com/welcome. Project design is one of our sections. I can't comment without reviewing or discussing your content where it will fit perfectly but I think "Project design" is still a better location than collaboration for what you are explaining.

**Comment by KirstieJane** [comment]
As leave investigator of The Turing Way I am closing this issue as the associated PRs have been closed and will not be reviewed.
