### ISSUE TITLE
Zenodo-GitHub release workflow plan

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1118]
### Summary

* Create a somewhat automated solution for Zenodo releases

### What needs to be done?

- [x] Connect the GitHub to Zenodo account (it is already done: https://github.com/alan-turing-institute/the-turing-way/releases)
- [ ] Need to clarify admin rights and Zenodo account access
- [ ] Need to decide release schedule (discuss with Kirstie)
- [ ] Extend the GitHub authorship script that @adswa has written
    - [ ] For every commit extract an authorship list since the last release

### Who can help?

* @pherterich, @rosiehigman, @emdupre and other members who have Zenodo account access 
* @adswa to have her script on a repo where the contribution can be made
* @sgibson91 help include this in the current CI for the project
* Anyone who would like to join to discuss this 👍 

---

### Updates

* Will work on this next week and communicate with the folks mentioned in this issue

**Comment by sgibson91** [comment]
Hi @malvikasharan, I will try and look into this soon. Did you mean to tag @rosiehigman RE Turing Way Zenodo access?

**Comment by malvikasharan** [comment]
Thanks @sgibson91. Kirstie told me the Elizabeth and Chris M were involved in the last releases, so I thought of checking with them. But yes, I should have also added Rosie in there.

**Comment by sgibson91** [comment]
Ah, I didn't know! Fantastic 👍🏻

**Comment by EstherPlomp** [comment]
@malvikasharan: I think you have recently worked on this workflow and the Zenodo-GitHub workflow is now sorted? I'll therefore close the issue now. If it is not sorted, feel free to reopen or add to the catch-all issue!  #2936
