### ISSUE TITLE
Binder comic on Twitter

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#112]
This should be included in the book somewhere: https://twitter.com/mybinderteam/status/1082556317842264064

(Accompanying discussion thread: https://twitter.com/JulietteTaka/status/1082735653929000960)

**Comment by pherterich** [comment]
Just to make sure we move this to the right place in the book, which chapter would this fit best it. Computing environment? Or should it be a case study?

**Comment by sgibson91** [comment]
I think under capturing computing environment

**Comment by pherterich** [comment]
Cool, linking this to #148 then so @r-j-arnold can think of a way to include this and close this issue when done.

**Comment by r-j-arnold** [comment]
Great, comic, will close when I put it in

**Comment by r-j-arnold** [comment]
Have asked for permission to use this.

**Comment by r-j-arnold** [comment]
Permission given, figure added, closing issue.
