### ISSUE TITLE
Help with retaining history: I moved a file to a different folder and it lost history

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1124]
### Summary

* I moved the [personas.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/personas.md) file to the project management folder and it lost its commit history (https://github.com/alan-turing-institute/the-turing-way/pull/470/commits)

### What needs to be done?

- [ ] Help me to retrieve and retain the commit history of the file
- [ ] suggest how in future I can move files without losing commit history

### Who can help?

* Anyone who knows how to solve this

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
@tallamjr How is your git fu with this kind of problem?

**Comment by tallamjr** [comment]
A `git log --follow -p -- project_management/personas.md` will do the trick.

The main flag is `--follow`:
```
       --follow
           Continue listing the history of a file beyond renames (works only for a single file).
```
and then `-p` to show the "patches" changed.. `--` to say not more flags from this point.. and finally the path to where the current file is located..

Hope this helps.

**Comment by malvikasharan** [comment]
Thank you @tallamjr. Let me try this and update.

**Comment by sgibson91** [comment]
To answer your second question @malvikasharan, did you use `mv` when you moved the file, or `git mv`?

**Comment by malvikasharan** [comment]
I used `mv` and I see the error in that! The git log and blame keeps the history (thanks for the hat tips @tallamjr) but GitHub doesn't after `mv` :(

**Comment by sgibson91** [comment]
😢That's disappointing. I imagine to GitHub, this looks like a "new" file?

**Comment by malvikasharan** [comment]
so so disappointing, especially because the blame button knows who to blame for that (I am looking at me right now!). It's useful to add this in the contributing guideline for best git practices when moving locations of the file.

**Comment by sgibson91** [comment]
> It's useful to add this in the contributing guideline for best git practices when moving locations of the file.

Also the git chapter? :sweat_smile:

**Comment by pdurbin** [comment]
Judging from 906620a the file was moved properly. It's not being treated as a new file. The problem is that the GitHub web interface doesn't expose the `--follow` functionality discussed above.

It looks like many people want GitHub to support `--follow` judging from threads like these:

- https://github.com/isaacs/github/issues/900
- https://github.community/t5/How-to-use-Git-and-GitHub/Show-file-history-for-renamed-files/td-p/18981

It sounds like GitLab already has this feature.

**Comment by malvikasharan** [comment]
Thanks for those resource @pdurbin and clarifying the feature issue.
