### ISSUE TITLE
[BUG] Links in Open Research chapter seem to be broken

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1125]
### Bug description

* The Open Research chapter's [index ](https://the-turing-way.netlify.app/open_research/open_research.html) does not link correctly to each section/subsection
* A more specific issue seems to be around "2. Barriers to data sharing". Although the index (and the section) says there are two, only one is mentioned [in the section](https://the-turing-way.netlify.app/open_research/01/opendata.html#Barriers-to-data-sharing).

#### Expected behaviour

* Links in the [index ](https://the-turing-way.netlify.app/open_research/open_research.html) should take you to each section/subsection.
* [2. Barriers to data sharing](https://the-turing-way.netlify.app/open_research/01/opendata.html#Barriers-to-data-sharing) should list both privacy _and_ "Nationally and commercially sensitive data"

#### Actual behaviour

* Links in the [index ](https://the-turing-way.netlify.app/open_research/open_research.html) to subsections (for example: 3.1.1. Step 1: Make your data available) lead to higher level sections (here: 3. Open Data)
* I cannot read 3.2.2.National and commercially sensitive data

**Comment by Sylfrena** [comment]
Hi @Ismael-KG ,

Can I take up this issue and make a PR?

**Comment by Ismael-KG** [comment]
Hi @Sylfrena ,

By all means, that would be great! Thank you!
