### ISSUE TITLE
Add the new labels' details in the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1127]
### Summary

* I have created a new label "[good first PR review](https://github.com/alan-turing-institute/the-turing-way/pulls?q=is%3Apr+is%3Aopen+label%3A%22good+first+PR+review%22)" for new contributors to get started with reviewing in this repo

### What needs to be done?

- [ ] The label is not yet added in the [CONTRIBUTING.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md) which can be added in the [issue label section](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md#issue-labels) with a one-sentence explanation (see [here for reference](https://github.com/alan-turing-institute/the-turing-way/issues/labels))

### Who can help?

* Anyone who is willing to add this in the designated area as described above
* preferably new users who have never contributed to this repo

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by srishti-nema** [comment]
Hey @malvikasharan  Can I take this up?

**Comment by malvikasharan** [comment]
Absolutely! That would be great.

**Comment by malvikasharan** [comment]
This has been fixed.
