### ISSUE TITLE
Create standard project slides

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#115]
## Detailed description

Create some standard slides with content that we would expect to be covered in every presentation we give around the project's work
they can be stored as ppt in a presentation folder here on GitHub and maybe as a template on Google Slides etc. (depending on what people prefer to use)

Using these slides should be an explicit point in #114

**Comment by KirstieJane** [comment]
I don't really want to be too prescriptive about what people *have* to use. I'd prefer to share a slide deck that have lots of options for people to remix....but not *require* all that much.

My gut feeling is that the most important slide is the acknowledgments slide. 

This means checking in with the Turing comms team too to make sure that we're acknowledging them correctly 😸

**Comment by pherterich** [comment]
Agree on the acknowledgements slide - and actually that one will hopefully change with more people contributing, but having a central place where we list the latest version of who should be included on there would be good

I tried to soften the wording in the original description to make this more of a "content checklist to help you build your presentation slide template"

Should we think about a commitment to use a CC-BY licence for slides and just add some ways to make that obvious on slides and share them more formally on figshare or zenodo as well?

**Comment by KirstieJane** [comment]
I think we can nudge on CC-BY and on sharing...but I don't want to have to require it.

Definitely template slides that HAVE the doi and github url etc in them make it much easier for folks to remember to share ✨

**Comment by sgibson91** [comment]
Would the slide deck be in different formats too? E.g. we talked about my presentation just being a Markdown file because it's a demo and I'll be (hopefully!) live-coding.

Re: Acknowledging the Turing - I noticed there's a poster in the kitchen indicating the correct phrasing to acknowledge the Turing and the general grant number, might have to hunt for the appropriate number.

**Comment by pherterich** [comment]
@sgibson91 yeah, I would say some ppt slides, maybe some announcement posters for workshops?, links to a google slides+ a text file with the minimum content so it's easy to re-use in all kinds of contexts to start with adding more as we go along.

Worth taking a picture of that poster next week, so we have documentation of the Turing acknowledgement best practice, thanks for spotting!

**Comment by pherterich** [comment]
Poster in the ATI kitchen says acknowledgement should be:
"This work was supported by The Alan Turing Institute under the EPSRC grant EP/N510129/1"
@jamespjh does this programme have a separate EPSRC grant number that we should use when acknowledging the ATI or just the one above or both?

**Comment by pherterich** [comment]
@KirstieJane do you know the grant number for this or could figure out how we should acknowledge funding? Or is it fine just to refer to the Turing?

**Comment by pherterich** [comment]
Tempted to close this unless there are objections - we do have plenty of material to work with in the conferences and workshops folders.
