### ISSUE TITLE
Collect resources for a subchapter on Contributors License Agreements

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1182]
### Summary

* Contributors License Agreements (CLA): 
"In order to participate in a corporate-backed-projects, community or business group, CLAs help clarify the terms of usage of contributions by an open-source project or community."

* We have a chapter on the license that doesn't yet cover this topic.

### What needs to be done?

- [ ] Collect resources and literature (can be commented below)
  - **Papers/Books**
    -  [Qualitative Study on the Adoption of CLA](https://www.jipitec.eu/issues/jipitec-5-2-2014/3999)
    - Understanding the value of the CLA Licence to UK higher education [project report](https://www.sconul.ac.uk/sites/default/files/documents/CNAC%20Research%20Project%20Report%20FINAL%20with%20logos.pdf)
  - **Examples**
    - Ubuntu Example: https://ubuntu.com/legal/contributors
    - W3C Example: https://www.w3.org/community/about/agreements/cla/
    - Public knowledge project: https://pkp.sfu.ca/contributor-license-agreement/
    - Medium Example: https://github.com/Medium/opensource/blob/master/sign-cla.md
    - Microsoft Example: https://cla.opensource.microsoft.com/
    - Google Example: https://opensource.google/docs/cla/
  - **Blogs and articles**
    - [Producing OSS](https://producingoss.com/) resource - shared by Markus
    - [Blogs](https://ben.balter.com/) from Ben Balter (Product manager of GitHub), specially [about open licenses](https://ben.balter.com/2017/11/28/everything-an-open-source-maintainer-might-need-to-know-about-open-source-licensing/) and [against CLA](https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/)
    - post from [Lexicology](https://www.lexology.com/library/detail.aspx?g=489c0dfb-2376-4d20-a449-ca81cd2c721e)
   - [Another resource against CLA](https://opensource.com/article/19/2/cla-problems)
    - [Introducing CLA in a company called Hashi](https://www.hashicorp.com/blog/introducing-a-cla/) - probably clarifies a few legal grounds
- [ ] Discuss how this subchapter can be structured

### Who can help?

* @mloning who will lead this chapter in collaboration with others
* @c-martinez, @mkuzak and folks from eScience who might know about CLA 
* Folks who know about license and can share their recommendations and resources

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by mloning** [comment]
We should also discuss Developer's Certificate of Origin (DCO)

**Comment by srishti-nema** [comment]
I think we can use the following structure:
* Introduction- Including what are CLAs and what it includes.
* CLAs and their relation with open source projects 
   - Reasons of using CLAs
   - Pros and cons of using these agreements
   - The effect of CLAs on open source culture and contributions
* CLAs and DCOs- features and differences
* Case Studies or Personal Experiences
* Further resources 
 This is just a suggestion. I found a few more resources:
- [Elastic](https://www.elastic.co/contributor-agreement)
- [Android](https://source.android.com/setup/start/licenses)
- [Facebook](https://code.facebook.com/cla/)
- [CLAs vs DCOs blog](https://opensource.com/article/18/3/cla-vs-dco-whats-difference)
- [Discussions on StackExchange](https://softwareengineering.stackexchange.com/search?q=CLAs)

**Comment by IIITM-Jay** [comment]
@malvikasharan , @mloning , As this talks about nevertheless the license, hence to be included in licensing chapter along with software and data licensing( on which I am still working ).  
 Few suggestions from my side:
Before including this sub-chapter, a few checklist has to be completed ,
- [ ] Its short description must be added in summary of licensing chapter
- [ ] Benefits of having CLA has to included in why/how helpful section
- [ ] Sub-chapter flow has to be planned i.e., the series of sub-sections has to be maintained

The structure of the chapter can be organized as: 
1.**Introduction:**
 * What are CLA
 * Why is it necessary
* The reason to include in the sub-chapter

2.**Working of CLA:**
* How CLA settles the mutual agreements 
* How CLA benefits both the parties between which agreements are settled
* Precautions to be taken while signing the agreement

3.**Benefits and pitfalls:**
* Effects of CLA on an Open Source Project and Community
* Positive and negative impacts

4.**CLA Vs DCO:**
* What's the difference?
* DCO: as an alternative to CLA
* Barriers to CLA & DCO

5. **Case Studies and Experiences**

**Comment by malvikasharan** [comment]
Hi @IIITM-Jay, CLA should be, as discussed with Markus, a separate subchapter. Data licensing is a separate one. And your comment basically repeats why Srishti said.

**Comment by mkuzak** [comment]
Thank you @malvikasharan I thinks that's a very important topic. Pinging @LourensVeen, is this something you know about and could help with?

**Comment by LourensVeen** [comment]
Yes, and I'd be happy to help.

I think there are two sides of this, and maybe it would be good to treat them separately. On the one hand there's contributing to a project that has a CLA, and getting it signed by a legal agent representing your organisation, and on the other hand there's the question of whether your open source project should have a CLA, DCO, or nothing.

**Comment by mloning** [comment]
One more useful book with a section on CLA/DCO: [Forge Your Future with Open Source](https://learning.oreilly.com/library/view/forge-your-future/9781680506389/f_0035.xhtml#sect.cla)

**Comment by EstherPlomp** [comment]
Hello from 2023! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
