### ISSUE TITLE
FIT4RRI Call for Training Events

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#121]
## Detailed description
- Project seems to be doing training on responsible research and innovation
- Call for events is available at https://fit4rri.eu/2019/01/fit4rri-call-for-training-events/
- Deadline: February 8th, 2019

First quick look at it looks like a binder / handbook workshop would fit quite nicely, maybe we can discuss when talking about #43 and #44 tomorrow.

**Comment by pherterich** [comment]
As we haven't discussed this, @KirstieJane do you think this would be useful to run more workshops later this year? If so, I guess @rosiehigman and myself could make a start on filling the application.

**Comment by KirstieJane** [comment]
I think we can find money if we need it, so this isn't a huge priority for me, but if you have time then - absolutely - lets go for it!

I think I'd love to coordinate it with the binder team - to see if there are folks we can bring across.

I like the idea of a 2 day event: 1 for researchers and 1 for RSEs.

**Comment by pherterich** [comment]
Agreed with @rosiehigman that we don't really have time to put this in now.
