### ISSUE TITLE
Capture different issues that may have appeared after the book format update

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1220]
### Summary

* This issue invites you to report issues that might have appeared due to the recent update in the book format

### What needs to be done?

- [ ] Post an issue as a comment here or open a new issue

### Who can help?

* Anyone who is reading this book in the new format, or have any suggestion that can improve how the book looks

---

### Updates

* Have included this issue in the newsletter for June

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
