### ISSUE TITLE
Guide for Ethical Research: Introduction

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1227]
## Detailed description

**captures contributions made in #913**

 * This issue is a place to discuss matters relating to the writing of the chapter on _Introducing Ethics in Research_ within the book of _[Guide for Ethical Research](https://github.com/alan-turing-institute/the-turing-way/blob/jupyterbook-restructure/book/website/ethical-research/ethical-research.md#guide-for-ethical-research)_
* The outline of this book is specified in [pull request #913](https://github.com/alan-turing-institute/the-turing-way/pull/913)
* This chapter is being written in [pull request #1228](https://github.com/alan-turing-institute/the-turing-way/pull/1228)

### Planned table of contents for this chapter

1. Defining Ethics
2. Why ethics matters to research
3. The research life-cycle
4. Examples of ethical dilemmas in research

### Resources

* European Textbook on Ethics in Research ([2010](http://ec.europa.eu/research/science-society/document_library/pdf_06/textbook-on-ethics-report_en.pdf))
* Please keep writing style consistent with the rest of the book (see [this issue](https://github.com/alan-turing-institute/the-turing-way/issues/1174))

### Discussion points/related issues

* Does the order of the table of contents seem logical?
* Do you have any interesting examples of ethical dilemmas in real-life research? (If there is enough info on them, they can develop into case studies for chapter 6 (the plan for each chapter is [here](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-645955721))

## Current status

This chapter is still at an early stage. If anyone would like to help, please do so!

 - [X] Write chapter outline
 - [ ] Review current contents
 - [ ] Add material to the chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by GeorgiaHCA** [comment]
Heya @Ismael-KG - this is a beautifully written issue! I wish all the ones in my repo were this good

**Comment by Ismael-KG** [comment]
There's a nicely written paper by Ecoffet and Lehman ([2020](https://arxiv.org/pdf/2006.04734.pdf)) that explains really well some big-picture moral theories, as well as how the gap between machine ethics and machine learning might be bridged

**Comment by Ismael-KG** [comment]
There's a nicely written paper by Ecoffet and Lehman ([2020](https://arxiv.org/pdf/2006.04734.pdf)) that explains really well some big-picture moral theories, as well as how the gap between machine ethics and machine learning might be bridged

**Comment by LauraCarter** [comment]
Closing this now that the chapter is up! https://the-turing-way.netlify.app/ethical-research/ethics-intro.html
