### ISSUE TITLE
Would a Spellcheck Action be useful?

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#1229]
### Summary

I found a GitHub Action that can be configured to perform a spellcheck on Markdown files (https://github.com/marketplace/actions/check-spelling-js-vue-html-markdown-text), would this be a useful addition to our CI suite?

➕ This will make tracking down typos easier
➖ We probably have a lot of words not in standard dictionary that would need to be explicitly excluded using `wordlist.txt`, for example Jupyter, BinderHub, and so on

You can see an example of it running on my website repo: https://github.com/sgibson91/sgibson91.github.io/actions?query=workflow%3A%22Check+Spelling%22+branch%3Amaster

### What needs to be done?

- [ ] Decide if the benefits outweigh the drawbacks of using this action
- [ ] If the decision is positive, implement the action

### Who can help?

* @malvikasharan 
* @martinagvilas 
* Anyone else

---

**Comment by malvikasharan** [comment]
Hi Sarah, spellcheck will be a good action, but I would request not making it a mandatory pass for the following reasons:

1) English: we allow any English assuming that authors come from different demography. I think spell check may not all English spellings, creating unnecessary errors.

2) Reviewer/co-authors: A lot of the errors are fixed over the review process, so if an author has done a massive edit, and don't have time/patience for a thorough grammar/spell check, a non-mandatory pass will give enough work for new co-authors to join in or reviewers to point the authors to.

**Comment by sgibson91** [comment]
Yeah I agree, I didn't think it would be a good idea to be mandatory either :hibiscus:

**Comment by sgibson91** [comment]
Please see the example and discussion in PR #1231 regarding why we did not implement this. If an alternative action appears that is more manageable, please feel free to reopen this issue.
