### ISSUE TITLE
Access policy for BinderHub

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#123]
## Detailed description
 - needs some thinking about who can access the BinderHub, how people would access it, which features they have access to and if any of this needs costing for in terms of infrastructure

**Comment by betatim** [comment]
There is some work happening on "BinderHub with logins". Might be interesting for you to limit who can access the BinderHub. It should support all authentication mechanisms that JupyterHub has, so you can use anything from predefined user accounts (user + password) to GitHub based authentication.

**Comment by sgibson91** [comment]
Closing as I think this is duplicated in #290
