### ISSUE TITLE
Blog post on GenR website

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#1230]
### Summary

@mrchristian approached me and asked if I wanted to write a blog post about The Turing Way on the GenR website as part of their *publishing* theme https://genr.eu/wp/category/publishing-utopias/

### What needs to be done?

- [x] Collect ideas for blog post
- [x] Write blog post
- [x] Review blog post
- [x] Publish

### Who can help?

* Anyone who knows what Turing Way is about :)
* I am happy to take the lead on this

---

### Updates

Published on https://genr.eu/wp/a-community-handbook-for-open-data-science/

**Comment by HeidiSeibold** [comment]
# The Turing Way: An open source community-driven online boog about reproducible, ethical, inclusive and collaborative data science

## What is The Turing Way?

## Why do we develop The Turing Way the way we do?

## What can others learn from The Turing Way with respect to publishing?

**Comment by malvikasharan** [comment]
Hi Heidi, we have an impact story here that captures most of these points: https://www.turing.ac.uk/research/impact-stories/changing-culture-data-science

We also have quite a few talks (on Zenodo and Youtube), some of which also have transcripts, so do let me know if some of those will be useful.

**Comment by mrchristian** [comment]
You can write the blogpost in MD and push over to here https://github.com/Gen-R/publishing-utopia we did this with the @o2r_project people. On the GenR Wordpress site we run Gutenberg which gets messy with HTML and CSS, not worked out a clean transfer yet, so in end copy paste and nudge around. 

Thank you @HeidiSeibold for picking this up, really appreciated.

The Turing Way is a really stand out project, big tip of hat :-) Personally I'm a fan of the idea of the community owned publication and second that its using Jupyter Book. Can't really get better.

The purpose of GenR is to show research examples of how they can do open science. We run a theme in parallel, currently that includes 'publishing utopias' with an emphasis on Computational Research and second 'COVID-19 and innovating open science systems'.

**Comment by HeidiSeibold** [comment]
@KirstieJane why did you decide to create The Turing Way the way you did and not such that it is just "your's" or "your group's"? I'd like to add a quote from you on this to the blog post.

**Comment by KirstieJane** [comment]
Thanks @HeidiSeibold!!

There are three answers to this question. One is that openness is a political act of justice and empowerment. Disseminating knowledge is not a capitalistic activity: I am not lessened by sharing information whose generation and synthesis was funded by the UK tax payer. The second is that I believe in the power and creativity of diverse groups. A community-created resource will be better and more effective than one developed by "me" or "my team". Finally, writing the book together under an open source license supports its scalability. _The Turing Way_ can only achieve its hugely ambitious goals of making reproducible research "too easy not to do" if we all work together to use, re-use, remix and refine the content for specific use cases across all aspects of data intensive research. 

Is that useful? Too long I'm sure, but let me know if there's a shorter quote inside of there that I can give you!

**Comment by HeidiSeibold** [comment]
I added some ideas on **What can others learn from The Turing Way with respect to publishing?**

Please add some more, anyone!

**Comment by pherterich** [comment]
Not sure how to phrase it but I like the contributor bot and acknowledging people beyond authorship. That becomes more common in traditional publishing, too, but I still think that the contributors bot credits people for a wider and more diverse role than e.g. the Credit taxonomy allows for

**Comment by HeidiSeibold** [comment]
Thanks for your support! I created the pull request https://github.com/Gen-R/publishing-utopia/pull/3 and am waiting for feedback. As soon as the PR is merged, we can close this issue :woman_dancing:  :tada:

**Comment by HeidiSeibold** [comment]
It's published now! 
:tada: :woman_dancing: 

Thanks for everyone's support!

https://genr.eu/wp/a-community-handbook-for-open-data-science/

**Comment by HeidiSeibold** [comment]
Uh can I get a "blog" emoji in the all-contributors table @malvikasharan? :nerd_face:
