### ISSUE TITLE
Guide for Ethical Research chapter: Benefits and Challenges

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1234]
## Detailed description

**captures contributions made in #913**

 * This issue is a place to discuss matters relating to the writing of the chapter on _Benefits and challenges of ethics within research_ within the book of _[Guide for Ethical Research](https://github.com/alan-turing-institute/the-turing-way/blob/jupyterbook-restructure/book/website/ethical-research/ethical-research.md#guide-for-ethical-research)_
* The outline of this book is specified in [pull request #913](https://github.com/alan-turing-institute/the-turing-way/pull/913)
* This chapter is now being written in https://github.com/alan-turing-institute/the-turing-way/pull/1649

### Planned table of contents for this chapter

1. Brief intro to ethical concerns (mention/recap of chapter one)
2. Argument(s) in favour of making ethical considerations in research
3. Costs and challenges to research ethics
4. How to overcome challenges identified in (3), where possible

### Resources

- European Commission ([2013](https://ec.europa.eu/research/swafs/pdf/pub_research_ethics/KI3213113ENC.pdf))
- Please keep writing style consistent with the rest of the book (see [this issue](https://github.com/alan-turing-institute/the-turing-way/issues/1174))

### Discussion points/related issues

Does the above table of contents follow a logical order?

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [X] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by Ismael-KG** [comment]
New chapter outline from [this discussion](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815):

1. Why to devote resources to ethical processes and how to justify it? Why it is easiest / most important to already design a research project with ethics in mind? Starting research with ethics in mind already makes project planning and management easier
2. Standard Q&A about why and how to do ethics, responding to common challenges and criticisms of ethics, misconceptions about ethics and whether it applies to you, e.g.: _**Q:** it costs a lot to do ethics - in terms of researcher time to fill in ethics forms. **A:** project management-wise you could have 1 person responsible for the form, but ethical thinking should be in the part of decisions, could engage domain ethics experts and bring into discussions, have an Advisory Board, etc._
3. Impact of making ethical considerations within science vs. not doing so

**Comment by LauraCarter** [comment]
This chapter now has a landing page and 3 subchapters, all in PR #1649
