### ISSUE TITLE
Guide for Ethical Research chapter: Ethical considerations by research stage

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1236]
## Detailed description

**captures contributions made in #913**

 * This issue is a place to discuss matters relating to the writing of the chapter on _Ethical considerations by research stage_ within the book of _[Guide for Ethical Research](https://github.com/alan-turing-institute/the-turing-way/blob/jupyterbook-restructure/book/website/ethical-research/ethical-research.md#guide-for-ethical-research)_
* The outline of this book is specified in [pull request #913](https://github.com/alan-turing-institute/the-turing-way/pull/913)
* This chapter does not yet have a linked pull request

### Planned table of contents for this chapter

1. Brief intro describing chapter and identification of research stages (make these and [those of chapter one](https://github.com/alan-turing-institute/the-turing-way/issues/1227) consistent with each other)
2. Idea generation (for example: reference how chapter 3's values can play a role here)
3. Data collection (consider biases here, such as Ọnụọha's _[missing data](http://mimionuoha.com/writing)_)
4. Data storage and management (privacy is mentioned elsewhere in the book, but data management plans can be defended on the basis of reproducibility as an epistemic value, for example)
5. Data analysis (this is about methodology: are potential biases considered in the methodology? How are these counteracted? [This article](https://research.google.com/bigpicture/attacking-discrimination-in-ml/) has some helpful thoughts on this in regards to ML)
6. Communication of results (consider D'Ignazio and Klein's discussion around [emotion in data visualisation](https://bookbook.pubpub.org/pub/8tjbs2x5/release/2), for example)

### Resources

- Linked in outlined content
- Please make use of this [illustrated flow](https://zenodo.org/api/iiif/v2/e4125eaf-b456-4097-85fc-6a2e80482d1c:f6c04b0b-0f25-4062-9287-6c1ea94317bf:1728_TURI_Book%20sprint_36%20data%20research%20cycle_040619.jpg/full/750,/0/default.jpg) of research stages!
- Please keep writing style consistent with the rest of the book (see [this issue](https://github.com/alan-turing-institute/the-turing-way/issues/1174))

### Discussion points/related issues

What staged should we identify for this discussion? Each project is unique, but might there be a generally accepted list of research stages?

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Review chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by Ismael-KG** [comment]
New chapter outline from [this discussion](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815):

1. Ethical design

- Should we be doing this?
- Who should be doing this? Who is on the team?
- What is the question we are asking?
- What are the ways we could answer that question? Do we always need, e.g. to invade people's privacy?
- Why are you choosing the method you are choosing? Is it appropriate to answer your question? Are you objective about the results or cherry picking methods that fit your hypothesis?
- How are we planning the data management / data access? E.g.: (a) if you plan on reusing personal data, make sure you have informed consent for this. (b) Are we working with vulnerable groups of the population, e.g. children, elderly, minority groups and how are you minimising risks? How will you anonymise data before sharing it?

2. Ethically conducted research

- Did you follow your initial plan? What changes took place and were these submitted to ethical scrutiny?
- Is your research process auditable (i.e.: recorded as it took place in practice)?
- Who is responsible and/or accountable?

3. ethically distributed research

- Open science in practice - who are you sharing your research with? How are you sharing it?
- Data repositories: how are you using those?
- Risks of misuse / abuse of your research or your data

**Comment by LauraCarter** [comment]
@rockita has already written parts on scoping and on data collection in this PR: https://github.com/alan-turing-institute/the-turing-way/pull/627
