### ISSUE TITLE
Guide for Ethical Research chapter: Suggested workflows

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1237]
## Detailed description

**captures contributions made in #913**

 * This issue is a place to discuss matters relating to the writing of the chapter on _Suggested workflows_ within the book of _[Guide for Ethical Research](https://github.com/alan-turing-institute/the-turing-way/blob/jupyterbook-restructure/book/website/ethical-research/ethical-research.md#guide-for-ethical-research)_
* The outline of this book is specified in [pull request #913](https://github.com/alan-turing-institute/the-turing-way/pull/913)
* This chapter does not yet have a linked pull request

### Planned table of contents for this chapter

1. Intro to what ethics committees at universities and research institutions generally do
2. List of different ethics approval processes
...
n. Final discussion about similarities amongst processes and the evident need for ethics approvals

### Resources

One example is that of the UK Statistics Authority (they even have a [self-assessment](https://www.statisticsauthority.gov.uk/about-the-authority/committees/nsdec/data-ethics/self-assessment-2/))

### Discussion points/related issues

Does your institution have an ethics process you understand and might want to share? If it is a transparent process and you can share links to their policies and procedures, that would be a great start! 

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by Ismael-KG** [comment]
Following the discussion [here](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815), this chapter is on hold -- unless somebody has a strong interest in (and good argument for) sharing different ways ethics committees work!

In any case, this chapter's initial idea will most likely make it to point two in the Benefits and Challenges chapter (outlined [here](https://github.com/alan-turing-institute/the-turing-way/issues/1234#issuecomment-652865842)).

**Comment by malvikasharan** [comment]
Ethics framework of NHS: https://www.gov.uk/government/publications/data-ethics-framework/data-ethics-framework-2020
