### ISSUE TITLE
Guide for Ethical Research chapter: Case studies

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1238]
## Detailed description

**captures contributions made in #913**

 * This issue is a place to discuss matters relating to the writing of the chapter on _case studies_ within the book of _[Guide for Ethical Research](https://github.com/alan-turing-institute/the-turing-way/blob/jupyterbook-restructure/book/website/ethical-research/ethical-research.md#guide-for-ethical-research)_
* The outline of this book is specified in [pull request #913](https://github.com/alan-turing-institute/the-turing-way/pull/913)
* This chapter does not yet have a linked pull request

### Planned table of contents for this chapter

1. Brief intro explaining this chapter describe scientific work that has been conducted in the past and that is worthy of ethical scrutiny
2. Case study 1
...
n. Case study n

### Resources

The European Textbook on Ethics in Research ([2010](http://ec.europa.eu/research/science-society/document_library/pdf_06/textbook-on-ethics-report_en.pdf)) shares some "research ethics scandals" (paged 15-18)

### Discussion points/related issues

It would be great to add more resources with stories of more recent "research ethics scandals" (for example, on biased predictive technologies used for policing, or biased facial recognition software)

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by Ismael-KG** [comment]
Following the discussion [here](https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815), it was agreed that case studies be mentioned throughout the book rather than described in their own chapters.

This issue can remain open for the purpose of discussing case studies as they emerge.

**Comment by Ismael-KG** [comment]
A few case studies we’ll be looking into more in-depth with [Data Science for Social Good](https://www.turing.ac.uk/collaborate-turing/data-science-social-good) participants this year are listed below, along with some thoughts as to what they may be used to discuss throughout this book:

- [Reviving pigs’ brains](https://www.nature.com/articles/d41586-019-01216-4): one question being “what was the end goal of this research? What good were they trying to achieve?” (Although there are many questions this case raises!)
- [COVID-19 paper retraction](https://doi.org/10.1016/S0140-6736(20)31324-6) on the importance of consent for the sharing and analysis of personal data
- [Netflix Prize and re-identification](https://en.wikipedia.org/wiki/Netflix_Prize#2009) raises questions around anonymisation
- [Kent Police](https://www.bbc.co.uk/news/uk-england-kent-46345717) and [Predpol](https://www.newscientist.com/article/mg23631464-300-biased-policing-is-made-worse-by-errors-in-pre-crime-algorithms/) remind us of how algorithms may unintentionally reinforce structural injustices

**Comment by sukanyashukla** [comment]
Another good resource can be: Automating Inequality- How High-Tech Tools Profile, Police and Punish the Poor by Virginia Eubanks. It mentions an interesting source of structural injustice by computer algorithm in case of Medical insurance. Here is a link to the book review: 
https://blogs.lse.ac.uk/lsereviewofbooks/2018/07/02/book-review-automating-inequality-how-high-tech-tools-profile-police-and-punish-the-poor-by-virginia-eubanks/

**Comment by malvikasharan** [comment]
Moving this comment from #913 to ensure that the record by @Chrisisour is not lost:

https://github.com/alan-turing-institute/the-turing-way/pull/913#issuecomment-651731815

> _Case studies to be included throughout as examples to illustrate what is said in the chapters_
> 
> 1. **Landing page** with a definition of ethics, why ethics matters to research (what is research ethics, including mention of the research lifecycle) and a few examples of ethically curious research cases (e.g.: biased facial recognition, crime-predicting algorithms)
> 
> 2. **Benefits and challenges** of ethics within research: why ethics are important to consider vs. why they might be hard to implement (but always possible to consider) 
> 
> 2.1. Why to devote resources to ethical processes and how to justify it? Why it is easiest / most important to already design a research project with ethics in mind? Starting research with ethics in mind already makes project planning and management easier
> 
> 2.2. Standard Q&A about why and how to do ethics, responding to common challenges and criticisms of ethics, misconceptions about ethics and whether it applies to you, e.g.:
> - it costs a lot to do ethics - in terms of researcher time to fill in ethics forms. - A: project management-wise you could have 1 person responsible for the form, but ethical thinking should be in the part of decisions, could engage domain ethics experts and bring into discussions, have an Advisory Board, etc. 
> 
> 2.3. Impact of making ethical considerations within science vs. not doing so (@malvikasharan this might actually repeat a bit of point 2... Maybe this issue can be held back? Or do you have a clearer idea as to why this one is necessary)
> 
> 3. **Ethical considerations by research stage**; i.e.: around design, data collection, data storage, analysis, results communication and making open source (some of this content can be linked to other parts of the book)
> 
> 3.1. ethical design
> 
> - Should we be doing this?
> - Who should be doing this? Who is on the team?
> - What is the question we are asking?
> - What are the ways we could answer that question? Do we always need, e.g. to invade people's privacy? 
> - Why are you choosing the method you are choosing? Is it appropriate to answer your question? Are you objective about the results or cherry picking methods that fit your hypothesis?
> - How are we planning the data management / data access? - e.g. if you plan to have data being reused, make sure you collect it in the appropriate ways to allow for that (informed consent). Are we working with vulnerable groups of the population, e.g. children, elderly, minority groups and how are you minimising risks? How will you anonymise data before sharing it? (MASSIVE PIECE)
> 
> 3.2. ethically conducted research
> 
> - did you actually follow your plan? If not, why not and are you justifying it?
> - is your research process auditable, recorded as it took place in practice?
> - who is responsible or accountable?
> 
> 3.3. ethically distributed research
> 
> - open science in practice - who are you sharing your research with? How are you sharing it?
> - data repositories, how are you using those?
> - risks of misuse / abuse of your research or your data
> 
> 4. **More abstract philosophical discussion**: 
> 
> - very basic discussion around moral philosophy: consequentialism, deontology and virtue ethics, and 
> - the inevitable role of epistemic and non-epistemic values
> - brief (1-2 para) introductions to key ethical values and principles
> 
> 5. **Law and policy** 
> - define law, policy, and ethics and their relationships / differences
> 
> 5.1. Law
> - what's the difference / relationship between ethics and law
> - GDPR and privacy laws (and how privacy and data protection are different)
> - HRs law --> check that your national law if there's anything that applies to you / your company
> - IP law - ownership or datasets, databases that you are using? T&C of websites when webscraping?
> - tort law - if you are negligent / reckless and your work harms someone, you are liable
> 
> 5.2. Policy on responsible research and innovation (RRI)
> - government / international organisations policies (e.g. European Commission guidance for RRI)
> - voluntary commitments
> - professional bodies, initiatives, statements (e.g. IEEE Ethically-aligned design initiative, ACM explainability and transparency statement)
> - a list of resources of Codes of Conduct for ethical research, frameworks, etc. 
> 
> 
> _TBD - Suggested workflows with different ethics committees' processes - does it add to what might be in other chapters? Is it something that needs to be done on an institutional basis? of interest to members of ethics committees_
>

**Comment by malvikasharan** [comment]
Hey @ashatitus. Please look at this issue for the case studies in the Ethical Research guide.
@Ismael-KG Please meet Asha :)

**Comment by ashatitus** [comment]
Thanks for directing me to the case studies section - while prepping for the book dash, I have been working through the structure of the Ethics chapter in order to get a sense of the style of the overall book and how it is pitched at a data science practitioner audience...

**Comment by BrainonSilicon** [comment]
> Thanks for directing me to the case studies section - while prepping for the book dash, I have been working through the structure of the Ethics chapter in order to get a sense of the style of the overall book and how it is pitched at a data science practitioner audience...

Awesome! This will be a great addition @ashatitus. Feel free to ask if you have any questions, the book is being built as we go!

**Comment by LauraCarter** [comment]
Folks: we're building up a little library of case studies (which is awesome) and at the moment they're stand-alone subchapters. I'm broadly in favour of keeping them stand-alone so they're easier to find and to read alongside the other chapters - what do others think? If others agree, I think we can close this issue?

**Comment by Ismael-KG** [comment]
Does the issue become redundant (new issues for each case study) or useful to link all case-study PRs to? I'm not sure - more than happy for you to make the call, @LauraCarter.

**Comment by LauraCarter** [comment]
I don't think it's that useful since the case-studies are more closely related to the things they are cases of. Unless there's a strong argument to keep this open, I'll close it I think?
