### ISSUE TITLE
Chapter idea: Coding styles; Linting hows and whys

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#124]
## Detailed description
 - Formatting your code to a particular style is super important
 - Linting can be a little confusing though!
 - This chapter can cover good practise for stying your code so that others can read and understand it easily.

**Comment by harisood** [comment]
Hello from autumn 2022 @KirstieJane ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

This issue looks like it has now been incorporated in the Turing Way [here](https://the-turing-way.netlify.app/project-design/code-styling.html). Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
