### ISSUE TITLE
On paper review process

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1240]
## Detailed description

 * This issue is a place to discuss matters relating to the writing of the chapter on _reviewing_

### Resources

* This post by Rene Bekker: https://renebekkers.wordpress.com/2020/06/24/how-to-review-a-paper/
  * Twitter thread: https://twitter.com/renebekkers/status/1275724073297985540?s=20

### Discussion points/related issues

* Open for anyone to take and adapt for the chapter

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by malvikasharan** [comment]
More resources to mention: 
- Prereview: https://t.co/GDns1IUHiJ?amp=1
- Advice on research and writing: https://www.cl.cam.ac.uk/~jac22/advice.html
- Suereview blog series: 
  - dart.ed.ac.uk/june-blogs
  - http://dart.ed.ac.uk/start-new-project
  - http://dart.ed.ac.uk/how-to-finish-a-project
  - http://dart.ed.ac.uk/poster-perfect

Twitter thread by Kirstie: https://twitter.com/kirstie_j/status/1275688758097129481?s=20

**Comment by Ismael-KG** [comment]
I wonder if Heesen and Bright's (2020) arguments against prepublication peer review is a useful resource?

- https://academic.oup.com/bjps/article/doi/10.1093/bjps/axz029/5526887

**Comment by malvikasharan** [comment]
Hey @karvovskaya , here is the issue we discussed.

**Comment by Karvovskaya** [comment]
I will start working here: https://hackmd.io/cg2uL01nSd6TVrjxHU5c2A Once I have a draft I will ask someone to review :-)

**Comment by Ismael-KG** [comment]
@BrainonSilicon, @LauraCarter and Ana Basiri and I just had a really interesting chat about everything peer review and we returned to this issue to see how it's going. @Karvovskaya have you put some ideas together on that hackmd? (The link isn't working for me!). We would love to see.

There's also a lot around the work in Living With Machines at the Turing: https://livingwithmachines.ac.uk/highlighting-authors-contributions-and-interdisciplinary-collaborations-in-living-with-machines/ (yet to discuss with @fedenanni!)

**Comment by EstherPlomp** [comment]
@Karvovskaya: I think you finalised this chapter and included these resources right? So I think we can close this issue?

**Comment by EstherPlomp** [comment]
As mentioned above, I think we got this covered so I'll close this issue!
