### ISSUE TITLE
New Chapter: Reproducible Research/Case Studies

### ISSUE THREAD

**Issue by kkmann** [alan-turing-institute/the-turing-way#1242]
## Detailed description

With the growing complexity of The Turing Way, I felt it might be useful to reference real-life examples of how to implement issues discussed in TTW and cross reference to the respective sections. 
I am happy to make a start with a recent manuscript of mine (topic: statistics) that makes heavy use of repo2docker + mybinder.org for interactive, reproducible supplemental materials, zenodo.org for long term storage, and snakemake for workflow management (well, two steps...). 

### Table of contents

* one section per example repository
* template section for new examples at the very end

### Resources

none

### Discussion points/related issues

* once there are enough examples, it might be 

## Current status

 - [x] @kkmann: document first example, see https://github.com/kkmann/sample-size-calculation-under-uncertainty
 - [x] proofread
 - [x] request reviews
 - [ ] address reviews
 - [ ] merge to master branch.

**Comment by HeidiSeibold** [comment]
@kkmann I saw you pinged me in the PR. That sounds like something I could contribute to. Let's touch base after after the holiday season! :clap: :sun_with_face:
