### ISSUE TITLE
Update the New Chapter Template

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1243]
### Summary

*Following a conversation with @malvikasharan, it was noted that the ["New Chapter Template"](https://github.com/alan-turing-institute/the-turing-way/blob/ca80260d989e77fbac63c9433d6caf93b44e71c9/.github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md) needed updating. After raising my first few new-chapter issues, I think what would help are more links within the template. Details below.*

### What needs to be done?

- [ ] *Add links to the template:*
  - _Under "Detailed description", each bullet point should link to the book/issue/PR they reference_
  - _Also, add a bullet point:_ "This chapter does not yet have a linked pull request" _and the clarifying message:_ "Please link to a pull request when one has been raised by changing the text to This chapter does not yet have a linked pull request #xxxx"
  - *Under Resources, add the bullet point:* Please keep writing style consistent with the rest of the book (see [this issue](https://github.com/alan-turing-institute/the-turing-way/issues/1174))
- [ ] _Change the "Table of contents" subtitle to "Planned table of contents for this chapter" (for clarity)_
- [ ] _Change the to-do list to:_
  - [ ] Write chapter outline under *Planned table of contents for this chapter* once agreed upon
  - [ ] Add material to the chapter
  - [ ] Proofread
  - [ ] Request reviews
  - [ ] Address reviews
  - [ ] Merge to master branch.

### Who can help?

* *Anybody!*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
Thank you Ismael! I will make some time to add some more notes here.

@pgadige I think @Ismael-KG notes will be useful for you to add in the template Description and #1174 issue.

**Comment by harisood** [comment]
Please also consider #1090 for this issue & template!
