### ISSUE TITLE
[BUG] Book Dash Agenda is missing, broken link

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#1247]
### Bug description

- [ ] The full day agenda advertised in the book dash folder is not present
- [ ] This causes a broken link: https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/book-dash/README.md

#### Expected behaviour

- [ ] The agenda document is available and the link works
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

#### Actual behaviour

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### Your personal set up

- OS:

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

- Browser:

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
There is a reorganized folder with last book dash's report proposed in a PR #928, which should fix this once approved ([preview here](https://github.com/alan-turing-institute/the-turing-way/tree/malvikasharan-bookdash-feb20-report/workshops/book-dash))
