### ISSUE TITLE
Update Contributing guidelines to reflect authorship discussion

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#125]
## Detailed description
 - Discussion at January Sprint on authorship and acknowledgement
 - Agreed to recognise contributions through [humans.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/humans.md) - **Update:** this is implemented now :smile: 
 - The Turing Way project will be first author on all chapters/book, authors listed alphabetically afterwards
 - Interim solution for non 'core' contributors is to apply to @KirstieJane 
 - Important to be able cite chapters individually from a usability point of view
 - Open up individual chapter citations issue to the community

**Comment by pherterich** [comment]
* Use https://github.com/bids-standard/bids-specification/blob/master/src/99-appendices/01-contributors.md for recognizing contributions

**Comment by KirstieJane** [comment]
Just saw this tweet for a book that does the individual doi think: https://twitter.com/pjdunleavy/status/1086455853140520960?s=21

Worth checking out 🌻

**Comment by pherterich** [comment]
@all-contributors add @r-j-arnold for answering questions, documentation, code, reviewed pull requests

**Comment by pherterich** [comment]
@all-contributors add @LouiseABowler for question, code, doc, examples, eventOrganizing, review
@all-contributors add @sgibson91 for question, code, doc, tool, review, talk
@all-contributors add @pherterich for question, doc, review, talk
@all-contributors add @rosiehigman for question, doc, eventOrganizing, review
@all-contributors add @annakrystalli for question, examples, doc, review, talk
@all-contributors add @alexmorley for question, review, test
@all-contributors add @martintoreilly for question, tool
@all-contributors add @KirstieJane for question, design, fundingFinding, ideas, review, test, talk

**Comment by pherterich** [comment]
@all-contributors please add @LouiseABowler for question, code, doc, examples, eventOrganizing and review

**Comment by pherterich** [comment]
@all-contributors please add @sgibson91 for question, code, doc, tool, review and talk

**Comment by pherterich** [comment]
@all-contributors please add @pherterich for question, doc, review and talk

**Comment by pherterich** [comment]
@all-contributors please add @rosiehigman for question, doc, eventOrganizing and review

**Comment by pherterich** [comment]
@all-contributors please add @annakrystalli for question, examples, doc, review and talk

**Comment by pherterich** [comment]
@all-contributors please add @alexmorley for question, review and test

**Comment by pherterich** [comment]
@all-contributors please add @martintoreilly for question and tool

**Comment by pherterich** [comment]
@all-contributors add @KirstieJane for question, design, fundingFinding, ideas, review, test and talk

**Comment by EstherPlomp** [comment]
Hello from 2023 @rosiehigman, @pherterich,@aleesteele! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - the 'Important to be able cite chapters individually from a usability point of view' part is not yet resolved. 

We've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
