### ISSUE TITLE
Section on managing sensitive data?

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1267]
### Summary

I do not think we have a separate section on managing sensitive data (personal data, commercial data), which could be helpful. 

### What needs to be done?

- [ ] Set up a draft of a section under Research Data Management (reproducible research book)
https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/rym-ZyrO8/edit (scroll down)
- [ ] Check the draft!

### Who can help?

Anyone that has some experience with managing this type of data!

---

**Comment by MariaEriksson** [comment]
Hi @EstherPlomp! 👋  I work with sensitive data, and might be able to help. Would you like to work together on this during a Co-working call/Collaboration café? Or I add comments here under the 'Updates'-section?

**Comment by EstherPlomp** [comment]
Hi @MariaEriksson ! That would be great! 
I set up a very rough text on a hack md: https://hackmd.io/kKm1R1PfRZStmbo9GtwuBg#Managing-senstive-data-1267 
I'm not sure how that works with collaborative writing, perhaps I should move it to a google doc or github so it is easier to contribute?
I'm planning to attend the following co-working calls so it might also be good to discuss it then? 
- 26 Oktober
- 2 November
- 5 November
Please let me know what you prefer :)

**Comment by MariaEriksson** [comment]
Hey @EstherPlomp! Happy to hear that we can meet during the co-working call! Today works great for me (it's at 11am GMT if I'm not mistaken?). Looking forward to meeting you then!

**Comment by EstherPlomp** [comment]
This issue will probably need have two separate new sections as the term senstive data can be confusing: 
1. personal data #1267
2. commercial sensitive (probably needs a new issue)

**Comment by EstherPlomp** [comment]
Created a pull request that @MariaEriksson, @LauraCarter and myself are still working on: Create personal.md #1471
https://github.com/alan-turing-institute/the-turing-way/pull/1471
