### ISSUE TITLE
Gitter vs Slack

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#127]
### Detailed description
 - Do we want to move from gitter to slack?
 - One of the barriers we have is that gitter doesn't support threads so conversations can be rather difficult to have over the top of each other
 - The motivation for gitter over slack originally was because it is open and anyone can join (you have to be invited to a slack team
 - One option is to keep the gitter channel for public chats, but move to slack for the regular cor contributors meetings

**Comment by sgibson91** [comment]
Upvote for private contributors slack, think this is a great way to solve the issue and still maintain openness for the main project.

**Comment by LouiseABowler** [comment]
I'm in favour of a private Slack channel for group meetings too, as Slack threads will make keeping track of the separate discussions within the meeting much easier. But I'm aware that means another Slack channel/workspace for everyone - what are opinions on that?

I think we should keep the public Gitter, it gives anyone interested in the project a really easy way of getting in touch with the entire team.

**Comment by alexmorley** [comment]
I'm also in favour of slack for private. We can also have a bot to relay public messages to a thread on slack so we don't miss any if that's useful?

**Comment by pherterich** [comment]
Closing this following a successful first meeting on slack and ongoing conversations in the public gitter :smile:
