### ISSUE TITLE
Consider how to improve ways of working so that PRs and issues don't get super long

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#128]
### Detailed description
 - The problem with writing collaboratively and openly with lots of feedback is that some of the threads get SUPER long! See @r-j-arnold's PR for the version control chapter #88 🙀 
 - There are probably some human ways of splitting up these conversations into more manageable chunks....this issue is to capture thoughts around developing that process 👾

**Comment by r-j-arnold** [comment]
Suggested idea

Chapter developed on a person's fork. When ready for review make a branch on the turing way repo for the chapter. Make a pull request from the chapter developer's fork to that branch. 

High level reviews go on that pull request, major changes to structure etc. Changes requested should be of the scale of paragraphs+, not sentences. 

Following that merge to the chapter branch on the turing repo.

Subsequent changes made via pull requests to that branch, and discussed in issues linked to and summarised in the main chapter issue.

When everyone's happy merge to Turing master.

**Comment by r-j-arnold** [comment]
Changes added to contributing guidelines
