### ISSUE TITLE
Review chapter: Research Data Management landing page

### ISSUE THREAD

**Issue by Ismael-KG** [alan-turing-institute/the-turing-way#1293]
### Summary

Following a general review of the [Research Data Management](https://the-turing-way.netlify.app/reproducible-research/rdm.html) chapter in the [Guide for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/reproducible-research.html), there seems to be an opportunity for greater clarity and increased usability for researchers in the field. Below I outline some ideas that can be implemented in the chapter's [landing page](https://the-turing-way.netlify.app/reproducible-research/rdm.html). Please feel free to refute any of the suggestions, and tackle only one of the tasks (rather than all) if you want!

### What needs to be done?

- [ ] *For the [benefits section](https://the-turing-way.netlify.app/reproducible-research/rdm.html#what-are-the-benefits-of-research-data-management), could there be an introductory paragraph? Something along the lines of "Whilst it can not be denied that research data management is a complex exercise and comes at a financial cost (consider UK Data Service's commentary and tool for [data management costing](https://www.ukdataservice.ac.uk/manage-data/plan/costing)), there are clear benefits to integrating RDM into your research project. Some benefits are listed below:".*
- [x] *The five [benefits of data management](https://the-turing-way.netlify.app/reproducible-research/rdm.html#what-are-the-benefits-of-research-data-management) can be expanded on/justified and linked to further resources (or other sections within the book, like the third bullet point does).*
- [x] *The ["What is Data" section](https://the-turing-way.netlify.app/reproducible-research/rdm.html#what-is-data) offers useful questions for researchers to identify data, but the distinction between data science and other fields of inquiry can be toned down.*
- [ ] *Add an image or a clearer description of the research data lifecycle in the [last section](https://the-turing-way.netlify.app/reproducible-research/rdm.html#the-research-data-lifecycle-a-model-for-data-management)*

### Who can help?

* *Anybody with the time to reflect on data management!*

**Comment by EstherPlomp** [comment]
Addressed the two middle comments! I think it is nicer to keep the benefit section as short as possible. I also don't think we have a nice image to go with the research data lifecycle, so I haven't addressed this point! 

Thanks for reviewing the chapters!
