### ISSUE TITLE
Compile talks and workshop details delivered in association with The Turing Way

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1300]
### Summary

* Add missing details of the talk/workshop conducted this year [here](https://github.com/alan-turing-institute/the-turing-way/tree/master/conferences)

### What needs to be done?

- [ ] Ask core team and community members who have delivered talks to add their details either as a comment to this issue of directly to the conference table
- [ ] Gather idea on what would be the best way to collect these info in the future

### Who can help?

* Turing members: @sgibson91, @Ismael-KG, @LouiseABowler, @pherterich, @KirstieJane     
* Community members: @martinagvilas, @EstherPlomp, @HeidiSeibold   

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by pherterich** [comment]
In the beginning, we had issues for most talks and workshops that were submitted or delivered, not sure if that's feasible? You could introduce a label for them and that should make collection for newsletter and any other reports fairly easy.

**Comment by sgibson91** [comment]
- [Remote ReproHack](https://n8cir.org.uk/events/remote-reprohack/), _14th May 2020_, https://doi.org/10.5281/zenodo.3826152
- [CogX](https://cogx.co/), _8-10th June 2020_, https://doi.org/10.5281/zenodo.3885704
- [e-Rum](https://2020.erum.io/), _17-20th June 2020_, https://doi.org/10.5281/zenodo.3895699
- [EuroPython](https://ep2020.europython.eu/), _23rd-26th July 2020_, https://doi.org/10.5281/zenodo.3937310
- [JuliaCon](https://juliacon.org/2020/), _27th-31st July 2020_, https://doi.org/10.5281/zenodo.3956320

**Comment by malvikasharan** [comment]
@pherterich Label for issues is a good idea. I will create one right away.
Thanks @sgibson91. So, I assume they should not be included in The Turing Way report, but for TPS report by Kirstie.

**Comment by sgibson91** [comment]
I think the ReproHack one would fit, but the others yes you're probably right

**Comment by LouiseABowler** [comment]
I’ve not got anything to add for this year @malvikasharan, but I possibly have one from last year to add. Not sure if it’s in scope though - it was a talk about the Turing Way but was for an internal Turing meeting (AI for Science and Government: Digital Twins for Complex Engineering Systems theme meeting). Let me know if you want it to be included and I’ll add to the list :slightly_smiling_face:

**Comment by malvikasharan** [comment]
Thank you @LouiseABowler. Though not necessary for this quarter's report, it would still be useful to record your talk to measure internal communications. Whenever you have some time, please go ahead and add the details.
