### ISSUE TITLE
[accessibility] Reduce image sizes to lower than 1 mb  ( 26 PR ideas for HacktoberFest participants)

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1313]
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

### About Hacktober and The Turing Way
Hacktober is a month long celebration of Open Source Projects where the goal is to make 4 Pull Requests during the month.

#### A bit about Git
If you’re new to git then here are [some instructions](https://help.github.com/articles/signing-up-for-a-new-github-account/) to help you get going. Remember that you can ask us any questions you need to along the way.

A [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) (what Hacktober is measured on) lets you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

Under the Issues listed in our Hacktober tag, we’ve outlined what needs to be done, and how you can go about addressing it. Once the Issue has been addresses, you can submit a Pull Request for review (tell us what you’ve done) and we can incorporate it into The Turing Way.

We’ve also created this special Hacktoberfest tag to make is easy for you to find places to contribute if you’re new.

In the spirit of Hacktoberfest, please only do a few of these to submit your PR so that we can learn and grow as a community together.

#### Our Community
Please read our core Contributors document and our Code of Conduct while you engage in The Turing Way. We want to ensure that every user and contributor feels welcome, included and supported to participate in The Turing Way community.

In addition, for Hacktober we would also like to recognise the work that you are doing. If you would like to be featured on our [Twitter](https://twitter.com/turingway?s=20) Hacktoberfest series then: 
- Add your twitter handle to the comments when you submit your PR, 
- What brings you to Open Source, Hacktoberfest, and/or The Turing Way,
- and anything else you’d like to celebrate about your contribution!

We welcome all contributions to this project via GitHub issues and pull requests. Please follow these guidelines to make sure your contributions can be easily integrated into the projects. As you start contributing to The Turing Way, don't forget that your ideas are more important than perfect pull requests. ❤️

If you have any questions that aren't discussed below, please let us know through one of the many ways to get in touch.

# Summary of Issue

* Problem: Many images in the online books are very large and take enormous time to load (listed below)
* Solution (suggested for PRs): Reduce the image size to make them lower than 350 KB
* Image location: [book⁩/⁨website⁩/figures⁩](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/website/figures)

### What needs to be done?

From the file path [book⁩/⁨website⁩/figures⁩](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/website/figures) please select a maximum of 2-3 files from the list below to create a PR. To select, but click on the checkbox and comment below in the issue so others know which files you will be working on.

- [x] community.jpg
- [x] ThatCouldBeAChapter.png
- [x] reproducibility.jpg
- [x] communication.jpg
- [x] bookdash.png
- [x] binder_comic.png
- [x] file-collection.jpg
- [x] flipped_taj_mahal.png
- [x] welcome.jpg
- [ ] collaboration.jpg
- [ ] data-ecosystem.jpg
- [ ] distributed-collaboration.jpg
- [x] Provenance.jpg
- [x] ResearchCompendium.jpg
- [x] contributors-twopanel.png
- [ ] outreach.jpg
- [ ] project-design.jpg
- [ ] ethics.jpg
- [ ] data-privacy.jpg
- [ ] allcontributorsbot-emoji.png
- [ ] persona-creation.png
- [ ] virtual_machine.png
- [ ] Contributors.png
- [ ] scriberia-newsletter.png
- [ ] templates.png
- [ ] testing_motivation_2.png

### Who can help?

- Anyone who would like to participate in Hacktoberfest or contribute to The Turing Way GitHub repository for the first time
- easier to do locally (by git) but not mandatory
---

**Comment by giannidsp** [comment]
I will be working on these 3 files:

- [ *] reproducibility.jpg

- [ *] communication.jpg

- [ *] bookdash.png

**Comment by ikayz** [comment]
I would like to work on some images

**Comment by malvikasharan** [comment]
Go for it @ikayz. You can see the last contributor’s PR for reference.

**Comment by ikayz** [comment]
@malvikasharan I've worked on these files and reduced the file sizes
[ *] binder_comic.png

[ *] flipped_taj_mahal.png

[ *] welcome.jpg

**Comment by paulowoicho** [comment]
Hi @ikayz, thank you for your work. I have reviewed and merged your PR!

**Comment by C-Lion** [comment]
Currently working on these 3: 
[ ] collaboration.jpg
[ ] data-ecosystem.jpg
[ ] distributed-collaboration.jpg

**Comment by paulowoicho** [comment]
> Currently working on these 3:
> [ ] collaboration.jpg
> [ ] data-ecosystem.jpg
> [ ] distributed-collaboration.jpg

Thank you @C-Lion! When you're done, you can tag me in your PR so I can review and merge!

**Comment by ikayz** [comment]
These have been worked and submitted a PR
[x]  Provenance.jpg
[x]  ResearchCompendium.jpg
[x]  community.jpg

**Comment by C-Lion** [comment]
Currently working on these 3:

[ ]  ThatCouldBeAChapter.png
[ ]  contributors-twopanel.png
[ ]  file-collection.jpg

**Comment by da5nsy** [comment]
Closed in #2767 (specifically: https://github.com/alan-turing-institute/the-turing-way/commit/37eb85d61dc233b5ff36b486e1f69197be542c2c)
