### ISSUE TITLE
Issue on page /welcome.html: "the third sector" is jargon

### ISSUE THREAD

**Issue by skade** [alan-turing-institute/the-turing-way#1319]
The Turing ways main page says:

> Our goal is to provide all the information that data scientists in academia, industry, government and in **the third sector**

As a third language English speaker not into the subject space, this was non-obvious jargon for me. Not bad, but it tripped me. I assume it means [voluntary work](https://en.wikipedia.org/wiki/Voluntary_sector) as described here.

Changing it or maybe defining it quickly would help with that confusion.

Thanks for writing and making available the book!

**Comment by malvikasharan** [comment]
Thanks @skade for the issue. That is indeed a jargon. I wonder "other research communities" might make it clear.

**Comment by KirstieJane** [comment]
https://www.nao.org.uk/successful-commissioning/introduction/what-are-civil-society-organisations-and-their-benefits-for-commissioners

Third sector organisations are those that are neither public nor private. Charities and non-government organisations fit into this category but third sector is a broader and more inclusive term. It is a standard phrase so I'm disinclined to change it though. It certainly isn't restricted to research communities.

**Comment by LauraCarter** [comment]
I think 'the third sector' as a phrase is well-understood in the UK, but I'm not sure it's as common in other countries. How about "...and in civil society (including community groups, charities and non-governmental organisations)."?

**Comment by skade** [comment]
To be clear, I don't think it should necessarily be removed, but precisely as @LauraCarter says, it's rather local jargon. Introducing it quickly, at least in broad sense will ease the entry into the book. I needed to go look it up the definition. :)

**Comment by da5nsy** [comment]
Wording has been changed [here](https://github.com/alan-turing-institute/the-turing-way/commit/a6663bdc555fc8eb714f554ba4d310ead9e5dd40#diff-201b65911e60d39894b9d22b1223c54b9e844372f8efce1afaa73eb5244d9be0) and so closing this issue.

FWIW I agree with OP - I'm from the UK and this was the first time I'd seen the phrase.
