### ISSUE TITLE
Coworking chapter: extend that with a guide for hosting a coworking call

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1329]
## Detailed description

 * This issue is a place to discuss matters relating to the writing of the subchapter on _hosting a coworking call_.

### Table of contents

- Motivation
- Planning
- Logistics
  - before
  - during 
  - after

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by LauraCarter** [comment]
Things to add/signpost (a lot of this is in the coworking chapter already)
Before the call
- [ ] How to set up a HackMD or similar - what information needs to be included
- [ ] How to set up a call 
- [ ] Adding to community calendar
During the call
- [ ] Hosting: introductions, icebreaker, managing balance of catching up and coworking
After the call
- [ ] Reporting any problems e.g. with IT systems, for future hosts

**Comment by malvikasharan** [comment]
We have a subchapter now for online meeting logistics: https://the-turing-way.netlify.app/collaboration/remote-collab/remote-collab-meetings.html. This covers all the points mentioned by you, do you think we can refer to that in this subchapter? https://the-turing-way.netlify.app/collaboration/remote-collab/remote-collab-coworking.html#, or do you think we need to specifically write that in the later subchapter?

**Comment by LauraCarter** [comment]
I think it's all covered there! So I think this issue can be closed now :)
