### ISSUE TITLE
Plan the BioHackathon - Book Dash in November 2020

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1333]
### What needs to be done?

*Tasks are being coordinated by @malvikasharan, you are welcome to support her with your ideas and suggestions.*

- [x] Finalise dates based on the location and organisers' availability: 9-13 November 2020
- [x] Book location for in-person events
- [x] Set up an online platform ([Zoom](https://zoom.us/), or other accessible software) for remote collaboration - Malvika's Zoom
- [x] Set up shared notes: main event, predash drop in calls and feedback
- [x] Set up a form for application by updating the previous version of the form
- [x] Discuss with co-organisers if some resources (such as email drafts or templates) need to be updated
- [x] Write a short description for online advertisement
- [x] Clearly state the following information in the registration form and communicate by email with the selected participants:
  * what financial support will be available for either online or in-person events
  * What arrangements will be available for online (such as online helpers and designated mentors) or on-site (such as quiet room and child care) for in-person events
  * Include accessibility information such as live captioning for in-person events and quiet room/child nursing room for in-person events
  * Mention the maximum limit for financial support request for online (such as for headphones) and in-person (such as for travel and accommodation) events
- [x] Announce in the newsletter and promote on twitter
- [ ] Think about who else needs to be invited, like Artists, speakers, more diverse participants
  - [x] Scriberia
  - [x] Last book dash attendees
  - [ ] REG: GH
- [x] Identify helpers from the core members and invite them
- [x] Send a reminder in next newsletters with more details if needed
- [x] Set an Eventbrite page with a registration code for the selected participants
- [x] Close the application round in time
- [x] Set-up a form for reviewing applications
- [x] Review applications in a designated panel using Book Dash Rubrics for selection
- [x] Send an email to the selected attendees with registration
- [x] Send an email to the unselected attendees with feedback
- [x] Update presentation for introducing the project to the participants on day-1 of the book dash
- [x] Update shared HackMD for pre-event calls
- [x] Provide details on Code of Conduct, contribution guideline and ways to get involved in an ongoing discussion: create a dedicated page on GitHub
- [ ] Prepare a care-package as a token of thanks for everyone involved

**Additional task for an online Event**

- [x] State the requirement and expectation of the event
  * An active GitHub account
  * Some experience with using GitHub
  * Familiarity with contribution guideline and Code of conduct
  * A full working day time commitment
  * Willingness to collaborate with others
  * Participation at least one pre-book-dash call or a Collaboration Cafe
- [x] Discuss with the participants the possibility of creating 3 short days, rather than 1 full workday commitment to ensure flexibility
- [ ] Collect address where a care package for them can be delivered

**Comment by KirstieJane** [comment]
- [ ] idea: social breakout sessions in other languages, eg spanish for the ones in sessions 3 and 4 each day.

**Comment by malvikasharan** [comment]
Short blurb for online advert:

The Turing Way (https://the-turing-way.netlify.app) invites you to submit your application to participate in the upcoming Book Dash taking place online from 9-13 November 2020: https://forms.gle/usZkYogVfH2nhNjh7. The deadline is 22 October 2020. 
 
The Turing Way is an open source and community-developed book project that aims to make reproducible, ethical, inclusive and collaborative data science “too easy not to do”. Book Dash is a collaborative event where you'll work with others to add to and improve The Turing Way book.

Successful applicants will be able to claim financial reimbursement to support their participation as laid out in the online chapter: https://the-turing-way.netlify.app/community-handbook/bookdash.html.
