### ISSUE TITLE
[BUG] dead link on the rdm-spreadsheets page

### ISSUE THREAD

**Issue by Remi-Gau** [alan-turing-institute/the-turing-way#1334]
### Bug description

- dead link in [Using spreadsheets for research data](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-spreadsheets.html)
- The following is not a valid DOI.

```
Some of these mishaps are not unique to spreadsheets, but [many are](https://doi.org/10.1186/s13059-016-104).
```

I can happily fix that but I am not sure what the target is supposed to be. :-)

On a related note: maybe I missed it but there seems to be no automatic checks for dead links.

In case you are looking for an easy way to set one up I have started using this one and can give a hand setting it up.

https://github.com/marketplace/actions/markdown-link-check

**Comment by malvikasharan** [comment]
Thanks @Remi-Gau. We will add this to our Hacktoberfest issue :)

**Comment by malvikasharan** [comment]
@all-contributors, please add @Remi-Gau for bug.

**Comment by JimMadge** [comment]
Looking at the git blame for `book/website/reproducible-research/rdm/rdm-spreadsheets.md`, it seems that the DOI got truncated and [was previously `10.1186/s13059-016-1044-7`](https://github.com/alan-turing-institute/the-turing-way/commit/27314d4ce5a9bc53327f8e013300df2497d234ff).

I will open a PR to revert this. @malvikasharan The article you suggested is on a very similar subject (gene names being changed in excel), would linking to both articles be better?

**Comment by malvikasharan** [comment]
Hey @JimMadge adding both examples would be great. Thank you 😊
