### ISSUE TITLE
[Translate] README Spanish translation 

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/the-turing-way#1337]
### Summary

As suggested by @malvikasharan in #1335, @camachoreina and I we will be translating the README to Spanish.
### What needs to be done?

- [ ] *README.md translation*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by alanverdugo** [comment]
Hello @crangelsmith , do you still need help with this issue?
Please let me know. Thanks.
