### ISSUE TITLE
January Sprint Hack md

### ISSUE THREAD

**Issue by annakrystalli** [alan-turing-institute/the-turing-way#135]
Continuous integration etc: https://hackmd.io/LiDeD6D7TZSTUUDZa8kk1w

Binder: https://hackmd.io/SmqXlWBhRGa8AWOZhDsdzQ#

**Comment by pherterich** [comment]
Linking this to #146 #147 and #148 for @r-j-arnold 's attention to be closed when the content from the hackmds has made it into the chapter drafts.

**Comment by r-j-arnold** [comment]
Material added to the relevent chapters.
