### ISSUE TITLE
Plan Feb sprint in London

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#138]
## Detailed description
Things to do
- [x] send around doodle to find dates - @KirstieJane one for you to set up as you might be busiest? 
  * Here's the link: https://doodle.com/poll/fmqiiyedd995gd8u
- [x] complete doodle
  * Please reply by Thurs 24 Jan
- [x] choose a date
  * Wed 20 Feb & Thurs 21 Feb
- [x] book rooms at the Turing
  * Wed: Jack Good, 9 - 5
  * Thurs: Jack Good, 9 - 3; Lovelace, 3 - 5
- [x] let reception know: @pherterich @r-j-arnold for both days @rosiehigman on Wed 20 Feb only
- [x] book travel and accommodation (*KW: Requests sent on Monday morning 18 Feb*)
 * for @pherterich train on 20 Feb 2019 from Birmingham New Street (7:10) to London Euston (8:31), return on 22 Feb from London Euston (19:13) to Birmingham New Street (21:20) and hotel on 20 & 21 Feb
 * for @r-j-arnold train on 19 Feb Sheffield 15:00 -> st pancras 17:12, return on the 21st 19:01 -> 21:25 and hotel on 19 & 20 Feb
 * for @rosiehigman train on 19 Feb 17.35 Manchester Piccadilly - London Euston 19.45, return on 20 Feb 20.00 Euston - Manchester Piccadilly 22.04, hotel on 19 Feb
- [x] create agenda
  * Workshops: content, who delivers what, set up any additional info pages, CoC, evaluation and feedback collection - Details in #217

**Comment by pherterich** [comment]
Agenda item suggestions:
following discussion in #96 : investigate ways to collect feedback from workshops

**Comment by KirstieJane** [comment]
Hey @pherterich @rosiehigman @r-j-arnold @annakrystalli @sgibson91 @LouiseABowler @alexmorley @martintoreilly - Feb sprint is going to be on Wed 20 & Thurs 21 Feb. Please give a little emoji reaction to confirm you've seen this. I know not everyone can make it, but I think those were the best dates from the doodle!!

**Comment by pherterich** [comment]
@KirstieJane do you want our travel accommodation needs again? I feel time is flying and we're pretty close again already...

**Comment by pherterich** [comment]
@r-j-arnold @annakrystalli @rosiehigman @alexmorley if you are attending the sprint, could you add the trains you'd like to take below and accommodation needs as usual? Thank you!

**Comment by r-j-arnold** [comment]
Train Sheffield 15:00 -> st pancras 17:12 on the 19th. Return on the 21st 19:01 -> 21:25.

Accomadation for the 19th and 20th please!

**Comment by rosiehigman** [comment]
17.35 Manchester Piccadilly - London Euston 19.45 on 19th, 20.00 Euston - Manchester Piccadilly 22.04 on 20th. Accommodation on 19th please

**Comment by annakrystalli** [comment]
Hi @pherterich I'm actually not joining this sprint as my family are visiting next week :)

**Comment by pherterich** [comment]
@annakrystalli I thought I read that but wasn't sure. Enjoy time with your family!

**Comment by alexmorley** [comment]
I'm going to be in New York but will be following along. Just caught up on all the slack messages today. All looking awesome :smile:
