### ISSUE TITLE
Misleading section on auto-formatting

### ISSUE THREAD

**Issue by JimMadge** [alan-turing-institute/the-turing-way#1390]
### Summary

The Style Guide contains a section about [auto-formatting](https://the-turing-way.netlify.app/community-handbook/style.html#auto-formatting) which describes setting up prettier.io to run pre-commit in the same way as it will run in CI. Although this was [previously configured](https://github.com/alan-turing-institute/the-turing-way/pull/646), it looks like the pre-commit configuration and CI step were [later removed](https://github.com/alan-turing-institute/the-turing-way/pull/908) as prettier.io's style didn't align well with the project. However, it looks like the documentation about setting up pre-commit and the prettier.io hook have remained which is a bit misleading.

### What needs to be done?

- [ ] Remove the auto-formatting section

---

**Comment by malvikasharan** [comment]
Thanks @JimMadge, I agree with you. The style guide should be updated as the auto formatting is outdated. We can open another issue of creating some CI actions that could help with some formatting (besides the surrent one on Latin word checker).

**Comment by JimMadge** [comment]
@malvikasharan I'm happy to open a PR updating the style guide.

The original issue on auto-formatting (#630) is still open. However, that issue became largely about implementing prettier.io so perhaps it is best to close that issue and create a new one? Also, it might be interesting to look at other types of CI tools, like a checker for dead links, grammar or prose.
