### ISSUE TITLE
Invite contribution to the subchapters that are missing contents or are incomplete 

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1391]
### Summary

Some of the content in the book are either missing or incomplete For example, the Licensing chapter in the Guide for Reproducible Research contains a Data Licenses subchapter that is empty. As I work through the book, I will use this issue to keep track of other such chapters that need to have content written for them. Any members of the community willing to help out in writing the content, can! 

### What needs to be done?

Write content for the following chapters and sub chapters:
- [x] **Data Licences** sub-chapter of the Licenses chapter in the Guide to Reproducible Research. The markdown file can be found here: `the-turing-way\book\website\reproducible-research\licensing\licensing-data.md`
- [ ] **Resources for Code Reviewing** sub-chapter of the Code Reviewing Process Chapter in the Guide to Reproducible Research. The markdown file can be found here: `the-turing-way\book\website\reproducible-research\reviewing\reviewing-resources.md`
- [ ] **Risk Assessment** chapter landing page of the Guide to Reproducible Research. The markdown file can be found here: `the-turing-way\book\website\reproducible-research\risk-assess.md`
- [ ] **Summary of Risk Assessment** subchapter of the Guide to Reproducible Research (I think this can also be renamed to `Resources` so that it is consistent with the rest of the book). The markdown file can be found here `the-turing-way\book\website\reproducible-research\risk-assess-resources.md`
- [ ] **Leadership in Data Science** chapter of the Guide to Collaboration. Markdown file can be found here: `the-turing-way\book\website\collaboration\leadership.md`
- [x] **Ethical Decisions in Preclinical Research** subchapter of the Guide for Ethical Research. The markdown file can be found here: `the-turing-way\book\website\ethical-research\preclinical-research.md`

### Who can help?

* Anyone with knowledge of the missing content

---

### Updates

* A PR (#1448) was raised for the Data Licenses chapter. It is currently being worked on based on the comments on the PR

**Comment by malvikasharan** [comment]
Hey @paulowoicho. Thank you for opening this very useful issue. I am updating the header to make sure we think about such work in terms of the processes and methods to involve others.

**Comment by malvikasharan** [comment]
Data Licensing chapter is in this PR #1185  but needs some work as listed in the comments.

**Comment by malvikasharan** [comment]
> Data Licensing chapter is in this PR #1194 but needs some work as listed in the comments.

updated in https://github.com/alan-turing-institute/the-turing-way/pull/1448

**Comment by EstherPlomp** [comment]
Hello from 2023 @paulowoicho, @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
