### ISSUE TITLE
[BUG] Netlify shows "Not Found" instead of The Turing Way Book

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#1393]
### Bug description

The Turing Way book is down :sob:

#### Expected behaviour

- [x] We (anyone on the internet) can see The Turing Way book 
- [x] We (anyone on the internet) can see The Turing Way netlify page

#### Actual behaviour

- [ ] As of 9am on 12 October https://the-turing-way.netlify.app shows "Not Found" in multiple browsers for multiple people
- [ ] As of 9am on 12 October https://app.netlify.com/sites/the-turing-way gives a Page Not Found error.

### How to reproduce

* https://the-turing-way.netlify.app
* https://app.netlify.com/sites/the-turing-way 

### Your personal set up

- OS: Windows

- Browser: Chrome & Firefox

## Tried so far

- [x] As of 9:30am on 12 October, Netlify status is green 🟢 so its not that https://www.netlifystatus.com
- [ ] I think we were building from @alexmorley's Netlify account so I wonder if he can check to see if _he_ can access the Netlify page?

**Comment by EstherPlomp** [comment]
https://the-turing-way.netlify.app: Not Found
https://app.netlify.com/sites/the-turing-way: I see the welcome page of Netlify
OS: Windows
Browser: Firefox

Not sure if this is what you wanted as replies to the issue but here you go!

**Comment by KirstieJane** [comment]
Thanks @EstherPlomp - I'm mostly using this as a place for us to not all discover the problem independently 😆 And to track what we've done. but also really helpful to know that is isn't just me 😬 

I've pinged @alexmorley - fingers crossed there was a netlify change at that end and it will all be figured out soon 🤞🏻

**Comment by sgibson91** [comment]
We should 100% more to a generalised Netlify account that more members of the core team can access as well. We could keep the pass word in the repo, encrypted with git-crypt and then just keep track of who has the git-crypt key (this could also work for other passwords that need to be accessed by multiple people and/or passed from one team member to another, such as Zenodo, Gmail, etc)

**Comment by KirstieJane** [comment]
We're back! Yay! Thank you @alexmorley!!

Lets leave this issue open until we've figured out the best way to hand ownership of the netlify build to someone who is a current core contributor (or a group, as @sgibson91 suggests above).

**Comment by martinagvilas** [comment]
What is the main reason for using Netlify as opposed to Github pages? Using the second people with writing access to the repository would have access to the deployment, there are no problems with payment, and no cap on bandwidth. But I'm probably missing an advantage of Netlify out of lack of experience 🤣  (or a disadvantage of Github pages in this case)

**Comment by sgibson91** [comment]
@martinagvilas The biggest advantage is the deployment preview on PRs https://github.com/alan-turing-institute/the-turing-way/pull/1394#issuecomment-707059983

**Comment by alexmorley** [comment]
Yeah that's one main advantage. The other is that jupyter book requires a build step so (AFAIU) to host on github pages we'd either have to a) build it locally and push to a special branch that contains the static html etc (this is what I do for my personal website, it's not so bad but it's not as friendly) or b) set up a github action to do that for us (this wasn't an option when the turing way has started as github actions didn't exist but it's potentially a nice route to go down now - also it would probably be "free").

Other thing to note is that you can setup access to a netlify build via organization so it'd be to give all Turing folks access for example. It may even be worth just starting a Turing Institute netlify account if sticking with netlify is worth it?

In the meantime please bug me whenever. Always happy to touch base with this awesome community!

**Comment by sgibson91** [comment]
> Other thing to note is that you can setup access to a netlify build via organization so it'd be to give all Turing folks access for example. It may even be worth just starting a Turing Institute netlify account if sticking with netlify is worth it?

Is it just orgs or can it grant access to teams as well? As I think there might be a Turing Way Core team under the Turing org already. I manage the software tools, like GitHub, for the Turing now so it would be within my service area to investigate this! Otherwise, I think we should set up a _Turing Way_ account, rather than a Turing Institute one.

**Comment by alexmorley** [comment]
Yeah. So the cheapest way will be to set up a turingway account with an email address/password. The Pro ones where you can add team members cost a fair bit more I think.

**Comment by EstherPlomp** [comment]
Hello from 2023 all! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
