### ISSUE TITLE
Introduction to the "Project Design Handbook"

### ISSUE THREAD

**Issue by NZR** [alan-turing-institute/the-turing-way#1395]
### Summary

Following a short meeting between Malvika Sharan, Yasemin Turkyilmaz-van Velden @yaseminturkyilmaz and myself (Nicolas Dintzner @NZR), we thought we could get started with the introduction to the "Project Design Handbook".  

The objective is to provide a project overview, in chronological order (from preparation to archival), with key steps and references to the relevant section of the book. 

### What needs to be done?

- [ ]  Create a "bullet-point" list of the key steps identified in the following publication (https://www.sciencedirect.com/science/article/pii/S2666389920301331)  
- [ ]  Provide minimal, yet relevant, highlight of each point (based on the content of the publication)
- [ ]  link each item to the right chapter
- [ ]  any further clean-up (as the content found in the paper may not be always ideal for the book! Up for discussion)

### Who can help?

* @marianaiv is attempting the first draft - Book Dash attendees are welcome to collaborate with her
* *Nicolas and Yasemin will be tagged for review*
* *We will need assistance for the consistency checks + formatting/content review by Turing way people :)*

---

### Updates

None yet!

**Comment by malvikasharan** [comment]
@all-contributors please add @NZR for idea.

**Comment by malvikasharan** [comment]
@all-contributors please add @yaseminturkyilmaz for idea.

**Comment by marianaiv** [comment]
First draft: https://hackmd.io/@marianaiv/BJQyvZJKu

**Comment by malvikasharan** [comment]
That looks good @marianaiv. You might find some useful content here: https://docs.google.com/document/d/1VZkxGZeleLidPDMuNl5QB7AWE2MDC-OhgqzYwU63m1U/edit
