### ISSUE TITLE
[BUG] Fix Markdown formatting of non-consecutive headers: Style guide

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1398]
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

# Summary of Issue

- Part of #1321 

_The Turing Way_ chapters are written in [MarkDown format](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf). Each chapter has a header (top-level header denoted by single # - h1 tag) and subheaders (## - h2, ### - h3, #### - h4 tags). 

A standard expected format should follow `#` (h1 tag) -> `##` (h2 tag) -> `###` (h3 tag) and so on in sequence.

## What needs to be done

The [Style guide chapter](https://the-turing-way.netlify.app/community-handbook/style.html) in the community handbook have non-consecutive header levels (instead of starting from h1, they start at h2, or some chapters have h1->h3, or h2->h4 instead of h1->h2->h3->h4 headers) which needs to be fixed.

- [x]  all h3 tags should be updated to h2 tags: [community-handbook/style.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style.md)
- [x]  The top level starts with h3 tag, update that to h1 and all h4 should be updated to h2: [community-handbook/style/style-citing.md](https://raw.githubusercontent.com/alan-turing-institute/the-turing-way/master/book/website/community-handbook/style/style-citing.md)
- [x]   The top level starts with h3 tag, update that to h1 and all h4 should be updated to h2: [community-handbook/style/style-crossref.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style/style-crossref.md)

### Who can help

Anyone who would like to participate in Hacktoberfest or contribute to The Turing Way GitHub repository for the first time easier to do locally (by git) but not mandatory

### About Hacktober and The Turing Way

Hacktoberfest is a month-long celebration of Open Source Projects where the goal is to make 4 Pull Requests during the month.

#### A bit about Git
If you’re new to git then here are [some instructions](https://help.github.com/articles/signing-up-for-a-new-github-account/) to help you get going. Remember that you can ask us any questions you need to along the way.

A [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) (what Hacktober is measured on) lets you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

In this issue, we’ve outlined what needs to be done, and how you can go about addressing it. Once the issue has been addressed, you can submit a Pull Request for review (tell us what you’ve done) and we can incorporate it into The Turing Way.

We’ve also created this special Hacktoberfest tag to make it easy for you to find other places to contribute if you’re new.
In the spirit of Hacktoberfest, please only do a few of these to submit your PR so that we can learn and grow as a community together.

#### Our Community
We want to ensure that every user and contributor feel welcome, included, and supported to participate in The Turing Way community. We welcome all contributions to this project via GitHub issues and pull requests. Please read our [Contributors document](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md) and our [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md) while you engage in The Turing Way. As you start contributing to The Turing Way, don't forget that your ideas are more important than perfect pull requests. ❤️

If you have any questions that aren't discussed below, please let us know through one of the many ways to get in touch.

**Comment by ikayz** [comment]
@malvikasharan I would like to also work on this issue.
