### ISSUE TITLE
Add Writer's Free Grammar Checker to Page

### ISSUE THREAD

**Issue by Cybernick1993** [alan-turing-institute/the-turing-way#1419]
Hey guys,

I was browsing your website today and came across this page: https://the-turing-way.netlify.app/community-handbook/newsletters/newsletters-process.html

I noticed that you referenced grammarcheck.net’s grammar checker on the page, so I wanted to introduce you to Writer’s alternative!

Grammarcheck.net’s tool checks for simple things like spelling, grammar, and punctuation. Our tool takes it a step further with the addition of these features:

Helps users simplify their language for more precise writing.
Suggests sentence breaks to improve readability.
Checks for language redundancies.
You can check it out here with some pre-populated text: https://writer.com/grammar-checker/

If you like the tool, would you be able to also give Writer a mention on your page?

While Writer does offer paid accounts, this tool is 100% free forever.

**Comment by KirstieJane** [comment]
I think we can include this if we find _existing_ members of the community way who use the tool (can be from now!) and want to recommend it.

Otherwise I think we're setting a precedent that is going to be a little difficult to manage if we incorporate every tool that is promoted to us.

@malvikasharan - what do you think?

**Comment by malvikasharan** [comment]
This chapter refers to the newsletter, that at the moment I am responsible for. I use the free version of Grammarly, and I am happy to give this tool a try for this month's newsletter. If this works (if this really helps simplify my language - which is a long term goal 👍), I'd be happy to add this tool as a recommendation.

**Comment by Cybernick1993** [comment]
@malvikasharan that'd be great! If you decide not to include it, I'd love to hear your feedback on how we can make it better!

**Comment by malvikasharan** [comment]
Hey @Cybernick1993, I gave your tool a try for my draft in https://github.com/alan-turing-institute/the-turing-way/pull/1452. It doesn't particularly fit for my purpose. It worked quite well for creating clarity of some sentences (for example by removing the passive voice), but here are some things that I think were not particularly helpful for me:
1. It follows the rule "numbers up to nine should always be written in words" - but that's not applicable when writing dates or creating a listed items
2. formatting is lost, which would not allow me to simply copy-paste the corrected documents - meaning that I will have to manually correct all the suggestions in my original document
3. It doesn't recognise names (and tries to correct them)
4. It doesn't allow me to keep my document in British English (unless there was some setting that I missed using)
5. It doesn't recognise numbers as part of a text, e.g.  .33 in [November 2020Vol.33 (pp.34-37)] is not be recognised as part of a text but as a mathematical item (that asks me to correct it to 0.33) - sure that can be ignored by me, like most suggestions but I think raising so many errors can discourage users like me to assume that there are more errors than "there actually is"

I hope this feedback is useful, and it also justifies that I would not be recommending it in my newsletter chapter.
Thank you once again for sharing this tool with me, I look forward to using it in the future.
