### ISSUE TITLE
A central page to link to, explaining that the book does not constitute legal advice

### ISSUE THREAD

**Issue by LauraCarter** [alan-turing-institute/the-turing-way#1469]
## Detailed description

 * This issue is a place to discuss matters relating to the writing of the chapter on "this book is not a substitute for legal advice"
 * This chapter is being written in https://github.com/alan-turing-institute/the-turing-way/pull/1498
 * This chapter is being developed in https://github.com/LauraCarter/the-turing-way/blob/legal-disclaimer/book/website/afterword/legal-disclaimer.md

### Table of contents

- Legal disclaimer
- Short note that laws are different in different jurisdictions
- Very brief note on how to find legal advice

### Discussion points/related issues

More and more chapters in the book mention legislation and it would be nice to link them all to a central page explaining that The Turing Way is not a substitute for legal advice

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [x] Write chapter outline
 - [x] Add material to the chapter
 - [x] Combine materials into a readable chapter
 - [x] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

**Comment by LauraCarter** [comment]
This is some text from the licencing chapter that we are currently copying and pasting into lots of chapters, which seems inefficient. 

_Disclaimer: Good legal advice is timely, specific, and given by an expert; this chapter is none of these. It was written by an engineer, not by a lawyer, and it’s a heavily simplified overview of a very complex field. The intent is to give you an overview of the basics, so that you will know when to check whether something you want to do has potential legal ramifications. Don’t make any important decisions based solely on the contents of this chapter._

**Comment by LauraCarter** [comment]
@MariaEriksson, @EstherPlomp and I have been discussing where this should live: perhaps in the Afterword? Any other thoughts?

**Comment by paulowoicho** [comment]
I think putting this chapter in the Afterword is a great option. Although, I think some readers may appreciate knowing this information beforehand, so expanding Welcome to have its own chapters and including this Disclaimer chapter there might be another option.
