### ISSUE TITLE
Adding a page for git rebase and squash 

### ISSUE THREAD

**Issue by bsipocz** [alan-turing-institute/the-turing-way#1492]
### Summary

These are very powerful and useful tools that can be utilized in any projects, either to keep the commit history clean and organized or to e.g. remove files accidentally added to the repo (e.g. big binary files, etc.)

**Comment by EstherPlomp** [comment]
Hello from 2023 @bsipocz! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!

**Comment by bsipocz** [comment]
I like the idea of the meta issue of collecting old ideas, however I don't think it's likely than any unaddressed enhancement ideas will be picked up/or well be easy to identify, if the original issue is referred but it's closed, especially when it's closed as fixed rather than with with grey "won't fix" status.

**Comment by EstherPlomp** [comment]
Thanks for that @bsipocz ! We didn't realise there was a not planned issue option when closing the issues!

**Comment by TheAbstract** [comment]
@bsipocz @EstherPlomp - git rebase and squash are powerful but this issue seems to conflict with guidelines given here 
-> [make-the-changes-youve-discussed](https://github.com/alan-turing-institute/the-turing-way/blob/main/CONTRIBUTING.md#3-make-the-changes-youve-discussed):

> Please do not re-write history! That is, please do not use the [rebase](https://help.github.com/en/articles/about-git-rebase) command to edit previous commit messages, combine multiple commits into one, or delete or revert commits that are no longer necessary.
>
