### ISSUE TITLE
Onboarding new Github users chapter

### ISSUE THREAD

**Issue by EKaroune** [alan-turing-institute/the-turing-way#1537]
### Summary

Chapter to explain in more detail how to start to use Github for researchers that have no previous experience of Github or of coding. Will also cover why Github is good for collaborative reproducible projects and why version control is needed. Instructions for use of Github will be based around using it through a web browser.

### What needs to be done?

- [x] Plan of chapter
- [x] Incorporate resources already written in to the plan
- [x] Writing of the first draft
- [x] Adding annotated images of github screen shots
- [x] Add glossary
- [ ] Add resources for extra help with Github accessibility
- [x] Share with other contributors for feedback
- [x] Edit for markdown formatting and check style 

### Who can help?

* *Contributors that are new to using Github* - please comment to tell me if I have missed anything out
* *Github pros to check for any technical mistakes please.*
* *General checks for text editing, markdown editing and style checking* 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by EstherPlomp** [comment]
Hello from 2023 @EKaroune ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
