### ISSUE TITLE
Chapter proposal: Contributing to open source for organizations

### ISSUE THREAD

**Issue by choldgraf** [alan-turing-institute/the-turing-way#1554]
### Summary

I recently published [a short blog post](https://predictablynoisy.com/posts/2020/organizations-help-oss-guide/) to provide some tips and ideas for organizations that wish to contribute to open source projects/communities. @KirstieJane suggested that I open an issue here to discuss if it was of interest to contribute to the Turing Way. 

### What needs to be done?

- [ ] TW folks take a look at the blog post and decide if the content is of interest: https://predictablynoisy.com/posts/2020/organizations-help-oss-guide
- [ ] @choldgraf makes a first pass at moving this to TW
- [ ] A few rounds of edits to adapt the content to fit with TW style/structure, maybe even some additions or modifications from TW members who would like to provide their own experience and thoughts? :-)

### Who can help?

Anybody with experience in working w/ open source communities (esp. who are also embedded in an organization).

---

**Comment by bsipocz** [comment]
I would be happy to review this/collaborate on this!

**Comment by choldgraf** [comment]
Looping back in on this. Do folks think that this would make the most sense as a sub-section here: https://the-turing-way.netlify.app/collaboration/github-collaboration.html

?

**Comment by malvikasharan** [comment]
I agree on adding this in the guide for collaboration. @bsipocz do you agree?

**Comment by EstherPlomp** [comment]
Hello from 2023 @choldgraf! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
