### ISSUE TITLE
A new sub-chapter for GitHub actions

### ISSUE THREAD

**Issue by BatoolMM** [alan-turing-institute/the-turing-way#1557]
## Detailed description

Writing down a new sub-chapter about GitHub actions with @bsipocz. A discussion about the outline is described in this [HackMD](https://hackmd.io/@bsipocz/SJChYvdYP).
 
 - [x] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
- PR #1558

**Comment by EstherPlomp** [comment]
Hi @BatoolMM! It looks like this was resolved via #1558? Please re-open this issue if that is not the case!

**Comment by BatoolMM** [comment]
Thank you, Esther. Yes, it was resolved!
