### ISSUE TITLE
Idea proposal: cognitive biases/cognitive constraints in data visualisation and understanding

### ISSUE THREAD

**Issue by Marta-MM** [alan-turing-institute/the-turing-way#1572]
### Summary

I looked through the open issues, but I did not seem to find a section addressing cognitive biases in thinking about data/data visualisation. Would it be something we are interested in exploring? It's one of my main research interests so I can provide valuable contribution, insights, and references

### What needs to be done?

- [ ] exploring whether the topic is interesting and appropriate for the book
- [ ] drafting chapter structure
- [ ] gathering relevant material
- [ ] writing up a structured and readable chapter
- [ ] proofread
- [ ] request reviews
- [ ] address reviews
- [ ] merge

### Who can help?

* gathering material: anyone who has the knowledge and is familiar with the topic (psychologists, cog/behav scientists)
* writing up: anyone who has the knowledge and is familiar with the topic
* proofread, check grammar and tone, suggest reviews: anyone!
* address reviews: anyone who has the knowledge and is familiar with the topic

---

### Updates

N/A

**Comment by c-martinez** [comment]
Hi @Marta-MM -- I came across [this tweet](https://twitter.com/OpenAcademics/status/1391468734661890051?s=09) on using matplotlib? Is it useful as reference material?

**Comment by dingaaling** [comment]
Hello from 2023 @Marta-MM! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
