### ISSUE TITLE
Write the chapter on continuous integration 

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#158]
## Detailed description
 - This issue is a place to discuss matters relating to the writing of the chapter on continuous integration.
- This chapter is being written in #146 
- This chapter is being developed on the continuous_integration branch.

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

- [x] Write chapter outline
- [x] Add material to the chapter
- [x] Combine materials into a readable chapter
- [x] Proofread
- [x] Request reviews
- [ ] Address reviews
- [ ] Merge to master branch.

**Comment by pherterich** [comment]
Closing this as it's written and merged and any additional edits are picked up in separate issues and pull requests.
