### ISSUE TITLE
Add different OS and Python versions to CI

### ISSUE THREAD

**Issue by martinagvilas** [alan-turing-institute/the-turing-way#1594]
### Summary

It might be a good idea to change the CI to test the jupyter book build in multiple OS using different Python versions. What do you think?

### What needs to be done?

- [x] upgrade jupyter book by merging #1561 
- [ ] add to [this file](https://github.com/alan-turing-institute/the-turing-way/blob/master/.github/workflows/ci.yml) different OS and python versions

### Who can help?

- @sgibson91 
- @malvikasharan 
- **anyone** with an opinion on this!

---

### Updates

()

**Comment by sgibson91** [comment]
I can pick up the second point. Which versions of Python should we check? I think definitely 3.7 and 3.8, but is jupyter book supported by 3.9 yet?

**Comment by sgibson91** [comment]
I opened #1623 to address this. We have an issue that containerised actions can only run on linux builds, which means HTML proofer will **not** run on windows on mac. We could skip this step on those OSs for now and hope there's a fix later?

**Comment by martinagvilas** [comment]
> I can pick up the second point. Which versions of Python should we check? I think definitely 3.7 and 3.8 (_maybe_ 3.6 but I think that is considered out-of-scope by the Python community now), but is jupyter book supported by 3.9 yet?

I don't know about Jupyter Book's support for python 3.9 actually, but I guess it is not necessary to test this version for now


> I opened #1623 to address this. We have an issue that containerised actions can only run on linux builds, which means HTML proofer will **not** run on windows on mac. We could skip this step on those OSs for now and hope there's a fix later?

Awesome! Since we might get rid of the HTML proofer at some point (#1443) I agree we can skip this step on those OSs
