### ISSUE TITLE
N simple rules for making your code reusable?

### ISSUE THREAD

**Issue by eglerean** [alan-turing-institute/the-turing-way#1596]
### Summary

I had to give a short talk on "how to make your code reusable" for my university (Aalto University, Finland) and wrote this down for the occasion:

Text: https://hackmd.io/@AaltoSciComp/howToMakeYourCodeReusable
Video of the talk: https://www.youtube.com/watch?v=FdMEeUqhJNw&feature=youtu.be

They are a collection of "N simple rules" for reaching multiple levels of code re-usability (from re-running of everything as it was when the original results where created, to more generalisable code that will live its own life). I start from the "reproducibility matrix" and re-adapt those concepts to software re-usability.

My question for you is: do you think this is valuable for the Turing way? It is a text that basically points to many different parts of the Turing way book as well as other hands-on teaching materials (e.g. CodeRefinery), so eventually a section like this could live at the end of the guide for reproducible research, ... but I am unsure if it adds really anything or if readers would find it useful, so I would like to have some fresh independent eyes to check it and give an opinion. 

Side note: I am also happy to get contributors/co-authors if you get inspired by the idea and want to help.

### What needs to be done?

[ ] Here an opinion from core Turing way members who curated the guide to reproducibility part, to see if there is any value in the text/lecture I linked above

### Who can help?

* I am not sure, sorry

---

### Updates

Updates will be here

**Comment by malvikasharan** [comment]
@eglerean first of all, thank you for the issue and apology for the late reply. I really like the scope of this chapter for the guide for reproducible research after code testing and code reviewing chapter. Would you like to create a PR on that?

**Comment by eglerean** [comment]
Thank you @malvikasharan and no apologies! It is fantastic to hear that this sounds interesting to you. I will gather some collaborators first and then we can create a PR (most likely in the new year).

**Comment by c-martinez** [comment]
Hey @eglerean,

I just came across your issue while looking if there were any open issues in the direction of upgrading the reproducible research chapter in the direction of reusable software (so, pretty much what you are proposing here). Really cool resource!

I would like to contribute to this (and perhaps ask some of my colleagues for their help as well). One of my colleagues recently pointed me to these links: 

http://sites.computer.org/debull/A18mar/A18MAR-CD.pdf#page=17
https://drops.dagstuhl.de/opus/volltexte/2016/5817/pdf/dagrep_v006_i001_p108_s16041.pdf#page=23

which also talk about "extendable" and "modifiable" levels of reproducibility (very similar to what you call "GENERALISABLE CODE". So I think perhaps we could also use those concepts here?

Hope to be able to collaborate with you for this contribution!

**Comment by eglerean** [comment]
That’s fantastic! Yes please let’s work on this together in the beginning of 2021. I also have two more collaborators from https://coderefinery.org/ . I’ll set things up after Xmas and let you (and anybody else) know.

**Comment by avakiai** [comment]
Hi all, I would love to contribute to this section. I checked but couldn't find an open PR for this, so sorry if I missed it and should be commenting there. Could someone kindly point me to where any activity on this front is going on? 

Specifically, I wanted to suggest the addition of a particular sub-element to @eglerean's already great tabulation of steps toward re-usability: perhaps we can call it the "**Code Appendectomy**":
Many scientists write analysis scripts that have, at first, many sub-optimal modules (e.g. logics that sort of do what you want but aren't that great or generalizable) and then find better ways of implementing the same code as they progress in the project. But sometimes we leave in those parts that we know aren't adding much, and are maybe even generating data we no longer care about. In the end, you have a script with many "appendices" that can (should) be removed.

**Comment by c-martinez** [comment]
Hi @avakiai, @eglerean  -- will you be joining the book dash from the 17th May? I think that would be a good opportunity to start working on this issue.

**Comment by eglerean** [comment]
Hello! That's a great idea @c-martinez! I will sketch something before that date so we have a base to start. 

I have been following also the developments of the FAIR4RS RDA interest group https://www.rd-alliance.org/groups/fair-research-software-fair4rs-wg 

My humble goal is not to come up with a universal taxonomy of code replicability/reproducibility. Goal of this issue could be more about raising awareness of all the shades of "code re-usability" (from "simple/technical" software environment reproducibility to more generalizable creation of packages and software tools). There are already bits about these issues in the turing way, so this is more of a review chapter that can link the bits (and add what's missing)

**Comment by c-martinez** [comment]
Great @eglerean, that would be good to have a starting point.

If it helps, some of my colleagues recently wrote a [blog about software reuse](https://nl-rse.org/2021/04/02/software-reusability.html). It might be a good starting point.

@avakiai -- the Book Dash runs for the whole week, so I'm sure there should be enough time for you to join via zoom.

**Comment by c-martinez** [comment]
Things to consider when drafting a PR for this issue: 

## Where would this chapter fit in the "Guide for reproducible research"
The most logical place in my opinion would be as a sub-chapter from the [Open Source Software](https://the-turing-way.netlify.app/reproducible-research/open/open-source.html)

## How would it connect to other sections
We should link to relevant sections when touching on the topic, for example
 - [Version control](https://the-turing-way.netlify.app/reproducible-research/vcs.html)
 - [containers](https://the-turing-way.netlify.app/reproducible-research/renv/renv-containers.html)
 - [testing](https://the-turing-way.netlify.app/reproducible-research/testing.html)
 - [packaging](https://the-turing-way.netlify.app/reproducible-research/renv/renv-package.html)
 - [Licencing](https://the-turing-way.netlify.app/reproducible-research/licensing.html)
 - etc

## Rough outline of the chapter
 - Definition of code reuse (reproducible vs. generalisable discussion -- point to existing sections).
 - Why is code reuse important?
 - Steps for making code reusable (point to relevant sections)
 - Useful resources

What do others think about this? Anything I've missed?

@bvreede, you had worked on this before in our blog. Any comments?

**Comment by eglerean** [comment]
Should we draft on a hackmd doc? I can create one

**Comment by bast** [comment]
I would love to contribute. I am in particular interested in the aspects: modularity and adaptability.

**Comment by annefou** [comment]
I'd like to contribute too. And yes @eglerean let's draft a hackmd doc! Thanks.

**Comment by c-martinez** [comment]
@eglerean, if you can create a hackmd doc and link to it here, that would be great.

@bast and @annefou -- nice that you are also willing to contribute :+1:

**Comment by c-martinez** [comment]
Hi @eglerean, @bast, @annefou 👋 

Next week (8th-12th November) there will be another book dash, so I thought it might be a good opportunity to work on this issue. In preparation for next week, I was wondering: did you get very far with that draft hackmd doc? Could you share that, so we can use it as a starting point? Otherwise, I think we can start a new draft.

**Comment by bast** [comment]
Carlos, I am sorry I am not aware of the draft having moved forward. I think we are all still interested but maybe it got forgotten. Thank you for the reminder. Sorry if something happened actually and I missed it.

**Comment by annefou** [comment]
In that case I missed it too! No I don't think anything happened.

**Comment by c-martinez** [comment]
Ok, so if anyone is interested in working in this during the book dash, they could have a fresh start :-)
