### ISSUE TITLE
Present Turing Way at csv,conf,v4

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#160]
Kirstie is a keynote speaker for csv conf!

This issue is a catch all place for comments, suggestions, requests on what to cover etc 🚀✨🥳

For more info: https://csvconf.com

**Comment by alexmorley** [comment]
Maybe it'd be nice to, just before the event, have a curated wishlist of things people could do to help / get involved /test it out?

**Comment by pherterich** [comment]
Closing this as @KirstieJane delivered a great presentation that has been added to the repo already :sparkles:
