### ISSUE TITLE
Write an introduction and motivation chapter

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#161]
## Description
@KirstieJane to write something about 
- the motivation why The Turing Way exists as a project 
- what the goals are - some of this might be vaguely covered in #150 
- maybe something on impact we expect this to have and how we would measure it?

using the initial hackmd for scoping this https://hackmd.io/PLOGTWUmQW2XCUwXIm5z2Q#

**Comment by pherterich** [comment]
@KirstieJane are you happy with what you put together for CollabW19 and we can close this or do you want to keep this open?

**Comment by rainsworth** [comment]
Pinging @KirstieJane again - are we happy to close this? :)

**Comment by HeidiSeibold** [comment]
Hi all, it seems this issue can be closed, right?

@malvikasharan

**Comment by rainsworth** [comment]
I'm closing it :)
