### ISSUE TITLE
[BUG] Maintaining Consistency in github-collaboration.md

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1632]
# Summary of Issue 

_The Turing Way_ project is an open-source endeavour that empowers contributors from around the world to leverage their skills, knowledge and expertise to build and expand its content.
_The Turing Way_ guides are evolving with multiple chapters co-developed by individuals from varied backgrounds, who are all passionate about sharing knowledge around data science and research.
To sustain and support this vibrant community, _The Turing Way_ book must remain consistent and accessible as it evolves. 
Although the [style guide](https://the-turing-way.netlify.app/community-handbook/style.html) chapter already outlines guidelines for keeping a consistent style across the book, not all chapters follow these suggestions as they have been written asynchronously by different authors.

We have curated a consistency checklist that chapters in _The Turing Way_ need to pass to help us maintain a consistent style across the book. However, we need your help to push this forward!

For reference, the checklist is discussed in the chapter on [maintaining consistency](https://the-turing-way.netlify.app/community-handbook/consistency.html) in _The Turing Way_. There you can also find useful instructions on how to address these issues

## What needs to be done

This issue focuses on maintaining consistency in [Collaborating on Github chapter](https://the-turing-way.netlify.app/collaboration/github-collaboration.html) Guide for Communication. To help with this, we invite contributors to do the following:

- **File Location**: [book/website/collaboration/github-collaboration.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/collaboration/github-collaboration.md)
- **Latest commit when this issue was created**:  cb2a9a9

#### File Specific Checklist

- [ ] The landing page should follow the [template for landing pages](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-landing-page.md). Write a summary of the chapter for the summary section
- [ ] Change `Prerequisites/recommended skill level` to `Prerequisites`
- [ ] Change `Why this is useful` to `Motivation and Background`
- [ ] Change the title from `Collaborating on Github\Gitlab` to `Collaborating on Github`
- [ ] Add a label to all headers as recommended in the [landing page template](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-landing-page.md)
- [ ] Use `MyST` to format fix the link in the broken link in Prerequisites table. 
  - [ ] `[Experience with version control](../../reproducible-research/version_control/version_control)` in line 8 should be `{ref}Experience with Version Control<rr-vcs>`
- [ ] Check for proper grammar usage

#### How you can help
1. Please pick a consistency check from the checklist above (check it off from the issue description)
2. Comment below what consistency check you would like to work on
3. Work on your contributions locally or on Github
4. Raise a PR for your contributions to be reviewed and integrated in _The Turing Way_ repo!

### Who can help

Anyone who would like to make the _The Turing Way_ as consistent and polished as possible. We especially welcome new contributors to try their hand on this!

For any questions, comments, suggestions, or feedback, please comment below :muscle:

**Comment by afzal442** [comment]
Taking up this

**Comment by paulowoicho** [comment]
@afzal442 awesome! Feel free to ping me to review your PR when you're through
