### ISSUE TITLE
[BUG] Maintaining Consistency github-contributors.md

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1635]
# Summary of Issue 

_The Turing Way_ project is an open-source endeavour that empowers contributors from around the world to leverage their skills, knowledge and expertise to build and expand its content.
_The Turing Way_ guides are evolving with multiple chapters co-developed by individuals from varied backgrounds, who are all passionate about sharing knowledge around data science and research.
To sustain and support this vibrant community, _The Turing Way_ book must remain consistent and accessible as it evolves. 
Although the [style guide](https://the-turing-way.netlify.app/community-handbook/style.html) chapter already outlines guidelines for keeping a consistent style across the book, not all chapters follow these suggestions as they have been written asynchronously by different authors.

We have curated a consistency checklist that chapters in _The Turing Way_ need to pass to help us maintain a consistent style across the book. However, we need your help to push this forward!

For reference, the checklist is discussed in the chapter on [maintaining consistency](https://the-turing-way.netlify.app/community-handbook/consistency.html) in _The Turing Way_. There you can also find useful instructions on how to address these issues

## What needs to be done

This issue focuses on maintaining consistency in the [Getting contributors chapter](https://the-turing-way.netlify.app/collaboration/github/github-contributors.html) of the Guide for Collaboration. To help with this, we invite contributors to do the following:

- **File Location**: [book/website/collaboration/github/github-contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/collaboration/github/github-contributors.md)
- **Latest commit when this issue was created**:  f0da923

#### File Specific Checklist

- [x] Change the label from `(rr-github-contributors)=` to `(cl-github-contributors)=`
- [x] Title case all the headers, for example: `Personas and pathways` should be `Personas and Pathways`
- [x] Add labels to each header as described in the [style guide](https://the-turing-way.netlify.app/community-handbook/style/style-crossref.html)
- [x] Check for proper grammar and spelling

#### How you can help
1. Please pick a consistency check from the checklist above (check it off from the issue description)
2. Comment below what consistency check you would like to work on
3. Work on your contributions locally or on Github
4. Raise a PR for your contributions to be reviewed and integrated in _The Turing Way_ repo!

### Who can help

Anyone who would like to make the _The Turing Way_ as consistent and polished as possible. We especially welcome new contributors to try their hand on this!

For any questions, comments, suggestions, or feedback, please comment below :muscle:

**Comment by inwaves** [comment]
Hi @paulowoicho, is there a file in the repo where there are already labels added to the headers so I can use it as an example? What would a label look like for the "Personas and Pathways" header? Something like `(cl-github-contributors-personas-and-pathways)=`?

**Comment by paulowoicho** [comment]
Hi @inwaves. Sorry for the delayed response on this issue and thank you for your interest in working on it!

Yes, there are several chapters in The Turing Way have labels defined for the headers they contain. For example, you can take a look at the [Retrieving and Comparing Versions](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/reproducible-research/vcs/vcs-git-compare.md) file for the Version Control chapter. There are also descriptions and samples of guidelines to follow for coming up with label names. For example, the [Style Guide](https://the-turing-way.netlify.app/community-handbook/style/style-crossref.html#the-turing-way-naming-convention-for-the-labels) has some useful guidance on the naming convention for the different guides in the book, and the [chapter content template](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-content/chapter-content.md) also has some guidelines for label naming as well.

I also think `(cl-github-contributors-personas-and-pathways)=` is fine as it follows the book's label naming recommendations, however you might consider keeping it short as in `(cl-github-contributors-personas)=` or `(cl-github-contributors-pathways)=`. All these options are fine so long as they are "obvious" to other contributors who may want to use the labels for cross-referencing in the future.

**Comment by inwaves** [comment]
Thanks @paulowoicho! PR #1801 raised.
