### ISSUE TITLE
[BUG] Maintaining Consistency in Managing a New Community and Team chapter

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1638]
# Summary of Issue 

_The Turing Way_ project is an open-source endeavour that empowers contributors from around the world to leverage their skills, knowledge and expertise to build and expand its content.
_The Turing Way_ guides are evolving with multiple chapters co-developed by individuals from varied backgrounds, who are all passionate about sharing knowledge around data science and research.
To sustain and support this vibrant community, _The Turing Way_ book must remain consistent and accessible as it evolves. 
Although the [style guide](https://the-turing-way.netlify.app/community-handbook/style.html) chapter already outlines guidelines for keeping a consistent style across the book, not all chapters follow these suggestions as they have been written asynchronously by different authors.

We have curated a consistency checklist that chapters in _The Turing Way_ need to pass to help us maintain a consistent style across the book. However, we need your help to push this forward!

For reference, the checklist is discussed in the chapter on [maintaining consistency](https://the-turing-way.netlify.app/community-handbook/consistency.html) in _The Turing Way_. There you can also find useful instructions on how to address these issues

## What needs to be done

This issue focuses on maintaining consistency in the [Managing a New Community and Team chapter](https://the-turing-way.netlify.app/collaboration/new-community.html) of the Guide for Collaboration. To help with this, we invite contributors to do the following:

- **Chapter Location**: [book/website/collaboration/new-community](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/website/collaboration/new-community)
- **Latest commit when this issue was created**:  5c209e5

#### Chapter Specific Checklist

- [Landing Page](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/collaboration/new-community.md)
  - [ ] Check for proper grammar usage and spelling
  - [ ] Add this label to the top of the file: `(cl-new-community)=`
  - [ ] Remove height parameter (`500px`) from image formatting

- [Guide to Planning a Community](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/collaboration/new-community/new-community-guide.md)
  - [ ] Check for proper grammar usage and spelling
  - [ ] Add this label to the top of the file: `(cl-new-community-guide)=`
  - [ ] Add a label to each item in the checklist. See the [chapter content template](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-content/chapter-content.md) for recommendations

- [Addressing Technical Issues](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/collaboration/new-community/new-community-techissues.md)
  - [ ] Check for proper grammar usage and spelling
  - [ ] Change the label at the top of the file from `(cm-new-community-techissue)=` to `(cl-new-community-techissue)=`
  - [ ] Add a label to each item in the header. See the [chapter content template](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-content/chapter-content.md) for recommendations

- [Valuing Diversity and Differences](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/collaboration/new-community/new-community-differences.md)
  - [ ] Check for proper grammar usage and spelling
  - [ ] Change the label at the top of the file from `(cm-new-community-differences)=` to `(cl-new-community-differences)=`
  - [ ] Add a label to each item in the header. See the [chapter content template](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/templates/chapter-template/chapter-content/chapter-content.md) for recommendations

- [ ] Add a Checklist and resources subchapter as demonstrated in the [chapter template](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/templates/chapter-template/chapter-content)

#### How you can help
1. Please pick a consistency check from the checklist above (check it off from the issue description)
2. Comment below what consistency check you would like to work on
3. Work on your contributions locally or on Github
4. Raise a PR for your contributions to be reviewed and integrated in _The Turing Way_ repo!

### Who can help

Anyone who would like to make the _The Turing Way_ as consistent and polished as possible. We especially welcome new contributors to try their hand on this!

For any questions, comments, suggestions, or feedback, please comment below :muscle:

**Comment by inwaves** [comment]
@paulowoicho I can take this issue.

**Comment by paulowoicho** [comment]
Sure thing! Feel free to tag me to review your PR when you're done

**Comment by inwaves** [comment]
@paulowoicho There's a similar issue with consistency where we title-case'd all headings. Should I title case all headings here also, all the way down to H3s?

For example, should:
```## A checklist for planning collaboration in your project```

be:
```## A Checklist for Planning Collaboration in Your Project```

**Comment by paulowoicho** [comment]
HI @inwaves! Sorry again for the delayed response on this! Yes, title-casing the headings here is a good idea
