### ISSUE TITLE
[BUG] Maintaining Consistency in the Guide for Ethical Research

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1640]
# Summary of Issue 

_The Turing Way_ project is an open-source endeavour that empowers contributors from around the world to leverage their skills, knowledge and expertise to build and expand its content.
_The Turing Way_ guides are evolving with multiple chapters co-developed by individuals from varied backgrounds, who are all passionate about sharing knowledge around data science and research.
To sustain and support this vibrant community, _The Turing Way_ book must remain consistent and accessible as it evolves. 
Although the [style guide](https://the-turing-way.netlify.app/community-handbook/style.html) chapter already outlines guidelines for keeping a consistent style across the book, not all chapters follow these suggestions as they have been written asynchronously by different authors.

We have curated a consistency checklist that chapters in _The Turing Way_ need to pass to help us maintain a consistent style across the book. However, we need your help to push this forward!

For reference, the checklist is discussed in the chapter on [maintaining consistency](https://the-turing-way.netlify.app/community-handbook/consistency.html) in _The Turing Way_. There you can also find useful instructions on how to address these issues

## What needs to be done

This issue focuses on maintaining consistency in the [Guide for Ethical Research](https://the-turing-way.netlify.app/ethical-research/ethics-intro.html). To help with this, we invite contributors to do the following:

- **Guide Location**: [book/website/ethical-research](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/website/ethical-research)
- **Latest commit when this issue was created**: 8c0a340

#### File Specific Checklist

[Landing Page](https://the-turing-way.netlify.app/ethical-research/ethical-research.html)
- [ ] Format image using MyST - see the style guide for [recommendations](https://the-turing-way.netlify.app/community-handbook/style/style-figures.html)
- [x] Add this label `(er)=` to the top of the file
- [ ] Check for proper grammar and spelling

[Ethical Decisions in Preclinical Research](https://the-turing-way.netlify.app/ethical-research/preclinical-research.html)
- [ ] Chapter is incomplete. Raise an issue for content to be written for the chapter and for it to be modularised. See the [chapter template](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/templates/chapter-template) for guidance

#### How you can help
1. Please pick a consistency check from the checklist above (check it off from the issue description)
2. Comment below what consistency check you would like to work on
3. Work on your contributions locally or on Github
4. Raise a PR for your contributions to be reviewed and integrated in _The Turing Way_ repo!

### Who can help

Anyone who would like to make the _The Turing Way_ as consistent and polished as possible. We especially welcome new contributors to try their hand on this!

For any questions, comments, suggestions, or feedback, please comment below :muscle:

**Comment by JKasmire** [comment]
First contribution - I'll have a look at the (er=) labels

**Comment by paulowoicho** [comment]
> First contribution - I'll have a look at the (er=) labels

Thanks! Look forward to reviewing your PR!

**Comment by JKasmire** [comment]
I have come up against a bit of a barrier. Normally, when I work in git, I just push and pull to my own repos. I don't know the best way of pushing my changes to a repo like this. Should I branch? Fork? At what level? 

Is there a guide for getting started with git on a collaborative repo?

**Comment by ufangYang** [comment]
Hi, I added the figure ("EthicalResearch.jpg) and format image using MyST. please let me know if you did not find them, thanks!

**Comment by paulowoicho** [comment]
> I have come up against a bit of a barrier. Normally, when I work in git, I just push and pull to my own repos. I don't know the best way of pushing my changes to a repo like this. Should I branch? Fork? At what level?

Hi @JKasmire. Since you're a collaborator on this project, you don't have to create a fork of the Turing Way repository. I'd recommend creating a branch, making your changes there, then making a PR when you're satisfied with your changes.

Perhaps you might find [this resource](https://guides.github.com/introduction/flow/) useful. I'll be happy to assist if you have any more questions!

**Comment by paulowoicho** [comment]
> Hi, I added the figure ("EthicalResearch.jpg) and format image using MyST. please let me know if you did not find them, thanks!

Hi @ufangYang, could you send me a link to your PR? I can't seem to find it. Thanks!

**Comment by ufangYang** [comment]
@paulowoicho  Hi I sent a PR, please let me know if you don't see it, thanks!

**Comment by paulowoicho** [comment]
> @paulowoicho Hi I sent a PR, please let me know if you don't see it, thanks!

I've seen it! I left a comment about where you placed the image, but the `myst` formatting looks great
