### ISSUE TITLE
Updating Chapter Landing Pages

### ISSUE THREAD

**Issue by paulowoicho** [alan-turing-institute/the-turing-way#1663]
### Summary

The new chapter template recommends that the `How This is Useful/Why This is Helpful` section of chapter landing pages should be titled as `Motivation and Background`. This issue curates a list of all chapters that still use the old title and welcomes contributors to update them to follow the template's recommendations.

### What needs to be done?

Pick a chapter landing page from the list (tick it off from the list) below and change the title of the `How This is Useful/Why This is Helpful` section to `Motivation and Background`:

- [x] [Open Research](https://the-turing-way.netlify.app/reproducible-research/open.html)
- [x] [Licensing](https://the-turing-way.netlify.app/reproducible-research/licensing.html)
- [x] [Research Data Management](https://the-turing-way.netlify.app/reproducible-research/rdm.html)
- [x] [Reproducible Environments](https://the-turing-way.netlify.app/reproducible-research/renv.html)
- [x] [BinderHub](https://the-turing-way.netlify.app/reproducible-research/binderhub.html)
- [x] [Code Testing](https://the-turing-way.netlify.app/reproducible-research/testing.html)
- [x] [Continuous Integration](https://the-turing-way.netlify.app/reproducible-research/ci.html)
- ~~[ ] [Credit for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/credit.html)~~  **404- Note that this page no longer exists.**
- [x] [Case Studies](https://the-turing-way.netlify.app/reproducible-research/case-studies.html)
- [x] [File Naming Convention](https://the-turing-way.netlify.app/project-design/filenaming.html)
- [x] [Community Communications for Open Source Projects](https://the-turing-way.netlify.app/communication/os-comms.html)
- ~~[ ] [Collaborating on GitHub/GitLab](https://the-turing-way.netlify.app/collaboration/github-collaboration.html)~~ **404- Note that this page no longer exists.**
- [x] [Ethical Decisions in Preclinical Research](https://the-turing-way.netlify.app/ethical-research/preclinical-research.html)

### Who can help?

* Anyone interested in keeping the Turing Way consistent. We especially welcome new contributors to try their hand at this

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by Hanaffi** [comment]
@malvikasharan  Assign?

**Comment by Athene-ai** [comment]
I would like to contribute on this :)

**Comment by paulowoicho** [comment]
Hi @Athene-ai, thanks for your interest in this! You could also request a review from me on your PR when you're done with the task.

**Comment by Athene-ai** [comment]
Many Thanks !
Is there a deadline ?

Daniela

**Comment by paulowoicho** [comment]
There isn't! Feel free to work on it when you have the time

**Comment by Athene-ai** [comment]
Many thanks for the clarification

Daniela

**Comment by dingaaling** [comment]
Hello from 2023 @paulowoicho! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
