### ISSUE TITLE
Create a reference page for Remote Collaboration Chapter

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1666]
### Summary

* We have a chapter on Remote Collaboration: https://the-turing-way.netlify.app/collaboration/remote-collab.html
* It needs a further reading section to add all the guides, papers and tutorials that have been released recently. In this issue, we want to capture those.

### What needs to be done?

- [ ] Test this and delete later

### Who can help?

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by TimRodgers340125go** [comment]
Thanks for your patience

**Comment by malvikasharan** [comment]
Further reading:
- Tips for Teaching Online from The Carpentries Community: https://carpentries.org/blog/2020/03/tips-for-teaching-online/
- Yehudi, Y., Whitney, K. S., & Sharan, M. (2020, November 24). Enhancing the inclusivity and accessibility of your online calls. https://doi.org/10.31219/osf.io/k3bfn
- Woodley, Louise; Pratt, Catherine; Ainsworth, Rachael; Amsen, Eva; Bakker, Arne; Butland, Stefanie; O'Donnell, Stephanie;  Penfold, Naomi;  Pope, Allen; Quigley, Tom;  Tsang, EmmyTsang, Emmy. (2020, July 17). Using virtual events to facilitate community building: event formats. Zenodo. http://doi.org/10.5281/zenodo.3934385

Tutorials:
- Bonus Modules for Carpentries Instructors - online workshop: https://carpentries-incubator.github.io/instructor-training-bonus-modules/
- Facilitating Events and Courses in an Online World: https://moodle.inasp.info/enrol/index.php?id=247

**Comment by malvikasharan** [comment]
New DCC guide: tips on online meetings and events: https://www.dcc.ac.uk/news/new-dcc-guide-tips-online-meetings-and-events
