### ISSUE TITLE
[BUG] Fixing external links

### ISSUE THREAD

**Issue by martinagvilas** [alan-turing-institute/the-turing-way#1670]
### Summary

The way some external links are written trigger a warning in the Jupyter-Book build. External links should be written down with `https://` (e.g.  `https://twitter.com`) and not with `www.` (e.g.  `www.twitter.com`) or without prefix (e.g. `twitter.com`)

### What needs to be done?

Replace the external links written down with `www.` and without prefix, with external links written down with `https://`

The following links should be corrected:

- [x] link `twitter.com/` in line 23 of file `collaboration/new-community/new-community-guide.md`
- [x] link `arewemeetingyet.com` in line 121 of file `collaboration/remote-collab/remote-collab-conferences.md`
- [x] link `osf.io/meetings` in line 187 of file `collaboration/remote-collab/remote-collab-conferences.md`
- [ ] link  `www.slack.com` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md`
- [ ] link `www.twitter.com` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md` 
- [ ] link `www.github.com` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md` 
- [ ] link `www.gitter.im` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md` 
- [ ] link `www.grammarly.com` in line 19 of file `community-handbook/consistency/consistency-language.md`
- [ ] link `arewemeetingyet.com/` in line 89 of file `community-handbook/coworking/coworking-organisation.md`
- [ ] link `theturingway.slack.com` in line 38 of file `community-handbook/newsletters/newsletters-process.md`
- [ ] link `tinyletter.com/` in line 96 of file `community-handbook/newsletters/newsletters-process.md`
- [ ] link `theturingway.slack.com` in line 116 of file `community-handbook/newsletters/newsletters-process.md`

### Who can help?

Everyone!

**Comment by malvikasharan** [comment]
@Hanafi can you please take on this issue?

**Comment by Hanaffi** [comment]
@malvikasharan Yes, Can you assign it to me please?
Btw, Its `Hanaffi` not `Hanafi`  (Double 'n') 😁

**Comment by malvikasharan** [comment]
Corrected your username. It's all yours.

**Comment by malvikasharan** [comment]
Warning that still exist:
- File: afterword/contributors-record 
  - (line  557) broken    https://umontreal.openscience.ca
- collaboration/github/github-maintainers 
  - https://the-turing-way.netlify.app/open-source-comms/intro.html MOVED TO `https://the-turing-way.netlify.app/communication/os-comms.html`
- collaboration/leadership/leadership-stories  
  -  https://grp-bio-it.embl-community.io/blogs/posts/2019-08-29-hackathon-report/ MOVED TO `https://grp-bio-it.embl-community.io/blog/posts/2019-08-29-hackathon-report/`
- collaboration/new-community/new-community-guide 
  - https://about.riot.im/free - 404 Client Error: Not Found for url: https://element.io/free-forever
- collaboration/remote-collab/remote-collab-conferences
  - https://galaxy-carpentries.github.io/gallantries/handbook - 404 Client Error: Not Found for url: https://galaxy-carpentries.github.io/gallantries/handbook
- community-handbook/coworking/coworking-collabcafe
  - https://hackmd.io/@KirstieJane/CollabCafe MOVED TO `https://hackmd.io/@turingway/collaboration-cafe`
- community-handbook/style/style-more-styling 
  - https://the-turing-way.netlify.app/afterword/afterword.html#a SHOULD BE `https://the-turing-way.netlify.app/afterword/glossary.html#a`

See the full list: https://hackmd.io/v3ecu4QlTsiV5ZEDAiyqZQ?both

**Comment by Lovkush-A** [comment]
@malvikasharan I have locally built the book using jupyter-book. Where do I see the warnings for links? I got a bunch of warnings in my terminal, but none that reference links. (Many of the warnings are `'myst' reference target not found`
