### ISSUE TITLE
Organize project team travel for Manchester workshop

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#168]
### Summary
To avoid too much information in the workshop issue #44 I suggest separate issues to plan travel etc. for the project team to the workshop.
This issue is for the "Boost reproducibility with binder" workshop in Manchester on 1st March 2019.

### What needs to be done?

- [x] Let us know if you can attend and help facilitate. ~@r-j-arnold~ @sgibson91 @LouiseABowler @KirstieJane @rosiehigman @pherterich ~@alexmorley~ ~@annakrystalli~ 
Please use :+1: for attending, :-1: if you can't make it and :eyes: as a maybe
- [x] Comment below with train and accommodation needs
- [x] @KirstieJane to let us know how to book travel and accommodation

----
**Update**
Confirmed facilitators: @rosiehigman @LouiseABowler @sgibson91 @KirstieJane @trallard and some help from @rainsworth 

- @pherterich to figure out if she wants to come and hang out with people 

Check please check the table for travel and hotel: https://github.com/alan-turing-institute/the-turing-way/issues/168#issuecomment-466945857

**Comment by rosiehigman** [comment]
No travel needs 😃

**Comment by rainsworth** [comment]
Very happy to help more than "some" - just let me know what you need me to do! 😊 So excited for this! (Also no travel needs.)

**Comment by pherterich** [comment]
I would go for the 07:31 train from Birmingham New Street to Manchester Piccadilly (arriving 8.59) and return leaving at 18.05 (arriving back in Bham at 19.33)

**Comment by trallard** [comment]
No travel needed for me

**Comment by sgibson91** [comment]
Could I have:
* 18:57 train from London Euston to Manchester Piccadilly on 28/02
* Hotel for the evening of 28/02
* 17:35 train from Manchester Piccadilly to London Euston on 01/03
I have a 26-30 railcard if that helps ✨

**Comment by KirstieJane** [comment]
Hey folks!! I have a meeting today with @LouiseABowler and we'll figure out exactly who's going to the Manchester workshop then. So in the afternoon I'll sort out the travel.

I'll do a block hotel booking so we're all in the same place.

Please can you make sure that this table is correct for the travel?

| Name | Hotel 28 Feb | Train to M/Cr | Train home |
| @sgibson91  | ✅ |  London Euston to Manchester Piccadilly 18:57 on Thurs 28 | Manchester Piccadilly to London Euston 17:35 on Fri 1 |
| @KirstieJane | ❌ | London Euston to Manchester Piccadilly 18:57 on Thurs 28 | Manchester Piccadilly to London Euston 17:35 on Fri 1 |
| @pherterich | ❌ | Birmingham New Street to Manchester Piccadilly 07:31 on Fri 1 | Manchester Piccadilly to BNS 18.05 on Fri 1 |

**Comment by pherterich** [comment]
@KirstieJane I wasn't attending any longer but if @LouiseABowler can't make it and you want another core team member attending, I'm happy to come.

**Comment by KirstieJane** [comment]
Ah - gotcha - I'll check with @LouiseABowler when we meet and let you know @pherterich! Thank you 😸

**Comment by KirstieJane** [comment]
Ok - @LouiseABowler is going to come to the London workshop but *not* the Manchester one.

I'll give the talk on reproducible computation environments in Manchester 😸 🙀 💪 

@pherterich - I think we don't _need_ additional helpers because we have the wonderful @trallard and @rainsworth joining us. So shout if you want to come up but I'm going to just organise a hotel and train for Sarah and me unless I hear anything else ✨
