### ISSUE TITLE
Organize project team travel for Sheffield workshop

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#169]
### Summary
To avoid too much information in the workshop issue #44 I suggest separate issues to plan travel etc. for the project team to the workshop.
This issue is for the "Build a BinderHub" workshop in Sheffield on 18th March 2019.

### What needs to be done?

- [x] Let us know if you can attend and help facilitate. @r-j-arnold @sgibson91 @LouiseABowler @KirstieJane @rosiehigman @pherterich @alexmorley @annakrystalli 
Please use :+1: for attending, :-1: if you can't make it and :eyes: as a maybe
- [x] Comment below with train and accommodation needs
- [x] @KirstieJane to let us know how to book travel and accommodation

**Update:**
Confirmed facilitators: @sgibson91 @annakrystalli @r-j-arnold @alexmorley @arm61 @KirstieJane @pherterich 

---

### Travel & accomodation

- [x] @KirstieJane: 
  * Hotel on Sunday 17 and Monday 18 March
  * Sunday 17 March: 17:35 from London St Pancras to Sheffield
  * Tuesday 19 March: 17:45 from Sheffield to Cambridge
- [x] @sgibson91 
  * Hotel on Sunday 17 and Monday 18 March
  * Sunday 17 March: 17:35 from London St Pancras to Sheffield ***Booked online***
  * Tuesday 19 March: 17:29 from Sheffield to London St Pancras ***Booked online***
- [x] @LouiseABowler 
  * Hotel on Monday 18 March
  * Monday 18 March: 14:31 from London St Pancras to Sheffield ***Booked online***
  * Tuesday 19 March: 17:29 from Sheffield to London St Pancras ***Booked online***
- [x] @pherterich 
  * Hotel on Monday 18 March
  * Monday 18 March: 7:30 Birmingham New Street to Sheffield 
  * Tuesday 19 March: 18:24 Sheffield to Birmingham New Street
- [x] @rosiehigman 
  * Monday 18 March: 7:18 from Manchester Piccadilly to Sheffield
  * Monday 18 March: 21.11 from Sheffield to Manchester Piccadilly
- [x] @alexmorley 
  * Hotel on Sunday 17 March 
  * Sunday 17 March: 18.35 from St Pancras to Sheffield (16-25 rail card)
  * Tuesday 19 March: 17.24 from Sheffield to Oxford (16-25 rail card) 
- [x] @arm61 
  * Hotel on Sunday 17 March
  * Sunday 17 March: 19:01 Bath Spa to Bristol Temple Meads; 19:30 Bristol Temple Meads to Sheffield
  * Monday 18 March: 18:52 Sheffield to York; 19:52 York to Edinburgh; 22:30 Edinburgh to Croy
- [x] @takluyver 
  * Hotel on Sunday 17 March
  * Sunday 17 March: 16:00 Edinburgh to Sheffield (changing at Newcastle; 26-30 railcard)
  * Monday 18 March: 18:00 Sheffield to St Pancras (26-30 railcard)
- [x] @rainsworth
  * Hotel on Monday 18 March
  * Monday March 18: 07:38 Manchester Oxford Road to Sheffield
  * Tuesday March 19: 18:40 Sheffield to Manchester Oxford Road

**Comment by r-j-arnold** [comment]
👍 No travel or accommodation needs.

**Comment by rosiehigman** [comment]
I can attend but happy not to if we have too many bodies, if I'm coming please could I get the 7.18 train from Manchester Piccadilly to Sheffield and the 18.11 train from Sheffield to Manchester Piccadilly.

**Comment by annakrystalli** [comment]
👍 No travel or accommodation needs either 😊

**Comment by annakrystalli** [comment]
@KirstieJane, I've added a catering item to the checklist. I don't think we've discussed details yet but might be a good time to do so, ie:
- Will we be offering food/refreshments?
- If so what will we cover?
    + [ ] morning coffee (cake? biscuits?)
    + [ ] lunch (how will we cater for diverse dietary requirements)
    + [ ] afteroon coffee?

What do you think?

**Comment by sgibson91** [comment]
@alexmorley Will you be able to attend this? I could really use the support, if I'm honest!

**Comment by alexmorley** [comment]
@sgibson91 I'm supposed to be giving a talk that day, but I think I can push it forward a week so that I can do this instead. If we are 100% on the date I will try and sort that out today?

**Comment by sgibson91** [comment]
The eventbrite invites have gone out and people have signed up, so I'm pretty confident that we're fixed to that date.

**Comment by alexmorley** [comment]
OK. I'm on it!

**Comment by sgibson91** [comment]
Could I have:
* 17:15 train from London King's Cross to Sheffield on 17/03
* Hotel for the night of 17/03
* 17:29 train from Sheffield to London St Pancras

And I have a 26-30 railcard ✨

**Comment by alexmorley** [comment]
Could I please book the:
- 18.35 St Pancras to Sheffield  (east midlands)
- Hotel for night of 17.03
- 17.24 from Sheffield to Oxford (cross country)

I have a 16-25 railcard.

**Comment by rosiehigman** [comment]
@annakrystalli we're going for 50:50 veggie and not, aiming for a variety of vegan/gluten-free options. I'll email attendees to check if there are any special dietary requirements.

**Comment by rosiehigman** [comment]
@arm61 will be joining us for the Sheffield workshop and would like the following travel and accommodation on the Sunday night:
Would be coming from “Croy” station on the Sunday (ideally one that gets to Sheffield before 5pmish) and ideally coming back the Monday (assuming we are planning to finish before like 7pm).

**Comment by arm61** [comment]
cheers @rosiehigman just to say that I have a 26-30 railcard thing so can save some cash there!

**Comment by rgaiacs** [comment]
@annakrystalli Do you still need my help?

**Comment by takluyver** [comment]
@annakrystalli asked me to come and help as well. If that's useful, I'd need to come from Edinburgh on the Sunday evening, stay overnight in Sheffield, and then go on to London on Monday evening. I had already planned to take the Tuesday & Wednesday off to go to London, so I can book Sheffield - London myself if that's a problem.

I'll ensure I've got a 26-30 railcard before the journey.

**Comment by annakrystalli** [comment]
Thanks for your response @takluyver! We've noted your travel requirements and will forward confirmations when everything is booked. @rgaiacs thanks for the offer! I think we will be ok now for helpers at Sheffield. You are going to the Manchester workshop aren't you?  Have a chat with everyone there and if you still would like to come we could probably arrange it :)

**Comment by arm61** [comment]
Hey I hope nothing is booked yet, as my plans have changed and ideally I would be coming from Bath Spa the night before (the latest train possible), then returning to Croy on the Monday...I hope that is okay.

**Comment by KirstieJane** [comment]
Thanks @arm61 - booking trains is on my to do list for today :smiley:

Can you send me the exact train times please and I’ll get those booked for you.

And one night accomodation in Sheffield, right?

**Comment by KirstieJane** [comment]
@takluyver - can you send me the exact trains you’d like me to book? I can do that this evening ✨

**Comment by arm61** [comment]
@KirstieJane 

Bath Spa - Sheffield 2019-03-17: 19:01 Bath Spa - Bristol Temple Meads; 19:30 Bristol Temple Meads - Sheffield
Sheffield - Croy 2019-03-18: 18:52 Sheffield - York; 19:52 York - Edinburgh; 22:30 Edinburgh - Croy

And the Sunday night in Sheffield ideally!

Thanks!

**Comment by takluyver** [comment]
@KirstieJane thanks! Something like this would be fine:

- Sunday 17th: Edinburgh 16:00 to Sheffield 19:20, changing at Newcastle
- Monday 18th: Sheffield 18:00 to St Pancras 20:11

Feel free to shift those around a bit if it makes anything easier. And you can book with a 26-30 railcard, I've been meaning to get one.

And yes, one night's accommodation in Sheffield. :-)

**Comment by KirstieJane** [comment]
@alexmorley - can you stay for the sprint on Tuesday? Or should I book you to go home on Monday as detailed above?

**Comment by KirstieJane** [comment]
DONE! 

![](https://media.giphy.com/media/xT8qBqNisx9dkXWAX6/giphy.gif)
