### ISSUE TITLE
Getting started with Github wrong image and images are squashed

### ISSUE THREAD

**Issue by EKaroune** [alan-turing-institute/the-turing-way#1690]
### Summary

*Images are squashed and fig 42 is the wrong image.*

### What needs to be done?

- [x] *fix all images so not squashed.*
- [x] *change fig 42 to correct image and change alt text*

### Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
Is it solved with the last PR?

**Comment by EKaroune** [comment]
Yes this is done now!
