### ISSUE TITLE
Add data availability statement info to Open Data (Guide for Reproducibile Research, Open Research)

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1701]
### Summary

There is no info or examples for a data availability statement that you need in publications nowadays to point others to your data. 

### What needs to be done?

- [ ] Add info/examples on data availability statements to the open data section (in Guide for Reproducible Research, Open Research)

### Who can help?

* *Anyone with some knowledge about data availability statements

---

### Updates

*No updates yet. 
https://www.library.manchester.ac.uk/using-the-library/staff/research/research-data-management/sharing/data-access-statements/ could be used as a starting point.

**Comment by nehamoopen** [comment]
I'm swamped at my day job, so I can't get involved as much as I would like. But here's a link I thought was useful too: https://researchdata.springernature.com/posts/tips-for-writing-a-dazzling-das-data-availability-statement
