### ISSUE TITLE
The Turing Way on the Open Science Stories podcast

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#1706]
### Summary
Following my new year's resolution I am starting a podcast called Open Science Stories.

https://anchor.fm/opensciencestories

I would love to do one or more episodes with people from the Turing Way community. About the project or also about other things. The idea is that each podcast episode explains an Open Science concept or idea as part of a story. Concepts that I could imagine are 

- reproducible data science
- collaborative book writing
- open licensing
- ...

Each episode is 3-10 minutes, so not a lot of time to be invested. Think about it!

Here is the trailer: https://anchor.fm/opensciencestories/episodes/Season-1-Trailer-eohl3j

Happy new year to you all!

### What needs to be done?

- [ ] Think about whether you'd like to invest some time to speak on a short podcast episode :thinking: 
- [ ] Message me: opensciencestories@gmail.com :mailbox_with_mail: 
- [ ] Write a script with your story :page_facing_up: 
- [ ] Record the story :studio_microphone: 

### Who can help?

Anyone who's interested. We can figure out what the story is as we go. If you're interested, we'll find something :wink: 

---

### Updates

None yet

**Comment by KirstieJane** [comment]
I love this @HeidiSeibold !! @Arielle-Bennett - can we add this to the TPS newsletter?
