### ISSUE TITLE
Create a code of conduct for workshops

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#171]
### Summary

As @annakrystalli noted, we should have a code of conduct for our workshops

### What needs to be done?
Look at some examples and
- [x] Create a code of conduct document
- [x] Link to it from the eventbrite page
- [x] Include it into reminder email sent to attendees closer to the date for those who have signed up before link was added

### Who can help?
Everyone to find Code of Conducts for events that they like so we can pick the one we like most or combine paragraphs we like.

**Comment by pherterich** [comment]
The one for the original build a binder workshops https://build-a-binder.github.io/CoC/

**Comment by pherterich** [comment]
Reading through the software carpentry one, that one seems to cover workshops and the community which makes me wonder if we need a specific one for the workshops or if extending our existing one to by a bit would be enough. @KirstieJane @annakrystalli @alexmorley opinions?

**Comment by rosiehigman** [comment]
I think if we could expand the existing Code of Conduct that would be a nice way of more closely integrating the workshops with the rest of the project

**Comment by alexmorley** [comment]
Pro: Unifying is good. We probably do expect the same standards of behaviour in the real and online world so having two might be redundant.

Con: Keeping them separate keeps each one shorter and more relevant for online vs. offline community. Maybe lowers barrier to people reading/understanding them, people tend to stop paying attention as soon as things aren't immediately relevant.

Conclusion: I'd maybe verge on having separate ones but I think having just one is pretty reasonable too.

**Comment by pherterich** [comment]
Looking at the original binder workshop resources, they also had participation guidelines (https://build-a-binder.github.io/participation-guidelines/). Wondering if that would work as a split to have 2 separate short documents. Would someone have issues with the wording "Workshop participation guidelines"?

**Comment by KirstieJane** [comment]
Is this done? I think it can close. Tagging @rosiehigman to make the call 😸

**Comment by rosiehigman** [comment]
Yes, didn't spot that last tickbox but I did it on Friday 😄

**Comment by KirstieJane** [comment]
Gah! Everyone is awake! Do as I say not as I do and take it easy 😆 🤦‍♀️ 🤗
