### ISSUE TITLE
2021 conferences to attend: Invite volunteers, submit abstract

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1717]
### Summary

* There are several conferences in 2021 that are open for abstract submissions. Please respond below which conference you would like to attend and represent The Turing Way.

### What needs to be done?

Some ideas - your contributions are invited:
- [x] FOSS Backstage <-- I will be giving a talk here
- [ ] CSV,Conf 21 <-- would like to submit an abstract
- [x] Collab Workshop 21
~~- [x] FAccT conference (https://facctconference.org/2021/cfw.html) by @LauraCarter - abstract for this is on the conference page https://github.com/alan-turing-institute/the-turing-way/tree/master/conferences~~
- [x] #1716 <-- suggested by @sgibson91 
- [x] Data community/DataSharqiyah (https://www.datacommunitysa.com/home/) and WiDs Soudi Arabia <-- @BatoolMM
- [x] RightsCon https://www.rightscon.org/program/  <-- abstract [here](https://github.com/alan-turing-institute/the-turing-way/blob/master/conferences/abstracts/2021-01-RightsCon.md) put together by @LauraCarter, @malvikasharan and @lauracion 

### Who can help?

* Community members

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
Put me down for CW21! I'd be interested in helping out with the csv,conf submission too (saw the CFP but wasn't sure what to submit!)

**Comment by LauraCarter** [comment]
For RightsCon, there is an option to record an 8-10 minute tech demo - this might be a good opportunity to record a short talk (maybe based on [this talk](https://zenodo.org/record/3968454#.YAAnuOAaSi4) @malvikasharan did last year - how long was that?) which we could use for other purposes?

**Comment by malvikasharan** [comment]
My talk was for 10 minutes followed by Q&A. Feel free to reuse them.

**Comment by LauraCarter** [comment]
> For RightsCon, there is an option to record an 8-10 minute tech demo - this might be a good opportunity to record a short talk (maybe based on [this talk](https://zenodo.org/record/3968454#.YAAnuOAaSi4) @malvikasharan did last year - how long was that?) which we could use for other purposes?

**Comment by LauraCarter** [comment]
@malvikasharan great! I'll work on a proposal in today's collaboration cafe.

**Comment by malvikasharan** [comment]
Pinging @EKaroune https://or2021.openrepositories.org/call-for-proposals/

**Comment by LauraCarter** [comment]
PR open for RightsCon submission here: https://github.com/alan-turing-institute/the-turing-way/pull/1722 - I'm hoping to finalise this in the coworking on Monday 25th Jan (deadline is 26th!)

**Comment by LauraCarter** [comment]
> PR open for RightsCon submission here: #1722 - I'm hoping to finalise this in the coworking on Monday 25th Jan (deadline is 26th!)

Submitted!

**Comment by sgibson91** [comment]
#1716 has been accepted, I am continuing to use that issue to plan unless a new one would be preferred?

**Comment by malvikasharan** [comment]
The CW21 abstract "Good Practices for Designing Software Development Projects (The Turing Way)" has been accepted: The session has been tentatively scheduled for CW21 Day 2: Wednesday, 31 March 2021 from 14:15 - 14:45 BST (13:15 - 13:45 UTC), you can view the full agenda here: https://bit.ly/ssi-cw21-agenda

**Comment by BatoolMM** [comment]
As I mentioned in the slack, my talk for [Saudi Data Science Community/DataSharqiyah](https://www.datacommunitysa.com/home/) will be next week on the 17th of Feb. A very brief agenda is [here](https://twitter.com/DataSharqiyah/status/1360279420603404295). I'll also finish it off completely on Sunday. Any feedback will be greatly appreciated 🌷 .

**Comment by LauraCarter** [comment]
@BatoolMM how did the talk go?

**Comment by BatoolMM** [comment]
Thank you for asking @LauraCarter 🥰, that's so nice of you.  It was better than I anticipated. I tried to keep it simple because the audience has no background in Open Science and Biology at all. So, I didn't discuss Machine Learning (ML) algorithms in details. I only gave an overview of how ML is used in life sciences with an introduction to Open Sciences.  My code for xaringan slides is available [here](https://github.com/BatoolMM/An-Open-Science-Approach-to-Machine-Learning) and the presentation is deployed [here](https://github.com/BatoolMM/An-Open-Science-Approach-to-Machine-Learning). Thank you again for asking ❤️️ and good luck with your RightsCon talk.

**Comment by malvikasharan** [comment]
Note: Add Batool's slides (https://zenodo.org/record/4557637) on this table: https://github.com/alan-turing-institute/the-turing-way/tree/master/conferences

**Comment by BatoolMM** [comment]
Thank you Malvika, I'll submit a PR now.

**Comment by BatoolMM** [comment]
Submitted PR #1746 to link the talk to the TW GitHub repo.

**Comment by Arielle-Bennett** [comment]
PR for Lightning Talk on the Activism Chapter of the Ethics Book: https://github.com/alan-turing-institute/the-turing-way/pull/1769

**Comment by Athene-ai** [comment]
I'd like to contribute on this

**Comment by LauraCarter** [comment]
Our lightning talk proposal for RightsCon has been accepted! I've opened a PR https://github.com/alan-turing-institute/the-turing-way/pull/1844, currently awaiting some guidance on what they want lightning talks to look like.
