### ISSUE TITLE
Collect news item for February 2021 newsletter

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1718]
### Summary

* The next newsletter will be sent on 17 January 2021
* Any news item can be posted below as a comment

### What needs to be done?

- [ ] Collect all the items and share in the news letter

### Who can help?

* Anyone from the community who has something to share 👍 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by crangelsmith** [comment]
Hi @malvikasharan, maybe we can let the community know that we are hosting sessions to work on the Spanish translation of the book every Monday at 5pm (UK time). If anyone wants to join they can go to the slack channel #traducción-español or contact me directly and I'll send them the rolling invite to these sessions :)

**Comment by Aida-Turing** [comment]
Dear Turing Way Community,

Here is an opportunity to engage with UKRN (UK Reproducibility Network) to help them draft scripts for animated videos (2-3 min) explaining topics in open research. :film_projector: Full info below. 
..............

As you may know, UKRN recently produced a series of Primers on Open Research (https://www.ukrn.org/primers/). These are now being developed into 2-3 minute animated videos to engage a wider audience.
We are seeking researchers with experience in several areas to help draft the scripts for these animations. Interested researchers can contact us by replying to Matt Jaquiery [matt.jaquiery@psy.ox.ac.uk]. 
The topics we are looking to cover are:
Preregistration and registered reports | https://osf.io/8v2n7/
Preprints | https://osf.io/m4zyh/
Open Access | https://osf.io/94rsp/
 
Please forward this to other people at your institution who might be able to help!

**Comment by malvikasharan** [comment]
https://twitter.com/Gen_R_/status/1357305382390145025?s=20

**Comment by malvikasharan** [comment]
https://scigen.report/info/reproducibility
