### ISSUE TITLE
Add quarterly report on repo: check with Kirstie

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1726]
### Summary

* For Turing quarterly report, The Turing Way drafts a document every few months
* It's a good record of what happens in the project and will be valuable to add them on the repo

### What needs to be done?

- [ ] Check with @KirstieJane if we should add the report online (I have all the reports for 2020)
- [ ] What kind of information should be removed (any specific information that is relevant only for internal use)

### Who can help?

* @KirstieJane and @Arielle-Bennett 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by KirstieJane** [comment]
YES PLEASE! OOOOOOOH - that's great.

Can you put them in a hackmd and send just to @Arielle-Bennett and me to check if there's anything that should be redacted? I _think_ for this project the answer is likely no.... but would be good to have a cautious run though.

**Comment by malvikasharan** [comment]
Shared! I will close this issue and open a PR once approved.
