### ISSUE TITLE
Talk proposal: Lightning talk at CW21 on the Activism Chapter of the Ethics Book - deadline 7 March 

### ISSUE THREAD

**Issue by Arielle-Bennett** [alan-turing-institute/the-turing-way#1749]
### Summary

Issue to discuss Lightning Talk proposal for the "Activism" chapter of the Ethics Book for the Software Sustainability Institute's Collaborations Workshop 2021. 

Deadline 7 March 

Guidelines and more information here: https://www.software.ac.uk/news/call-lightning-talks-collaborations-workshop-2021 

### What needs to be done?

- [ ] Draft title
- [ ] Draft abstract
- [ ] Feedback on title & abstract
- [ ] Submit! **deadline 7 March 2021**
- [x] *make sure the chapter is live by then....*
- [ ] Draft slide & Lightning Talk
- [ ] Feedback on slide & Lightning Talk 

### Who can help?

* Contributors to the Ethics book or ethics discussions particularly welcome: @LauraCarter, @Arielle-Bennett, @irenekp, @Ismael-KG   

---

### Updates

*Updates when we have them.*

**Comment by Lovkush-A** [comment]
@ArielleBL @Arielle-Bennett. I would be happy to help. :smile:

Note I am new to Turing Way, so I am not best positioned in the drafting stages. However, the fact I am new might provide a useful perspective for feedback. Please let me know if/when I can help!
