### ISSUE TITLE
[community] [question] Is the Gitter channel redundant?

### ISSUE THREAD

**Issue by Lovkush-A** [alan-turing-institute/the-turing-way#1756]
### Summary
In the 'Getting in touch' section of contributors guide, it says for Gitter:
> This will be a good place to start if you are new to the project, or have any quick question.
We'd love for you to swing by to say hello.

I went there and there has not been a message since October. It seems to have been a bit more active previously, but not so in past 6 months.

### What needs to be done?
- [ ] At a minimum, I think the description of the Gitter channel needs to be updated, as it is no longer accurate.
- [ ] Decision made on whether Gitter channel should be kept.

---

**Comment by Lovkush-A** [comment]
My own (uninformed - I am new to this project) preference is that Gitter channel can be removed.
* It does not give good (nor accurate) first impression to a newcomer. Especially when project advertises itself as super welcoming and friendly!
* It seems redundant. Is there anything you can do in Gitter that you can't do in Slack?
* I have a general tendency towards minimalism and decluttering.

**Comment by malvikasharan** [comment]
Gitter is a public-facing platform, and Slack needs a link to enter. Slack was launched last summer and therefore there was a  transfer time, which is the reason why the Gitter channel was not achieved and kept active. So it is still accurate information.

You can create a PR to update the link in the contribution guideline.

I don't think we advertise ourselves as a super friendly project, we try to model the behaviour. I am not sure how does that connect tp lack of friendliness. Can you explain it?

**Comment by Lovkush-A** [comment]
Thanks for the reply! I apologise - I did not explain myself well.

1. The description for Gitter is: "This will be a good place to start if you are new to the project", which sounds like one should go to Gitter before Slack. However, and I could be wrong, it looks like Slack is currently the better place to start.  This is why I think the description for Gitter is inaccurate.

2. Friendliness.
I tried, but failed, to imply that Turing Way community *is* friendly and welcoming. I said "It does not give good (nor accurate) first impression to a newcomer."  When I said 'nor accurate', I was trying to say that the impression from Gitter channel does not reflect what is really going on. Explicitly, based solely on first impression of the Gitter channel, it looks like things are inactive (and hence not welcoming), which is not accurate reflection of the Turing Way.

3. I will try to find updated links and make a PR.

Apologies again for being unclear. Please let me know if I am still not being clear!

**Comment by malvikasharan** [comment]
Thanks for PR #1757 and for updating the links. I have suggested rephrasing of Gitter section to address your concern. I hope that helps.

**Comment by Lovkush-A** [comment]
Yes, that helps, thanks for making the change. As with most of these things, we could spend hours going back and forth on the phrasing of a single sentence. Might be worth getting the opinion of other new-comers or other contributors. Otherwise, am happy for issue to be closed.
