### ISSUE TITLE
GSoC and ISCAS 2021: Project idea and task for the interested candidates

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1787]
## :tada: **Welcome GSoC and ISCAS Contributors! This is The Turing Way repository** :tada:

:dizzy: _We're excited that you're here and want to contribute._ :dizzy:

### Summary

**ISCAS**
  * The Turing Way has been accepted as a project in [ISCAS](https://summer.iscas.ac.cn/#/org/prodetail/210940619?lang=en) hosted Summer of 2021 Open Source Promotion plan
**GSoC**
  * INCF is accepted as [Google Summer of Code](https://summerofcode.withgoogle.com/) (GSoC) organisation, & _The Turing Way_ is listed as one of the projects ([see the proposal](https://docs.google.com/document/d/14wnNV-cIqTIF3eE9QJXtkwyW7lQomUiCLVVPFafX6Js/edit#heading=h.fteilwpgb5py))

**NOTE**: The proposal for both GSoC and ISCAS are the same.

**Information for students interested in working on the project:**
* Please read the assessment process and task in the next section
* We urge all the candidates to work on a minimum of 2 projects simultaneously so that they are not completely relying on their selection in The Turing Way if we end up not selecting them.
* We will not be handling communication via personal emails. All responses will be directed to this issue. You are welcome to join our Slack channel, here is a link to the [full Slack Workspace](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw).

### Assessing candidates

* We have provided a specific task for the participants to work on during this exploration phase. This task will help the project team members in assessing the technical and communication skills of the interested candidates.
* Other technical contributions are always welcome, but non-assessable contributions like fixing a broken link or typos will not be sufficient to build a proposal with The Turing Way - we need to learn about your ability to work on the technical aspects as well as your collaboration skills while offering you a welcoming environment to participate in Open Source project.
*  **FEEDBACK**: Feedback will be offered within 2 days to let the candidate know as soon as possible if their proposal can be supported by us or not.
* We will be able to point candidates to the right resources (please ask on Slack or in this issue by replying below), however, please note that we will not be able to promptly reply unless necessary (all our mentors are volunteer members and do not work on the project full time). 

### Specific task for assessment

Students upon selection will be helping to improve the searchability aspects of The Turing Way Book. The task below is therefore related but have been kept small and specific to assess if the candidate:
  * knows how to work on GitHub
  * can work locally using git and local build of the book -  [SEE HERE](https://github.com/alan-turing-institute/the-turing-way/tree/master/book) 
  * have read the [contribution guideline](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md), [Code of Conduct](https://the-turing-way.netlify.app/community-handbook/coc.html) and our [proposal](https://docs.google.com/document/d/14wnNV-cIqTIF3eE9QJXtkwyW7lQomUiCLVVPFafX6Js/edit#heading=h.fteilwpgb5py)
  * understands the problem we have described in our proposal and have the skill set to help address them

**Task: Suggest how we can improve browsability of The Turing Way.**

1. Explore [The Turing Way book](https://the-turing-way.netlify.app/welcome.html), and take note of how 5 guides in the book are displayed.
1. There are many issues that make browsing the book quite difficult for a new user. However, in this task, we want to discuss and suggest a solution specific to the issue relating to the display of the table of content (as shown in the image above). For example:
    * You can click the expand button to see the content of each guide, but there is no way to know what subchapters exist.
    * It is hard to differentiate which chapter has subchapters (small chapters within chapters), and which does not, without manually clicking them.
    * Pages with many sections are hard to browse (jump to the section of interest) using the index displayed on the right-hand side of the chapters. See here for a specific example: https://the-turing-way.netlify.app/afterword/contributors-record.html
1. What specific ideas and solutions can you suggest for improving the display of the table of content and/or chapter index? Create a short report (max 500 words) describing your ideas and proposal. 
  - As an inspiration, see how search functionality currently works and what we can improve (adding tags, metadata etc.)
  - See how [FAIR Cookbook](https://fairplus.github.io/the-fair-cookbook/content/home.html) (another collaborating project that uses Jupyter Book) organises its resources.
1. When ready, please make a small Pull Request to demo how you will approach your idea in The Turing Way and add your report in the description of your Pull request. 
1. Reply under this issue linking to your Pull Request or issue so that we can review it. Please note, that Netlify will allow you to preview your changes on a chapter/book's page without merging the Pull Request to this repository. 

**Please reply under this issue, if any further clarification is needed.**

*Further ideas can be discussed as a comment below, however, we will prefer if we can assess all candidates through the same assessment process.*

### Where else can you start to learn about the project?

* Link to the project repository: https://github.com/alan-turing-institute/the-turing-way 
* Project's [README](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md)
* Community handbook: https://the-turing-way.netlify.app/community-handbook
* Go through existing [issues](https://github.com/alan-turing-institute/the-turing-way/issues) and [Pull requests](https://github.com/alan-turing-institute/the-turing-way/pulls) to explore where else you can contribute
* Open a new issue if you have any specific idea for contributions and/or proposals not listed above

### What can _The Turing Way_ offer during this period?

As an Open Source and contribution-driven project, we would like to invite interested candidates to start engaging with the project as a contributor. Please be sure that you follow our contribution guidelines and code of conduct.

* We would like to encourage interested members to work openly and collaboratively in line with the community participation guidelines
* This will allow interested members to learn about the project while helping us see their enthusiasm and willingness to work on this project
* By completing the task, they would be able to provide us examples of their technical skills through contributing to our project on GitHub
* This will also allow them to generate ideas for their proposal or consider if contributing to _The Turing Way_ is the right fit for them 
* If they end up getting selected, they will be able to keep on working with mentorship and guidance to further enhance their work within the project
* If they don't get selected or decide to not go ahead with the proposal, their contributions will still be counted and they will be listed as one of our community members.

*For any further questions, please comment below!*

**Please Note**

Contributing during the exploration phase is meant to assess how well the candidates’ work fit the requirement of a project.
We are looking for a candidate who can work on improving users experience by making the book easy to browse and search for the desired content. 
Furthermore, these candidates will bring their unique skill set to help us improve the quality of our resources. 
With that motivation in mind, we want interested candidates to be aware that we will try to give feedback on Wednesdays to make sure that the co-mentors can review the task in their own time before the FEEDBACK DATES.
It should NOT be assumed that contributing to the project will automatically secure you a position as a selected participant.

**Comment by Athene-ai** [comment]
I am interested in Task: Suggest how we can improve browsability of The Turing Way.

**Comment by malvikasharan** [comment]
@Athene-ai the task is described in the issue. Specifically, I discuss some of the issues in the bullet point 3
> 3. There are many issues that make browsing the book quite difficult for a new user. However, in this task, we want to discuss and suggest a solution specific to the issue relating to the display of the table of content (as shown in the image above). 

Based on your idea and interest, you can suggest some improvement:
> What specific ideas and solutions can you suggest for improving the display of the table of content and/or chapter index? Create a short report (max 500 words) describing your ideas and proposal.

You can also follow the discussion we are having on the Slack channel for the GSoC candidates.

**Comment by Athene-ai** [comment]
In my opinion it could be useful not to link every section and subsections in the left-hand side menu

**Comment by malvikasharan** [comment]
Hi Daniela, I recommend taking some time to browse the book and explore the problem that I have discussed in my issue. Please, make a short report of the technical solution you would apply to solve the discussed problem. Based on your report, please make a PR that fully or partially solves the problem. We will use this to assess your technical skills and understand how you approach accessibility and usability problems. Furthermore, what you would like to work on during GSoC if you get selected to improve the interactivity in the book overall.

**Comment by Athene-ai** [comment]
Which is the deadline ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by malvikasharan** [comment]
There is no real deadline, but as stated in the issue, the exploration phase is until 29 march, meaning that if you would like to submit a proposal with us, we need to make sure that you are the right fit for the project and that you have a plan to write a proposal to submit in time. Please see the timeline here: https://summerofcode.withgoogle.com/

**Comment by Athene-ai** [comment]
Many thanks for the clarification

**Comment by JiaruiWang-Jill** [comment]
Hi @malvikasharan , thanks for your guidance in slack channel. My try of "good first issue" is #1848. And I also leave my drafted proposal here. Look forward to hearing from you.
[gsoc_proposal-2.pdf](https://github.com/alan-turing-institute/the-turing-way/files/6302242/gsoc_proposal-2.pdf)

**Comment by priyanshuone6** [comment]
@malvikasharan @BatoolMM
Could you please look at [#1950](https://github.com/alan-turing-institute/the-turing-way/pull/1950), thanks!

**Comment by Spnetic-5** [comment]
@malvikasharan @BatoolMM
Can you please Please review #1966, Thanks in advance!
