### ISSUE TITLE
Write the chapter on Research Data Management

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#179]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _Research Data Management_.
 * This chapter is being written at https://hackmd.io/c0SDICBDQJ2abzjqAmFOqg?both
 * This chapter is being developed on [https://github.com/pherterich/the-turing-way-1/blob/rdm-chapter/chapters/rdm.md](https://github.com/pherterich/the-turing-way-1/blob/rdm-chapter/chapters/rdm.md).
 * Table of contents
 * Resources
 * Discussion points/related issues

## Current status
@pherterich and @rosiehigman are currently writing this chapter

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by pherterich** [comment]
@rosiehigman @jensmith3 I've added a few random comments in the hackmd where opinions are appreciated before I go off and write more if you have time to give the chapter a quick look. Thanks!

**Comment by rosiehigman** [comment]
I think I've responded to all the comments (did not know about the comment facility on HackMD - very cool!)
