### ISSUE TITLE
Add robodebt image to subchapter

### ISSUE THREAD

**Issue by LauraCarter** [alan-turing-institute/the-turing-way#1792]
### Summary

There is a lovely robodebt image from the Nov 2020 book dash - it would be great to add it to the robodebt case study!

### What needs to be done?

- [ ] Add robodebt image to this page: https://the-turing-way.netlify.app/ethical-research/activism/activism-robodebt.html

### Who can help?

- [ ] anyone who knows how to add images!

---

**Comment by inwaves** [comment]
Hey @LauraCarter, I can lend a hand with this. Is the image located anywhere on this repo?

**Comment by ashatitus** [comment]
@inwaves It is here: https://zenodo.org/record/4323154?fbclid=IwAR2KGeaNELHxIV7-wvbxHnFfrtB9noav8pBvx20vrvwZ7y0bZTLnYkmrrR0#.YEnZ6I77TIW

**Comment by Athene-ai** [comment]
I can help with it
