### ISSUE TITLE
Write SSI blog post

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#181]
### Summary

The SSI has raised the possibility of me writing a blog post about the turing way. I plan to do so, and this issue is a place for people to discuss any material they'd like me to highlight/include.

### What needs to be done?

Discuss and write blog. If anyone had a creative commons image they'd like to use in it that would be good too, we could use the team photo?

### Who can help?

Anyone who has an opinion/interest in material to include, particularly @KirstieJane 

### Updates

Will be published on 06/03/19

**Comment by pherterich** [comment]
Highlighting #80 would be good, other than that I'm not sure we have too much beyond the first newsletter content at the moment.

**Comment by r-j-arnold** [comment]
> Highlighting #80 would be good, other than that I'm not sure we have too much beyond the first newsletter content at the moment.

Good point, added it now.

**Comment by pherterich** [comment]
@r-j-arnold will they not just be part of the book or did I just misunderstand?

**Comment by r-j-arnold** [comment]
@KirstieJane Here's my draft of the blog (at least one of these links should work)

https://docs.google.com/document/d/1uzQ0yTD1J8vTyIkdTJXxoWOlHzqIN_lS9ABZdYa0uZ0/edit?usp=sharing

https://drive.google.com/open?id=1uzQ0yTD1J8vTyIkdTJXxoWOlHzqIN_lS9ABZdYa0uZ0

**Comment by LouiseABowler** [comment]
@r-j-arnold, I've added some comments about the case studies into your Google doc - hope they're helpful, but ping me in Slack if you've got any more questions about that section. I fixed a couple of spelling mistakes while I was there; I made those edits directly.

And this reminds me, I should get a blog post up on the Turing REG website at some point!

**Comment by r-j-arnold** [comment]
Thanks very much @LouiseABowler! I've included all your changes but one, and left a reply about the one I haven't.

**Comment by KirstieJane** [comment]
Reviewed! Sorry for being so slow @r-j-arnold! Thank you for writing this up!!

**Comment by r-j-arnold** [comment]
Great, I've submitted it to the SSI but according to the autoreply Selina's on leave until the 25th, so it's unlikely to be published before that. I'll make a pull request with the blog in after any SSI edits.
