### ISSUE TITLE
Content and discussion topics for BinderHub workshop

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#183]
### Summary

This is an issue to suggest ideas and topics for discussion for the Build a BinderHub workshop in Sheffield on 18th March 2019.

We want to make this workshop as useful as possible for attendees, so please do suggest what you want to talk about on that day and it will shape the agenda for the day.

**Comment by willfurnass** [comment]
Some suggestions from @chryswoods and a few of my own:

1. How to avoid abuse of BinderHub instances if public and no auth?  They could be used to e.g. disseminate encrypted illegal material.    
1. Use cases for BinderHub.  Dissemination to public?  Or within organisation?  Should cloud computing providers be pushed to provide BinderHub instances with basic auth (c.f. Azure Notebook service)
1. Strategies for use in teaching e.g. resource management.
1. Can mybinder.org be relied on to exist in two years?  How to make BinderHub instances sustainable i.e. what is the business model?  *Should* we aspire to providing sustainable public BinderHub instances or require that the Notebook consumer pays?
1. Hosting options (inc. security implications of on-prem hosting)
