### ISSUE TITLE
Utrecht open science programme

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#184]
### Summary

This seems quite similar to what we’re trying to do: https://open-science.sites.uu.nl

### What needs to be done?

- [x] Have a read through the doc and see if there’s overlap
- [x] Get in touch w Bianca and Jeroen to make sure they know about the Turing Way and to see if we can support each other? ✨

### Who can help?

* Anyone
* @pherterich, @r-j-arnold, @rosiehigman if this content fits into their chapters?
---

### Updates

None so far

**Comment by r-j-arnold** [comment]
In short there's little/no crossover in actions, though a lot of crossover in motivation. 

Their aim is to encourage open science practices within Utrecht university by giving mini grants, changing how they assess their own researchers, and providing training to their researchers. 

Their motivation is essentially that open science is a good idea and they want people to do more of it, so we're well aligned there.

I'll reach out and let them know that we exist, that they're welcome to re-use anything they think's useful, and that we'd welcome any input from them on the turing way.

**Comment by pherterich** [comment]
I will reopen this until I've managed to read and think through it to make sure we're not missing anything for the RDM chapter.

**Comment by KirstieJane** [comment]
@r-j-arnold - yeah - I think that's the miscommunication. This is _also_ to ensure we're educating the Turing community. It links in really well with the Champions project around promoting examples of great work.

My quick read through is that there's lots of similar topics covered in the doc. But mostly I was thinking that we're best linking up with the team there to make sure that we promote Turing as an organisation that cares about reproducible research (as they're going for with Utrecht!)
