### ISSUE TITLE
Discuss colour coding sections within chapters by difficulty level

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#186]
### Summary

Spoke to someone that had taken a look at the chapters so far. They said it was loads of useful stuff, but too much for a beginner. A solution we discussed is making sections of chapters colour coded by how advanced they are so it's less intimidating and these huge detailed chapters become more skimable. 

### What needs to be done?

Discuss if this is a good idea, and if so how to implement it.

### Who can help?

Anyone interested in the style choices of the final book.

### Updates

Following discussion on the zoom meeting 06/02/19 we decided to discuss this probably at the March sprint when we're talking more about the presentation/final form of the book.

**Comment by dingaaling** [comment]
Hello from 2022 @r-j-arnold ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by the end of October we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
