### ISSUE TITLE
There is a missing link in the Inclusivity section of `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by griff-rees** [alan-turing-institute/the-turing-way#1865]
### Summary

A link in the **Inclusivity** section of [`CONTRIBUTING.md`](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md), specifically within this sentence

> use respectful, gender-neutral and inclusive language (learn more about [inclusive writing](https://www.le.ac.uk/oerresources/ssds/studyskills/page_37.htm), resource by University of Leicester).

is missing (raises a [404 error](https://en.wikipedia.org/wiki/HTTP_404)). A version I've found via the wayback machine is here (but hard to read): https://web.archive.org/web/20170901073508/http://www.le.ac.uk/oerresources/ssds/studyskills/page_37.htm

### What needs to be done?

- [ ] *Ideally find a new example of that page.*
- [ ] *If the previous doesn't work, find a new citation or simply copy some of the text and reference the original author if possible.*

### Who can help?

* *Whoever originally cited that text could provide helpful advice on what's essential to the quote.*

---

### Updates

*None yet.*

**Comment by inwaves** [comment]
Good catch @griff-rees! The materials are available for download from the website, but for some reason are not published as hyperlinked pages anymore. We can either link to [the PDF](https://www2.le.ac.uk/projects/oer/oers/ssds/oers/study-skills/studyskills.pdf) (pp. 22) or to the downloadable [HTML course pack](https://www2.le.ac.uk/projects/oer/oers/ssds/oers/study-skills/studyskills_HTML.zip).

**Comment by griff-rees** [comment]
Thanks for replying and finding the options @inwaves. I thought the HTML pack would be a better option but given it's zipped thinking the PDF may be more straightforward and [accessible](https://caniuse.com/pdf-viewer) if the target audience will use modern browsers. Could just proivde both for backups. I'm guessing if there's also a way to auto check links for `404` errors, maybe that would be useful generally (like a unit test for a merge request)?

**Comment by inwaves** [comment]
I agree that the PDF is less hassle, especially if someone is reading the book from a mobile device. I don't know if we currently check for broken external links, but that's something we could benefit from if you have any suggestions!

@malvikasharan, do you know if we use something like the Jupyter book [link-checker](https://jupyterbook.org/advanced/html.html#check-external-links-in-your-book)?

**Comment by griff-rees** [comment]
Ah whoops, I meant to make the pull request here, apologies!
