### ISSUE TITLE
Add information on how to cite and link to your data in a publication

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1875]
## Summary

The 'Sharing and Archiving Data' in the Research Data Management chapter could do with another step where the practicalities of linking the datasets and the publication is better explained (currently in step 3 but not really explained how to do it!). 

### Discussion Points

- [ ] Are there resources out there? 
- [ ] Is this the appropriate place in the book?

### Resources

- [ ] Are there any resources on this? I can only find information on how to reserve the DOI but not the other steps needed. 

## Who can help?

* Anyone who has some experience publishing a paper and a dataset OR wants to learn how to do this and can proof read :) 
* @EKaroune 
*  Anyone who has more experience with adding images to the book :)

## Updates

- [ ] Write chapter outline (https://hackmd.io/kKm1R1PfRZStmbo9GtwuBg)
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to master branch.

**Comment by EstherPlomp** [comment]
@lottycoupat Can you please have a look at this?

**Comment by EKaroune** [comment]
I'm going to be writing about data papers - this is something that you can mention to improve the findability and accessibility of datasets.

So eventually you can also link to that section in the Guide for Communication.

**Comment by EKaroune** [comment]
Data availability statements are an important thing to mention. Some journals require these now where as others not and there is the issue that you are still allow to use 'data by request', which should not be allowed in my view. 

There are lots of links for this from publishers such as these:
* https://www.ametsoc.org/index.cfm/ams/publications/author-information/formatting-and-manuscript-components/data-availability-statement-examples/
* https://www.cambridge.org/core/services/authors/open-data/data-availability-statements

**Comment by EstherPlomp** [comment]
Thanks Emma! We do already have a small section on Data Availability Statements here: https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-sharing.html 

I can include the links you provided as I'm updating the same page :D

**Comment by EKaroune** [comment]
Also saw this recently from ERC that has some handy tables at the bottom with info about different data repositories: https://open-research-europe.ec.europa.eu/for-authors/data-guidelines
