### ISSUE TITLE
Organize project team travel for London workshop

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#189]
To avoid too much information in the workshop issue #44 I suggest separate issues to plan travel etc. for the project team to the workshop.
This issue is for the "Boost reproducibility with binder" workshop in London on 12th March 2019.

### What needs to be done?
* [x]  Let us know if you can attend and help facilitate. @r-j-arnold @sgibson91 @LouiseABowler @KirstieJane @rosiehigman @pherterich @alexmorley @annakrystalli
  Please use +1 for attending, -1 if you can't make it and eyes as a maybe
* [x]  Comment below with train and accommodation needs
* [ ]  @KirstieJane to let us know how to book travel and accommodation
  * Update by @KirstieJane: Train requests sent to Gray Dawes on Monday morning 😭 

*Update*
Confirmed facilitators: @sgibson91 @LouiseABowler @rosiehigman @KirstieJane @pherterich

**Comment by r-j-arnold** [comment]
Would need train down on the 11th ( 15:00 Sheffield -> 17:12 St pancras), accommodation on the 11th and train back on the 12th (19:01 St pancras -> 21:25 Sheffield)

**Comment by sgibson91** [comment]
No travel/accommodation needs

**Comment by rosiehigman** [comment]
17.35 Manchester Piccadilly - 19.41 London Euston on 11/03, 19.00 London Euston - 21.05 Manchester Piccadilly on 12/03, no accommodation please

**Comment by pherterich** [comment]
07:10 Birmingham New Street - > 08:31 London Euston and 18:13 - > 20:20 return on 12 March for me please

**Comment by KirstieJane** [comment]
DONE! Just in time!
