### ISSUE TITLE
[WIP] Self-reflection prompts on ethical research practice

### ISSUE THREAD

**Issue by ninadicara** [alan-turing-institute/the-turing-way#1919]
## Summary

This chapter is a suggested contribution to the Guide for Ethical Research. Ethical dilemmas are complex, and whilst ethics checklists can help us to simplify decision making processes, we also need to understand the biases and world views that we approach these decisions with.

Self-reflection is a great tool for this! It supports us to critically examine our own thought processes, think about power and privilege in the context of a particular research project and be better informed about our own biases. Reflective skills can be applied to the way we work in teams, the way we work with the communities we research, or the research we choose to do or not do. 

Reflection can be difficult though, and wouldn't usually be something data scientists are trained in, unless as part of training to teach. This chapter proposes a series of guided prompts that could be helpful for anyone wanting a refresher or place to start thinking about how to apply self-reflection to their data science work. 

### Discussion Points

- [ ] Which prompts would be most helpful?
- [ ] Are the prompts accessible for everybody?
- [ ] Have we referenced the right thinkers in this area? What theory do we need to make sure we have mentioned?
- [ ] Have we incorporated prompts that cross a broad range of perspectives?
- [ ] Are these prompts helpful for those doing data science work with no human data? For instance, they could still apply to working in a team. 

## Who can help?

This chapter is aimed at anyone in any field of data science, so everyone will be able to help write it!

* People working on the Guide to Ethical Research for advice on where this chapter will fit.
* Anyone interested in helping to write self-reflection prompts.
* Anyone willing to try out the ones in the draft and give feedback! 

## Updates

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews (inc. trialling the prompts)
- [ ] Address reviews
- [ ] Merge to master branch.

**Comment by ninadicara** [comment]
Note - think this would have relevant cross-overs with other currently open issues such as #1315 and #1236.

**Comment by Ismael-KG** [comment]
Super quick recap of suggestions following our chat yesterday, @ninadicara!

1. Maybe work off (or find inspiration in) a case study of a researcher who needs to reflect on their work (perhaps someone who is unreflectively using racial racial categories or in the realm of brain organisation theory)
2. Ismael's waffling
3. Maybe focus on the discovery of one's assumptions (these can be fed into by education; one's experiences relative to their ethnicity, culture, age, gender, (dis)ability, class... -- but focussing on these sources can be complicating)

**Comment by ninadicara** [comment]
I'm going to close this for now because we've now merged this chapter, but feel free to reopen if you have suggestions for changes!
