### ISSUE TITLE
Adding contributors details from the book dash May 2021

### ISSUE THREAD

**Issue by BatoolMM** [alan-turing-institute/the-turing-way#1937]
### Summary

* We ran a book dash from 7-21 May 2021, and we would like to capture highlights of all attendees

### What needs to be done?

Please make sure that you share your feedback and experience from the last 5 days with us in this document: https://hackmd.io/@turingway/bookdash-may2021-feedback
1. Comment below with a link to your issues and PRs
2. Comment below your details in the following format (Paul's bio/details below for example):
  * All attendees should add a short bio, highlight from their work in The Turing Way (during and outside the Book Dash) and add a role "Book Dash 2021 participant"
  * All mentors/planning committee members can update their bio and highlights and add a role "Book Dash Planning Committee member 2021"
```
* Role: Book Dash 2021 participant
* GitHub id: 
* ORCID: 
* Short bio:
>
* Personal highlights:
>
* More information:
>
* Quotes:
>
```
```
### Paul Owoicho

* Role: Google Season of Doc: Technical Writer, [OLS-2 for Turing project lead](https://github.com/alan-turing-institute/the-turing-way/tree/master/open-life-science-mentoring)(2020)
* GitHub id: [paulowoicho](http://github.com/paulowoicho)
* ORCID: TBA
* Short bio:
> I am a Technical Writer / Google Season of Docs (GSoD) Participant working to make The Turing Way consistent, sustainable, and accessible.
> I have a BSc in Software Engineering from the American University of Nigeria. Thereafter, I worked as a Research Analyst in the Fintech & Innovation Division of Guaranty Trust Bank, Nigeria and helped to drive the Bank's push to become a platform by creating innovative digital products.
> I completed a Master's in Data Science from the University of Glasgow and starting my PhD in January 2021 studying conversational information-seeking systems. I spent two years as a Research Analyst at Guaranty Trust Bank in Lagos, Nigeria helping to build innovative digital products to meet the Bank's customer objectives.

* Personal highlights:
> The Turing Way is my first foray into open source and has been a fantastic learning experience.
> Not only have I gained a deeper understanding and appreciation for how GitHub works, but I am also learning to prioritise sustainability and empowerment in the work that I do.
> Although The Turing Way is my first open source project, I thoroughly enjoyed the experience and learned a lot along the way. Before the GSoD program, I only used Github to 'store' my projects. Now, I am much more proficient at using Github for collaborative endeavours and I am more adept at working with tools such as Markdown, Jupyter Book, and Sphinx. In addition, I gained familiarity with setting up and working with web analytics software.
> You can see the full report from GSoD participation [here](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/GSOD-applications/GSoD-2020-Project-Report.md).
> The BookDash November 2020 was great! It was awesome to meet, collaborate, and share ideas with people from around the world. Beyond the Book Dash, The Turing Way is the very first open-source project I have ever worked on. The experience has been fantastic, and I intend to stick around as a contributor after the Google Season of Docs program ends. I also see myself getting involved in other open-source projects.

* Personal Quote:
> Asides technical skills, I developed a deep appreciation for what working on an open source project entails. My mentors helped me realise that the value I left behind from the GSoD program was not in the amount of work I did, but how I enabled other contributors to also do the work I was doing. As a result, I learned to contribute as a Technical Writer in a manner that was reproducible, sustainable, accessible, and inclusiv
```

You can also add sections on:

* What skills/knowledge have you developed through *The Turing Way*
* What outreach have you undertaken for *The Turing Way* community
  * These could be blogs, talks, tutorials, training etc...
* Do you know of any data science research/practices that have changed and improved as a result of working on *The Turing Way*

### Who can help?

* All book dash attendees

### What happens next

- We will add your bio to the [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md) which will be updated to the online book in the afterword of the book
- We will use this to add to our report from the event that will be added to this repository
- Finally, we will ask for your permission to give you the spotlight in one of our next newsletters

**Comment by EKaroune** [comment]
### Emma Karoune

* Role: Book Dash Planning Committee member 2021, Bookdash November 2020 Attendee.
* GitHub id: EKaroune
* ORCID: https://orcid.org/0000-0002-6576-6053

* Short bio: I'm a Research Associate and Community Manager of DECOVID at The Alan Turing Institute. I’m also a post-doctoral researcher working in the field of Environmental Archaeology and Palaeoecology. I have a PhD in Palaeoecology from the Institute of Archaeology, University College London. I am leading a project to improve the FAIRness of phytolith data. I am also working on a project with Historic England concerning the development of novel methodologies in phytolith research for application to British Archaeological remains. 
>
* Personal highlights: I've enjoyed mentoring new contributors contributions, reviewing pull requests and helping to run sessions during the bookdash. It was great to work collaboratively to improve and publish a new chapter on 'Communicating with wider audiences' in the Guide for Communication. 
>
* More information:
>
* Quotes:
>

**Comment by hlnicholls** [comment]
### Hannah Nicholls
* Role: Book Dash 2021 participant
* GitHub id: hlnicholls
* ORCID:https://orcid.org/0000-0002-3480-7852
>
* Short bio: I am a PhD student contributing to The Turing Way to develop writing about reproducibile research practices. I have a BSc in biomedical science and a background in wetlab cardiovasuclar research. My PhD is in applying machine learning to prioritise most likely causal disease genes from genome-wide association studies. 
>
* Personal highlights: collaborating with others to build something new as a contribution to The Turing Way, and collaborating with others to review and support their work. Understanding the inner workings of The Turing Way via navigating within its GitHub. Also getting to help and watch a really cool illustrating being made!
>
* Quotes: 
> Taking part in the Turing Way Book Dash was one of the first times I've done collaborative working over an extended period of time and it was such a great experience! It allowed me to try out new skills and really build confidnece in what I was doing, I feel really encouraged to continue contributing to The Turing Way!

**Comment by marianaiv** [comment]
### Mariana Vivas
* Role: Book Dash 2021 participant
* GitHub id: marianaiv
* ORCID: N/A
* Short bio:  I'm an undergrad physics student at the Central University of Venezuela. Working on my thesis and trying to do it reproducible.
* Personal highlights: Working on the introductory chapter for the Project Design Guide was incredible. I really enjoyed collaborating with Malvika writing it.  I'm also very happy to had an illustration made specifically for the chapter.
* Quotes:
> This Book Dash was my first time doing collaborative work. I really enjoyed meeting everyone - such a welcoming environment, I really appreciate it! I enjoyed collaborating with a chapter for The Turing Way, couldn't be happier 🥰

**Comment by beckigreen** [comment]
# Becki Green
- Role: Book Dash 2021 participant
- Github id: beckigreen
- ORCID: https://orcid.org/0000-0002-0513-5188
- Short bio: I am a PhD student at King’s College London (supervised by Dr Petroula Proitsi & Professor Marcus Richards) and Engage student at The Alan Turing Institute. My PhD project aims to identify early mechanisms and biological markers of dementia, and I am currently also working on the DECOVID project at the Institute. 
- Personal highlights: Working alongside such wonderful people and learning so much! A truly enriching and rewarding experience - I look forward to contributing in future events. A further highlight was gaining experience in working collaboratively on a large project, including reviewing my first pull request!
- Quotes:
> A welcoming and enriching environment. Collaborating with others was really valuable and has provided me with tools to apply to my research and share with others.

**Comment by Marta-MM** [comment]
* Role: Book Dash 2021 participant
* GitHub id: Marta-MM
* ORCID: 0000-0001-7995-3717
* Short bio: I am a Research Assistant and Teaching Fellow in Psychology at the University of Leicester. My main research interests involve probabilistic inference, social hypothesis testing, and reasoning biases. I am also passionate about science communication and research dissemination and interested in replicability, open science issues, and the interface between cognitive and social aspects in social psychology.
>
* Personal highlights: I was very happy to start where I had left off in the previous bookdash. I believe I made small but relevant contributions and I have a clear idea of where I would like to go next which is much more than what I was hoping for!
>
* More information: I loved taking part in the bookdash, it is such a rewarding experience above and beyond its material outputs.
>

**Comment by mcnanton** [comment]
### María Nanton

- Role: Bookdash May 2021 Attendee.

- GitHub id: mcnanton

- ORCID: https://orcid.org/0000-0003-0426-2879

- Short bio: I'm a Data Analyst with a social communications background experienced in data analysis, reporting and dashboarding in marketing, social and health data. I'm currently a Data Analyst at the Health Information and Statistics Office, part of the Ministry of Health of the Buenos Aires City Government. I'm also a TA at the University of Buenos Aires, a RLadies Buenos Aires organizer, and a social data analytics and data visualization instructor at EANT. 

- Personal highlights: Going from being a new and insecure contributor to a solid team member was amazing. Even having a very short time to participate daily in the Book Dash I was able to review PRs, solve issues, detect bugs and contribute to an amazing and creative chapter in development. 

- Quotes:

> This was my first Book Dash and I can't imagine a better enviroment to do some serious, challenging and fun collaborative work. I'm inmensly grateful to everyone I encountered this week, and I cant wait to share the tools I've learned with fellow coworkers and members of data communities in Argentina.

**Comment by ninadicara** [comment]
### Nina Di Cara

* Role: Book Dash 2021 participant
* GitHub id: ninadicara
* ORCID: https://orcid.org/0000-0002-6179-1067
* Short bio: I am a PhD student at the University of Bristol, working on data science for mental health using social media data. I also have a masters degree in family social work, and was trained as a social worker before starting my PhD. I co-organise the [Data Ethics Club](https://github.com/very-good-science/data-ethics-club/), and am really interested in how we can understand the way we approach data analysis as a function of our lived experiences and positionality. 
>
* Personal highlights: I started to design and draft a new chapter about self-reflection for data scientists, and was really excited to meet lots of fascinating and kind people who are also working on the Guide for Ethical Research! 
>
* Quotes:
> Being part of the Book Dash has been a great reminder of how team-based science can be such a joyful and fun experience! An especially well-timed reminder after spending a year working from my flat!

**Comment by ninadicara** [comment]
Sorry, pressed the wrong button!! 😆 🙄

**Comment by Arielle-Bennett** [comment]
### Arielle Bennett

* Role: Research Project Manger, Tools, Practices & Systems Programme, Book Dash May 2021 Organising Committee
* GitHub id: [Arielle-Bennett](http://github.com/Arielle-Bennett)
* ORCID: https://orcid.org/0000-0002-0154-2982
* Short bio:
> I am the Research Project Manager for the Tools, Practices & Systems Programme at the Alan Turing Institute, a critical research infrastructure role ensuring smooth delivery of complex collaborations, initiatives and overall programme strategy. 
> The programme is focused on developing and enhancing the culture change, research tools, and knowledge needed to support open source, multidisciplinary work across data science and beyond. 
> I have worked in research infrastructure roles since graduating with a BA in Natural Sciences, resulting in a breadth of understanding across the complex ecosystem of research publishing, start ups, community and project management. 
> Following my Community Engagement Fellowship in 2019 with the Center for Scientific Collaboration & Community Engagement, I am an active member of the CSCCE community, sitting on their Code of Conduct Committee and organising the Diversity, Equity & Inclusion Special Interest Group. 

* Personal highlights:
> Before participating in the Turing Way, I didn't know what a pull request was, nevermind how to make one!
> Now I have contributed to several different parts of the five guides, including co-writing the initial chapters on [activism for researchers](https://the-turing-way.netlify.app/ethical-research/activism.html) and given presentations on the topic at conferences. 
> I also now mentor other community contributors on how to create pull requests, contribute to existing chapters, review others work, and draft new ideas. 
> The May 2021 Book Dash was an amazing opportunity to engage with the community and get excited about the project all over again! 
> I came away from it feeling enthused and proud of the contributions people made with my support - it will be brilliant to see how these evolve over the coming months into content and chapters. 


* Personal Quote:
> The Book Dash is an incredible experience for both newer and established community members. It is joyful work to spend focused time on developing content for the Turing Way and supporting people from across the globe to contribute. I feel lucky to have been able to take part and take on a more prominent role as part of the organising committee.

**Comment by EstherPlomp** [comment]
### Esther Plomp

* Role: Book Dash Planning Committee member 2021, Book Dash February 2020 Attendee, semi regular co-working call crasher
* GitHub id: [EstherPlomp](https://github.com/estherplomp)
* ORCID: [0000-0003-3625-1357](https://orcid.org/0000-0003-3625-1357)
* Twitter: [@PhDToothFAIRy](https://twitter.com/PhDToothFAIRy/)
* Short bio: 
> I'm a Data Steward at Delft University of Technology in the Netherlands, where I support researchers with their data management and open science practices. For my PhD research I analysed human teeth for their isotopic/chemical composition in order to say something about human mobility patterns (fields of forensics, archaeology, osteology). Next to the Turing Way I'm also involved with other teams, such as the [Open Research Calendar](https://openresearchcalendar.org/) ([follow the calendar on Twitter!](https://twitter.com/OpenResearchCal)), [IsoArcH](https://isoarch.eu/) and I was an [OLS3](https://openlifesci.org/ols-3/) mentor! I'm also interested in anything related to physical samples in research, and I'm a co-chair of the [Research Data Alliance Physical Samples Interest Group](https://www.rd-alliance.org/groups/physical-samples-and-collections-research-data-ecosystem-ig). 

* Personal highlights:
> Thanks to the Turing Way I really learned how to work collaboratively using GitHub. The book dash in February 2020 was a great kick start to actually practise and directly apply these skills, which now allows me to contribute more confidently to other projects as well! I primarily contributed to the Reproducible Research Chapter, to the Research Data Management section. I reviewed existing content and I'm working on adding a section on Data Management Plans and how to handle personal data. I also made a [The Turing Way poster](https://doi.org/10.5281/zenodo.4263403) that I presented during a conference. I hope to pay it forward and facilitate others in learning how to work with GitHub through The Turing Way or The Carpentries workshops. I'm very grateful to be part of this great and inclusive community!

* Quotes:
>

**Comment by andreea-avramescu** [comment]
* Role: Book Dash 2021 participant
* GitHub id: [https://github.com/andreea-avramescu](andreea-avramescu)
* ORCID: [https://orcid.org/0000-0001-6837-6272](0000-0001-6837-6272)
* Short bio: I am a PhD student at the Alliance Manchester Business School, the University of Manchester (supervised by Dr. Richard Allmendinger and Dr. Manuel López-Ibáñez) and an Engage@Turing/Enrichment Student at The Alan Turing Institute. My research interests lie in the fields of personalised medicine, optimisation and data science, and how all these can be used together to improve the availability and accessibility of targeted treatments worldwide. I have an MSc in Data Science and have previously worked on various research problems from within the fields of social sciences, law, computer science, and operations research.
* Personal highlights: Throughout the week I had the chance to improve a chapter on project design and review existing PRs. i also engaged in discussions with the team around the general challenges encountered in reproducible research and project design. 
* Quotes: The 2021 May Book Dash was an exciting and inspiring opportunity. The events throughout the week were extremely well organised and the inclusive environment was very welcoming. 
>

**Comment by malvikasharan** [comment]
All these contributors have been added to the contributor's file. Thank you @BatoolMM for coordinating this. <3
