### ISSUE TITLE
Preprint information

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1943]
## Summary
I don't think we have a clear explanation of what a preprint is within the book and why you can consider this. Would it help to have an explanation in the Open Access section or could it do with it's own section?

### Discussion Points

- [ ] Is a preprint explanation needed? 
- [ ] Where would a preprint explanation section go?

## Who can help?

* Anyone!

**Comment by da5nsy** [comment]
This is my go-to place for info on preprints, in case it is useful: https://asapbio.org/preprint-info
Lots of nifty infographics

**Comment by da5nsy** [comment]
Looks like the current spot where this is discussed is here https://the-turing-way.netlify.app/reproducible-research/open/open-access.html#repositories-and-self-archiving
I think it could definitely be expanded and brought up to date

**Comment by vhellon** [comment]
@EstherPlomp I think this has been completed when I re-wrote the OA chapter during the bookdash- #2167  Do you think we can close this issue?

**Comment by EstherPlomp** [comment]
Late response, but yes - think so and will close it now :D
