### ISSUE TITLE
Open Access: add more detailed information (colours)?

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#1944]
### Summary

We have an open access section but it doesn't really address the different options that are available (green/gold/diamond etc). Would it make sense to add this information or would that just be more confusing? 

### What needs to be done?

- [ ] Discussion on whether adding more detailed open access information is helpful or more confusing

### Who can help?

* Anyone!

---

**Comment by Arielle-Bennett** [comment]
Hi @EstherPlomp I think it would be good to cover in a chapter or check if there's a good explanation out there that we can adapt/reuse to explain this? Surely one of the OA journals (PLOS/eLife) has done something on this we can quote? 

Open Access isn't as unfamiliar as it would have been 10 years ago, but there's a lot of confusion about the colours as you mention!

**Comment by AlexiaDievart** [comment]
Hi @EstherPlomp and @Arielle-Bennett ! I am new to the project but very happy to contribute if I can. I had a look at the Open Access chapter, and it is quite nice already but lacks a lot of information (especially in the publication part).

I would suggest to write on predatory journals (what are they and why do they exist ? how to recognize them ? where could you flag them ?), either as a full chapter (ideal) or as a note in the "Open Access" chapter (Publication)
If it is as a full chapter, I suggest creating a new "Guide for Publishing" and maybe separate the philosophy behind open access (to keep where it is now) and how to practically publish a paper in open access (with links back and forth) in this new guide for publishing.

A nice infographic image would be awesome to show the difference between the different open access options ! Love your idea !

What could be done at short-term is :
1.  Find this infographic and adapt it for the open access options
2.  Write a short note on predatory journals so long to add in the Open Access chapter until a decision is taken collaboratively to create a new guide (depending on the pertinence of it).

What do you think about it ?

**Comment by EstherPlomp** [comment]
Hi @AlexiaDievart! 

Sorry for the slow response: holiday period :)

I'm happy to start drafting a text about Open Access etc. I opened up a HackMd document where I'll start writing down things when I have some time: https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/rk605rBJK/edit. I quite liked the infographic that you shared! Perhaps the easiest thing to do is just add that link somewhere :)

Feel free to add your thoughts on predatory publishing on that HackMd or to start your own (collaborative) notes! I'm happy to have a look at it when you could use some feedback. 

Cheers!

**Comment by vhellon** [comment]
Hi all, I will be working on reviewing and updating this chapter during the book dash- will let you know when I've made some edits ready for review.

**Comment by EstherPlomp** [comment]
Hi @vhellon! A couple of resources that I found helpful and that might fit somewhere: 


- OA publishing: https://www.youtube.com/watch?v=CFa2QeMgk9k
- Why not use Academia/ResearchGate? Blogpost: https://osc.universityofcalifornia.edu/2015/12/a-social-networking-site-is-not-an-open-access-repository/
- what are APCs? https://www.youtube.com/watch?v=QAeTKUpZq_Y 
- Find a suitable OA journal for your discipline by searching the [Directory of Open Access Journals](https://doaj.org/) (DOAJ). 
- ['Think. Check. Submit' checklist](http://thinkchecksubmit.org/check/) to help you assess the quality of the journal you are considering (because some people equate Open Access with bad quality/predatory publishing)
- Open access / licensee intro by heather piwowar which is super understandable :D : http://go.sirsidynix.com/2020-04-29-Episode-1-Introduction-to-Open-Access.html

**Comment by vhellon** [comment]
Amazing thank you! Already have think, check, submit but will add in some of the others :)

**Comment by vhellon** [comment]
@EstherPlomp I think this has been completed when I re-wrote the OA chapter during the bookdash- #2167  Do you think we can close this issue?

**Comment by EstherPlomp** [comment]
Yes, I think you addressed that with your bookdash contributions!
