### ISSUE TITLE
[BUG] Syntactic highlighting after search

### ISSUE THREAD

**Issue by priyanshuone6** [alan-turing-institute/the-turing-way#1956]
### Description

Syntactic highlighting after search is not working as expected

#### Expected behaviour

- [ ] *The word should be highlighted after searching*

#### Actual behaviour

![](https://user-images.githubusercontent.com/64051212/119231134-dc192780-bb3c-11eb-89ee-60772c3b4003.png)

### How to reproduce

1. Go to https://the-turing-way.netlify.app/
2. Click on `Search this book...`
3. Search something
4. See the word searched is not highlighted

**Comment by da5nsy** [comment]
Not sure when this was fixed, but it is now working: 
![image](https://user-images.githubusercontent.com/3739866/208964013-94f859ce-a7ce-4414-ae83-cf90debd8a3e.png)

Thank you for pointing this out @priyanshuone6, and apologies for the very slow reply.

@all-contributors please add @priyanshuone6  for bug

**Comment by da5nsy** [comment]
Well, you seem to have worked it out @.all-contributors, so I'll disregard your previous message 👍 
![image](https://user-images.githubusercontent.com/3739866/208964984-8f743999-7162-4f69-902d-d4cac3f3bdc2.png)
