### ISSUE TITLE
[BUG] Duplicate content in Open Data section

### ISSUE THREAD

**Issue by flavio2018** [alan-turing-institute/the-turing-way#1970]
### Summary

Hi all!
I noticed a duplicate in the paragraphs [Privacy and Data Protection](https://the-turing-way.netlify.app/reproducible-research/open/open-data.html#privacy-and-data-protection) and [Anonymization](https://the-turing-way.netlify.app/reproducible-research/open/open-data.html#anonymisation) of the [Open Data](https://the-turing-way.netlify.app/reproducible-research/open/open-data.html) section of the book. In particular, the following piece of text appears twice:

> Individuals must be protected from (re)identification through their data Anonymisation of the data may be sufficient in some cases, but ensuring that re-identification is not possible is becoming increasingly difficult. It might even be impossible due to technical progress, growing computational power and – ironically – more open data.
> For example, re-identification may be possible via data-mining of accessible data and so-called quasi-identifiers, a set of (common) properties that are – in their combination – so specific that they can be used to identify an individual. Preserving privacy may still be possible if partial or generalised datasets are provided, like age groups instead of birth date, or only the first two digits of postal codes. It may also be possible to provide the data in such a format that researchers can query whilst keeping the data itself closed. For example, a user may be able to send a query to retrieve the mean of a dataset, but not be able to access any of the individual data points. 

I don't know if this is intended, but I think it would be clearer if the duplicate content was only included in the Anonymization paragraph (which seems to me more coherent with the content) and the Privacy and Data Protection paragraph included only a part of the duplicate content (if deemed necessary) or entirely different content.

### What needs to be done?

- [ ] changing the content of Privacy and Data Protection paragraph in the Open Data section

### Who can help?

* editors
* me?

---

**Comment by malvikasharan** [comment]
Thanks for pointing it @flavio2018. I agree with removing the duplicated content and keeping them in the anonymisation section only. Would you like to create a PR fixing it?

**Comment by flavio2018** [comment]
Sure, I'll create it as soon as I can

**Comment by EstherPlomp** [comment]
Belated thanks for catching this @flavio2018! I'm addressing this now in #2891
