### ISSUE TITLE
The Turing Way out there in the wild

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#1986]
### Summary

This issue is to collect resources that mentions The Turing Way:
For example, [ University of Exeter Funding for prospective students](http://www.exeter.ac.uk/studying/funding/award/?id=4157) (Upon joining the team a candidate will be trained in modern approaches to open science, following the Turing Way, covering skills to provide runnable and transparent models and artefacts for other researchers and the NHS. Training in machine learning and computer simulation will be provided as required.)

**Comment by malvikasharan** [comment]
Image used: 
- Should We Mandate a Course in Ethics for All Research-Based PhD Candidates? - Social Science Space. (2021, June 11). Retrieved from https://www.socialsciencespace.com/2021/06/should-we-mandate-a-course-in-ethics-for-all-research-based-phd-candidates

**Comment by EstherPlomp** [comment]
@malvikasharan, @aleesteele: I think this is now collected through the newsletter issue, or elsewhere? Can we close this issue? 

(again, as part of the reviewer/editor group :))

**Comment by aleesteele** [comment]
I would say we can go ahead and close it, @EstherPlomp!
