### ISSUE TITLE
Chapter curation for data study group

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2018]
### Summary

* We will post the chapter links that we would like DSG to participants to use

### What needs to be done?

- [ ] @DaisyParry and @malvikasharan are curating this
- [ ] Add detailed tag in the chapter

---

**Comment by EKaroune** [comment]
[Reproducible research overview](https://the-turing-way.netlify.app/reproducible-research/overview.html)

[Open Research](https://the-turing-way.netlify.app/reproducible-research/open.html)

[Data licenses](https://the-turing-way.netlify.app/reproducible-research/licensing/licensing-data.html)

[Planning for project design](https://the-turing-way.netlify.app/project-design/pd-overview/pd-overview-planning.html)

[Creating a project repository](https://the-turing-way.netlify.app/project-design/project-repo.html)

[Getting started with Github](https://the-turing-way.netlify.app/collaboration/github-novice.html)

[Remote collaboration](https://the-turing-way.netlify.app/collaboration/remote-collab.html)

[Guide for ethical research](https://the-turing-way.netlify.app/ethical-research/ethical-research.html)

**Comment by malvikasharan** [comment]
Thank you @EKaroune and @DaisyParry, Let me propose the tags in these chapters and tag you there.
Apology that I could not give time during the collaboration cafe today.

**Comment by malvikasharan** [comment]
Here are the tagged chapters: https://deploy-preview-2019--the-turing-way.netlify.app/search.html?q=dsg (when merged, they should appear with https://the-turing-way.netlify.app/search.html?q=dsg)
