### ISSUE TITLE
"book(s)" vs "guide"

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#2030]
### Summary

There appears to be inconsistent usage of the terms "book(s)" and "guide".

My understanding is that the Turing Way (the whole thing) is a "guide", though in the early days it was a "book", before several more "books" were added, at which point it became a "guide" which comprises several "books" (each of which have multiple "chapters").

It would be nice to keep the terms clear and consistent.

Current issues:
- The landing page switches back and forth between the various uses.
- The search bar says "search this book" but actually searches *all* the books, not just the one the user is currently browsing.
- The footer says 'This book is powered by Jupyter Book', where it should probably read 'This _guide_ is powered by Jupyter Book'.

### What needs to be done? and by who?

- [ ] *Confirm/dispute my understanding of how we should be using the terms* (needs input from a long-term contributor)
- [ ] *Fix the places where they are used incorrectly* (anyone can help)

**Comment by malvikasharan** [comment]
Good point to raise.

The Turing Way is described as a book with multiple guides, but also as a handbook/guide to data science.
The inconsistency in welcome is probably historical - but your auditing actually helps in describing each of these explicitly:
- Book
- Guide
- Chapter
- Subchapters

**Comment by da5nsy** [comment]
Let's have a stab at defining these explicitly:
 
### Option A (levels from top to bottom):
1. **Book**: The whole thing / "The Turing Way", comprising multiple guides.
2. **Guide**: Collection of chapters on a topic, e.g. "Guide for Reproducible Research"
3. **Chapter**: Sub-unit within a guide (better definitions welcome).
4. **Subchapters**: Sub-unit within a chapter (better definitions welcome).

which is based on what you've said above @malvikasharan.

### Option B (levels from top to bottom):
1. **Guide**: The whole thing / "The Turing Way", comprising multiple guides.
2. **Books**: Collection of chapters on a topic, e.g. "Guide for Reproducible Research"
_(3. and 4. as above)_

which was my previous impression.

---

I think either is reasonable. 

#### Pros for Option A: 
- Sticks with 'The Turing Way' being a "book", which allows continuity from before the addition of the additional "Guides for X"
- It allows the "Guides for X" to be referred to as guides.
- It makes sense in the context of this being a single jupyter *book* project ("search this book" etc. make sense).

#### Cons for Option A:
- Would require changing some things around. I would suggest doing a full search for the words "book" and "guide" throughout the repo and making sure they're used correctly.

#### Pros for Option B: 
- It is in line with the current landing page descriptions: 
   - "The Turing Way is an open source community-driven **guide** to reproducible, ethical, inclusive and collaborative data science."
   - "In February 2020, The Turing Way expanded to a series of **books**..."

#### Cons for Option B:
- Given the naming of "Guides for X" (which I assume would be a pain/ineffective to change), referring to the whole thing as a guide, and then each "Guide for X" as a "book" is inherently confusing.
   
My vote goes for Option A.

**Comment by malvikasharan** [comment]
Thank you @da5nsy! I like making things more explicit - and I can use your energy in getting them done faster than planning and never getting to them alone.

I vote for option A, as this is how the project has been defined from the start. I am happy to help and also check with others interested (maybe @RaoOfPhysics) to help out with this in the welcome page and community handbook.

**Comment by RaoOfPhysics** [comment]
Hi folks!

@da5nsy, you raise a good point. And your breakdown of the current state of things and the two options is very clear to me. Like @malvikasharan, I'm leaning towards referring to the entire document – _The Turing Way_ – as a book. That said, I don't find it particularly problematic to refer to the entire book as a guide; indeed guides were once produced in traditional paper-book form. :) So, I suppose you can have a guide to X with "sub-guides" within? Since @malvikasharan also mentions referring to it as a handbook, calling it a "guidebook" would also work, I think.

Within, each section is a guide to a specific area/topic. The name there is less important, I feel. But referring to them as "guides" works really well. :) You could say "see our section on reproducible research" or equally "see the Guide for Reproducible Research" [in capitals because it is a section title].

Would you like me to review any changes, besides the one in the commit [1b26045](https://github.com/alan-turing-institute/the-turing-way/commit/1b260455bb3c0ddd073b531c81592c742013fa31)?

Cheers,  
A.

**Comment by da5nsy** [comment]
Thanks for the input @RaoOfPhysics. 

I think I agree with all your points, though I'm less keen on calling the entire document a 'guide', not because it isn't appropriate (in fact, in 1b26045 for example, 'guide' definitely reads better) but because I think there is value in having distinct terms for the different levels, especially for new users.

Don't worry about reviewing 1b26045 for now. I've rolled https://github.com/alan-turing-institute/the-turing-way/pull/1961 back to a draft for now while I work some other things out and it may well get overwritten.

**Comment by RaoOfPhysics** [comment]
Yes, I'm with you on having distinct terms. :) "_The Turing Way_ is a book in which you will find guides to…"

**Comment by da5nsy** [comment]
> "The Turing Way is a book in which you will find guides to…"
That's lovely! Tagging #2032 so that we keep a note of this...

**Comment by da5nsy** [comment]
Closing this because:
- I got the answers I needed to complete #1961 
- There seems to be agreement from those who have commented here
- Looking through the project at the uses of "guide" and "book" everything seems to fit "Option A" already, so it appears that there is no additional work required to improve consistency
