### ISSUE TITLE
[Bug] Add Fair Cookbook as reference in the FAIR (RDM) chapter

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2037]
### Summary

* The FAIR cookbook should be added as a reference in the [FAIR chapter](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-fair.html), as well as linked to the [impact story by Susanna](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-stories.html)

### What needs to be done?

- [ ] As a collaborating project, we want to highlight the Fair cookbook resources and also find ways for people to get involved there.

### Who can help?

* Anyone interested to add this
* Understanding of FAIR principle is not necessary but useful

---

**Comment by EKaroune** [comment]
This resource should also be added: RDM kit - https://rdmkit.elixir-europe.org/

**Comment by malvikasharan** [comment]
@EKaroune there is sub chapter about it in RDM by @KimDeRuyck from Elixir. Maybe we can revisit that and see if that should be expanded.

**Comment by EKaroune** [comment]
I think what needs to happen is the resources from the chapters need to be moved to the resources sub-chapter at the end of the RDM chapter and put under the other sub-chapter headings. This will make all the resources easier to find.

**Comment by EstherPlomp** [comment]
These resources are listed on the FAIR page: https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-fair.html#community-involvement. 

I'll also add both to the resources page: thanks!
