### ISSUE TITLE
OSFair 2021 submission draft

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2040]
### Summary

* @EKaroune @EstherPlomp and @rainsworth are drafting workshop proposal for OSFair (see the [call for workshops](https://www.opensciencefair.eu/call-for-workshops-2021))

### What needs to be done?

- [x] Copy the proposal outline
- [x] Add notes
- [x] Submit 
- [x] Add abstract to the GitHub conference folder

### Who can help?

* @EKaroune @EstherPlomp and @rainsworth 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by EKaroune** [comment]
PR for abstract here: https://github.com/alan-turing-institute/the-turing-way/pull/2041

**Comment by EKaroune** [comment]
Abstract has been submitted now.
