### ISSUE TITLE
Book Dash Planning Issue: 8 - 12 November 2021

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2064]
# Book Dash Logistics

Date for the next event: 8 - 12 November 2021

## Before the Event

- [x] Establish a Book Dash Planning committee by inviting returning members of the event
- [x] Finalise dates based on the location and organisers' availability
- [x] Update the Book Dash chapter to reflect any changes introduced by the feedback from previous events
- [x] Set up an online platform ([Zoom](https://zoom.us/), or other accessible software) for remote collaboration
- [x] Set up a form (see a template {ref}`here<ch-bookdash-application-additional-materials>`) for application by updating the previous version of the form
- [x] Discuss with co-organisers if some resources (such as email drafts or templates) need to be updated
- [x] Write a short description for online advertisement and create an Eventbrite page with codes for free registrations
- [x] Clearly state the following information in an application form and later communicate by email with the selected participants:
  * what financial support will be available for either online or in-person events
  * What arrangements will be available online (such as online helpers and designated mentors) or on-site (such as quiet room and child care) for in-person events
  * Include accessibility information such as live captioning for in-person events and quiet room/child nursing room for in-person events
  * Mention the maximum limit for financial support requests for online (such as for headphones) and in-person (such as for travel and accommodation) events
- [x] Set up the Book Dash Planning meeting to discuss these details before the announcement is sent out
  * Find volunteers from the organisers who would like to host onboarding calls (1 week before the event)
  * Find volunteers from the organisers who would like to host a GitHub introduction session (1 week before the event)
  * Find volunteers from the organisers who would like to run social events (discussion session, meal, informal chat) - During the event
  * Find volunteers from the organisers who would like to run community share out sessions - on the last day
  * Check with them if there is anything else they would like to suggest or get involved in
- [x] Announce in the newsletter and promote on Twitter at least 2-3 months in advance
- [x] Think about who else needs to be invited, like Artists, speakers, more diverse participants
- [x] Identify helpers from the core members and invite them
- [x] Send a reminder in next newsletters with more details if needed
- [x] Close the application round in time (1-2 months ahead of the event)
- [x] Set-up a form for reviewing applications (see {ref}`ch-bookdash-application-rubrics` for details)
- [x] Review applications in a designated panel (Book Dash Planning Committee) using Book Dash Rubrics for selection
- [x] Set up another meeting with the Book Dash Planning Committee to discuss the applications and finalise the selection
  * Use this meeting to also allocate tasks for during and after the event (indicate that on the GitHub issues)
- [x] Send an email to the selected attendees with registration link and code
- [x] Send an email to the unselected attendees with feedback
- [x] Set up an email chain and a Slack channel to connect all members and share updates
- [x] Update presentation for introducing the project to the participants on day-1 of the book dash
- [x] Update shared HackMD for `pre-event calls<ch-template-bookdash-precall>`, {ref}`book dash event<ch-template-bookdash-notes>` and {ref}`feedback<ch-template-bookdash-feedback>`
- [x] Provide details on Code of Conduct, contribution guideline and ways to get involved in an ongoing discussion
- [x] Host the onboarding call one week before the event to share logistics and facilitate the drafting of SMART goals
- [x] Group participants into the proposed working groups as per their SMART goals from the onboarding call
- [x] Host the onboarding call one week before the event to share logistics and facilitate the drafting of SMART goals
- [x] Send a reminder email to register on Eventbrite sharing important links and information including support grant, GitHub session, onboarding call info and reimbursement process
- [x] Create a GitHub issue to collect bio and highlight of the participants to add them to the Contributors Record

**Additional task for an online event**

- [x] State the requirement and expectation of the event
  * An active GitHub account
  * Some experience with using GitHub or plan to participate in the Book Dash GitHub training session
  * Familiarity with contribution guidelines and Code of Conduct
  * A full working day time commitment
  * Willingness to collaborate with others
  * Participation in at least one onboarding call or a Collaboration Cafe
- [x] Plan to attend at least one development session (2.5 hour) each day
- [x] Collect address if something needs to be posted

**Additional task for hub Event**

- [x] Provide guidance to set up a Hub event (hybrid)
- [x] Collate participants' information for travel or accessibility requests through the registration form
- [x] Send an email to the participants regarding their in-person logistics
- [ ] Confirm a plan for social meals

## During the Event

- [x] Run onboarding sessions on the first day
  * Welcome everyone (for each slot)
  * Ask to fill the icebreaker
  * One of the organisers delivers introduction talk
  * Create breakout groups for people working on 
- [x] Host coworking sessions with Pomodoro sessions 30-35 mins long
  * At the beginning of the session, ask people to document or verbally share their plan for the session
  * End each session with any report people want to make
  * Give 5 minutes break before entering the next Pomodoro
  * Keep last 10 minutes for final reporting and co-documenting the work that took place during the Pomodoro
- [x] If an artist, illustrator or consultant is invited, coordinate the schedule with participants so they have the chance to engage
- [x] Run a social session each day
  * These are run by organisers to ensure everyone has the chance to connect informally
- [x] Host community share out the event on the last day to demonstrate and celebrate the contributions made by everyone during the Book Dash
- [x] Ask for feedback on the last day (plus and delta)
- [x] Share the GitHub issue for adding bio and highlight
- [x] Take screenshots or group photos (with permission) to share in reports or social media

## After the Event

- [x] Send a thank you email to everyone for their work
- [x] Move bio and highlight from the GitHub issue to the Contributors Record
- [x] Summarise the event (number of pull requests, issue, chapters, and other significant news) to share with the participants
- [x] Share the update via the newsletter
- [x] Develop a report with highlights and updates on GitHub
- [x] Set up a debrief meeting with the planning committee
- [x] Send a thank you note (or a package when possible) to the planning committee

**Comment by malvikasharan** [comment]
The form and shared document have been set-up. See all links: https://hackmd.io/@turingway/bookdash-nov2021

**Comment by EstherPlomp** [comment]
Just some small comments on the application form: 
Is it clear what a developmental session is? Would working session be a better description? 
I find the **'s a bit difficult to read: is there a reason why these aren't in bold?
Other than that it looks great!

**Comment by malvikasharan** [comment]
Thanks, Esther, the development session can be replaced with a working session and also linked to the chapter where it is described. Google form doesn't allow bold or any special formatting. I can remove the "**" and replace them with apostrophes.

**Comment by c-martinez** [comment]
Github session and related materials look good to me (I love https://learngitbranching.js.org/ ! glad it is included!)

**Comment by BatoolMM** [comment]
**I love the new Bookdash chapter that is attached to the forum** 😍. 

Nothing to suggest or add, but that it will be nice to know how did they get to hear/apply to the event. Just so we can reflect on the promotion of the event the next time! Is there a reason why we can't add the typical question "How did you hear about Book Dash? Twitter, newsletter, others". 

Also, as Esther suggested, it's easy to miss some of the links in the intro because there's no bold/formating. It's sad that Google forms don't allow formatting but can I suggest to re-add the link to Book Dash chapter to this question "What could you contribute to The Turing Way during the book dash event?" This is one of the most important questions in the application and most people are usually not sure what to add! Maybe something like 
> You can review examples of the type of possible contributions from [here](https://the-turing-way.netlify.app/community-handbook/bookdash.html). We aim to co-create contents that are comprehensible and beneficial for the wider community of data scientists and researchers. 

These are very small suggestions but free to ignore them!

**Comment by malvikasharan** [comment]
Brilliant suggestions @BatoolMM. I have integrated them in the form now, can you review that please? You can also directly edit them (I have given access to the complete shared folder for this event to the planning committee).

**Comment by malvikasharan** [comment]
Responding to some info that might be useful for others planning to hire a paid illustrator as asked by @cassgvp https://twitter.com/cassgvp/status/1427252529751105542

> I guess I was looking for something like, “these are the benefits”, “this is why you should get a professional”, “this is what you should think about when creating a brief”, “this is how you find someone”, “this is how much it might cost, inc signing over to cc-by”.

## background

The Turing Way involves a professional illustrator in the Book Dash events to help capture the work of Book Dash participants. These are either something that they are writing about in the context of reproducible research, discussions they have at the book dash or the event activities in general.

## Benefits of illustrations and why you should get a professional

The Turing Way chapters often include research or scientific concepts described by professionals. As experts, many of us are not always efficient at communicating our ideas in simple terms for those who are new to those research concepts. This is where illustrations are quite powerful at communicating complex ideas simply and accessibly.

Simple images, tables and flow charts are something that many of us are able to do. Sketchnoting is another way to visually describe a set of ideas. Several resources can be found for people interested in sketchnoting and visual thinking, for example, see this [post from Sketchnote Academy about sketchnotes](https://sketchnoteacademy.com/what-is-sketchnoting/) and [video on visual thinking by Scriberia](https://www.youtube.com/watch?v=-Owxi2QNjlI).

It is definitely an advantage for scientists who are also excellent visual communicators, but it is likely that most people may find it challenging and time taking to create both written and visual materials. Therefore, it is useful to hire expert/professional scribes if a project or event budget allows. These scribes/artists generally talk to researchers for 10-20 minutes to gather all information they need to express their ideas through drawings, illustrations or infographics. Sometimes, these can be done as scribing of a talk or discussion as described in [this video by Scriberia](https://www.youtube.com/watch?v=LjrtKaZVEio). These illustrations can be described for the screen reading apps as well to express abstract concepts more clearly.

Having a scribe at an event can also improve engagement and help participants contribute to something that is immediately and visually achievable in a short duration. Furthermore, even if they are not able to interact with everyone in person, can use their illustrations as a way to exchange their ideas more widely.

## This is what you should think about when creating a brief

Finding a good illustrator or scribe can be a new challenge if you have not worked with one before. It is always useful to ask in your network if someone has previously worked with someone who they may recommend. The cost may vary based on the country, type of service or experience of the scribe/company. Generally, you can find multiple companies or freelancers who offer their services, describe your requirements and ask for quotes. Your request/brief should include the following details:
- your budget and how many hours or days would you require a scribe for
- what kind of sketches do you need: simple illustrations, infographics, motion videos, live scribing
- what would you use those illustrations for reports, videos, presentations or something else
- how do you hope to work with the scribe: in person or online (what platform, do they need audio or video, how would you like them to show illustrations)
- do you have any colour preference (for example, to project your brand or event)
- what should the scribe know about your project or event that will help them think about their sketches
- how much creative freedom would they have in making artistic decisions

## Working with Scriberia

For each Book Dash, The Turing Way works with [Scriberia](https://www.scriberia.com/) artists/scribe that cost £1900 (excluding VAT) per day at the time of writing this (August 2021). The cost is less for half-day, and additional charges apply for infographics.

We directly get in touch with the company to set a 15-20 minutes meeting with their account manager to discuss details. They share a set of quotes the next day and block the dates/time as per our requests.

For each event, we have worked with different scribes and enjoy the diverse style and skills they bring to the event. Our illustrations are often a mix of simple and complex concepts and are often described with cartoon-like characters. The Scribria company is given equal authorship with The Turing Way community members who contribute to the development of those images during the Book Dash. Images are uploaded on Zenodo with descriptive names as individual images in 'jpg' format to allow preview and zipped folder in different file formats to allow downloading. See details here: https://zenodo.org/record/3332807

## Pro tips

To enhance the use of these illustrations, we have learned to keep the concepts simple, self-contained and reusable in different contexts. If texts or sentences are used in the image, we request a copy of those illustrations without text to make sure that they can be translated into other languages. We ensure that the cartoon-like characters in the images are designed while maintaining representations of our diverse community members.

**Comment by BatoolMM** [comment]
Thank you @malvikasharan for the elaborate explanation. These are the same questions I had in my mind - one thing I was also wondering - is there a specific reason why Scribria illustrations can't be vector graphics rather than pixelated images? Or do they charge higher prices for vector graphics?

**Comment by malvikasharan** [comment]
When working live, images are made on photoshop or a platform of scribe's choices. They often don't work in layers because of the time constraints and edits as attendees discuss with them during the calls. For the in-person events, we pay extra for the hand-drawn images to be digitalized which is done in layers and shared as SVG.

**Comment by BatoolMM** [comment]
It makes sense now, thank YOU!

**Comment by vhellon** [comment]
Hello from 2023 @malvikasharan ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
