### ISSUE TITLE
[BUG] Fix link

### ISSUE THREAD

**Issue by timyers** [alan-turing-institute/the-turing-way#2089]
### Description

- [ ] Line 32 of the Github repo README.md has a link to the online book that renders to the Github repo.

#### Expected behaviour
 
- [ ] Expected the link to target [*The Turing Way* online book](https://the-turing-way.netlify.app/welcome.html).

#### Actual behaviour

- [ ] The link circles back to the Github repo.

### How to reproduce

For example:
1. Go to [Github repo for *The Turing Way*](https://github.com/alan-turing-institute/the-turing-way).
2. Scroll down to the paragraph just below the first illustration. See screenshot below.

<br>

![Screen Shot 2021-09-13 at 2 58 23 PM](https://user-images.githubusercontent.com/48717893/133141082-8addd49a-1f6a-47a7-b74f-7deec97420d6.png)

<br>

3. Click on the link for the **online** book.  
4. The link takes you back to the Github repo.

### Your personal set up

- OS:  OSX

- Browser:  Chrome

**Comment by da5nsy** [comment]
Thank you for the very clearly written issue @timyers! 
I've put in a pull request that should fix this issue, and hopefully someone will approve that so that it is fixed soon.

@all-contributors please add @timyers for bug fix
