### ISSUE TITLE
[HACKTOBERFEST] Markdown header levels need to be corrected (PRs for HacktoberFest participants)

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/the-turing-way#2108]
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

# Summary of Issue

There are non-consecutive header levels (eg. level 0 to 2, or 1 to 3). Below are listed the current places where this occurs. 

When the issue lists "Non-consecutive header level increase; 0 to 2", it expects headers to follow `#` (a level 0 header), `##` (a level 1 header), `###` (a level 2 header) sequence. So we would love contributors to change the headers to follow (header 0, header 1, header 2, and so on).   

#### What needs to be done
Please select 1-2 of these to fix, open a separate issue, make a PR with the fixed headers, and enjoy your Hacktober! 

**Note:** if there are multiple instances then it means that there are multiple headers that need to be fixed within that book. 

#### List of Non-consecutive header levels to be fixed 

- [x] #1408 reproducible-research/open/open-hardware.md currently starts with h2 tags.
- [x] #1424: reproducible-research/vcs/vcs-resources.md: Create a top header h1 tag called "Resources" and provide a sentence summary of what this subchapter talk about.

#### Who can help?
Anyone who would like to participate in Hacktoberfest or contribute to The Turing Way GitHub repository for the first time easier to do locally (by git) but not mandatory

### About Hacktober and The Turing Way
Hacktober is a month long celebration of Open Source Projects where the goal is to make 4 Pull Requests during the month.

#### A bit about GitHub
If you’re new to GitHub then here are [some instructions](https://help.github.com/articles/signing-up-for-a-new-github-account/) to help you get going. Or refer to The Turing Way's own [Getting Started with GitHub Guide](https://the-turing-way.netlify.app/collaboration/github-novice.html). Remember that you can ask us any questions you need to along the way.

A [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) (what Hacktober is measured on) lets you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

Under the Issues listed in our Hacktober tag, we’ve outlined what needs to be done, and how you can go about addressing it. Once the Issue has been addresses, you can submit a Pull Request for review (tell us what you’ve done) and we can incorporate it into The Turing Way.

We’ve also created this special Hacktoberfest tag to make is easy for you to find places to contribute if you’re new.

In the spirit of Hacktoberfest, please only do a few of these to submit your PR so that we can learn and grow as a community together.

#### Our Community
Please read our core Contributors document and our Code of Conduct while you engage in The Turing Way. We want to ensure that every user and contributor feels welcome, included and supported to participate in The Turing Way community.

In addition, for Hacktober we would also like to recognise the work that you are doing. If you would like to be featured on our [Twitter](https://twitter.com/turingway?s=20) Hacktoberfest series then: 
- Add your twitter handle to the comments when you submit your PR, 
- What brings you to Open Source, Hacktoberfest, and/or The Turing Way,
- and anything else you’d like to celebrate about your contribution!

We welcome all contributions to this project via GitHub issues and pull requests. Please follow these guidelines to make sure your contributions can be easily integrated into the projects. As you start contributing to The Turing Way, don't forget that your ideas are more important than perfect pull requests. ❤️

If you have any questions that aren't discussed below, please let us know through one of the many ways to get in touch.

**Comment by BrainonSilicon** [comment]
> 
> 
> Hi @BrainonSilicon, is #1408 still open? If it is, can I work on it? :)

Hi @aniketh-varma! I think @C-Lion is working on it. Want to take #1424 instead?

@C-Lion - if you've fixed the headers, do you mind checking the item off this list here?

**Comment by aniketh-varma** [comment]
> > Hi @BrainonSilicon, is #1408 still open? If it is, can I work on it? :)
> 
> Hi @aniketh-varma! I think @C-Lion is working on it. Want to take #1424 instead?
> 
> @C-Lion - if you've fixed the headers, do you mind checking the item off this list here?

Sure! I can work on #1424
