### ISSUE TITLE
Write Turing REG blog post

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/the-turing-way#213]
### Summary

We have a space for blog posts (actually titled "Programme articles") on the [Research Engineering Group's website](https://www.turing.ac.uk/research/research-programmes/research-engineering). A post about The Turing Way would be good way of promoting the project.

### What needs to be done?

Decide on the topic of the blog post (to avoid overlap with Becky's - see #181), write the post, then receive and implement feedback.

### Who can help?

Anyone who wants to send feedback :)

---

### Updates

**Comment by pherterich** [comment]
Would @sgibson91 's Binder work be a nice one? Avoids too much overlap with the other comms we've sent out and probably won't be written by someone else...

**Comment by sgibson91** [comment]
I guess I could turn the demo into a blog type post. I'm hesitant with anything else Binder related as progress is still slow. (Maybe tomorrow...)

**Comment by LouiseABowler** [comment]
Yep, definitely a good call to include @sgibson91's demo in there. Maybe we should do a general intro to the Turing Way, then a couple of paragraphs on how @sgibson91 and I are involved? I have some content already in a draft form that we can use for getting started.

**Comment by rainsworth** [comment]
Hi @LouiseABowler - is this still in progress or ok to close?

**Comment by sgibson91** [comment]
Hi @rainsworth, I think this is still in progress. We have a Hut23 blog repo and Louise has an issue relating to the Turing Way open over there.

**Comment by dingaaling** [comment]
Hello from 2022 @LouiseABowler ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by the end of October we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by LouiseABowler** [comment]
Hi @dingaaling, thanks for checking in! I'll close this issue as I'm no longer in Turing's REG so won't be able to contribute a blog post there. It's really great to see how the Turing Way has been growing since I last dropped by! 🌱🌳😊

**Comment by dingaaling** [comment]
Thanks for the response @LouiseABowler! Glad for your virtual visit to TTW, years later 😄
