### ISSUE TITLE
[BUG] Netlify doesn't run with updated default brach

### ISSUE THREAD

**Issue by bsipocz** [alan-turing-institute/the-turing-way#2150]
The last deployment seems to be days ago, while there have been multiple merges to the main branch since.  One of the latest relevant, and failing logs shows that it still tries to pull the `master` branch. Updating the default branch likely requires admin access either to github, or admin access to netlify, see screenshot here:

https://docs.netlify.com/site-deploys/overview/#branch-deploy-controls

cc @sgibson91

**Comment by sgibson91** [comment]
cc @malvikasharan do you have admin access now, or do we still need to ping Alex Morley?

**Comment by sgibson91** [comment]
Thank you to @malvikasharan who gave me team access. I updated the deploy branch to be `main` and manually triggered a new deploy so the book should be up-to-date now!
