### ISSUE TITLE
Improving the Translation of the TW

### ISSUE THREAD

**Issue by BatoolMM** [alan-turing-institute/the-turing-way#2166]
### Summary

There has been extensive work to build a workflow for [ translating The Turing Way using Transfix](https://www.transifex.com/theturingway/theturingway/dashboard/) but there's no formal documentation to the process. Some of the discussion is mentioned in issue #767

### What needs to be done?

- [ ] When the English version is updated, the version on transifex is not updated automatically and this creates a lag between the versions. Then a rebase is needed to update the version on the translation branch. This needs to be fixed maybe using github action. Possibly consider other options for localisation different than Transfix
- [ ] Deploy the translated version
- [ ] Provide documentation for the workflow and potential new translators for other languages (LTR and RTL languages) - things to include in the chapter are:
- Why use the localisation platform?
- Adding a new language
- Adopting the workflow for Jupyter Book
- How to start translating
- How to use ML
- How to use Glossary
- How to share the Translation Memory
- How to approve the translation
- [ ] Improve Glossary and sharing Translation Memory

### Who can help?

*  Anyone who wanna experiment with the deployment of the translated version
* Anyone who wants to give feedback about the current workflow.

---

### Updates

We use [this HackMD](HQQQMlwvTIOtX5nHH9R4eg) to track the work

**Comment by da5nsy** [comment]
Closing as superseded by #2961. Feel free to reopen if I'm misunderstanding 😊
