### ISSUE TITLE
Sprint 20/21 Feb - agenda 

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#217]
### Summary

This is @KirstieJane's first bash at an agenda for the February sprint.

### Wednesday 20 Feb

*Jack Good meeting room on 1st floor of Turing Institute booked from 9am to 5pm*

| Time | Task |
| --- | ---  |
| 9:00 | ☕️ Arrive and get coffee |
| 9:30 | 👍 pluses and deltas, hopes and dreams for the sprint |
| 10:00 | Build a binder workshop planning |
| 11:15 | 15 min break |
| 11:30 | Build a binder workshop planning, hopefully including training for delivering a successful event |
| 12:30 | 🌮 Lunch | 
| 14:00 | Build a binderhub workshop planning | 
| 15:15 | 15 min break |
| 15:30 | Build a binderhub workshop planning, maybe small group working |
| 17:00 | 👋 Close |

 ### Thursday 21 Feb

*Jack Good meeting room on 1st floor of Turing Institute booked from 9am to 3pm*

*Mary Shelley meeting room on 2nd floor of Turing Institute booked from 3pm to 7pm*

| Time | Task |
| --- | ---  |
| 9:00 | ☕️ Arrive and get coffee |
| 9:30 | 🍅 pomodoro working 1 |
| 9:55 | 5 min break |
| 10:00 | 🍅 pomodoro working 2 |
| 10:25 | 5 min break |
| 10:30 | Short share back to group |
| 10:45 | 🍅 pomodoro working 3 |
| 11:10 | 20 min break |
| 11:30 | 🍅 pomodoro working 4 |
| 11:55 | 5 min break |
| 12:00 | Share back to group |
| 12:30 | 🌮 Lunch |
| 14:00 | Open - use as necessary |
| 15:00 | Whitaker Lab Meeting, Turing Way sprint special |
| 16:00 | 👋 Sprint close |
| 17:00 | Binder team meeting (optional) |
| 18:30 | 👋 Really close |

### What needs to be done?

- [ ] Let me know what you think of the idea!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by pherterich** [comment]
Like it, will the hopes and dreams inform the pomodoro to do list?

**Comment by KirstieJane** [comment]
I was imagining that the pomodoro to do list would emerge over the 1st day. So it *might* cover the hopes and dreams, or it might just end up being "this is a good use of my time".

The main point is that I don't think we all need to be working in one big group on Thursday.....but there are definitely pieces of work that I'd like to be able to cross pollinate.

For example: integrating binder into the book, integrating the champions into the book, encouraging community contributions, platform for rendering the book etc.

I don't think we'll complete those during the pom :tomato: sprints but I'd like us to be building up some design docs and getting feedback on them in a quick iterative way.

Does that make sense? Happy to adjust!

**Comment by pherterich** [comment]
Yeah, it does! Just couldn't see a clear slot for :tomato: planning. Also, do we need a slot for admin stuff or will we just us a :tomato: slot for that?

**Comment by KirstieJane** [comment]
Ah - I was imagining that everyone could use the 🍅s as they would like....which includes planning ✨ 

Lets use 🍅 sessions for admin. I don't think its useful to do admin all together, but you and I could do some community engagement or repo tidy up admin in one or two of those sessions for example.

**Comment by LouiseABowler** [comment]
HackMD for "Build a Binder" workshop planning: https://hackmd.io/Uwo81G4YRfa6H11FrAeNWA#

**Comment by arm61** [comment]
Hey, just to confirm what I said in the meeting. At some point next week I will attempt to get a BinderHub running on a cloud resource (initially azure) and make an effort to document this as I go. Following this, I will share this documentation with everyone, in particular, @sgibson91 to see if it makes any sense whatsoever.

**Comment by sgibson91** [comment]
@arm61 Perfect, thanks so much!
