### ISSUE TITLE
Contributing.md doesn't mention co-working calls and collaboration cafés.

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2204]
### Summary

* The Contributing.md doesn't mention co-working calls and collaboration cafés and the current file on the collaboration cafés is outdated. I'm not sure whether it is clear that people can just join these calls if they don't already know about them!

### What needs to be done?

- [ ] Add information about the calls/cafe to the contributing.md OR
- [ ] Set up separate files to explain these calls?

### Who can help?

* A new contributor to check if everything is clear
* @malvikasharan to decide if this info is needed and where it should go

---

**Comment by malvikasharan** [comment]
@EstherPlomp there are separate chapters in the community handbook the describe these calls.
We can add a sentence each and link them to the chapter for details. What do you think?
