### ISSUE TITLE
More information on actual teamwork

### ISSUE THREAD

**Issue by svenvanderburg** [alan-turing-institute/the-turing-way#2207]
### Summary

There is a lot of information about collaboration in the Turing Way, but not a lot on how to work in teams. 

We are developing an open-source course/guide: ['Teamwork for research software development'](https://nlesc.github.io/teamwork-for-research-software-development/), because we noticed there is a lot to learn about teamwork in a research (software) environment that you can not learn from the existing learning resources about teamwork frameworks (e.g. agile, scrum, kanban). It would be nice to add some information from the course and a reference it in the Turing way. I am happy to discuss where would be the best place to add this information.

Seems to be related to #1436, but that focuses only on task management (there is much more to teams than that).

The chapter https://the-turing-way.netlify.app/collaboration/new-community.html slightly touches the teamwork topic, but also doesn't really discuss it.

### What needs to be done?

- [ ] Decide on where to add new information about teamwork, I suggest a new chapter under https://the-turing-way.netlify.app/collaboration/collaboration.html called 'Working in a team'. But I am curious to hear other's opinions.
- [ ] Decide on what information about teamwork to add. I suggest to add a small executive summary of the ['Teamwork for research software development'](https://nlesc.github.io/teamwork-for-research-software-development/) course. And refer the reader to the course for further reading.

### Who can help?

* 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by c-martinez** [comment]
@svenvanderburg -- @malvikasharan is one of the authors of the chapter where this would fit, I'm sure she will be able to guide you through the process.

@malvikasharan, as a bit of background, @svenvanderburg and others have started writing [a standalone guide on teamwork for research software development](https://nlesc.github.io/teamwork-for-research-software-development/) -- I don't think it should be reproduced in full here, but I agree with the "executive summary and refer to the course" idea. Do you have any thoughts on this issue?

**Comment by malvikasharan** [comment]
This looks fantastice. Thank you for the issue @svenvanderburg and the pointers @c-martinez.
I think these resources will fit in the Guide for Collaboration as well as project design (especially the kanban, agile etc.) and can be cross linked with many chapters across the book.

Do you have any preference on where you'd like to see them?

**Comment by svenvanderburg** [comment]
@malvikasharan sorry for this late reply, I somehow completely missed your comment...
Nice to hear you like the suggestion. 

I don't really have a preference, but I will create a Pull Request adding a new chapter on teamwork in the Guide for Collaboration. Then we can see from there how to crosslink it.

I will make some time to do this in about two weeks time.

**Comment by svenvanderburg** [comment]
I created #2239 with a suggestion for fixing this issue. @malvikasharan I am curious what you think! 🤗

**Comment by svenvanderburg** [comment]
Fixed with #2239
