### ISSUE TITLE
Workshop comms | to go out 22 Feb

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#222]
### Summary

We need to send out some details about the workshops *to the people who have signed up*

#### Email to binder participants

- [x] Updated agenda - updated on the eventbrite. @LouiseABowler is currently making a workshops folder on GitHub but if that isn't done by the time this needs to be sent out, just update on eventbrite 😄 
- [x] Note the start and end times, you're welcome to hang out for an extra hour but we'll officially finish at 4pm so that anyone with childcare responsibilities can get home!
- [x] We have funds available for travel and childcare support if you need them. Please get in touch with [EMAIL] to discuss how we can support you.
- [x] Please bring some code and some data. The code should take less than 10 minutes to run, and the data should be less than 10 MB. This might mean that you just pick one script from a bigger project, or bring a subset of your data. Note that it's really important that the code and data can be made public because we'll be using the public binder instance.
- [x] We have helpers at the event who are confident building binders for Python and R projects. They can be either scripts (`.py`, `.R`) or notebooks (`.ipynb` or `.Rmd`). If you are planning to bring code that is not written in R or Python, please send [email address] a little message to make sure that we're prepared for your project 😸 
- [x] Please sign up for a GitHub account if you don't already have one: https://github.com/join.
- [x] We are dedicated to an inclusive and supportive event. Please read the code of conduct before you come along.
- [x] Tweet along at #TuringWay and stickers for those who don't want photos.

#### Email to BinderHub participants

*Not done yet!*

- [ ] Need to get cloud computing resources - PLEASE get from the same place otherwise we'll get stuck.

#### Email to Binder helpers (Manchester)

- [x] Thank you for helping - we really appreciate the support
- [x] You can see the schedule at [GITHUB LINK] and we'll keep updating it over the next week.
- [x] You can see the information that we've sent to the participants at [GITHUB LINK]
- [x] As stated in our code of conduct - need to support everyone who is learning. If there are expert users in the room please feel free to chat with them about anything you'd like, but please do not derail the other learners with more complex topics. Our focus is on supporting the least confident and experienced users as the first priority.
- [x] Would you like to close the workshop? We'd love to give you a few minutes at the end to summarise the day and say well done to the participants.
- [x] Please email Kirstie your travel requirements (if you have any). She'll get train tickets and hotels booked (as required).

#### Make workshops page within this github repository

- [x] Where are we going to host the agenda and docs etc? Shall we make a website from the [build-a-binder one](https://build-a-binder.github.io/)?
  * Need a link!

### Who can help?

* @rosiehigman to send out 🚀 
* @LouiseABowler working on #221

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by pherterich** [comment]
@rosiehigman I will update Eventbrite with new agendas and link to code of conduct now, for new people to look at it to get a better picture. I'll leave it to you to send out the emails to attendees later if that's okay!

**Comment by KirstieJane** [comment]
I remembered this morning about acknowledging pictures etc. So if you (@rosiehigman) can add something about a) please tweet and share your experiences on social media using #TuringWay and b) if you don’t want to be in any pictures, we’ll have stickers for you to put on your name badge so we know to keep you out of pics

**Comment by rosiehigman** [comment]
Email with the comms in PR #234

**Comment by rosiehigman** [comment]
Closed this by accident, re-opening to allow the remaining actions to be addressed.
