### ISSUE TITLE
Version control for datasets

### ISSUE THREAD

**Issue by jcolomb** [alan-turing-institute/the-turing-way#2245]
## Summary

I would like to propose a chapter about the specifics of version control for datasets. Especially, I would emphase the use of git workflows for data, starting with (1) why git is not working well (binary data, large files, lots of files), and (2) how to use git anyway (use submodules, use git-annex). We could then write about different solution (3), probably showing datalad (and gin-cli) implementation of the idea.

I would like to discuss this here before working on it and opening a pull request. 

This may be linked to #585 #622 

### Discussion Points

- [ ] how to organise this chapter
- [x] where to put it in the book
- [ ] find images

### Resources

- [x] https://github.com/datalad-handbook/book

## Who can help?

- [ ] https://github.com/tonic-team
- [ ] @adswa and datalad team
- [ ] Brainhack community ?

## Updates

- [x] Write chapter outline
- [x] Add material to the chapter
- [x] include text/idea from #622 
- [ ] include ideas from 585
- [x] Combine materials into a readable chapter
- [x] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.

**Comment by jcolomb** [comment]
should we split `General Workflow` and put branching as a more advanced option (branches is a quite advanced concept) ?

**Comment by jcolomb** [comment]
Here a link of RDM part of https://github.com/carpentries-incubator/managing-computational-projects
(related project)

https://hackmd.io/7lJ8CxTgSwGS9u6OFBqByg?both

**Comment by jcolomb** [comment]
about structuring the information, see also https://github.com/alan-turing-institute/the-turing-way/issues/1786

**Comment by jcolomb** [comment]
add figures
- [ ] ../figures/folderorga.jpg
- [ ] ../figures/datascience-tree.jpg

**Comment by Elisa-on-GitHub** [comment]
There's an issue with the figure on lines 23-31 of [this page](book/website/reproducible-research/vcs/vcs-data.md). The figure does not show properly in the book

**Comment by jcolomb** [comment]
@malvikasharan can't find the issue with the image, any clue ?

```

> ```{figure} ../../figures/provenance.jpg
> ---
> height: 500px
> name: provenance
> alt: Provenance on which data in which version was underlying which computation is crucial for reproducibility.
> ---
> Provenance on which data in which version was underlying which computation is crucial for reproducibility.
> _The Turing Way_ project illustration by Scriberia. Used under a CC-BY 4.0 licence. DOI: [10.5281/zenodo.3332807](https://doi.org/10.5281/zenodo.3332807).
> ```

```
In another file with similar path:

```
> ```{figure} ../../figures/data-privacy.jpg
> ---
> height: 500px
> name: data-privacy
> alt: An image detailing why private data should be used. A person stands next to a well with 'private data' written on it and a padlock around it. It is black and white and blue. The text lists that 'people deserve - dignity, agency, privacy, rights, confirmed consent.'
> ---
> _The Turing Way_ project illustration by Scriberia. Original version on Zenodo. [http://doi.org/10.5281/zenodo.3695300](http://doi.org/10.5281/zenodo.3695300)
> ```
> 
> 
```

**Comment by jcolomb** [comment]
issue with image fixed (file was called Provenance.jpg)

**Comment by RichardJActon** [comment]
You may be interested in data version control (DVC) https://dvc.org/ which is an interesting tool which fills a similar role to git-lfs and git annex

The Renku's integration of git-lfs if also worth a look at: https://renku.readthedocs.io/en/stable/topic-guides/data/data.html#using-git-lfs-responsibly
