### ISSUE TITLE
2022 conferences to attend, abstract to submit, invite collaborations

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2249]
Closes #1717 

There are several conferences in 2022 that are open for abstract submissions. Please respond below which conference you would like to attend and represent The Turing Way.

- [x] Collaboration Workshop: https://www.software.ac.uk/cw22, deadline 4 Feb
- [x] RightsCon: https://rightscon.secure-platform.com/a, deadline 20 Jan
- ~[ ] Fosdem: https://fosdem.org/2022/news/2021-12-12-call-for-participation/~  <- deadline passed (4 Jan)
- [x] GSoC #2240 
- [x] RSE Con 22 (9 May): https://rsecon2022.society-rse.org/call-for-submissions/
- [x] RightCon - Malvika, Batool, Emma - scheduled on 9 June
- [] ~useR!: https://user2022.r-project.org/~ <-- deadline passed
- [x] CarpentryCon: https://2022.carpentrycon.org/
- [ ] WriteTheDocs: writethedocs.org/ (30 June)

Mentioned by @EstherPlomp @ChrisBeeley @Arielle-Bennett 
- [ ] ~[PUTMET2022](https://pubmet2022.unizd.hr/call-for-submission/)~ <-- Deadline passed
- [x] [Dutch Open Science Festival](https://opensciencefestival.nl/) <-- Lena, Esther, Carlos
- [x] Carpentry Con: https://2022.carpentrycon.org/ <-- deadline 12 June (Esther, Sophia, Hari, Anne)
- [x] Big Science: deadline: https://bigteamscienceconference.github.io/ 22 July
- [ ] Munin Conference: https://site.uit.no/muninconf/call-for-submissions/ (deadline: 22 Aug)
- [ ] NHS-R Conference: https://www.smartsurvey.co.uk/s/JTRT2V/ (deadline: 1 Aug)

Invited conferences

- [x] PyCon USA maintainers summit
- [x] Neic (Nordic Open Science for Collaboration)
- [x] King's College (Anne and Vicky)
- [ ] Newcastle (will connect for September event)
- [ ] Southampton (Malvika and Emma invited on 27 June) 
- [x] Open Science Concordia

Updated with notes from @aleesteele 

- [x] csv,Conf: https://csvconf.com/ <-- returning in 2023 in Argentina, local community members to apply
- [ ] PyData conference: https://pydata.org/ and PyCon: https://pycon.org/ <-- multiple dates

**Comment by aleesteele** [comment]
Historical conferences that TTW contributors have attended, according to previous mailing lists her (ongoing list)e:
- PyCon: https://pycon.org/
- useR!: https://user2022.r-project.org/

**Comment by aleesteele** [comment]
Other events found of Twitter, using the following search: https://twitter.com/search?q=%23openscience%20submit&src=typed_query&pf=on or `#openscience submit`
https://www.open-bio.org/events/bosc-2022/
https://www.open-science-conference.eu/calls2022/
https://bosscon2022.bhki.org/
https://www.opensciencefair.eu/menu/call-for-proposals
https://elifesciences.org/inside-elife/2e7e4ad1/sparks-of-change-share-your-story-in-elife (call for pitches)

**Comment by EstherPlomp** [comment]
Maybe https://site.uit.no/muninconf/call-for-submissions/ (17th Munin Conference on Scholarly Publishing, 29 November–1 December)

**Comment by Arielle-Bennett** [comment]
There's also the recently announced https://bigteamscienceconference.github.io/ in October 2022 which I think we should submit an abstract for!

**Comment by aleesteele** [comment]
Code for All might also be a good place to talk about communities of practice: https://codeforall.org/ (submissions due by 30 June)

**Comment by EstherPlomp** [comment]
[FORCE22 has their call for contributions out now](https://docs.google.com/forms/d/e/1FAIpQLSfNq2oykwEoEaanmuYkmcsZ4sqy-aiOFj3siSB_84Sb2gTJkA/viewform?mc_cid=296b17d06e&mc_eid=20be5be582). It might fit? But I think we also had something last year so it might have to be something more specific than an intro-talk. Deadline = October 20. Conference takes place online on 6-8 December.

**Comment by aleesteele** [comment]
@EstherPlomp - just saw this, sorry I'm late! FORCE22 looks like a great place for us to submit to. Will check it out and add it to the list.

**Comment by aleesteele** [comment]
ACM 2023 - https://cscw.acm.org/2023/

**Comment by aleesteele** [comment]
`
