### ISSUE TITLE
Collect newsletter items for 2022 - January

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2254]
### Summary

* We publish (almost) monthly newsletter on TinyLetter: https://tinyletter.com/TuringWay/archive, most items in that comes from our community members
* Please use this issue to share any update from your project/org/community and work in The Turing Way or beyond that are relavnt for our community

### What needs to be done?

- [ ] Add a short blurb (2-3 sentences) with relevant links that could be added in the newsletter
- [ ] Please do mention the month when this announcement should be made

### Who can help?

* Anyone who has an update to share

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by vhellon** [comment]
If appropriate could you please plug the new Turing-Roche newsletter? Some text (feel free to tweak) if so:

The newly established Turing-Roche strategic partnership (which sits within the Turing's Health programme) has the aim of establishing a world-leading collaboration in advanced analytics between Roche and the Turing, focused on enabling the transformative benefits of personalised healthcare to become a reality for patients around the world over a 5 year period. The partnership has set up a newsletter which will include information about Turing-Roche projects and opportunities, jobs, events and funding calls from both The Alan Turing Institute and Roche. Please sign up to the newsletter here.

**Comment by rainsworth** [comment]
Please share in January, February, and March newsletters if possible ❤️ :

The Software Sustainability Institute’s Collaborations Workshop series brings together researchers, developers, innovators, managers, funders, publishers, policy makers, leaders and educators to explore best practices and the future of research software. Collaborations Workshop 2022 (CW22) will take place online from Monday 4 April - Thursday 7 April 2022 and the themes of the CW22 keynote presentations, discussion groups, mini-workshops, collaborative ideas, and hack day will be around the following areas of research software: Code Review, Ethics, Hybrid Working, and Software Sustainability. To find out more information including registration, agenda, call for submissions and how to sponsor the unconference, please visit the CW22 website: https://software.ac.uk/cw22

**Comment by malvikasharan** [comment]
we cordially invite you to the ninth international Open Science Conference. The conference will take place in virtual form from 08 to 10 March 2022. Registration is now open.
Conference page & programme: https://www.open-science-conference.eu/
Twitter hashtag: #osc2022
Registration: https://www.open-science-conference.eu/registration
The Open Science Conference 2022 is dedicated to the Open Science movement and provides a unique forum for researchers, librarians, practitioners, infrastructure providers, policy makers, and other important stakeholders to discuss the latest and future developments in Open Science.
The conference offers insights into both practical and technical innovations that serve the implementation of open practices as well as current and pioneering developments in the global Open Science movement. Such developments are, for example, the increasing plea for open practices as lessons learned from global crises as well as recent discussions about the relation between Open Science and knowledge equity. The conference offers many opportunities for networking and exchange.
This year’s conference is cooperating with the German Commission for UNESCO. They organise a panel discussion and a workshop in the context of the recently adopted UNESCO Recommendation on Open Science.
You can look forward to the following speakers:
·         Christos Arvanitidis, LifeWatch ERIC, Greece

·         Dr Lauren Cadwallader, Public Library of Science (PLOS), UK/USA

·         Suzanne Dumouchel, Huma-Num (CNRS), France

·         Dr Verena Heise, Freelancer, Germany

·         Dr Paweł Kamocki, Leibniz Institute for the German Language, Germany

·         Professor Daniel S. Katz, University of Illinois at Urbana-Champaign, USA

·         Dr Tony Ross-Hellauer, TU Granz, Austria

·         Dr Anne-Floor Scholvinck, Rathenau Instituut, The Netherlands

·         Joschka Selinger, Society for Freedom Rights, Germany

·         Professor Diethard Tautz, Director Ephemeridum (Chief Editor) of the Leopoldina / Max-Planck Institute for Evolutionary Biology, Germany

The International Open Science Conference is a joint event of the ZBW - Leibniz Information Centre for Economics and the Leibniz Research Alliance Open Science.

We would be happy to welcome you online.

Also, don't miss the Barcamp Open Science on 07 March 2022.
