### ISSUE TITLE
Deployment Failed error when setting up a k8s cluster on Azure

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#226]
### Summary

* Attempting to build a BinderHub
* Using a Free Trial subscription on a personal account (until Turing subscription is sorted out)
* Following these instructions to deploy a k8s cluster on Azure: https://zero-to-jupyterhub.readthedocs.io/en/latest/microsoft/step-zero-azure.html
* Step 6:

Command line input:
```
az aks create --name BHtest2cluster --resource-group BHtest2 --ssh-key-value ssh-key-BHtest2cluster.pub --node-count 3 --node-vm-size Standard_D2s_v3 --output table
```

Error output:
```
Deployment failed. Correlation ID: a53b3c34-b9f7-47ae-9422-882b8270f820. resources.DeploymentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="DeploymentNotFound" Message="Deployment 'cedc4969-5aad-43c2-aeb5-486e5d582491' could not be found."
```

Attempted changing location of resource group from "West Europe" to "centralus" as per this issue: https://github.com/Azure/AKS/issues/145

### What needs to be done?

- [x] Need to figure out what this block actually means
- [ ] Need to know what consequences of using 1 node instead of 3 are on the Build a BinderHub instructions

### Who can help?

* Anyone with knowledge of Azure/Kubernetes/BinderHub

---

### Updates

* Changing `--node-count` from 3 to 1 works
* Error is due to a quota limit on free subscriptions

**Comment by sgibson91** [comment]
Changing `--node-count` from 3 to 1 created a successful output

**Comment by trallard** [comment]
Yes! This is definitely a quota limit, on a free trial account you are limited to a certain number and types of nodes. 
Depending on the number of people that are accessing the instance you might need to scale it up  or change the deployment type but that can  be taken care of when you upgrade the account (as per this * until Turing subscription is sorted out)

Also, I'd still recommend keeping the location as `WestEurope` due to resources availability

**Comment by sgibson91** [comment]
Thanks @trallard I'm only really running through the instructions to see if they work end-to-end, I have no intention of anyone actually using this particular interest.

@betatim  What happens to the BinderHub if you only have 1 node instead of 3? Can it still run or is it going to fall over at some point further in the instructions? This is relevant for the "Build a BinderHub" workshop if we ask attendees to sign up for their own free account ahead of time.

**Comment by trallard** [comment]
No worries! For demonstration purposes using 1 node should be ok, again this will only limit your ability to scale up shall you need more resources but you can always mention this during the workshop and explain that for larger courses or larger user bases more nodes would be needed.

**Comment by sgibson91** [comment]
Closing as I think my questions have been answered. Thank you! 👾
