### ISSUE TITLE
New section in RDM on data articles

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2264]
## Summary

We currently have no information on how you could share your data through a data article (in addition to making it available in the appropriate repositories).

### Discussion Points

- [ ] Am I missing any data article options?

### Resources

- [ ] ?

## Who can help?

* @EKaroune (if you have the time!)
* Anyone that would like to contribute

## Updates

- [x] Write chapter outline
- [x] Add material to the chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.

**Comment by EKaroune** [comment]
There are a lot more places to publish data articles - here is a list for bidoversity type paper - https://www.gbif.org/data-papers#:~:text=A%20data%20paper%20is%20a,means%20of%20a%20scholarly%20article.

But there are lots for health data too so might be best just to list a few examples rather than all?

**Comment by vhellon** [comment]
also happy to help!

**Comment by yabellini** [comment]
I don't know if this applies, but at JAIIO (and the Congress of Agroinformatics), we have the Data Paper format specifically to publish their datasets during the conference. They are published in the proceedings—link to the conference https://www.sadio.org.ar/jaiio/. JAIIO has 14 symposia of computer science and other disciplines in parallel, and the official languages are Spanish, Portuguese and English. (I let the same comment in the PR I think...sorry)

**Comment by EstherPlomp** [comment]
Thanks all! @yabellini: is there any information on the costs of the conference or the data paper in the proceedings? Or are there no charges? 

As discussed on Slack: publishing this now as a separate section on data articles that will later link back to Emma's part on the motivation, software and preregistration papers. Long term we need to think about where to put this information (discuss it during a Book Dash is probably a good idea for more input).

**Comment by yabellini** [comment]
The cost change every year with the conference. But they have a schema with different costs if you are a teacher, student, partner of SADIO, or general public.  Also has a different cost if you have more than one paper.  And early bird tickets.  Here is the cost for last year: https://50jaiio.sadio.org.ar/aranceles .  All the costs are in Argentinian$. That cost is for presenting at the conference and publishing in the proceeding that are Open Access.
