### ISSUE TITLE
GSoC 2022: Project idea and task for the interested candidates

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2266]
## :tada: **Welcome GSoC 2022 Contributors! This is The Turing Way repository** :tada:

:dizzy: _We're excited that you're here and want to contribute._ :dizzy:

*Note that The Turing Way proposal to GSoC 2022 is open for flexible application. This means that students and mentors jointly decide if the effort will be full or half time.*

### Summary

**GSoC**
  * INCF is accepted as [Google Summer of Code](https://summerofcode.withgoogle.com/) (GSoC) organisation, & _The Turing Way_ is listed as one of the projects - [see the proposal](https://github.com/alan-turing-institute/the-turing-way/issues/2240#issuecomment-1013710931) and join the discussion on [Neurostars](https://neurostars.org/t/gsoc-2022-project-idea-3-1-the-turing-way-a-how-to-guide-to-data-science/21380)

**Information for students interested in working on the project:**
* Please read the assessment process and tasks described in the next section
* We urge all the candidates to work on a minimum of 2 projects simultaneously so that they are not completely relying on their selection in The Turing Way if we end up not selecting them.
* We will not be handling communication via personal emails. All responses will be directed to this issue. You are welcome to join our Slack channel, the link for which is given in this HackMD along with all the info that might be helpful for you to learn about The Turing Way: https://hackmd.io/@turingway/demo-intro.
* Please read our [Contribution Guideline](https://github.com/alan-turing-institute/the-turing-way/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/main/CODE_OF_CONDUCT.md) that apply to all our conversations and activities related to GSoC - _The Turing Way_ engagements.

### Assessing Candidates

* We have provided a specific task for the participants to work on during this exploration phase. This task will help the project team members in assessing the technical and communication skills of the interested candidates.
* Other technical contributions are always welcome, but non-assessable contributions like fixing a broken link or typos will not be sufficient to build a proposal with The Turing Way - we need to learn about your ability to work on the technical aspects as well as your collaboration skills while offering you a welcoming environment to participate in Open Source project.

**FEEDBACK**: 
* Feedback will be offered within 7 days to let the candidate know as soon as possible if their proposal can be supported by us or not. 
* We will be able to point candidates to the right resources (please ask on Slack or in this issue by replying below), however, please note that we will not be able to promptly reply unless necessary.
* Please note that most of our community members are volunteers and hence may not be available to respond immediately.

### Resources

The Turing Way resources:
- The Turing Way book is developed in **this** GitHub repo in the 'book directory': https://github.com/alan-turing-institute/the-turing-way/tree/main/book (see the documentation for how to contribute/maintain locally)
- The Turing Way book hosted online at https://the-turing-way.netlify.app/

Please note the Python Package built to improve the usability of The Turing Way is what the GSoC candidates will be looking into during the GSoC exploration phase:
- Python Package: https://github.com/alan-turing-institute/bio-Turing-Way/tree/main/pathways
- Demo of this code on The Turing Way book: https://github.com/alan-turing-institute/bio-Turing-Way/tree/main/master
- Online test book when deployed: https://the-turing-way-personas.netlify.app/welcome

### Specific task for assessment

GSoC candidate upon selection will help improve a Python Package currently located here: https://github.com/alan-turing-institute/bio-Turing-Way.
This package has been developed to enhance the usability of The Turing Way by allowing users to browse a curated set of chapters (rather than the entire book) by clicking on different **cards** as shown for 'Data Study Group', 'PhD Students', 'Group Leaders' and 'Life Scientists': https://the-turing-way-personas.netlify.app/welcome#different-pathways

---
<img width="500" alt="image" src="https://user-images.githubusercontent.com/5370471/157552560-f4982027-1950-4efd-b242-1202daa13d1e.png">

---

We want to integrate this feature in The Turing Way, however, there are some improvements that need to be done to allow a better user experience (UX/UI). 

### Part 1: Tasks to test the Python package locally

- Follow Instructions for "users" as well as "Developers" as described here: https://github.com/alan-turing-institute/bio-Turing-Way/tree/main/pathways <-- for this you will be in bio-Turing-Way/pathways/ directory
- run `cd ..` to come back to the root directory
- run `python -m pathways.main pathways` master to create a local build
- Please see the **card-like** feature (See [panel in the Jupyterbook](https://jupyterbook.org/content/content-blocks.html?highlight=card#panels) and [as used in The Turing Way]()) - also shown in the screenshots above) and **page tag or badge** (see [book badge in Jupyterbook](https://jupyterbook.org/basics/building/index.html?highlight=badge#generate-a-badge-for-your-book) and [as used in The Turing Way on the top of curated pages](https://the-turing-way-personas.netlify.app/reproducible-research/overview.html))
  - you will explore these features locally by copy-pasting the path printed on your screen and scrolling down on the welcome page to the "Different Pathways" section
- Browse different test profiles (see documentation here for details: https://github.com/alan-turing-institute/bio-Turing-Way/blob/main/pathways/documentation.md)
- When you have better familiarity with the book and the user profile feature, you can move to the next part.

### Part 2: Create a GitHub issue

Before you submit your proposal to GSoC, please create an issue in this repository to discuss your plan with GSoC mentors:
- Describe what technical improvements in the Python Package you envision working on during the GSoC 2022.
  - The improvements you suggest should involve coding. 
  - Please don't spend time on content development as that is not in the scope of GSoC. You are welcome to create another issue to suggest content development beyond GSoC that others in our community can work on.
- Explain how you will achieve those improvements.
  - This can include pseudocode, process, visual description and the best-case scenario or rough prototyping of the update.
  - We don't expect you to implement your ideas completely during the exploration phase, but this report should help us understand if we can support the GSoC candidate in developing a proposal for submission
  - Comment under this issue linking to your GitHub issue so that we can review and feedback on it.

### Part 3: Create a test Pull Request

- When you have received some feedback from GSoC mentors @malvikasharan and/or @BrainonSilicon, please make a test Pull Request to demo how you will approach your idea in The Turing Way and add your report in the description of your Pull request. 
  - See this Pull Request for example: https://github.com/alan-turing-institute/the-turing-way/pull/2246 
- Reply under this issue linking to your Pull Request or issue so that we can review it. Please note, that Netlify will allow you to preview your changes on a chapter/book's page without merging the Pull Request to this repository. 

**Please reply under this issue, if any further clarification is needed.**

*Further ideas can be discussed as a comment below, however, we will prefer if we can assess all candidates through the same assessment process.*

### Some notes on what can be improved by the GSoC candidates upon selection

**Adding description in the landing page of all profiles (making it attractive)**

When you visit one of the profiles, for example, [Data Study Group](https://the-turing-way-personas.netlify.app/data-study-group.html), the top of the page says "These are the pages curated for ..." (hardcoded here: https://github.com/alan-turing-institute/bio-Turing-Way/blob/main/pathways/pathways/landing_page.py - Line 25). A better option will be to create a new feature like 'Description' in [profiles.yml](https://github.com/alan-turing-institute/bio-Turing-Way/blob/main/master/profiles.yml) page for each profile where the metadata of curated chapters exists. 

---
<img width="500" alt="image" src="https://user-images.githubusercontent.com/5370471/157552696-2ebaaab6-1a39-4af2-9efd-bb7d2e9eb086.png">

---

**Making the chapters less confusing for users who are exploring a single profile**

When you visit a chapter within a profile specific page like shown above, you will see that all profile **tag/labels** where this chapter is selected (the same chapter can be curated for multiple profiles) appears on the top of the page as shown below.

It will be helpful to have only the original profile (where the user clicked) on the top, and the rest could be hidden to avoid confusion. This may need some planning and development of nee Python Class.

---
<img width="500" alt="image" src="https://user-images.githubusercontent.com/5370471/157556414-cd5e90b5-407c-445d-ad9f-99d41f3f0d65.png">

---

It will be helpful to have only the original profile (where the user clicked) on the top, and rest could be hidden to avoid confusions. This may need some planning and development of nee Python Class.

**Some other ideas for improvement that you can come up with ...**

### Where else can you start to learn about the project?

* Link to the project repository: https://github.com/alan-turing-institute/the-turing-way 
* Project's [README](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md)
* Community handbook: https://the-turing-way.netlify.app/community-handbook
* Go through existing [issues](https://github.com/alan-turing-institute/the-turing-way/issues) and [Pull requests](https://github.com/alan-turing-institute/the-turing-way/pulls) to explore where else you can contribute
* Open a new issue if you have any specific idea for contributions and/or proposals not listed above

### What can _The Turing Way_ offer during this period?

As an Open Source and contribution-driven project, we would like to invite interested candidates to start engaging with the project as a contributor. Please be sure that you follow our contribution guidelines and code of conduct.

* We would like to encourage interested members to work openly and collaboratively in line with the community participation guidelines
* This will allow interested members to learn about the project while helping us see their enthusiasm and willingness to work on this project
* By completing the task, they would be able to provide us examples of their technical skills through contributing to our project on GitHub
* This will also allow them to generate ideas for their proposal or consider if contributing to _The Turing Way_ is the right fit for them 
* If they end up getting selected, they will be able to keep on working with mentorship and guidance to further enhance their work within the project
* If they don't get selected or decide to not go ahead with the proposal, their contributions will still be counted and they will be listed as one of our community members.

*For any further questions, please comment below!*

**Please Note**

Contributing during the exploration phase is meant to assess how well the candidates’ work fit the requirement of a project.
We are looking for a candidate who can work on improving user experience by making the book easy to browse and search for the desired content. 
Furthermore, these candidates will bring their unique skill set to help us improve the quality of our resources. 
With that motivation in mind, we want interested candidates to be aware that we will try to give feedback on Wednesdays to make sure that the co-mentors can review the task in their own time before the FEEDBACK DATES.
It should NOT be assumed that contributing to the project will automatically secure you a position as a selected participant.

**Comment by pranavich18** [comment]
https://github.com/alan-turing-institute/bio-Turing-Way  &   https://github.com/alan-turing-institute/my_jupyter_book both have the same Readme files. Which ones are the instructions to install which one? Can you please clarify? Thanks

**Comment by pranavich18** [comment]
![Screenshot from 2022-03-09 14-42-09](https://user-images.githubusercontent.com/65703661/157410070-52f0aa4c-4d22-48cf-96b4-d8db21a74b52.png)
This is what I get after running tests in the pathways directory. Is this the expected behavior? Can you please guide me what else needs to be done after this?

**Comment by malvikasharan** [comment]
Hi Pranav, thank you for your comment. I have hidden your previous screenshot post to avoid filling up this thread. Pleasee open a nnew issue if you wouldlike o discuss specific technical question.

As for the repos, https://github.com/alan-turing-institute/bio-Turing-Way is the repo where the code developed for UX exist. You an test how that works using the documentation providedd here: https://github.com/alan-turing-institute/bio-Turing-Way/tree/main/pathways.

In the description I have shared in this issue, I have not mentioned https://github.com/alan-turing-institute/my_jupyter_book, as that is I suppose @Iain-S's test copy.

**Comment by pranavich18** [comment]
Ok Thanks for the clarification

**Comment by malvikasharan** [comment]
Thanks @pranavich18 for getting started on the task. I am linking the issue that could be helpful: https://github.com/alan-turing-institute/bio-Turing-Way/issues/40#issuecomment-1063383305

**Comment by malvikasharan** [comment]
Closing this to move discussion for this year oin #2978
