### ISSUE TITLE
[BUG] Link in Online Collaboration Cafe section not working

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#2268]
### Description

The **GitHub page** link in the [**Online Collaboration Cafe**](https://the-turing-way.netlify.app/community-handbook/coworking/coworking-collabcafe.html#) section (see screenshot below) sends me to nowhere (`page not found`).

![image](https://user-images.githubusercontent.com/14146757/153560115-f4fce4f1-7348-465f-a86a-054c7ec32796.png)

TODOs:

- [ ] Find out what the correct link should be.
- [ ] Replace link.

I think this is a perfect beginner issue.

#### Expected behaviour

Link should send me to GitHub page mentioned.

#### Actual behaviour

Page showing `Page not found`

![image](https://user-images.githubusercontent.com/14146757/153560423-01dbe45e-e7fe-4b00-9027-e248520e4c63.png)

**Comment by eddybruv** [comment]
Hello @HeidiSeibold, please can you review this change? I'll be happy to get your feedback.
