### ISSUE TITLE
1 day Sprint in Sheffield

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#228]
### Summary

Please plan on a 1 day sprint in Sheffield on 19 March, the day after the BinderHub workshop (18 March).

### What needs to be done?

- [x] Book a room @annakrystalli 
- [x] Make an agenda (v emergent!)
- [x] Book somewhere for a group dinner 😸 😋 
- [x] Get travel details from the team!
---

### Updates

* Room: AT-509 (14) in the Arts tower, university of Sheffield
* All hotels booked & trains sorted
* Dinner at [Proove](https://goo.gl/maps/NZZjNYJs6B62) booked 😋 

### Agenda

*I (Kirstie) don't know what the agenda will be for Tuesday, but here's the beginning of a timeline...*

| Time | Activity |
| ----- | -------- |
| 9:00 | Arrive, grab coffee, chit chat |
| 9:30 | Reflections on the workshop yesterday & next steps |
| 10:40 | Coffee break ☕️ |
| 10:55 | Goals for #CollabW19, Offboarding @r-j-arnold, @annakrystalli and (maybe) @sgibson91, plans for April/May  |
| 13:00 | Lunch 😋 |
| 14:30 | Bits and bobs |
| 16:00 | Reflections and next steps |
| 16:30 | Close |

I think we'll be tired and there's no great need to push us too late 🤗. Lots of folks have trains home to catch 🚂💨💨💨.

---

Hackmd: https://hackmd.io/troYP801Taa3iPOXilIBHw

Capturing suggested topics for 

* From @pherterich: Agenda item ideas: I would like to make a start on the next newsletter. If we have some time, would this be a good moment to do some reworking of #16 ?
* From @KirstieJane: Goals for collaborations workshop
* From @KirstieJane: Plans for a graceful close out or handover of tasks that @annakrystalli, @r-j-arnold and (maybe) @sgibson91 have been leading on.
* From @KirstieJane: Looking forwards for April & May
  * Including "book dash" events in May.

**Comment by r-j-arnold** [comment]
Room has been booked: Room booking for AT-509 (14) - Arts Tower - 19 March 2019, 9:00 am - 5:00 pm

The arts tower post code: S10 2TN

It also has one of the last existing [paternoster lifts](https://www.youtube.com/watch?v=dPyn2qhD1es) which is quite fun.

**Comment by annakrystalli** [comment]
## Restaurant options

- [Wagamama](https://goo.gl/maps/HnqyJLxmbnn)
- [proove](https://goo.gl/maps/NZZjNYJs6B62) pizza
- [Frehiwat Habesha](https://goo.gl/maps/vHxVduRoxLy) Ethiopian
- [Maveli](https://goo.gl/maps/YV23UZLnsTG2) South Indian
- [The York](https://goo.gl/maps/Hdh6F3KNvQQ2) Pub


Feel free to edit with 👍

**Comment by r-j-arnold** [comment]
- [The Devonshire](thedevonshiresheffield.co.uk) Pub
- [The forum](forumsheffield.co.uk) Pub + small plates +pizzas
- [Orient express](orientexpresssheffield.com) Chinese
- [Piccolos](piccolositalian.co.uk) Italian, a bit small as is Proove

**Comment by pherterich** [comment]
Could I get Birmingham New Street 7:30 -> Sheffield 8:48 on 18th March and return on 19th at 18:24 (arriving in Birmingham at 19:27) please?
Sheffield is so close, I can't believe I haven't been yet...

**Comment by rosiehigman** [comment]
I think my coming or not depends a bit on the agenda as I need to be back in Manchester to teach in the afternoon. But if there is helpful stuff I can contribute to please can I get Manchester Piccadilly 7.18-> Sheffield 8.09 and 12.11 Sheffield - Manchester Piccadilly 13.02 on 19th March 😄

**Comment by KirstieJane** [comment]
@rosiehigman - how do you feel about coming over for the team dinner out? I can pay for you to stay in Sheffield that night and then it would be totally fine for you to skip out in the afternoon of the sprint....or you could just go home after that dinner....what do you think?

The agenda is mostly to capture what we learned during the sprint and to get super jazzed for launching the book at Collaborations Workshop..... which isn't very detailed and you may not have lots of time to dedicate anyway (it's less than 2 weeks from the Sheffield sprint) so happy to go with whatever makes sense for you!

**Comment by KirstieJane** [comment]
@rainsworth are you able to come to the workshop/sprint in Sheffield? No pressure but you're warmly welcome if you can.

**Comment by rainsworth** [comment]
@KirstieJane yes! Happy to come for both the workshop and the sprint, so can arrive morning of March 18th and depart evening of March 19th. Let me know what the procedure is about booking travel/accommodation?

Travel details:
On March 18th: depart 07:38 Manchester Oxford Road [MCO], arrive Sheffield [SHF] 08:34
On March 19th: depart 18:40 Sheffield [SHF], arrive Manchester Oxford Road [MCO] 19:41

(I based my departure off @pherterich's train times, but if it's easier to get an anytime return to more easily accommodate dinner plans on the 19th, I think they are only ~£31 total.)

Let me know if you need more info from me!

ps. is there a slack channel for the group?

**Comment by KirstieJane** [comment]
Decision:

* 1st choice: Proove
* 2nd choice: Maveli

@annakrystalli to give them a call

**Comment by sgibson91** [comment]
My travel is in #169

**Comment by annakrystalli** [comment]
Dinner booked for 6pm at Proove for 12. 🎉🍕♨️😋

To ring and confirm exact numbers nearer the time.

Lunch also moved to 12.30 (fyi @rosiehigman) 👍

**Comment by LouiseABowler** [comment]
I've already booked the following travel - sticking it here so you know when I'll arrive:
Monday 18th March: London St Pancras 14:31 - Sheffield 16:41
Tuesday 19th March: Sheffield 17:29 - London St Pancras 19:39

I'll need a hotel for the night of the 18th - that can go in @KirstieJane's big booking (thank you!).

**Comment by KirstieJane** [comment]
I think I got that in #169 @LouiseABowler! Thank you! 🚀

**Comment by pherterich** [comment]
Agenda item ideas: I would like to make a start on the next newsletter. If we have some time, would this be a good moment to do some reworking of #16 ?

**Comment by annakrystalli** [comment]
Agenda item: the size of the repository. Currently around 850 MB.
