### ISSUE TITLE
Broken image link on /reproducible-research/binderhub.html

### ISSUE THREAD

**Issue by susan-shu-c** [alan-turing-institute/the-turing-way#2296]
Missing image on [this page](https://the-turing-way.netlify.app/reproducible-research/binderhub.html)

Cheers

<img width="852" alt="Screen Shot 2022-03-15 at 4 44 39 PM" src="https://user-images.githubusercontent.com/23287722/158469745-91405d8d-4b84-49a7-81e0-eafc75d6e3de.png">

**Comment by TheAbstract** [comment]
Hey @susan-shu-c the image you referred too on [this page](https://the-turing-way.netlify.app/reproducible-research/binderhub.html) is rendering fine. See image below. I've tested this on Safari and Brave, it could be a browser specific issue 🤷🏾. Anyway, can you confirm which browser your having this issue on?
![Screenshot 2022-10-16 at 16 34 14](https://user-images.githubusercontent.com/56311555/196041449-3a3ef2b3-f39f-46e5-9f3c-dd6490f2dc38.png)

**Comment by susan-shu-c** [comment]
Hi @TheAbstract I was using Chrome! But now it's rendering fine for me too. Possible something was fixed between the time of the issue and now - perhaps a CDN thing. Thanks for the response and I'll close this issue now.
