### ISSUE TITLE
Submission to UK Network of Open Science Working Groups

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#230]
### Summary
@pherterich is considering a submission to UKOSWG (https://sites.google.com/view/ukoswg19) presenting the Turing Way and why librarians are involved and what we do to support Open Science more generally. Deadline is *1st March 2019* 
This might be a shortened version on the Hacker Within talk.

### What needs to be done?
@KirstieJane is basically okay with this, some feedback on the draft below is appreciated so @pherterich doesn't submit something stupid

### Who can help?
- [x] @KirstieJane to comment and edit

---
* Proposed (working) title:   
The TuringWay - supporting reproducibility and Open Science from a librarian's perspective

* Brief outline of session:
Professional services in research institutions such as librarians provide various services and guidance to support Open Science. This session will introduce “The Turing Way” project, a 7 month project led by the Alan Turing Institute to bring together research software engineers and research data librarians in order to write a handbook to support students, their supervisors, funders and journal editors in ensuring that reproducible data science is “too easy not to do”. The talk will be starting point for a discussion how librarians in your institutions might already support Open Science and what you would want them to provide to make your Open Science Working Group more successful.

* Type (e.g., workshop, talk, discussion group) 
Input talk followed by discussion

* Preferred session duration 
30 minutes (trying to keep talking short, otherwise we might need 1 h just to accommodate a proper discussion) 

**Update**: submitted by @pherterich on 28/02/2019

**Comment by pherterich** [comment]
@KirstieJane little nudge if you're happy for me to submit this or something similar. If you don't manage to feed back before the workshop on Friday, I will rewrite to make it "Turing agnostic"

**Comment by KirstieJane** [comment]
Looks awesome @pherterich!! Submit away!! 🚀 👩‍🎤 🌟
