### ISSUE TITLE
Book Dash Logistics: 16 - 20 May 2022

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#2301]
**We are hosting a Book Dash from 16 to 20 May 2022**

This issue is for the event organisers, **if you are an applicant please use this form to submit your application: https://forms.gle/uEbu1FJMmdfgGwvW6.** This application will likely take 30 minutes to complete. You can use this template document with all the questions to prepare your draft:[ https://tinyurl.com/tw-bookdash-template](https://tinyurl.com/tw-bookdash-template).

We have created the following checklists, which are chronologically structured to help organise Book Dash online or in-person.

## Before the Event

- [x] Finalise dates based on the location and core team’s availability
- [x] Set up a form (see a template [here](https://the-turing-way.netlify.app/community-handbook/bookdash/bookdash-selection.html#ch-bookdash-application-additional-materials)) for application by updating the previous version of the form
- [x] Write a short description for online advertisement
- [x] Open a call for application as well as invite interest to join the committee
- [x] Establish a Book Dash Planning committee by inviting returning members of the event
- [x] Book location for in-person events
- [x] Set up an online platform ([Zoom](https://zoom.us/), or other accessible software) for remote collaboration
- [x] Discuss with co-organisers if some resources (such as email drafts or templates) need to be updated
- [x] Clearly state the following information in an application form and later communicate by email with the selected participants:
  -   what financial support will be available for either online or in-person events 
  -  What arrangements will be available online (such as online helpers and designated mentors) or on-site (such as quiet room and child care) for in-person events 
  -  Include accessibility information such as live captioning for in-person events and quiet room/child nursing room for in-person events 
  - Mention the maximum limit for financial support requests for online (such as for headphones) and in-person (such as for travel and accommodation) events
- [x] Set up the Book Dash Planning meeting to discuss these details before the announcement is sent out
  -  Find volunteers from the organisers who would like to host onboarding calls (1 week before the event)
  -  Find volunteers from the organisers who would like to host a GitHub introduction session (1 week before the event)
  - Find volunteers from the organisers who would like to run social events (discussion session, meal, informal chat) - During the event
  - Find volunteers from the organisers who would like to run community share out sessions - on the last day
  - Check with them if there is anything else they would like to suggest or get involved in
- [x] Announce in the newsletter and promote on Twitter at least 2-3 months in advance
- [x] Think about who else needs to be invited, like Artists, speakers, more diverse participants
- [x] Identify helpers from the core members and invite them
- [x] Send a reminder in next newsletters with more details if needed
- [x] Set an Eventbrite page with a registration code for the selected participants
- [x] Close the application round in time (minimum 1 month ahead of the event)
- [x] Set-up a form for reviewing applications (see [Rubrics for scoring applications](https://the-turing-way.netlify.app/community-handbook/bookdash/bookdash-application.html#ch-bookdash-application-rubrics) for details)
- [x] Review applications in a designated panel (Book Dash Planning Committee) using Book Dash Rubrics for selection
- [x] Set up another meeting with the Book Dash Planning Committee to discuss the applications and finalise the selection
  - Use this meeting to also allocate tasks for during and after the event (indicate that on the GitHub issues)
- [x] Send an email to the selected attendees with registration
- [x] Send an email to the unselected attendees with feedback
- [x] Set up an email chain and a Slack channel to connect all members and share updates
- [x] Update presentation for introducing the project to the participants on day-1 of the Book Dash
- [x] Update shared HackMD for pre-event calls<ch-template-bookdash-precall>, [book dash event](https://the-turing-way.netlify.app/community-handbook/templates/template-bookdash-notes.html#ch-template-bookdash-notes) and [feedback](https://the-turing-way.netlify.app/community-handbook/templates/template-bookdash-feedback.html#ch-template-bookdash-feedback)
- [x] Provide details on Code of Conduct, contribution guideline and ways to get involved in an ongoing discussion
- [x] Host the onboarding call one week before the event to share logistics and facilitate the drafting of SMART goals
- [x] Group participants into the proposed working groups as per their SMART goals from the onboarding call
- [x] Host the onboarding call one week before the event to share logistics and facilitate the drafting of SMART goals
- [x] Send a reminder email to register on Eventbrite sharing important links and information including support grant, GitHub session, onboarding call info and reimbursement process
- [x] Create a GitHub issue to collect bio and highlight of the participants to add them to the Contributors Record

### Additional task for an online event
- [x] State the prerequisites to attend the event
  - An active GitHub account
  - Participation in at least one pre-event onboarding call or a Collaboration Cafe
  - Some experience with using GitHub or attend the Book Dash GitHub session
  - Familiarity with The Turing Way contribution guidelines and Code of Conduct
  -  Willingness to collaborate with others
- [x] Ask them to choose at least one development session (2.5 hours) for each day of the Book Dash to ensure flexibility (rather than blocking the full day)
- [x] Collect address if something needs to be posted

### Additional task for an in-person Event
- [ ] Collate participants’ preference for travel, meal, accommodation, and accessibility request through the registration form
- [ ] Send an email to the participants regarding their travel, accommodation, schedule, and meal
- [ ] Book dinner for people for day-1
- [ ] Book hotels rooms for people who requested accommodation
- [ ] Double-check with each participant if their plan as given on their registration hasn’t changed
- [ ] Book travel for those who requested
- [ ] Double-check with each participant if their plan as given on their registration hasn’t changed
- [ ] Book catering for lunch and coffee breaks
- [ ] Mention that the event will offer a vegetarian meal as default - and ask participants to get in touch if another meal type is required

## During the Event
-  [x] Run onboarding sessions on the first day
  - Welcome everyone (for each slot)
  - Ask to fill the icebreaker
  - One of the organisers delivers introduction talk
  -  Create breakout groups for people working on
-  [x] Host coworking sessions with Pomodoro sessions 30-35 mins long
  -  At the beginning of the session, ask people to document or verbally share their plan for the session
  - End each session with any report people want to make
  - Give 5 minutes break before entering the next Pomodoro
  -  Keep last 10 minutes for final reporting and co-documenting the work that took place during the Pomodoro
- [x] If an artist, illustrator or consultant is invited, coordinate the schedule with participants so they have the chance to engage
- [x] Run a social session each day: These are run by organisers to ensure everyone has the chance to connect informally
- [x] Host community share out the event on the last day to demonstrate and celebrate the contributions made by everyone during the Book Dash
- [x] Ask for feedback on the last day (plus and delta)
- [x] Share the GitHub issue for adding bio and highlight
- [x] Take screenshots or group photos (with permission) to share in reports or social media

## After the Event
- [x] Send a thank you email to everyone for their work
- [x] Move bio and highlight from the GitHub issue to the Contributors Record
- [x] Summarise the event (number of pull requests, issue, chapters, and other significant news) to share with the participants
- [x] Share the update via the newsletter
- [x] Develop a report with highlights and updates on GitHub
- [x] Set up a debrief meeting with the planning committee
- [x] Send a thank you note (or a package when possible) to the planning committee

**Comment by malvikasharan** [comment]
**Event timeline:**

- Call for application start date: 21 March 2022
- Deadline for submission: "21 April 2022" (midnight anywhere on Earth)
- Decisions on the applications: Latest by 29 April 2022
- Pre Book Dash Onboarding calls (2 x 1 hour): 10 May 2022
- Pre Book Dash GitHub Skill-up (1 hour): 11 May 2022 [Placeholder, subjected to change]
- Book Dash Contribution Sessions during the week: 16-19 May 2022
- The Turing Way community share-out: 20 May 2022

**Comment by aleesteele** [comment]
Feedback loops for documentation:
- [ ] #2364 
- [ ] #2387

**Comment by malvikasharan** [comment]
@aleesteele captured summary in a report and included in the newsletter #2438
