### ISSUE TITLE
How do you make your Open Source project sustainable? [working title]

### ISSUE THREAD

**Issue by AidaMehonic** [alan-turing-institute/the-turing-way#2360]
## Summary

Research Application Managers at the Turing are tasked with helping projects expand their real world impact, for example through diversifying the reach of who is able to use their research or shaping research outputs to better address specific stakeholder needs. Our team's work over the past year has uncovered that many researchers are unsure about what different impact pathways exist and the steps for embarking upon one. These pathways can include models such as 1) Open Source project sustained by grant funding, 2) project with Open source and commercial divisions 3) spin-out company/startup. The RAM team proposes to conduct research and interviews to gather information to write a chapter and create a diagram on these different research impact pathways. We aim to draw upon the knowledge of successful models of Open Source sustainability (e.g. OpenStreetMap, Redhat) as well as the institutional knowledge within the Turing Institute with various PIs.
 

### Discussion Points

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### Resources

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

## Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

## Updates

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.

**Comment by AidaMehonic** [comment]
What questions do we want to answer in this chapter?

- [ ] Is open source inherently opposed to commercialisation? What does this even mean?

**Comment by aldenc** [comment]
Jennifer: SciKit-learn, OpenCV, YOLO, Open AI, Hugging Face compare/contrast
Alden: right to replicate, why open source is NOT incompatible with revenue generation, read about redhat
Hari: Openstreetmap and jupyter (vs google colab)
Aida: Raphtory/Pometry

case studies: how to find "seed/runway" funding
    what governance model did you begin with and how did you fund it (public or private, donations, revenue)?
    why did you choose that model?
    what are/were the challenges establishing/maintaining that model?
    did you consider other models?
    what do you wish you had known beforehand?

**Comment by aldenc** [comment]
draft here: https://hackmd.io/@TuringRAMs/rJFvr7Wwc

**Comment by dingaaling** [comment]
- Quasir case study: https://hackmd.io/iUmaRumLQeyHlzHd7-lGKQ?view
- Open source AI org models: https://hackmd.io/XMB3hzOuSV2qxWtiqvNNPA?both

**Comment by AidaMehonic** [comment]
Some examples of OS projects becoming extraordinarily well funded:

- [ ] Spark
- [ ] Kafka

**Comment by dingaaling** [comment]
- Draft on the role of large OSS projects (including Spark/Kafka/Kubernetes) and the OS Foundations that back them: https://hackmd.io/RYx8uSnMSZ-Hi8lvenPrkg?view

**Comment by edwardchalstrey1** [comment]
Came across this issue after discussion today, it would be very cool if there was a sub-chapter called something like:

"Commercialising open source research software" - I guess things like Spark area great example for OS, but would be amazing if there was an example that came out of research (as opposed to industry) - but I don't know whether there is!

**Comment by dingaaling** [comment]
Thanks for the feedback @edwardchalstrey1 ! We got started on this topic on this [branch](https://github.com/alan-turing-institute/the-turing-way/compare/main...ram-oss-sustainability), but things slowed down after the last book dash. Might this be something you'd be interested/available to collaborate on?

**Comment by edwardchalstrey1** [comment]
> Thanks for the feedback @edwardchalstrey1 ! We got started on this topic on this [branch](https://github.com/alan-turing-institute/the-turing-way/compare/main...ram-oss-sustainability), but things slowed down after the last book dash. Might this be something you'd be interested/available to collaborate on?

Potentially, the only issue is that this is something I'd like to know the answer to, as oppose to something I already have the answer to and can easily share :)

**Comment by edwardchalstrey1** [comment]
> We're in a similar position, @edwardchalstrey1! One reason why the chapter has stalled.
> 
> The RAMs (especially @aldenc) might pick up this chapter again at the Nov book dash. It'd be great to get your take on the research plan or draft text for a commercialisation section - if you have the time 😄

Happy to do some reviewing sure :)

**Comment by aldenc** [comment]
hi @edwardchalstrey1, I'd love to chat about this during the book dash (nov 14-18), would be great to hear what you're hoping to learn so that can guide how the chapter turns out
