### ISSUE TITLE
Chapter or section on Open Education

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2362]
### Discussion Points

- [ ] What guide is best suited: Communication chapter or Reproducible research section under Open Research? 
- [ ] What is Open Education?
- [ ] Why Open Education?

## Who can help?

* Anyone with an interest in Open Education or no experience at all so you can check if the chapter makes any sense!

## Updates

- [ ] Write chapter outline: https://hackmd.io/zsi7LVSVS3yuPdXva6jhQA
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.

**Comment by jcolomb** [comment]
For me it sounds like a new guide, OER is quite different from communicating research or reproducible research, unless it is part of educating co-workers on the project details and workflows (collaborative data collection, common tool used, ...) (?).

**Comment by EstherPlomp** [comment]
I agree it is quite a separate thing, but the amount of information that I'll add does not really do justice to calling it a full guide... :D

**Comment by jcolomb** [comment]
just spotted there is already some text at `reproducible-research/open/open-scholarship`

**Comment by EstherPlomp** [comment]
Ah nice! I think I'll then add it as a sub section there and build on the OER info that is already there! Thanks @jcolomb !
