### ISSUE TITLE
Repositories and Archives

### ISSUE THREAD

**Issue by Karvovskaya** [alan-turing-institute/the-turing-way#2368]
### Adding Repositories and Archives chapter right after 

*Originally the ide was to include Open Science Framework into the Turing Way next to 
[Getting Started With GitHub](https://the-turing-way.netlify.app/collaboration/github-novice.html) Some examples. How to create a project. We haveseveral cool case studies - we can summarize them or include links*

### What needs to be done?

- [ ] *Setup the new chapter structure*
- [ ] *Follow the Research Life Cycle activities*
- [ ] *Use existing documentation to make a beginner friendly intro text.*
- [ ] *Add links to resources*
- [ ] *Ask for peer review*

### Who can help?

*  @Elisa-on-GitHub  for working on the text 
*  @eirini-zormpa Worked with OSF and for 4TU data repository
*  @EKaroune  has a great case study where google drive was integrated into OSF for fieldwork
*  @malvikasharan has a table with resources for Research Life Cycle - from NASA
* *Eric Olson from OSF.*

---

### Updates

*From specific OSF chapter we move to a generic chapter on repositories and archives.*

**Comment by Karvovskaya** [comment]
@eirini-zormpa I am about to start working on the text! Are you joining today - maybe we could chat about what informaiton  is needed for TTW?

**Comment by eirini-zormpa** [comment]
hi Lena! Not today, I'm afraid, the first two days this week are quite hectic 🙈 I'll try to join from tomorrow though if that works :blush:

**Comment by Karvovskaya** [comment]
I can be there for the first session tomorrow!

**Comment by Karvovskaya** [comment]
Started drafting the chapter here https://hackmd.io/hIa563koR3Ssdc6B_1Skyw
