### ISSUE TITLE
Write chapter: Credit for Reproducible Research

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#242]
## Detailed description

This issue is to collect ideas and organise the writing on a chapter on "Credit for Reproducible Research". The chapter could cover:

* Software citation (e.g. via workshop organised by @jezcope )
* Data citation
* Developments like DORA and other initiatives around promotion criteria
* Any awards available at the moment to promote this?

### Who can help?

Everyone with ideas what to include, useful links and especially volunteers to write sections :sparkle: 

## Current status

This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

- [ ] Add your ideas to this issue
- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to master branch.

**Comment by r-j-arnold** [comment]
There are bits to do with data/software citation and some other things related to credit. In the open research chapter. If you wanted to transfer them to this chapter (probably with modification to make them fir more neatly) and replace them with links to it in the open research chapter that would prevent us duplicating the same info in different places.

**Comment by jezcope** [comment]
Ok, brainstorming a few possible things about software citation:

- [FAIR data principles](https://www.force11.org/group/fairgroup/fairprinciples)
- [FORCE11 Software Citation principles](https://www.force11.org/software-citation-principles)
- Practical steps (checklists?) for:
  - People who write papers (and should therefore cite software)
  - People who write software and want it to be cited easily
  - People who build infrastructure
  - People who teach information management skills

**Comment by pherterich** [comment]
Neil's slides from the workshop with some of the checklists https://doi.org/10.6084/m9.figshare.8124284.v1

**Comment by jezcope** [comment]
Zenodo is down at the moment :sob: but all the workshop slides will eventually be [available there](https://zenodo.org/communities/citesoftware2019/).

**Comment by jezcope** [comment]
Something to add in the future would be non-citation metrics of impact:

- Downloads, forks, issues, PRs, `#include/require/import` stats for software
- Downloads, relationships for data
- altmetrics for articles
