### ISSUE TITLE
RightsCon 2022: Contextualising The Turing Way for the Global Community

### ISSUE THREAD

**Issue by BatoolMM** [alan-turing-institute/the-turing-way#2428]
:dizzy: _We're excited that you're here and want to contribute._ :dizzy:

#### Summary:
- At **RightsCon 2022**, _The Turing way_ will present a Community Lab Session under the title "Contextualising The Turing Way for the Global Community" on the 9 April 2022.
- **_The Turing Way_** is an open-source community-driven guide to reproducible, ethical, inclusive and collaborative data science.
- The Turing Way's goal is to provide all the information that researchers, industry professionals and members of the public need to understand reproducibility and ethical standards in data science at all stages of development.
- In this Community Lab session, we invite suggestions and contributions on how we can contextualise The Turing Way resources to enhance understanding and skills in data science of researchers in their local contexts.
- Despite a diverse representation of our contributors from both the global North and South, we are aware that many of our resources, examples and case studies present western-centric research views and references. Therefore, we specifically invite feedback from researchers from Asia, Africa and Latin America. Reflecting on best practices in data science from their communities, in order to integrate their local views, examples, case studies and new chapters in The Turing Way.
- **Contributions can include**:
    - Simple suggestions by commenting under this issue
    - Links and/or summary to different resources that could be useful for new contributors
    - Summary of a blog post that you have previously written (create a Pull Request)
    - Case studies from your projects
    - Impact stories inspired by your own experience (create a new issue, or Pull Request)
    - Join the next book dash and collaborate with the community to develop your idea: [Application Form](https://forms.gle/nDd5KzQaXQrkZ6Hn8)

#### Contribution Guidelines
- [ ] Read the [contribution guideline](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md) of _The Turing Way_
- [ ] Comment under this issue. You can use this template to make your comment as useful as possible: 
```
- Name: <YourName>
- Suggestions: 
    - How can we maintain an international platform to create resources or best practices that are globally applicable?
    - What are the challenges you have experienced in your own community while trying to adopt best practices developed elsewhere?
    - How can we create opportunities to champion, capture and highlight local knowledge, practices and views?
    - What are the different forms of knowledge production and outcomes as well as best practices you have benefitted from but don’t see represented in the international community?
- Link: <link to any resource that you think would be useful>
```

#### Who can help with this issue?

- Anyone interested, and folks joining the RightsCon 2022. We especially encourage new contributors who haven't contributed to our codebase before.
- Everyone who contributes to this discussion, will be added to the [Contributors' Table](https://the-turing-way.netlify.app/afterword/contributors-record.html)

**Comment by aleesteele** [comment]
Hi @BatoolMM! Is this okay to close now that RightsCon has passed?

**Comment by BatoolMM** [comment]
Sure!
I'll closed it now.
