### ISSUE TITLE
CarpentryCon session: Chapter on how to contribute to an Open Source project

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2430]
## Summary

As part of the Carpentry Con 22 conference The Turing Way is organising a workshop on how to contribute to Open Source projects. If there is time we will start a discussion to work on a chapter on what steps to take and things to consider when you want to contribute to a project. 

[Workshop submission](https://docs.google.com/document/d/1TEZCVXs0nxBeWAybjcAUCQN3o8DAmRLhQMiH1wXh9c0/edit)

### Discussion Points

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### Resources

- [ ] https://www.firsttimersonly.com/ 
- [ ] https://up-for-grabs.net/ 
- [ ] https://firstcontributions.github.io/
- [ ] https://opensourcediversity.org/
- [ ] On codes of conduct: https://www.contributor-covenant.org/

## Who can help?

* @aleesteele @BrainonSilicon @harisood 
* Anyone interested in decreasing barriers to participation in open source communities
* Participants of the CarpentryCon workshop

## Updates

- [ ] Write chapter outline
- [ ] Add material to the chapter
- [ ] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.

**Comment by aleesteele** [comment]
(testing) @all-contributors please add @BrainonSilicon @EstherPlomp @harisood for event organizing

**Comment by aleesteele** [comment]
@all-contributors please add @harisood for event organising

**Comment by aleesteele** [comment]
(also, hi everyone. sorry for the spam. i'm testing out some things with the all contributors bot!)

**Comment by aleesteele** [comment]
Going to archive this, now that CarpentryCon has passed!
