### ISSUE TITLE
Remove references to BIDS Starter Kit from contributing guidelines where appropriate

### ISSUE THREAD

**Issue by sdruskat** [alan-turing-institute/the-turing-way#244]
### Summary

*The contributing guidelines seem to contain a lot of copy and paste from the BIDS Starter Kit. This is confusing. I think it should probably be removed, exchanged with a reference to the TW project, and possibly the material taken from the BIDS Starter Kit attributed in a line at the bottom mentioning the reuse?*

### What needs to be done?

- [x] *Replace `BIDS Starter Kit` string with `The Turing Way` where appropriate.*
- [x] *Acknowledge the source of the text somewhere, depending on license, etc.*

### Who can help?

* *People who are comfortable with editing Markdown.*
* *Project maintainers who decide the appropriate way of handling this.*

---

### Updates

*...*

**Comment by r-j-arnold** [comment]
From the commit history it looks like the BIDS stuff was added by @pherterich. @pherterich, do you happen to remember where it came from and what license it had so we can give credit?

**Comment by pherterich** [comment]
I though I caught them all :disappointed: Thanks for spotting @sdruskat !
@KirstieJane wanted to do a full edit of the contributing guidelines soon as laid out in #16 so I add those points to the to do list there.

**Comment by rainsworth** [comment]
Changed any remaining BIDS Starter Kit strings with The Turing Way and added attribution to the bottom of the contributing guidelines.
