### ISSUE TITLE
Write the Docs Conference

### ISSUE THREAD

**Issue by BatoolMM** [alan-turing-institute/the-turing-way#2448]
### Summary

**Write the Docs** conference covers any topic related to documentation in the software industry!

> Write the Docs Conferences aim to create a time and a place for the global community of documentarians to share information, discuss ideas, and work together to improve the art and science of documentation.

## Who can help?

* The Translation and localisation co-leads
* @AsmaKacem1 @anilbey, @melibleq and anyone who contributed to the documentation of the translation so far!
* Any member from the translation team!
* Anyone interested in the documentation of the Translation!

## Questions?
* How to facilitate creating language bridges in open source projects that connect to diverse audiences?
* How to ensure consistency in Translation and localization crowdsourcing open source projects?

**Comment by anilbey** [comment]
Great idea, count me in!

**Comment by aleesteele** [comment]
@AsmaKacem1 @anilbey, @melibleq @BatoolMM - 

Hey amazing folks! ❤️  I was wondering if you all were interested in testing out the new 'give a TTW talk' issue template for this upcoming talk at Writethe Docs? It'd be great to get some feedback about what was/was not useful in the format through your talk, asking questions like:
- What is, and is not clear while you use the issue template
- Is there anything you would like to see included?

Tagging @aldenc and @sgibson91 (who created the issue) for their awareness. 😊

**Comment by anilbey** [comment]
Hi @aleesteele sure that would be great!

**Comment by melibleq** [comment]
Yes, @aleesteele! Please bring it and we'll test it! :)

**Comment by aleesteele** [comment]
Woohoo, thank you both so much! You should be able to see it by creating a new issue, and then the format should automatically come up! ❤️ 

![Screenshot 2022-09-05 at 12 25 16](https://user-images.githubusercontent.com/18509789/188438075-aa4cb4a7-8d87-45c8-a5cc-4e1a08cd6272.png)

**Comment by melibleq** [comment]
Hey everyone! I created the issue [here](https://github.com/alan-turing-institute/the-turing-way/issues/2665). It's a great way to make sure all links and acknowledgements are well prepared before the talk, and reminds the speaker of how to share the event details with TTW community. Should we talk about this at the collaboration cafe or in a translation team meeting?
