### ISSUE TITLE
Write chapter?: Continuous analysis

### ISSUE THREAD

**Issue by sdruskat** [alan-turing-institute/the-turing-way#245]
### Summary

*As discussed earlier on Twitter w/ @KirstieJane ([here ff.](https://twitter.com/kirstie_j/status/1098919079673499648)), I'd like to look into contributing a [continuous analysis](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6103790/)-like example from linguistics to TTW.*

### What needs to be done?

- [ ] *Decide if this should into a dedicated chapter "Continuous analysis", or if this should go into https://github.com/alan-turing-institute/the-turing-way/pull/146.*
- [ ] *If "continuous analysis" should get its own chapter, please create a branch `continuous_analysis` in this repo to pull request against.*

### Who can help?

* *Anyone interested in continuous analysis.*
* *Anyone who can provide examples from different fields.*

---

### Updates

*...*

**Comment by r-j-arnold** [comment]
From the commit history it looks like the BIDS stuff was added by @pherterich. @pherterich, do you happen to remember where it came from and what license it had so we can give credit?

**Comment by r-j-arnold** [comment]
Hi @sdruskat, this sounds great, personally I'd lean towards giving it its own chapter, and just including the continuous integration chapter and the reproducible computational environments chapter as prerequisites at the top.

I think it would work best as it's own chapter firstly because it's different enough to CI to merit it in my view, and secondly because making two shorter chapters rather than one long one makes things more bite-sized for readers. 

What are your thoughts on this?

**Comment by sdruskat** [comment]
Hi @r-j-arnold, a separate chapter makes sense I think, for the reasons you mention.

I've forked and created a branch `continuous_analysis` in my fork already, and set up the template. I'd like to start work on the chapter on a loooong plane flight tomorrow, so if you set up a branch `continuous_analysis` in this repo as well, I'd write a PR against it to start the process before I leave :). Will do a lot of work offline, but will update the PR with details on what is going into the chapter from my side once I'm back online :).

Does that sound okay to you?

**Comment by r-j-arnold** [comment]
Hi @sdruskat, sounds good, branch made, have a good flight and thanks for contributing!

**Comment by KirstieJane** [comment]
I love this whole thread and agree with everything that’s been said.

Have a great flight @sdruskat and thank you!! 👨‍💻🛫🚀🛸

**Comment by dingaaling** [comment]
Hello from 2022 @sdruskat ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by the end of October we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by sdruskat** [comment]
Thanks @dingaaling, please close this for now, I have no resources to work on this at the moment. I'll leave it in my backlog for future opprtunity though.

**Comment by dingaaling** [comment]
Thanks @sdruskat - appreciate the response and your contributions! Hope to collaborate in the future.
