### ISSUE TITLE
Finding the Slack channel

### ISSUE THREAD

**Issue by ToxSina** [alan-turing-institute/the-turing-way#2473]
### Summary

I was introduced to the Turing Way yesterday and am very interested in learning more and participating in the future. In the talk it was mentioned that there is a Slack workspace, however it took me quite long today to find it (I did eventually, through Google) as it isn't mentioned on the Github (as far as I found), at least not in many of the spaces where Twitter or Gitter are mentioned. I have now found the page on [Contributing](https://github.com/alan-turing-institute/the-turing-way/blob/main/CONTRIBUTING.md) where it is mentioned, but this space is also quite hidden when you start out. 
I think it would be helpful to have a more prominent site that helps you to get in contact with the community behind this project.

### What needs to be done - suggestions/ideas?

- [ ] *Add a "how to get started" page*
- [ ] *Add the Slack workspace to all occurrences of the Twitter/Gitter being linked*

### Who can help?

* *Maybe other newcomers have more ideas?*
* *Seasoned contributors needed, as I don't know all pages where things would have to be adapted yet.*

---

### Updates

I found the issue templates and tried to adapt this vaguely following the general template. I hope this is understandable and up to community standards now.

**Comment by malvikasharan** [comment]
Thank you so much @ToxSina for creating this issue and raising the important point.
We are currently working to revamp the entire welcome page to make these details easy to find (see a prototype: https://deploy-preview-2080--the-turing-way.netlify.app/welcome.html#the-turing-way-team-and-community). This is something our community manager, Anne Steele is working on.

Meanwhile, I will create a PR to add prominently on the README page as well as welcome page. Is it ok if I tag you for review?

**Comment by ToxSina** [comment]
Sure, I am happy to help if there is anything I can do.

**Comment by aleesteele** [comment]
Hi both -
