### ISSUE TITLE
Adding a chapter on cultural change to 'Ethical Research'

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2475]
## Summary

We do not yet have information on how to achieve cultural change in a community/organisation. I recently followed a course on this and want to collate some resources on this so I was thinking of adding a chapter to the Ethical Research Guide where it seems to fit best. 

### Discussion Points

- [x] Is the Ethical Research Guide indeed the best place? If not, open to suggestions!
- [ ] ?

## Who can help?

* Anyone with experience achieving cultural change 
* Beginners with this subject to ensure accessibility/clarity of the chapter

## Updates

- [x] Write chapter outline (WIP: https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/ryjfaOK3q)
- [x] Add material to the chapter
- [x] Combine materials into a readable chapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch.

**Comment by Arielle-Bennett** [comment]
Hi @EstherPlomp - very good idea to consolidate notes from the course! I think that the Ethics Guide - Internal Policy Advocacy section or similar would be a good fit for this chapter. Happy to review ✨
