### ISSUE TITLE
Add video resource to FAIR principles chapter

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2487]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during CarpentryCon 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aleesteele, @harisood, or @BrainonSilicon know on Zoom so that we can assist you.

## Summary
Addition of a video resource in the [FAIR principle chapter](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-fair.html).

## Guide to Contribution 

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/reproducible-research/rdm/rdm-fair.md

2. Search for statement: 
> "The FAIR principles are also applied to software"

3. Click 'Edit this file' to correct the wording.

Suggested Correction:
> "The FAIR principles are also applied to software (see [[LGK+20](https://the-turing-way.netlify.app/afterword/bibliography.html#id10)]and [[HCH+20](https://the-turing-way.netlify.app/afterword/bibliography.html#id9)]). Watch a [ten minute video on FAIR software](https://www.youtube.com/watch?v=ME8_NRGRhSs&list=PL1CvC6Ez54KDvJbbdLn5rPvf1kInifEh9&index=16) for a short explanation."

4. Use Markdown format to correct the wording on the page:
`The FAIR principles are also applied to software (see [[LGK+20](https://the-turing-way.netlify.app/afterword/bibliography.html#id10)]and [[HCH+20](https://the-turing-way.netlify.app/afterword/bibliography.html#id9)]). Watch a [ten minute video on FAIR software](https://www.youtube.com/watch?v=ME8_NRGRhSs&list=PL1CvC6Ez54KDvJbbdLn5rPvf1kInifEh9&index=16) for a short explanation.`

5. Click 'Preview' to check that the changes look the way you'd like them too!

6. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

7. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

8. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then add the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2487).

9. Click 'Create Pull Request'! Congratulations! 🎉 

10. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

11. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

12. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by BrainonSilicon** [comment]
@Varachkina is working on this issue in PR #2520

**Comment by aleesteele** [comment]
Solved by @Varachkina at CarpentryCon!
