### ISSUE TITLE
Fix links to 'barriers to data sharing' section

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2489]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Collaborations Workshop in October 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @EKaroune know on Zoom so that we can assist you.

## Summary
In the [Personal data management chapter](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-personal.html), there is a broken link to the 'barriers to data sharing' chapter.

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their GitHub usernames.

2. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/communication/citable/citable-cite.md

3. Search for statement: 
> "For example, you should consider whether the data can be adequately anonymised, and whether anonymised data will remain useful (see also [Barriers to data sharing](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-sharing.html#rr-rdm-sharing)Open Research Chapter)."

`For example, you should consider whether the data can be adequately anonymised, and whether anonymised data will remain useful (see also [Barriers to data sharing](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-sharing.html#rr-rdm-sharing)Open Research Chapter).`

4. Click 'Edit this file' to correct the wording.

Suggested Correction:
> "For example, you should consider whether the data can be adequately anonymised, and whether anonymised data will remain useful (see also [Barriers to data sharing](https://the-turing-way.netlify.app/reproducible-research/open/open-data.html?highlight=barriers#barriers-to-data-sharing) within the Open Research Chapter)."

5. Use Markdown format to correct the wording on the page:
`For example, you should consider whether the data can be adequately anonymised, and whether anonymised data will remain useful (see also [Barriers to data sharing](https://the-turing-way.netlify.app/reproducible-research/open/open-data.html?highlight=barriers#barriers-to-data-sharing) within the Open Research Chapter).`

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then add the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2489).

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by BrainonSilicon** [comment]
> Hey @aleesteele - this linking method isn't [the one stipulated in the style guide](https://the-turing-way.netlify.app/community-handbook/style/style-crossref.html).
> 
> I've [requested that the PR be modified](https://github.com/alan-turing-institute/the-turing-way/pull/2711#pullrequestreview-1137750691), but I thought I should flag here in case you wanted to update these instructions.

Hiya team! I caught this as well and so didn't want to review the PR yet just in case. @aleesteele, this was a suggestion @harisood made originally as an issue for CarpentriesCon - do you have a preference based on the style guide?

also tagging @harisood for some background as to why the change was suggested 

@da5nsy we used the issue in a workshop today so the folks may not be able to edit the PR again so we may need to keep an eye on it.
