### ISSUE TITLE
Remove repeated 'schedule' heading in the Weekly Coworking template

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/the-turing-way#2503]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Collaborations Workshop in October 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @EKaroune know on Zoom so that we can assist you.

## Summary
In the [Weekly Coworking Call Template](https://the-turing-way.netlify.app/community-handbook/templates/template-coworking-weekly.html) subchapter, under the 'Code of conduct heading there are two subheadings of 'Schedule:' when there should only be one.

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their GitHub usernames.

2. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/community-handbook/templates/template-coworking-weekly.md

3. Search for statement: 
> "Code of conduct"

4. Click 'Edit this file'.

5. Remove the second appearance of Schedule (you can remove the entire line and blank line above it, i.e. lines 29-30).

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project.

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a `#` in the description. You can find the issue number next to the title of this issue (this one of #2503).

Example: `this pull request fixes #2503`

10. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

11. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

12. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by BrianAndrewOneil** [comment]
@harisood @aleesteele, I'm happy to help with this issue.
