### ISSUE TITLE
Broken emojis on Collaboration Cafe Call Template

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/the-turing-way#2504]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Collaborations Workshop in October 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @EKaroune know on Zoom so that we can assist you.

## Summary
In the [Collaboration Cafe Call Template](https://the-turing-way.netlify.app/community-handbook/templates/template-coworking-collabcafe.html) near the top the emojis for coffee, sparkles and cake aren't displaying properly.

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their GitHub usernames.

2. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/community-handbook/templates/template-coworking-collabcafe.md

3. Search for statement: 
> "We're delighted to have you here"

4. Click 'Edit this file' to correct the wording.

Suggested Correction:
This is a bit of a weird one, as it displays on the GitHub preview but not on the actual book. It seems that the other emojis are hard-baked in, rather than written with the Markdown Syntax of colons. 

You can add actual emojis using the following shortcuts:
Mac: CTRL + CMD + space
Windows: Windows + ;

The suggested correction is:
> ☕️✨🎂

5. Use Markdown format to correct the wording on the page:
`☕️✨🎂`

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2504).

Example: `this pull request fixes #2504`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by SianC** [comment]
@SianC
