### ISSUE TITLE
Remove discussion comment included in Chapter content.

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/the-turing-way#2506]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during CarpentryCon 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aleesteele, @harisood, or @BrainonSilicon know on Zoom so that we can assist you.

## Summary
In [Ethical Decisions in Preclinical Research](https://the-turing-way.netlify.app/ethical-research/preclinical-research.html), under the heading 'How this will help you/ why this is useful' a comment left from a contributor has been included and written into the book itself. This comment needs to be removed from the file and captured in another format. 

## Guide to Contribution 

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/ethical-research/preclinical-research.md
2. Search for statement: 
> The above sentence may not fit with the structure of the book or flow within these chapters - Nadia

3. Click 'Edit this file' to remove the comment. 

4. Click 'Preview' to check that the changes look the way you'd like them too!

5. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

6. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

7. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then add the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2505).

8. Click 'Create Pull Request'! Congratulations! 🎉 

9. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

10. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

11. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅ 

## Additional Steps
As this comment was left by a past contributor outside of GitHub. It would be good practice to open an Issue where the comment was captured in order for those who have worked on the section to help work out who the unlisted contributor is.

**Comment by aleesteele** [comment]
Solved by @dpdong19 and @TueloNtlotlang at CarpentryCon 2022!
