### ISSUE TITLE
Unattributed comment in Ethics Chapter

### ISSUE THREAD

**Issue by BrainonSilicon** [alan-turing-institute/the-turing-way#2507]
### Summary

There is a comment from `Nadia` in `The Guide for Ethical Research` in the section on `Ethical Decisions in PreClinical Research` under the heading `How this will help you/ why this is useful` (located [here](https://github.com/alan-turing-institute/the-turing-way/blob/635a7d829821dc5c832bfb85f7f1e0fa3407f435/book/website/ethical-research/preclinical-research.md)) that is rendered and included in the published book rather than being captured as a comment on a WIP version of the section. 

The comment reads:
> The above sentence may not fit with the structure of the book or flow within these chapters - Nadia

Additionally, I have been unable to find a log of a Nadia being one of the contributors for that specific page. 

### What needs to be done?

Removing the comment from the book is captured in Issue #2506 and this Issue (#2507) was opened to capture the comment and in an attempt to figure out and give attribution to the contributor. 

### Who can help?

* @malvikasharan, @EKaroune, and @KirstieJane are the logged contributors on the file who may have more insight into who wrote the comment. 

---

**Comment by malvikasharan** [comment]
It was @nadiasoliman who is a medical professional. She was reviewing this chapter in one of the Book Dash. Best would be to create a PR to amend the error.

**Comment by BrainonSilicon** [comment]
solved by issue #2506
