### ISSUE TITLE
Updating Turing Way Issue Templates + Chapter in TTW

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2541]
### Summary

Adding a subchapter to the Community Handbook about giving a talk about _The Turing Way_: including resources needed to prepare for the talk, a checklist about steps needed to document the talk within _The Turing Way_ repository, and information about sharing the talk openly.

### What needs to be done?
- [x] Document process of giving a talk about *The Turing Way*
    - [x] Make an issue
    - [ ] Updating Github repository (conferences folder)
    - [x] Publishing on zenodo
    - [x] Add link to mailing list issue on Github
- [x] Write Sub-chapter in Community Handbook about giving a TTW talk: https://the-turing-way.netlify.app/community-handbook/community-handbook.html
    - [x] Link to promotion pack
        - [x] May need access to google drive
    - [x] Checklist for giving a talk
    - [ ] Adding to github chart of conference presentations

### Who can help?
@aldenc 

resolves #2591

**Comment by aleesteele** [comment]
Connected to #114 and this issue by @sgibson91!

**Comment by aleesteele** [comment]
Also connected to #1223 by @HeidiSeibold !

**Comment by aldenc** [comment]
remaining to do:

issue + sub-chapter:
- [ ] merge issue template
- [ ] create sub-chapter linking to issue template 
- [ ] link new sub-chapter from "Representing The Turing Way in your community/conference" in "After the Book Dash"

file management
- [ ] clean up conference and workshops folders on github
> - [ ] move files saved on github to google drive
- [ ] update list of past presentations

**Comment by aldenc** [comment]
closes #2591

**Comment by aldenc** [comment]
#2591

**Comment by aleesteele** [comment]
Connected to issue templates project board: https://github.com/orgs/alan-turing-institute/projects/31

**Comment by aleesteele** [comment]
Linked to: #2745
