### ISSUE TITLE
Adding a resource to the DMP section

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2547]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during CarpentryCon 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aleesteele, @harisood, @BrainonSilicon or @EstherPlomp know on Zoom so that we can assist you.

## Summary
In the [Data Management Plan](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-dmp.html) subchapter in the [Research Data Management chapter](https://the-turing-way.netlify.app/reproducible-research/rdm.html), add a resource at the end to the list of resources.

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their GitHub usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/edit/main/book/website/reproducible-research/rdm/rdm-dmp.md

3. Scroll all the way down to line 75 to add the resource

4. Click 'Edit this file' to correct the wording.
> Add a video on 'elements of a DMP': https://commons.esipfed.org/node/1442

5. Use Markdown format to add the resource and correct the wording on the page:
`- Video on [elements of a DMP](https://commons.esipfed.org/node/1442).`

Additionally, you could modify the text of "Further Reading Recommendations" on line 65 to "Additional Resources" (since we're now adding a video instead of an article/text. 

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one is #2547). 

Example: `this pull request fixes #2547`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by radersma** [comment]
@jsteyn
@martinjeanphd
@radersma

**Comment by aleesteele** [comment]
@all-contributors please add @jsteyn for bugs

**Comment by aleesteele** [comment]
https://github.com/all-contributors please add @jsteyn for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @jsteyn for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @martinjeanphd for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @klbarnes20 for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @radersma for bugs
