### ISSUE TITLE
Adding a resource to the Research Data Management chapter

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2548]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during CarpentryCon 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aleesteele, @harisood, @BrainonSilicon or @EstherPlomp know on Zoom so that we can assist you.

## Summary
In the [Documentation and Metadata](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-metadata.html) subchapter in the [Research Data Management chapter](https://the-turing-way.netlify.app/reproducible-research/rdm.html), add a resource. 

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their GitHub usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/edit/main/book/website/reproducible-research/rdm/rdm-metadata.md

3. Scroll all the way down to line 55 to add the resource

4. Click 'Edit this file' to add the resource:
Introduction to Metadata and Metadata Standards - https://commons.esipfed.org/node/1422

5. Use Markdown format to correct the wording on the page:
`Want to learn more about Metadata and Metadata Standards? Watch an [introduction video](https://commons.esipfed.org/node/1422).`

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one is #2548). 

Example: `this pull request fixes #2548`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by acrall** [comment]
@ubdbra001 @merlijn-de-smit and @acrall worked on this issue as part of CarpentryCon 2022 session 2; fixed by #2562

**Comment by aleesteele** [comment]
@all-contributors please add @acrall for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @ubdbra001 for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @merlijn-de-smit for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @merlijn-de-smit for bugs
