### ISSUE TITLE
Adding a video to Making Research Objects Citable

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2554]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Collaborations Workshop in October 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @EKaroune know on Zoom so that we can assist you.

## Summary
In the [Steps for Making Research Objects Citable](https://the-turing-way.netlify.app/communication/citable/citable-steps.html) subchapter in the [Guide for Communication](https://the-turing-way.netlify.app/communication/communication.html), add a video about persistent identifiers.

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/edit/main/book/website/communication/citable/citable-steps.md

3. Find line 30 to add the video ("Online publications are attached to persistent identifiers that are used for citing them.")

4. Click 'Edit this file' to add the resource.
> Add a video on persistent identifiers (https://www.youtube.com/watch?v=iea6d5oI8Ag) 

5. Use Markdown format to correct the wording on the page:
`Online publications are attached to [persistent identifiers](https://www.youtube.com/watch?v=iea6d5oI8Ag) that are used for citing them.`

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2554). 

Example: `this pull request fixes #2554`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by russellmartin321** [comment]
@russellmartin321 and @TngChangK are working on this
