### ISSUE TITLE
Typo in 'Research Ethics Committees Workflows' Guide

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/the-turing-way#2556]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during CarpentryCon 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aleesteele, @harisood, @BrainonSilicon or @EstherPlomp know on Zoom so that we can assist you.

## Summary
In the [Research Ethics Committees Workflows](https://the-turing-way.netlify.app/ethical-research/ethics-committees.html) subchapter, under 'Privacy and Security' there is a typo on a referenced link - the 'draft chapter' is actually now a live chapter in the book [here](https://the-turing-way.netlify.app/ethical-research/law-policy.html)

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/ethical-research/ethics-committees.md

3. Search for the title 'Privacy and security'. Just underneath you can see a link labelled 'draft chapte', this is what needs changing.

4. Click 'Edit this file' to amend the wording.
> [chapter](https://the-turing-way.netlify.app/ethical-research/law-policy.html)

5. Use Markdown format to correct the wording on the page:
`[chapter](https://the-turing-way.netlify.app/ethical-research/law-policy.html)`

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2556). 

Example: `this pull request fixes #2556`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by pascalflohr** [comment]
@pascalflohr is working on this issue

**Comment by aleesteele** [comment]
Thanks so much, @pascalflohr! 

@all-contributors please add @pascalflohr for bugs
