### ISSUE TITLE
Submit a Binder workshop proposal for CarpentryConnnect Manchester

### ISSUE THREAD

**Issue by anenadic** [alan-turing-institute/the-turing-way#257]
### Summary

Following my conversation with Kirstie W.  at "Boost your research reproducibility with Binder" workshop in Manchestearc 1st March, we thought it would be a good idea to repeat this workshop at CarpentryConnnect Manchester 25-27 June 2019 as a half-day workshop (deadline for submissions is 8th March 2019).

CarpentryConnect Manchester: https://software.ac.uk/ccmcr19
Call for proposals: https://docs.google.com/forms/d/e/1FAIpQLSdPtEFSWYyX09w1G1T5ZvhZJRQyBzXD4zvJbi_GDtnqhgsTKw/viewform
Deadline: 8th March 2019

### What needs to be done?

- [ ] *See who is available to deliver this and if Kirstie is free.*
- [ ] *Submit a proposal.*

### Who can help?

* Someone from the Manchester team, maybe Rachel Ainsworth or Rosie Higman.

**Comment by pherterich** [comment]
@KirstieJane do you need any help with this? The conference is in parallel to LIBER, so I can't help delivering, but shout if you need a hand in getting the proposal ready in time.

**Comment by KirstieJane** [comment]
@phertetich - yes please!! 🙏🙏

Basically a half day version of the build a binder (not hub) workshop....

**Comment by pherterich** [comment]
@KirstieJane do you want to close this issue or use it with @rainsworth to organise the workshop?
