### ISSUE TITLE
Suggested change of phrasing in "Unionisation" sub-chapter of "Guide for Ethical Research"

### ISSUE THREAD

**Issue by merlijn-de-smit** [alan-turing-institute/the-turing-way#2579]
### Summary

Currently, the "Unionisation" sub-chapter mentions (first section, "What is a union?") that "Under the General Data Protection Regulation (GDPR), the European Union considers union membership to be sensitive data and in the same category as genetic data or data on gender." 

I think this is incorrect: gender is not mentioned as a special category of personal data in GDPR (unlike political opinion, ethnic origin, and so on).

Of course, it's just mentioned as an example here. But GDPR tends to frighten researchers (sometimes unnecessarily so) and I think it's important to be careful.

### What needs to be done?

- [ ] Replace "gender" with something else, for example "ethnicity".

### Who can help?

* I can have a go at this. It'll take a while because I've never properly used Github, but it may be good exercise!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by BrainonSilicon** [comment]
Hi @merlijn-de-smit! Would love to support you tackling this. 

There's a few options if you want any support on the GitHub side of things, but genuinely please dive in if you want to get started. 

In terms of options
- there's a Collaboration Cafe session happening today which is a big group call and some coworking breakout rooms. If you're avaliable any time between 3pm - 5pm BST, feel free to come along and tackle the changes. Collab Cafe info is [here](https://hackmd.io/@turingway/collaboration-cafe).
- or comment on this issue if you get stuck or want help and we'll message back!

**Comment by aleesteele** [comment]
Hi @merlijn-de-smit! We're so glad to have you here after CarpentryCon - this is a really good catch regarding GDPR. Tagging @Arielle-Bennett and @LauraCarter for their awareness as well, as they have co-authored chapters in the Guide for Ethical research and may be able to give greater context. Or maybe you all could even collaborate. 😉 

Echoing @BrainonSilicon - we'd love to see you at Collaboration Cafe this afternoon, or learn more about what you might like to contribute to within this guide as well in whatever way works for you!

I'm going to check out the Pull Request now, nice work! 💯

**Comment by Arielle-Bennett** [comment]
Hiya - no additional context from me, I think it's a good catch and support a text change from "gender" to "ethnicity" or another category of sensitive data (biometric, genetic, etc). As @BrainonSilicon said, you can dive in with a PR to change this or we can walk through it at the CC today.

If you've got other suggestions for the content of this chapter (particularly suggestions for unions!) happy to chat that through in more detail ✨

**Comment by aleesteele** [comment]
I think this is all set to close, thanks again @merlijn-de-smit and @Arielle-Bennett !
