### ISSUE TITLE
[TALK] [Test] Toward the broader globalization of Open Source: documenting your localisation journey

### ISSUE THREAD

**Issue by melibleq** [alan-turing-institute/the-turing-way#2665]
### Date of talk

2022-09-13

### Details of the talk

We are presenting at [Write the Docs Prague 2022](https://www.writethedocs.org/conf/prague/2022/). This is the abstract:

The Turing Way is an open-source community-led guide to reproducible, ethical and inclusive data science. Its goal is to provide all the information that researchers, industry professionals and members of the public need to understand reproducibility and ethical standards in data science at all stages of development. The Turing Way contains chapters with best practices, guidance and recommendations that are crowdsourced, collaboratively documented and used internationally by researchers from across the globe.

The Turing Way community currently hosts over 200 sub-chapters across five guides and over 300 direct contributors on GitHub, where we develop our resources that are used by thousands of geographically and culturally diverse users. However, the guide is written in English. This language barrier motivated us to create community-led, multilingual versions of The Turing Way, with the same collaborative spirit that permeates the main guide. The community then started working collaboratively on translations of the Turing Way material to several languages, including Spanish, Arabic and Turkish, while trying out different platforms (such as Transifex and Crowdin).

Eventually, we established a workflow in Crowdin for the translation, which is a key step for internationalisation (i18n) of The Turing Way. Localisation (l10n) and internationalisation (i18n) are important aspects in the design of any open-source project or document. Internationalisation allows open-source projects to support and satisfy the needs of multiple locales, thus “enabling” localisation, which is the adaptation of it to meet the language and the culture of a specific target locale.

However, translation workflows can often become confusing and inconsistent, and many translation efforts go unfinished for several different reasons. Our aim is to provide clear guidelines so any potential contributor is able to participate freely while keeping consistency in the translation. We project clear documentation to facilitate the creation of language bridges that connect to diverse audiences. Therefore, we have documented the translation workflows inside the Community Handbook, which is a part of the Turing Way book. It provides information about all our practices within the project, ways of working, and other aspects that can make community participation equitable for all members. We also include language-specific documentation in GitHub written by the target language contributors. By structuring and combining the relevant glossaries available in such languages, we enable community members to consistently translate using standardised terminology. Sharing and documenting our translation journey has proven to be important in reaching out to new members and making their contributions smoother and more accessible.

### Checklist

- [X] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [X] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [X] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [X] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [X] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [X] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [X] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [ ] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by aleesteele** [comment]
This auto-closing is brilliant, thank you @aldenc and @sgibson91 :D
