### ISSUE TITLE
Broken internal links on `communication/peer-review/peer-review-overview`

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#2673]
### Description

- [ ] `{ref}preprint<rr-open-access-whatis-publishing>` does not resolve
- [ ] `[collaboration](We need to add links to collaboration here)` requires further work.

---
Part of #2611

**Comment by Karvovskaya** [comment]
@vhellon  I guess that's the reason I forgot to make a proper link here - there is no definition in the glossary, and if you look at the colalboration guide there is not so much about collaboration in general. Do you think it's appropriate to link the intr of the Collaboration guide https://the-turing-way.netlify.app/collaboration/collaboration.html# ?

**Comment by vhellon** [comment]
I think that works! Will fix both links this morning :)
