### ISSUE TITLE
[WORKSHOP] Big Team Science Hackathon Prep - 27 October 2022

### ISSUE THREAD

**Issue by Arielle-Bennett** [alan-turing-institute/the-turing-way#2684]
### Summary

This is the issue for collecting Big Team Science preparations! @dingaaling @aleesteele @Arielle-Bennett are presenting in October 2022 (27 October 11am EDT)

### Useful Links
Link to abstract here: [https://docs.google.com/document/d/1qlnFdy5sKMM48NxPFbzktGUyBtp4n6jRBym_cOeuAfk/edit](https://docs.google.com/document/d/1qlnFdy5sKMM48NxPFbzktGUyBtp4n6jRBym_cOeuAfk/edit)

Planning timetable here: [https://docs.google.com/document/d/1wJ1lmKefJn660KG0UhVpIFouRKneCvH_gCLWUvb2ddk/edit](https://docs.google.com/document/d/1wJ1lmKefJn660KG0UhVpIFouRKneCvH_gCLWUvb2ddk/edit)

Shared notes document for the session here: [https://pad.sfconservancy.org/p/ttw-bts-rir-hackathon-oct22](https://pad.sfconservancy.org/p/ttw-bts-rir-hackathon-oct22)

### What needs to be done?

- [x] Create zoom link for Google Doc - JD (make everyone co-hosts)
- https://turing-uk.zoom.us/j/98529528726?pwd=eGhGaWNYMUZlSEp2N25uU3F4VTlXdz09&from=addon
- [x] Create pre-event survey questions to share with BTS - JD
- https://docs.google.com/forms/d/e/1FAIpQLSeAwxJRqtBQMhXIHTzW8okU01JGOAF0mB-kdL2rDzwxbqs3lg/viewform?usp=sf_link
- [x] Create issue for workshop planning - ALS
- [x] Slides for first 15-min - ALS?
- [x] Create pre-formatted TTW templates for each room (x3) - AB
- [x] Create shared notes document (need to ask for GitHub handle for follow up PRs/names for acknowledgement in chapters) - Etherpad
- [x] Create PR for list of research infrastructure roles to add audience suggestions to 

### Who can help?

* People tagged above
* Those who want to volunteer as facilitators at the event

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by aleesteele** [comment]
Slides being prepped here: https://docs.google.com/presentation/d/1MQttPt19ptk_9G1WI6UISJ3IbZzD_D3n/edit#slide=id.p62

**Comment by aleesteele** [comment]
Google drive folder with planning materials: https://drive.google.com/drive/folders/1num-bvE9rR0-6rkK53vlbEuXv7OEZ8XG

**Comment by aleesteele** [comment]
Closing this, thanks @Arielle-Bennett and @dingaaling for a great workshop!
