### ISSUE TITLE
Adding a link to cross-reference the sub-chapter on Biological data

### ISSUE THREAD

**Issue by EKaroune** [alan-turing-institute/the-turing-way#2693]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Collaborations Workshop in October 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @EKaroune know on Zoom so that we can assist you.

## Summary
In the [Sensitive Data Projects](https://the-turing-way.netlify.app/project-design/sdp.html) chapter in the [Guide for Project Design](https://the-turing-way.netlify.app/project-design/project-design.html), add a link to cross-reference a sub-chapter.

## Guide to Contribution 

1. Comment on this issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/project-design/sdp.md

3. Find line 27 to add the cross-reference link for the sub-chapter - Biological data. 

4. Click 'Edit this file' to add the resource.

5. Use Markdown format to add the cross-referencing link on the page:
```
{ref}`Biological<pd-sdp-biological>`
```

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2693). 

Example: `this pull request fixes #2693`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by lakillo** [comment]
@lakillo and @ankita95 are working on this!
