### ISSUE TITLE
Make pull request template and redo issue template

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#27]
We're ok with updating the first entry in an issue with summaries of the discussions that flow down the thread to make it easier to follow where a conversation has gone.

It would be useful to have an issue template to make clear that we're going to keep summaries updated.

**Comment by pherterich** [comment]
Are we okay with the ones we have at the moment and can close this issue?

**Comment by r-j-arnold** [comment]
Yep, I'm happy to close
