### ISSUE TITLE
Research for Genomic Equity Conference discussion

### ISSUE THREAD

**Issue by EKaroune** [alan-turing-institute/the-turing-way#2743]
**Summary:**
At the Research for Genomic Equity Conference, *The Turing Way* will present a workshop under the title "Increasing equity through Open Research" on the 20 October 2022.

The Turing Way is an open-source community-driven guide to reproducible, ethical, inclusive and collaborative data science. It consists of five guides on different aspects Data Science, including the Guide for Collaboration.

We will capture here discussions from our workshop. 
 
**Discussion will be guided around the question of equitable research and its impact on research outcomes**

## Questions

**Contribution Guidelines**:
 Read the [Contribution guideline](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md) of The Turing Way.

**Comment under this issue**:

You can use this template to make your comment as useful as possible:
- Names of group members: <YourName>
- Question: <copy and paste the question you discussion>
- Details of discussion: <summary of main points of discussion, any conclusions you came to>
- Link: <link to any resource that you think would be useful>

**Who can help in this issue?**
* Attendees of the workshop. We especially encourage new contributors who haven't contributed to our project before.
* Everyone who contributes to this discussion, will be added to the Contributors' Table.

**Comment by aleesteele** [comment]
**Printed materials:**
- Printed flier (@aleesteele)
- Stickers
- Sign-up sheet

**Comment by aleesteele** [comment]
Adding in some notes from last week's workshop:
![IMG_2264 (2)](https://user-images.githubusercontent.com/18509789/197509433-45437e62-b1a9-437f-b3f1-632176e9e4bd.jpg)
![IMG_1276](https://user-images.githubusercontent.com/18509789/197509465-8f149d0c-565b-47e9-bb30-f5777b28fe00.jpg)

**Comment by aleesteele** [comment]
Closing this issue, now that the workshop has concluded! Go team! 🚀
