### ISSUE TITLE
[TO EDIT] project-design/pd-overview/pd-overview-sharing

### ISSUE THREAD

**Issue by padamson** [alan-turing-institute/the-turing-way#2760]
### Summary

There is a significant typo that needs to be fixed right away. **I**noperable should be **I**nteroperable! Also, I think the opening paragraph should be changed to convey that FAIR principles are considered throughout the life of the project and not "Now that you are in the last phase of your project..."

### What needs to be done?

- [x] fix inoperable->interoperable type
- [ ] modify opening paragraph - FAIR principles are considered throughout project life
- [ ] review full page for tweaks to reinforce message in opening paragraph

### Updates

- [ ] First set of edits to chapter/subchapter
- [ ] Proofread
- [ ] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by aleesteele** [comment]
Fixed by @TheAbstract 🚀
