### ISSUE TITLE
Broken link in reproducible-research/reviewing/reviewing-recommend

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#2766]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Bookdash Workshop in November 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon, @harisood, or @aleesteele know. 

## Summary
There is a broken link in the [Recommendations for Reviewing Code](https://the-turing-way.netlify.app/reproducible-research/reviewing/reviewing-recommend.html) subchapter of the [Guide to Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/reproducible-research.html). 

## Guide to Contribution 

1. Comment on this issue with the people working on the issue using their Github usernames.

2. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/reproducible-research/reviewing/reviewing-recommend.md

3. Find line 71 where the current link to the py4science/code_review is

4. Click 'Edit this file' to add the resource.

5. Use Markdown format to change the link from 
```
see the approach taken by a professor organizing [lab meetings for code](http://fperez.org/py4science/code_reviews.html).
```

to 

```
see the approach taken by a professor organizing [lab meetings for code](http://web.archive.org/web/20210512053038/http://fperez.org/py4science/code_reviews.html).
```

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one of #2695). 

Example: `this pull request fixes #2766`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by malvikasharan** [comment]
Thank you Patricia. I am posting the direct link to the chapter: https://the-turing-way.netlify.app/reproducible-research/reviewing/reviewing-recommend.html

**Comment by BrainonSilicon** [comment]
Hi team! Thanks for finding this @pherterich - I've edited the issue so that the workshop team can use it during Bookdash. If the issue isn't closed during bookdash then we can change the issue description back 🌟
