### ISSUE TITLE
[NEW CHAPTER] - Open Peer review & Code Review

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2770]
### Title

Open Peer Review

### Guide

Communication

### Summary of proposed chapter

Add information about what open peer review is and what the benefits are + add information on code review

### Resources

- [x] Limits of traditional post publication review: Hardwicke et al. 2022
- [x] https://openscience-utrecht.com/peer-review/
- [x] Bravo et al. 2019
- [x] Horbach et al. 2022 open peer review
- [x] CODECHECK

### Who can help?

@Karvovskaya , @c-martinez 

### Updates

- [x] Write chapter outline
- [x] Add material to the chapter
- [x] Combine materials into a readable chapter
- [x] Proofread
- [x] Create PR and link in the comments
- [x] Request reviews
- [ ] Address reviews
- [ ] Merge to main branch

**Comment by EstherPlomp** [comment]
Found out that we have a whole section on code reviewing where software is the primary research output! So now I'm just providing a short overview of code review when it is software underlying a research article (following the ReproHack guidelines which I find very helpful!), and I refer to the [Code Reviewing Process chapter](https://the-turing-way.netlify.app/reproducible-research/reviewing.html) for more information.

**Comment by EstherPlomp** [comment]
@c-martinez - was there still anyone interested to contribute to this during the Book Dash? If not, @Karvovskaya has approved the PR so I can merge it later today/tomorrow. Let me know!

**Comment by c-martinez** [comment]
Let me check with a couple of people, but not sure they will have time to look at it today.
