### ISSUE TITLE
"© Copyright 2020-2021."

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#2772]
In the footer for the website is the text "© Copyright 2020-2021."

1. This is out of date
2. Do we actually want to be making this statement? Would it in fact be better to have a link to our license instead?

**Comment by da5nsy** [comment]
See Wiktionary for an alternative
![Screenshot_20221115-193316](https://user-images.githubusercontent.com/3739866/202054371-6a06b8ec-2f03-4606-9228-666554590bf8.png)

**Comment by KirstieJane** [comment]
I think a link to how to cite the content from a CC-BY statement sounds perfect 💖

**Comment by bsipocz** [comment]
A couple of repos where the dates are embedded in e.g a python conf file, the end date is auto-generated :)

**Comment by da5nsy** [comment]
> I think a link to how to cite the content from a CC-BY statement sounds perfect 💖

@KirstieJane - the link that I've proposed in #2926 is to the [licence](https://github.com/alan-turing-institute/the-turing-way/blob/main/LICENSE.md), which says:

> You must give appropriate credit (mentioning that your work is derived from work that is Copyright © The Turing Way Community and, where practical, linking to https://github.com/alan-turing-institute/the-turing-way), provide a [link to the license](https://creativecommons.org/licenses/by/4.0/), and indicate if changes were made

I don't think there is anything more explicit in the book that says exactly "this is our preference for precisely how we would like you to cite us", which might be a separate issue. I assume we would want to copy/link to the text from Zenodo: 
<img width="240" alt="Screenshot_20230329_165304" src="https://user-images.githubusercontent.com/3739866/228597266-502303ae-925e-4a60-8bb8-9578c787fa77.png">

**Comment by da5nsy** [comment]
> A couple of repos where the dates are embedded in e.g a python conf file, the end date is auto-generated :)

Ooh this would be fun.
Worth noting though - that I think #2926 will actually _hide_ the copyright information, and so it might be a moot point for now (though I suspect it becomes relevant when versions are made and pushed to zenodo).

**Comment by bsipocz** [comment]
Sadly, I haven't yet seen one good way to do it in the yaml file level

**Comment by bsipocz** [comment]
@da5nsy - I don't open an issue for this to minimize clutter, but keep in mind this repo when/if I come across a solution (I would need that elsewhere anyways). I think ultimately it should/could be a jupyterbook config level feature, to say the start year and it figures out the end based on the current year at the time of rendering. Or keep it as an open interval, as `2019--` in our case.
