### ISSUE TITLE
[WIP] Book Dash: Github Training Workshop

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2776]
# Book Dash: Github Training Workshop

### 🚀🌟 Welcome to _The Turing Way_! We're so glad to have you here! 🌟 🚀 

_The Turing Way_ is a community-led resource for reproducible, open, collaborative, and inclusive data science. Created by over 400 contributors, The Turing Way uses open source tools to enable people to collaboratively write chapters, build and maintain resources, as well as share their skills and ideas around best practices. Core to this is the version control tool, Github which supports The Turing Way’s collaborative practices. 

### Workshop Information
**Date:** Wednesday 9 November
**Start time:** 17:00 | End time: 18:00
**Workshop Slides:** 
**Issue List:** [Workshop exercise list](https://github.com/alan-turing-institute/the-turing-way/issues?q=is%3Aissue+is%3Aopen+label%3A0-book-dash-nov22+label%3A%22good+first+issue%22)

In this workshop, co-facilitators from The Turing Way Community will introduce participants to using GitHub as a tool to support collaborative documentation-writing and knowledge sharing. 

They will discuss the importance of open community practices in building and maintaining collective resources, and learn about the importance of different roles in open source documentation communities like The Turing Way: including that of maintainers, reviewers, and translators.

Participants will gain hands-on experience in working collaboratively during the workshop by contributing to the The Turing Way project. A shared document will be used for collaborative note-taking, capturing feedback and learnings.

This training is being offered as a part of [Book Dash](https://the-turing-way.netlify.app/community-handbook/bookdash.html): a week-long event of contributions and collaborations within The Turing Way community.

#### About the Trainers

Sophia Batchelor (@BrainonSilicon) is a Community Manager of the AI for multiple long-term conditions: Research Support Facility (AIM-RSF) at the Alan Turing Institute and a core contributor to The Turing Way.

Hari Sood (@harisood) is a Research Application Manager (RAM) at the Alan Turing Institute and a core contributor to The Turing Way project. At ATI, he focuses on finding real world implementations for Turing's research outputs, with his role focusing on Trusted Research Environment infrastructure.

### Housekeeping 
**Privacy statement**
This event follows the [The Alan Turing Institute's Privacy Policy](https://www.turing.ac.uk/privacy-policy).

**Code of Conduct**
* Attendees of this session will be expected to adhere to the The Turing Way's [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/main/CODE_OF_CONDUCT.md)

If you have any questions, comments, and recommendations, please contact **Anne Lee Steele (asteele@turing.ac.uk), Hari Sood, or Sophia Batchelor** or comment on this issue. 

# Icebreaker question
Comment below with an answer to the following question: 

**What is an activity you could you do for a long time without getting bored?**

**Comment by harisood** [comment]
VR Ping Pong

**Comment by BrainonSilicon** [comment]
Knitting (especially a scarf)

**Comment by harisood** [comment]
Playing piano

**Comment by aleesteele** [comment]
Gardening!

**Comment by ClaudiaCAU** [comment]
Tennis

**Comment by AngelikaKerlin** [comment]
Reading! (and TikTok according to my usage stats...)

**Comment by s-shivanand** [comment]
Cricket (Test Cricket)

**Comment by WinnyNekesa** [comment]
Playing volleyball and dancing

**Comment by harisood** [comment]
Thanks for all your responses everyone! I'm going to close this issue now :)
