### ISSUE TITLE
Spelling error in Introduction to Research Ethics

### ISSUE THREAD

**Issue by harisood** [alan-turing-institute/the-turing-way#2780]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the BookDash in November 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @harisood, or @aleesteele know on Zoom so that we can assist you.

## Summary
In the [Introduction to Research Ethics](https://the-turing-way.netlify.app/ethical-research/ethics-intro.html) chapter there is a type in a subheading.

## Guide to Contribution 

1. Comment on this issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/ethical-research/ethics-intro.md

3. Find line 55 to find the sentence `Definition Research Ethics`

4. Click 'Edit this file'. 

5. Change the word 'Definition' to 'Defining':
```
Defining Research Ethics
```

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue.  

Example: `this pull request fixes #2780`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by s-shivanand** [comment]
I am working on this issue with ClaudiaCAU.
