### ISSUE TITLE
Fix citations in Introduction to Book for Ethics

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2796]
### Summary

During the Github Workshop at Book Dash November 2022, @BrainonSilicon discovered that the [Introduction for the Guide for Ethical Research uses academic citations](https://the-turing-way.netlify.app/ethical-research/ethics-intro.html), rather than our standard format. @da5nsy also noted this in #2789.

We need help in converting these citations into standard citation convention, which you can learn more about here: https://the-turing-way.netlify.app/community-handbook/style/style-citing.html

### How to help?
This page requires learning about how citations are made within the book,
- The Bibliography page would have to be updated, adding the resources that are currently listed in the intro page: https://the-turing-way.netlify.app/afterword/bibliography.html
- Update the Intro page with the appropriate format: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/ethical-research/ethics-intro.md

**Comment by KatrionaGoldmann** [comment]
I am currently working on this.
