### ISSUE TITLE
[BUG] Ambiguous link on `/project-design/sdp/personal.md`

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#2832]
[HCH+15] ?

https://github.com/alan-turing-institute/the-turing-way/blame/main/book/website/project-design/sdp/personal.md#L30

**Comment by EKaroune** [comment]
I think @EstherPlomp will know this reference???

**Comment by EstherPlomp** [comment]
I has found this! {cite}Smith2015participantdata, which is here [10.1186/s12916-015-0532-z](https://doi.org/10.1186/s12916-015-0532-z)
