### ISSUE TITLE
[WIP] Add a sub-chapter on Research Ethics in Social Data under Guide for Ethical Research

### ISSUE THREAD

**Issue by booktrackerGirl** [alan-turing-institute/the-turing-way#2871]
### Title

Research Ethics on Social Data

### Guide

Collaboration

### Draft

[Will add later!]

### Summary of proposed chapter

The current 'Guide for Ethical Research' page looks very well-documented. And it could be interesting to add a page dedicated to 'Research Ethics for Social Data'. I am sure that like myself, there are other people who face concerns and difficulty in understanding how to approach the social data, and by how much, primarily because of ethical reasons and keeping one's research integrity in check. A page solely dedicated to that (perhaps even with respect to different platforms) could hence be a useful addition to every researcher working or intending to work on social data.

### Resources

- [ ] Discussion with the collaborators and the wider team, receiving feedback on how they view the changes.
- [ ]  Reading the existing Guide for Research Ethics chapter to understand where it fits in and ensure consistency of tone with other chapters when reading.
- [ ] Google how other resources deal with research ethics while working with social data.

### Who can help?

Because of their previous work in Guide for Research Ethics, @Arielle-Bennett and @LauraCarter could be a good addition to contributing to this chapter as well.

### Updates

- [x] Write chapter outline
- [x] Add material to the chapter
- [x] Combine materials into a readable chapter
- [x] Proofread
- [x] Create PR and link in the comments
- [x] Request reviews
- [x] Address reviews
- [x] Merge to main branch

**Comment by aleesteele** [comment]
@all-contributors please add @booktrackerGirl for ideas

**Comment by aleesteele** [comment]
Closing this, as it is completed! Nice work @booktrackerGirl 🚀 hope to see you at the next Book Dash!
