### ISSUE TITLE
Add Lab manual/CoC to Collaboration

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#2877]
### Summary

It would be good to have a section on how to have a lab statement/manual/code of conduct - kind of like our community handbook but then for a lab. 

### What needs to be done?

- [x] Settle on name (Lab Guidebook, Manual, Code of Conduct, Statement?)
- [x] Decide where to place this chapter (I thought between Managing a New Community and Team and Data Science Leadership)
- [ ] Checklist for onboarding 

Checklist for off boarding
- [ ] http://hdl.handle.net/2142/111616
- [ ] https://resolver.caltech.edu/CaltechAUTHORS:20200519-142758925
- [ ] https://www.nature.com/articles/d41586-022-02967-3 (why you need one – memory loss)

Examples of lab manuals/coc's for inspiration

- [ ]  [Lab Manual Template](https://docs.google.com/document/d/1LqGdtHg0dMbj9lsCnC1QOoWzIsnSNRTSek6i3Kls2Ik)
- [ ] [A list of lab guides](https://docs.google.com/spreadsheets/d/1kn4A0nR4loUOSDn9Qysd3MqFJ9cGU91dCDM6x9aga-8/)
- [ ] [Collection thread by Hao Ye](https://twitter.com/Hao_and_Y/status/1537428359277334528)
- [ ] [Weecology Wiki](https://wiki.weecology.org/)
- [ ] Code of Conduct [Whitakerlab](https://github.com/WhitakerLab/Onboarding/blob/master/CODE_OF_CONDUCT.md).
- [ ] [Witteman lab guidelines](https://docs.google.com/document/d/1I4qgoQlfezd4rB0ktSO2wHk-mBmw2DVlvw7hvnnFVGo)
- [ ] CBIO [lab statement](https://lgatto.github.io/cbio-lab/)
- [ ] [Basin Research Group (BRG) ](https://docs.google.com/document/d/10y7TP48ik1rcQBPA5Do8mZM7DJ5EbF0hyWP-csgb1QE/edit)
- [ ] [Ethics and Values](http://faculty.washington.edu/bmarwick/values_and_ethics/) Ben Marwick
- [ ] [Faylab Lab Manual](https://thefaylab.github.io/lab-manual/index.html)
- [ ] [ContextLab](https://github.com/ContextLab)
- [ ] [Bahlai lab](https://github.com/BahlaiLab/Policies)
- [ ] Openscapes ['how we work'](https://github.com/Openscapes/how_we_work)

### Who can help?

anyone interested in the topic :)

---

### Updates

[
HackMD draft](https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/S1wczbd8j/edit)

**Comment by da5nsy** [comment]
I'd be interested in helping! ✋

**Comment by EstherPlomp** [comment]
Whooo! I still have to start with the on/off boarding checklists, but the HackMD already contains some drafts for the lab manual thing itself: [HackMD draft](https://hackmd.io/@TycZoDDEQIq6yttGuqbuww/S1wczbd8j/edit)
Feel free to edit or to jot down thoughts here :)

**Comment by EstherPlomp** [comment]
@adswa

**Comment by adswa** [comment]
@shreyadimri

**Comment by adswa** [comment]
@meliimming

**Comment by adswa** [comment]
Keeping a note from a discussion about what place this chapter would fit into: There are many places we could cross-link the new chapter to. This is what @shreyadimiri and I brainstormed quickly; Please feel free to edit this list (both by removing or adding elements):

- [ ] Guide for Communication: Authorship and Contributions on Academic Articles
- [ ] Guide for Collaboration: Tools for Facilitating Collaboration
- [ ] Guide for Collaboration: Organising Meetings
- [ ] Guide for Collaboration: Managing a New Community and Team
- [ ] Guide to Ethical Research: Self-reflection

**Comment by da5nsy** [comment]
Closed by #3028
