### ISSUE TITLE
[TALK] Internationalisation and Localisation of Open Science through The Turing Way

### ISSUE THREAD

**Issue by BatoolMM** [alan-turing-institute/the-turing-way#2879]
### Date of talk

2022-12-07

### Details of the talk

This talk will be presented by @aleesteele and @BatoolMM for RIOTS Science on the 7th of Dec 2022 at 13:00pm UTC.

### Notes from Anne:
**The talk will discuss the following:**

- Building a shared language for open science
- Challenges & opportunities of building laterally across borders but also building locally, by people & for themselves. 
- Institutionalisation of open science -> opportunities for increasing growth around the world, but what does that do for “ground truth” within small-scale, localised efforts?
- Embodied knowledge, knowledge equity, Standpoint theory (knowledge in context)
- (Speaking from global perspective) As the open science movement has gathered steam over the past few years, it has seen increasing visibility in international contexts: from UNESCO’s call for best practices, to NASA’s gathering of an international coalition of experts to advise, to increased arguments for [advocating for open science as a human right](https://blogs.lse.ac.uk/impactofsocialsciences/2022/08/17/the-human-rights-case-for-open-science/). However, these global groups and coalitions have grown, they can smooth over differences and nuances.

The working document is this [shared Google Doc](https://docs.google.com/document/d/1kRelDvPTvjCFCijsmGDCfdnFyOLWYkbuXMnSnhvoPoM/edit).

### Checklist

- [X] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [X] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [x] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [x] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [x] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [x] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [x] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [x] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by aleesteele** [comment]
Thanks so much for making this issue, @BatoolMM !

**Comment by BatoolMM** [comment]
It's added here: https://zenodo.org/record/7410496#.Y5EcRuymO3I
