### ISSUE TITLE
Discuss whether to rename humans.md

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#288]
### Summary

As mentioned in #269 the name of the humans.md file is quite ambiguous. Decide whether to change it to contributors.md or similar.

### What needs to be done?

- [ ] Decide whether to change it and if so what to
- [ ] Change it if so 

### Who can help?

Anyone with an opinion

**Comment by r-j-arnold** [comment]
I think contributers.md is better- it's more explicit about who the humans inside are. Humans.md is ambiguous. We could even go further and call it contributors_list.md

**Comment by KirstieJane** [comment]
From the issue I made:

> The name `humans.md` is a spin off from `robots.txt` and it's fun if you know what `robots.txt` is for, but doesn't make much sense otherwise!
>
> I propose we rename `humans.md` to `contributors.md` so is it more intuitive that we're listing the PEOPLE who have built the project.

**Comment by KirstieJane** [comment]
I like `contributors.md` rather than `contributors_list.md` because I don't think we need the `_list` part. I think `contributors` is clear enough, and I hope it will be a little more enriched than "just" a list 😄

**Comment by r-j-arnold** [comment]
Good point, if it's not just a list then we shouldn't describe it as one
