### ISSUE TITLE
December 2022 newsletter

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2886]
### Summary

Collecting information for December 2022 newsletter

### What needs to be done?
- Collecting talks/events from the past month
- Jobs/opportunities/events

Draft: https://hackmd.io/HnWkW6m6Q3uo-Y92dUc_lg

**Comment by aleesteele** [comment]
https://zenodo.org/record/7339751#.Y39sm4LP2RY - keynote by @sgibson91 on 2022-11-21.

**Comment by acocac** [comment]
Reuse of TTW/Scriberia illustrations and promotion of TTW and other amazing open science communities (OLS, TOPS, Metadocencia, EDS book & Pangeo) in a recent talk [in Spanish] at the [International Forest Model Network annual conference](https://imfn.net/) - keynote by @acocac on 2022-12-24

- [Zenodo DOI](https://doi.org/10.5281/zenodo.7357951)
- [YouTube Recorded URL](https://youtu.be/84arINjIB3E?t=14400)

**Comment by aleesteele** [comment]
Fireside chat feedback form: https://forms.gle/E77VESVxczWxFekB6

**Comment by aleesteele** [comment]
Reminder to add this amazing holidays graphic by @EstherPlomp !
![Alt: Scripted cursive in blue that reads "Happy Holidays". Small ovular bubbles are around the image that show doodles of each member of The Turing Way organisational team.](https://user-images.githubusercontent.com/18509789/205641325-de28fb49-31d8-460d-8755-f8970cff02f0.png)

**Comment by malvikasharan** [comment]
- Keynote on 17 Nov: https://zenodo.org/record/7428708
- Panel on 28 Oct: https://twitter.com/OpenLifeScience/status/1585973327654682625 <-- This might have already been captured in a previous newsletter
- Panel on 30 Nov: https://twitter.com/TheNeuro_MNI/status/1597994117791117313?s=20&t=ZFd6iWrlzesuXYe8qpg7CQ
- Panel of 12 Dec: Center for HelioAnalytics Transdisciplinary CoPs Town Hall <-- will add link when I find one

**Comment by malvikasharan** [comment]
OLS grad dates and OLS-7 call: https://openlifesci.org/posts/2022/12/01/announcing-applications-for-ols-7/

**Comment by malvikasharan** [comment]
Open Science Retreat in April: https://twitter.com/HeidiBaya/status/1600428757302489088?s=20&t=fbffXsxDIQqXEsxDvbFmnQ

**Comment by malvikasharan** [comment]
Announcement: The Turing Way received funding for 2 years to establish Practitioners Hub.
Proposal: https://zenodo.org/record/7427274

**Comment by aleesteele** [comment]
Closing this, as December's newsletter was published: https://tinyletter.com/TuringWay
