### ISSUE TITLE
Accessing private repos for Turing members

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#291]
### Summary

Ideally, authenticated Turing members should be able to access private repos belonging to the Turing Institute GitHub organisation.

BinderHub docs on private repo access:
* https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#accessing-private-repositories

Binder/BinderHub issue discussing private repo access:
* https://github.com/jupyterhub/binderhub/issues/237

### What needs to be done?

- [ ] Do these docs reflect our use case?
- [ ] What are the security risks?

### Who can help?

* Anyone with BinderHub/JupyterHub knowledge
* Anyone with Authentication knowledge

---

### Updates

See also #346

**Comment by sgibson91** [comment]
Documentation for accessing private repos can be found [here](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#accessing-private-repositories).

**Summary:**
Accessing private repos is as simple as creating a GitHub personal access token with full read/write access to all of the repos on the account the token belongs to. The repos are cloned "as BinderHub", not as the GitHub user. Therefore, any user with access to the BinderHub will have access to all of the private repos BinderHub has credentials for.

This is not ideal as we do not want users to be able to access repos they would not normally have access to, even within the Turing team.

Possible fine-grained solutions are GitHub's security model or Active Directory authentication.

**Comment by sgibson91** [comment]
**Another way to consider private repo access:**
Using GitHub as a provider via the GitHub API (v3 or v4), grant BinderHub read-only permissions to clone the private repos only the user has access. i.e. Not whichever repos the user who creates the Personal Access Token has access too, which would be the situation as described by the current BinderHub documentation.

**Comment by sgibson91** [comment]
/cc: @KirstieJane to introduce @sgibson91 to her colleague in Montreal with GitHub API knowledge

**Comment by sgibson91** [comment]
Paraphrasing conversation with @rmarkello (THANK YOU btw! ✨)

* Use a [List Collaborators call](https://developer.github.com/v3/repos/collaborators/#list-collaborators) (or check the user's collaborator status) to verify they can see a private repo
  * This is advantageous as it does not require full write access to the private repo
* Someone with admin rights to `alan-turing-institute` will need to make the OAuth app so it knows all the private repos (not just the ones I can see for instance)
* Edits to BinderHub to include such a call should probably be inserted somewhere around here:

https://github.com/jupyterhub/binderhub/blob/01b1c59b9e7dc81250c1ed579c492ec2fd6baaf6/binderhub/repoproviders.py#L403

  i.e. when building the repo URL, also check the user has access to it!
* An alternative option with be GitHub Apps (rather than OAuth apps) as they facilitate finer-grained access scopes
  * Could be an addition to: https://github.com/jupyterhub/oauthenticator

**Comment by betatim** [comment]
I think the "authenticator users" part of BinderHub is the least used and developed part. So all contributions are welcome. However this also means that how exactly to do it is less clear because we are much less constrained by existing things.

There is a authenticated BinderHub setup (the folks at GESIS did this), so you can ask people to login via GitHub. In this case you can use the access token you get from that login to clone the repo (-> GitHub takes care of permissions). You can also forward that token to inside the Binder container so people can keep being "logged in" to GitHub (e.g. if they want to commit and push stuff). I think if you search the binderhub repo issues you should find one on "authenticated binder".

**Comment by sgibson91** [comment]
Thanks!

Authenticated and persistent storage BinderHub: https://github.com/jupyterhub/binderhub/issues/794

**Comment by sgibson91** [comment]
If anyone would like to follow along or contribute, we're documenting in [this hackmd](https://hackmd.io/X_Hkb4YkRmiLp74IpZKkMA?view) 😄 ✨

**Comment by sgibson91** [comment]
This is resolved by applying the following project:

- https://github.com/yuvipanda/github-app-user-auth
