### ISSUE TITLE
Issue on page /ethical-research/activism/activism-unionisation.html

### ISSUE THREAD

**Issue by yabellini** [alan-turing-institute/the-turing-way#2960]
Add unions of scientific and academic workers from Latin America: 

Argentina: 
APINTA (Asociación del Personal del Instituto Nacional de Tecnología Agropecuaria, Staff Association of the National Institute of Agricultural Technology) is the entity that groups together all workers, who have an employment relationship with INTA, as well as its retirees and pensioners. 

CONADU: Federación Nacional de Docentes Universitarios (National University Teachers Federation). Main objectives are the defense of:
Public, Free, Democratic, Popular, Feminist and Latin American University; salary, working conditions, training and teaching careers;     access, permanence and graduation of students in Higher Education; research and the production of knowledge, science and technology; the linkage of the university with the State and society to promote national and regional development.

**Comment by Arielle-Bennett** [comment]
Yes please @yabellini ! Can you send through some links to more information about the unions? 

I can work on this during the Collaboration Cafe tomorrow if you would like to submit a PR (or I'm happy to update them for you!)

**Comment by yabellini** [comment]
Here are the links: 
* APINTA: https://www.apinta.org/
* CONADU: https://conadu.org.ar/

**Comment by Arielle-Bennett** [comment]
@all-contributors please add @yabellini for ideas
