### ISSUE TITLE
Set up call with Ollie to go through technical Qs (Lucy)

### ISSUE THREAD

**Issue by lucymellor** [alan-turing-institute/the-turing-way#2976]

**Comment by aleesteele** [comment]
Hi @lucymellor, thanks for making a pull request! It's so great to have you here at the Turing Way. 🚀 

Would you be able to add more context to your issue so that others might be able to know the context of the issue you are making, as well as possibly tag Ollie in this issue as well? That way, we in the community can see if there's any way that we can help you along. Cheers!

**Comment by lucymellor** [comment]
Hi Anne,

I’m really sorry but it was a mistake – I meant to add it to the project board of a different repo! Feel free to just delete.

Many thanks,
Lucy

_____________________________
Lucy Mellor
Strategic Support Officer
Office of the Director
+44 (0)7977492122
***@***.******@***.***>
_____________________________
The Alan Turing Institute
British Library
96 Euston Road
London NW1 2DB
turing.ac.uk<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fturing.ac.uk%2F&data=05%7C01%7Clmellor%40turing.ac.uk%7C5230b2118be24afe5fb508daa5ee89f3%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638004741170593352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QmeUKjl4HhA82MEr1yugMjjtEs4CXCeza8mU%2FdjYjVQ%3D&reserved=0>
@turinginst<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fturinginst&data=05%7C01%7Clmellor%40turing.ac.uk%7C5230b2118be24afe5fb508daa5ee89f3%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638004741170593352%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o4qK3DhY7C48MVoVOlo5GOFqqA1fptCN0yqNqZI9qn4%3D&reserved=0>

***@***.***<https://ai-uk.turing.ac.uk/>

**Comment by aleesteele** [comment]
No problem, thanks @lucymellor !
