### ISSUE TITLE
[FOSS Backstage]: Maintenance as a Turing Way

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2993]
### Date of talk

2023-03-14

### Details of the talk

Co-presentation with @da5nsy

> The Turing Way - an open guidebook for data science and research - emerged in response to the crisis of reproducibility in science, amidst a growing movement for new ways of managing research data: through initiatives such as the FAIR principles and various open source software projects. As the movement has matured, it has also entered a new phase that has asked different questions about its sustainability, governance, funding, and diversity. As these questions have evolved, so has the wider landscape of technology more broadly, pushing back against the ethos of ‘moving fast and breaking things’ as questions of maintenance come to the forefront. This talk discusses open source maintenance in the context of The Turing Way, within computational communities and open science more broadly: extending into the culture of research itself. It discusses the tensions between developing new ideas to change research culture and the cultivation of maintenance as an ethos for developing, contributing to, and participating in an open source community like The Turing Way.

Available here: 
https://program.foss-backstage.de/fossback23/talk/RMHQAB/

### Checklist

- [X] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [X] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [x] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [x] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [ ] If you re-used slides from a specific talk, please acknowledge the original author of the slides
- [ ] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [ ] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [ ] Share the Zenodo link and a recording (if available) in TTW Slack!

**Comment by da5nsy** [comment]
Adding the link to the recording here for posterity! (Or until youtube burns and falls at least!)
https://www.youtube.com/watch?v=Lt8iuKyqA8A

**Comment by da5nsy** [comment]
And not sure where the DOI should live, but again, I'll put it here for easy reference!
https://doi.org/10.5281/zenodo.7732459
