### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#2999]
### Summary

We seem to be getting a broken build on netlify, where accessing [The Turing Way](the-turing-way.netlify.app/) shows an error message: "Page Not Found. Looks like you've followed a broken link or entered a URL that doesn't exist on this site." All our CI checks & Netlify aren't showing that anything is incorrect - is there anything else I am missing here? 

<img width="628" alt="Screenshot 2023-03-15 at 09 29 29" src="https://user-images.githubusercontent.com/18509789/225267022-aca25278-8d54-4d25-b2ef-fef5df98653c.png">

Thank you to Alycia Crall of the Carpentries for flagging.

**Comment by sgibson91** [comment]
Did you do anything @malvikasharan or was it just a case of waiting?

**Comment by malvikasharan** [comment]
I went to the last build and clicked published (the second button - which was locked for auto publish):
<img width="732" alt="image" src="https://user-images.githubusercontent.com/5370471/225279718-d5f2ea6d-f8b5-4140-9680-11dd64e5178f.png">

**Comment by sgibson91** [comment]
Ok, so we should investigate auto-publishing settings to make sure this doesn't repeat

**Comment by malvikasharan** [comment]
This was quite a surprise - as this has never happened before. It's now not locked. Maybe @arronlacey can share if he did something differently in his last PR.

**Comment by malvikasharan** [comment]
That sounds like a good idea Sarah.

**Comment by sgibson91** [comment]
Ugh, it might involve me writing a Slack app in order to get an Incoming Webhook URL to pass to Netlify to send the notifications. Too much work.

<img width="760" alt="Screenshot 2023-03-15 at 10 31 53" src="https://user-images.githubusercontent.com/44771837/225282849-09221b6f-01bc-4eba-8573-66360cbe8dc4.png">

- https://api.slack.com/messaging/webhooks

**Comment by sgibson91** [comment]
I tried to anyway, but the workspace has reached it's limit of apps.

<img width="543" alt="Screenshot 2023-03-15 at 10 34 34" src="https://user-images.githubusercontent.com/44771837/225283490-5ea15d83-0841-490d-a987-1916eeb4edad.png">

**Comment by malvikasharan** [comment]
Lol, I have removed an app that we don't use.

**Comment by sgibson91** [comment]
Thank you. I have added notifications for when deploys are locked and unlocked to the auto-github-updates channel

**Comment by arronlacey** [comment]
So [this commit from my fork](https://github.com/arronlacey/the-turing-way/commit/57f8c10f7dae3b51cff45fb63e52f7b57e645bc7) was at 12.29am. that fixed an issue with the `netlify.toml` file. For context I set up a netlify deploy on my personal account for this fork and so had to modify the `netlify.toml` file to make that work on my own deployment. I guess it got locked because that file wasn't correct and then the commit that fixed it or any other further deploys would be locked from that point onwards?

**Comment by malvikasharan** [comment]
Can you revert that change @arronlacey for the toml file?

**Comment by arronlacey** [comment]
The latest commit should be correct (the previous commit fails deployment checks due to an incorrect toml file which I think caused the lock). Perhaps I could just make a dummy commit to re-trigger and see what happens? Happy to do this at a time you are able to have eyes on the website so it's not for long if it happens again.

**Comment by sgibson91** [comment]
Oh actually, maybe try removing the `.html` after `/welcome`? I don't remember that being appended?

**Comment by JimMadge** [comment]
I'm not sure if those rules are being used,

```console
❯ https https://the-turing-way.netlify.app
HTTP/1.1 301 Moved Permanently
Age: 29002
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 57
Content-Type: text/plain; charset=utf-8
Date: Thu, 16 Mar 2023 07:21:26 GMT
Location: https://the-turing-way.netlify.app/welcome
Server: Netlify
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Nf-Request-Id: 01GVNGC3VZD824YHMJNXK2FPWR

Redirecting to https://the-turing-way.netlify.app/welcome
```

I would expect that to redirect to https://the-turing-way.netlify.app/index.html

**Comment by sgibson91** [comment]
Useful issue? https://github.com/executablebooks/jupyter-book/issues/1048

**Comment by sgibson91** [comment]
I think I have a PR ready to land soon 🤞🏻

**Comment by sgibson91** [comment]
Eh, I'm now not sure. Rediraffe throws lots of warnings about things not existing which makes me think we are using Netlify's inbuilt redirects thing instead? https://docs.netlify.com/routing/redirects/

<details>
```
Writing redirects...
WARNING: (broken) https:/the-turing-way.netlify.app.html redirects to https:/the-turing-way.netlify.app/index.html.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/https:/the-turing-way.netlify.app/index.html.html does not exist!
WARNING: (broken) https:/the-turing-way.netlify.app/introduction/introduction.html.html redirects to https:/the-turing-way.netlify.app/index.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/https:/the-turing-way.netlify.app/index.html does not exist!
WARNING: (broken) https:/the-turing-way.netlify.app/welcome.html.html redirects to https:/the-turing-way.netlify.app/index.html.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/https:/the-turing-way.netlify.app/index.html.html does not exist!
WARNING: (broken) https:/the-turing-way.netlify.app/welcome.html redirects to https:/the-turing-way.netlify.app/index.html.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/https:/the-turing-way.netlify.app/index.html.html does not exist!
WARNING: (broken) \/reproducibility/*.html redirects to \/reproducible-research/reproducible-research.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/reproducible-research.html does not exist!
WARNING: (broken) \/reproducibility/04/resources.html redirects to \/reproducible-research/overview/resources.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/overview/resources.html does not exist!
WARNING: (broken) \/open_research/open_research.html redirects to \/reproducible-research/open_research.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/open_research.html does not exist!
WARNING: (broken) \/version_control/version_control.html redirects to \/reproducible-research/version-control.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/version-control.html does not exist!
WARNING: (broken) \/licensing/licensing.html redirects to \/reproducible-research/licensing.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/licensing.html does not exist!
WARNING: (broken) \/collaborating_github/collaborating_github.html redirects to \/communication/communication.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/communication/communication.html does not exist!
WARNING: (broken) \/open-source-comms/*.html redirects to \/communication/open-source-comms.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/communication/open-source-comms.html does not exist!
WARNING: (broken) \/credit/credit.html redirects to \/reproducible-research/credit.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/credit.html does not exist!
WARNING: (broken) \/rdm/rdm.html redirects to \/reproducible-research/rdm.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/rdm.html does not exist!
WARNING: (broken) \/reproducible_environments/reproducible_environments.html redirects to \/reproducible-research/reproducible-environments.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/reproducible-environments.html does not exist!
WARNING: (broken) \/code_quality/code_quality.html redirects to \/reproducible-research/code-quality.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/code-quality.html does not exist!
WARNING: (broken) \/testing/testing.html redirects to \/reproducible-research/testing.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/testing.html does not exist!
WARNING: (broken) \/reviewing/reviewing.html redirects to \/reproducible-research/reviewing.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/reviewing.html does not exist!
WARNING: (broken) \/continuous_integration/continuous_integration.html redirects to \/reproducible-research/continuous-integration.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/continuous-integration.html does not exist!
WARNING: (broken) \/make/make.html redirects to \/reproducible-research/make.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/make.html does not exist!
WARNING: (broken) \/research_compendia/research_compendia.html redirects to \/reproducible-research/research-compendia.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/research-compendia.html does not exist!
WARNING: (broken) \/risk_assessment/risk_assessment.html redirects to \/reproducible-research/risk-assessment.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/risk-assessment.html does not exist!
WARNING: (broken) \/binderhub/binderhub.html redirects to \/reproducible-research/binderhub.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/\/reproducible-research/binderhub.html does not exist!
WARNING: (broken) https:/the-turing-way.netlify.app/reproducible-research/credit.html.html redirects to https:/the-turing-way.netlify.app/communication/citable.html.html but /Users/sgibson/source/github/alan-turing-institute/the-turing-way/book/website/_build/html/https:/the-turing-way.netlify.app/communication/citable.html.html does not exist!
```
</details>

**Comment by sgibson91** [comment]
I think we should move to rediraffe for redirects though because 

1. The less we rely on Netlify, the more mobile we can be with hosting platforms
2. Rediraffe has a diff checker and a redirect builder that we could run in CI so these things don't have to be manually done

**Comment by JimMadge** [comment]
Maybe this explains why the rules are not being followed?

### The redirects file should be in the publish directory

https://docs.netlify.com/routing/redirects/
> Save a plain text file called _redirects without a file extension to the [publish directory](https://docs.netlify.com/configure-builds/overview/#basic-build-settings) of your site.

https://app.netlify.com/sites/the-turing-way/deploys/64139ba97a673800083b7fe8
`10:46:32 PM: A "_redirects" file is present in the repository but is missing in the publish directory "_build/html".`

### The publish directory is `book/website/_build/html`

https://github.com/alan-turing-institute/the-turing-way/blob/1401bf6f24ac78fc6de81a5c619a178ef0f46c08/netlify.toml#L1-L4

However, `_redirects` is in `book/website`

**Comment by sgibson91** [comment]
So a quick fix solution would be to append to the build command in netlify.toml `copy book/website/_redirects book/website/_build/html` because we don't commit the publish dir to git.

However, I still think we should move to using rediraffe instead, because this would automatically run during the `book build` step, and I just don't trust Netlify to do anything complex in a way that overstretched engineers would be able to debug quickly given none of us are paid to do this work.

**Comment by sgibson91** [comment]
I am +1 on making the quick fix solution  I suggested though in order to get the site working as expected. Then the rediraffe work doesn't have to be time pressured.

**Comment by JimMadge** [comment]
> So a quick fix solution would be to append to the build command in netlify.toml cp book/website/_redirects book/website/_build/html because we don't commit the publish dir to git.

Sounds right, shall I make a PR?

> However, I still think we should move to using rediraffe instead, because this would automatically run during the book build step, ...

Agreed. Keeping the build process simple (at least in terms of the command(s)) is a good idea.

**Comment by sgibson91** [comment]
Yes please @JimMadge !

**Comment by JimMadge** [comment]
Wait a second...

https://github.com/alan-turing-institute/the-turing-way/blob/1401bf6f24ac78fc6de81a5c619a178ef0f46c08/netlify.toml#L16-L29

😆 

I will try updating those and just removing `_redirects` first (it looks like those rules weren't being used anyway).

**Comment by sgibson91** [comment]
_Sigh_... We clearly need to converge on a single method of applying and managing redirects!

**Comment by sgibson91** [comment]
I have reopened https://github.com/alan-turing-institute/the-turing-way/issues/1542 to track the rediraffe migration work

**Comment by sgibson91** [comment]
<img width="686" alt="Screenshot 2023-03-17 at 10 33 16" src="https://user-images.githubusercontent.com/44771837/225880634-b7d7659a-356f-4b30-8924-917d22a81367.png">

😢

**Comment by JimMadge** [comment]
😢

**Comment by JimMadge** [comment]
So, I think this means there is an infinite (or at least long) chain of redirects.

```console
❯ https --form POST deref.link/deref url="the-turing-way.netlify.app"
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 30
Content-Type: application/json;charset=utf-8
Date: Fri, 17 Mar 2023 12:02:17 GMT
Server: Apache/2.4.18 (Ubuntu)

{
    "error": "Too Many Redirects"
}
```

Maybe `/` and `/index` are aliases?
Then this rule would create a loop.

https://github.com/alan-turing-institute/the-turing-way/blob/dd1d0e002eaef1d75f3ed844ece268f68ac1e2c0/netlify.toml#L16-L22

<details>

```console
❯ https the-turing-way.netlify.app
HTTP/1.1 301 Moved Permanently
Age: 117
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 55
Content-Type: text/plain; charset=utf-8
Date: Fri, 17 Mar 2023 12:04:50 GMT
Location: https://the-turing-way.netlify.app/index
Server: Netlify
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Nf-Request-Id: 01GVQQE8G5J26Q2H647YYJ1BVH

Redirecting to https://the-turing-way.netlify.app/index


❯ https the-turing-way.netlify.app/index
HTTP/1.1 301 Moved Permanently
Age: 0
Cache-Control: public, max-age=0, must-revalidate
Content-Type: text/html; charset=UTF-8
Date: Fri, 17 Mar 2023 12:06:49 GMT
Etag: "6622dc7cdcf95a3e84bd05d041890dfa-ssl-df"
Location: /
Server: Netlify
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Transfer-Encoding: chunked
X-Nf-Request-Id: 01GVQQEA5WHS0H1YWT707M2RFW
</details>

**Comment by JimMadge** [comment]
Also, is there a better way to test this?
I don't think the problems are replicated in the preview builds, only the production deployment.
Would we want to have a staging or dev deployment?

**Comment by sgibson91** [comment]
> is there a better way to test this?

This might be another case where swapping to rediraffe helps as you get feedback during the build on redirects (screenshot from jupyterhub docs)

<img width="767" alt="Screenshot 2023-03-17 at 15 13 24" src="https://user-images.githubusercontent.com/44771837/225946445-27c84906-9661-498c-98be-2330da7567dd.png">

**Comment by sgibson91** [comment]
It's logo is also *chef's kiss* https://github.com/wpilibsuite/sphinxext-rediraffe#sphinxext-rediraffe
