### ISSUE TITLE
Newsletter March 2023

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#3005]
### Newsletter Process

- [ ] Collate contents in replies to this issue by (2nd Wednesday of the month)
- [ ] Draft markdown version for proofing (by 2nd Thursday of the month)
- [ ] Proofing of markdown version 
- [ ] Proof, test & schedule newsletter
- [ ] Newsletter target send date: 3rd Monday of the month

### Summary

Template started here: https://hackmd.io/_yPbQ5mrSw-9pcoxEn3y4A?both

### Checklist

**Comment by malvikasharan** [comment]
Chelle requested to promote this (https://github.com/nasa/Transform-to-Open-Science/discussions/434)

**Comment by malvikasharan** [comment]
Requested by Scott and Alejandro to add this in Newsletter: https://twitter.com/eds_book/status/1640305300413530112?s=20

**Comment by malvikasharan** [comment]
Podcast: https://twitter.com/SoftwareSaved/status/1638181585051693056?s=20

**Comment by aleesteele** [comment]
Checklist of how to make the newsletter, reviewed with @AlexandraAAJ yesterday:
- [ ] Write in Markdown on HackMD file
- [ ] Create google slide deck with images
- [ ] Add alt text to images
- [ ] Make sure emoji icons are used rather than icon shortcut
- [ ] Convert Markdown to HTML code
- [ ] Paste into Tinyletter WISYWIG

**Comment by aleesteele** [comment]
Closing (and we can archive afterwards - will make issue for that)
