### ISSUE TITLE
[TALK] Reproducible data science

### ISSUE THREAD

**Issue by rainsworth** [alan-turing-institute/the-turing-way#3012]
### Date of talk

2023-05-09

### Details of the talk

I have been invited to present a talk on The Turing Way at the [Square Kilometre Array (SKA) Open Science School](https://www.granadacongresos.com/skaopenscience) taking place at the Instituto de Astrofísica de Andalucía headquarters (IAA-CSIC) in Granada, Spain from 8-10 May 2023. 

The aim of the talk is to introduce and demo The Turing Way project and guides, and include how it relates to the school's main science topics (where relevant):
- What is Open Science?
- How does Open Science benefit society and science itself?
- As a senior researcher, how do my individual research and collaborations benefit from Open Science practices? And, as a PhD student? As an engineer, will I need to update existing services to align with Open Science policies?
- Which tools can I use to follow Open Science principles?
- Is this good for my CV? Will it be acknowledged in the research assessment system? How can I capture these merits in my CV?
- Will everyone be following Open Science principles in 10 years from now? How would we expect it to change science?
- How will SKAO and the SKA Regional Centres contribute to enable best practices in Open Science?

The talk slot is 45 minutes, which includes time for questions.

### Checklist

- [ ] Schedule your talk and let the community know in [TTW Slack](https://theturingway.slack.com/). If you’d like feedback and/or to schedule a practice talk, ask in the TTW Slack!
- [x] Download template(s) from the [promotion pack](https://drive.google.com/drive/folders/1mzGmbJkPnP5q1goQesxDc_E5zAPL0eTF?usp=sharing) to ensure stylistic consistency
- [x] Generate a DOI on [Zenodo](zenodo.org/) and upload your slides when ready, preferably in the original format along with a PDF or any other format you are using. Tag with "the-turing-way" under **Communities**. Zenodo allows [versioning](https://help.zenodo.org/#versioning), so we encourage you to upload your slides before your talk and add additional file(s) with any changes after
- [x] Check all ackowledgements (bottom right corner of each slide) and add the DOI for your presentation and your personal contact info if desired
- [x] If you re-used slides from a specific talk, please acknowledge the original author of the slides -> used slides from the promotion pack, acknowledged in talk and Zenodo
- [x] Double check acknowledgements slide for TTW team, license info, Scriberia link, any additional acknowledgements
- [x] Double check contact info for TTW links (book, Twitter, GitHub, Slack, newsletter), your own contact into
- [x] Share the Zenodo link and a recording (if available) in TTW Slack! https://doi.org/10.5281/zenodo.7905071

**Comment by rainsworth** [comment]
@aleesteele Is it possible to get Turing Way stickers to bring with me to this event to give to students?

**Comment by aleesteele** [comment]
Absolutely! I'll follow up by email - maybe we can send some postcards too? I can bring along a big pack to pass on to you at Collaborations Workshop? (tagging @AlexandraAAJ here for awareness).

**Comment by rainsworth** [comment]
@aleesteele Yes please, thank you so much!

**Comment by rainsworth** [comment]
Link to slides: https://doi.org/10.5281/zenodo.7905071

Tweets:
- https://twitter.com/manugrapevine/status/1655887984334458880?s=20
- https://twitter.com/iaa_csic/status/1655893593674989575?s=20

The stickers have gone down a treat, thank you @aleesteele !
