### ISSUE TITLE
Get Service Principal to be able to deploy BinderHub on Turing Azure subscription

### ISSUE THREAD

**Issue by martintoreilly** [alan-turing-institute/the-turing-way#302]
### Summary
We need a Service Principal with access to our registry of Docker images on Azure in order to deploy a Kubernetes cluster on the Turing Azure subscription for BinderHub (see [Microsoft guide](https://docs.microsoft.com/en-us/azure/aks/tutorial-kubernetes-deploy-cluster)).

### What needs to be done?
Ideally one or more project members would be given permission to create Service Principals that can access our TuringAzure subscription. Failing this, someone who does have this permission needs to create one for us (at the moment this is just Turing IT).

### Who can help?
@martintoreilly is negotiating with Turing IT about this. The goal is to get a trial where some members of the Turing Research Engineering Group are granted the permission to create Service Principals and in the long run establish a process for this permission to be granted to other Turing folk (either by default or on request).

### Updates
2019-03-06: Turing IT have proposed a trial process for creating Service Principal that involves submitting a ticket on our help desk software. It doesn’t really match how we want to use Service Principals via the Azure CLI, so @martintoreilly has suggested some changes. Whether we get these or not, @sgibson91 and / or @martintoreilly will submit a request on whatever version of the form is in place on Thu 07 March..

**Comment by sgibson91** [comment]
I met with Turing IT today and they were happy to provide a Service Principal that never expires for a BinderHub deployment. I made it clear that this Service Principal is only required once to deploy the BinderHub and users would not have access. The Service Principal has now been activated on a separate subscription with a preliminary $1000 budget - I thought this would be best as this would give IT control over the budget and can have it's own restrictions set. We can develop a billing/budgeting strategy as the BinderHub becomes more commonly used or we deploy more BinderHubs (e.g. using GPUs, or a public instance).

**Next steps:**
* IT cannot retrieve the appID and secret of the Service Principal after they've created it so we need a safe place/key vault to store it in case we wish to deploy another BinderHub in the same subscription - currently the info is in the TopDesk ticket
* Decide which VM to build the Turing BinderHub on!

**Comment by sgibson91** [comment]
Closing this as we now have a process by which to obtain a Service Principal and the permissions granted to it have been sufficient to deploy a BinderHub.
