### ISSUE TITLE
Decide which VM to host the Turing BinderHub on and it's node size

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#306]
### Summary

The Zero to BinderHub tutorial advises to deploy the Kubernetes cluster (on Azure) onto a `Standard_D2s_v3` VM with `--node-count 3`. See Step 6 [here](https://zero-to-jupyterhub.readthedocs.io/en/latest/microsoft/step-zero-azure.html).

What does this mean for the scaling/user experience of the BinderHub? Do we want a different VM and nose count?

### What needs to be done?

- [ ] Explore what consequences changing the VM and/or node count would have
- [ ] Scope potential of different VMs to deploy onto

### Who can help?

---

**Comment by alexmorley** [comment]
For the main Turing one you might want a few more nodes but the way I would go about it is to start small and then monitor resource usage. Once you get to >80% (RAM or CPU...) on all the nodes then you can add more. IIRC it's easy to add/remove nodes without any downtime.

**Comment by alexmorley** [comment]
In terms of the VM I would choose a VM that has 50% more RAM memory than the largest load that you reckon will be common. Again though, these things are hard to guess and it's probably easier to not think *that* hard and then set up load monitoring on Azure.

**Comment by sgibson91** [comment]
Yeah, I'm aware. I only used one node because (up until yesterday) I didn't have permissions to create a Service Principal in order to deploy a k8s cluster on the Turing Azure subscription. So my test deployment in running on a personal Free Trial subscription, but they limit you to only 1 node. That's why I have a note in the workshop that if they're not using a Free Trial subscription, to try and deploy with 3 nodes instead. Then we can have some fun!

Thanks for the advice though! 🙂

**Comment by sgibson91** [comment]
Thanks for the advice! I don't think many people will be using it to begin with so we can scale as we see fit.

(Sorry, realised my last comment was responding as if we were talking about the workshop still 🤦‍♀️)

**Comment by sgibson91** [comment]
Closing as Hub23 has been deployed onto 3 nodes, `Standard_D2s_v3` VM type.
