### ISSUE TITLE
Correct a broken link on the 'open scholarship' page

### ISSUE THREAD

**Issue by aleesteele** [alan-turing-institute/the-turing-way#3063]
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Book Dash in May 2023. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aldenc, @Arielle-Bennett, @AlexandraAAJ know on Zoom so that we can assist you.

## Summary
In the chapter for [open scholarship](https://the-turing-way.netlify.app/communication/open.html#cm-open-scholarship), the link citing 'open scholarship' is incorrect.

## Guide to Contribution 

1. Comment on this issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/reproducible-research/open/open-scholarship.md

3. Find line 4 to find the phrase `Open research and its subcomponents fit under the umbrella of a broader concept - open scholarship [{term}`def<Open Scholarship>`].`

4. Click 'Edit this file'. 

5. Delete the phrase `Open research and its subcomponents fit under the umbrella of a broader concept - open scholarship [{term}`def<Open Scholarship>`].` Change the phrase to `Open research and its subcomponents fit under the umbrella of a broader concept - open scholarship`, deleting the syntax at the end of the phrase.

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue.  

Example: `this pull request fixes #3063`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

**Comment by robbykha** [comment]
test

**Comment by aldenc** [comment]
@robbykha @mkhslaa
