### ISSUE TITLE
Create and send out March Newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#313]
### Summary

We're rolling along with all our lovely Turing Way, its nearly time for the March one to be sent out!

This issue is to capture the points we'd like to include in that update.

### What needs to be done?

- [ ] Please can we promote this survey for anyone who cares about how the research landscape might change over the next few years so that the assessment can be improved, Anyone can take part and the survey closes on April 1. https://www.smartsurvey.co.uk/s/nationalresearchsurvey
- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### Who can help?

* Tagging @pherterich as she's been pulling these together so far 😄 
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

**Comment by pherterich** [comment]
Other content:
- [ ] workshop reports including some of the lovely quotes we got
- [ ] another update on chapters and launching the book (+ how to contribute if we have a nice graph)
- [ ] plans for the 2 months extension

The Sheffield sprint could be a good opportunity to make a start and then we can send it out next week.

**Comment by pherterich** [comment]
Done :smile:
