### ISSUE TITLE
Note from London Workshop

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#316]
### Summary

These are some notes to capture feedback and suggestions from the London reproducibility workshop on 12 March.

### What needs to be done?

- [ ] Just capture what you liked and didn't like!

#### Kirstie's comments

* Logistics were great - thank you team!!
* @pherterich's talk was great - good stage setting
* I think my talk was better than in Manchester (see #258) but still not _great_. I don't really know how to best integrate docker without getting INTO what docker is!
* The [paired_examples](https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/boost-research-reproducibility-binder/paired_examples.md) excercise was WAY better! REALLY happy with that. Thank you @sgibson91 :sparkles: :muscle:
* I finished early...I'm not really sure why. I didn't feel like I was rushing but I'm happy to hear feedback if I went too quicky for any part!
* I think the zero to binder was great (again) and I got the vibe in the room that folks were finding the information useful for their own work.
* I _personally_ liked that we "officially" ended a little early and some folks left. I think that's better than people floating out and not really having a proper _close_. Happy to hear feedback if not.

Generally - great stuff team! :muscle: :rocket: :star2:

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by pherterich** [comment]
Linking this to #536 and #537 as I think the feedback should go into the submissions and we can close these older issues then. Any other points where this feedback is relevant are welcome as links!
