### ISSUE TITLE
Find a place to promote Binder browser add-on

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#318]
### Summary

Our Binder friends have created an add-on for Firefox (https://addons.mozilla.org/en-US/firefox/addon/open-with-binder/) and Chrome (https://chrome.google.com/webstore/detail/open-with-binder/napgohblobncpnagnehjpooinnimhpkc?hl=en) which we should promote in the Turing Way.

### What needs to be done?

Find a good place to include it - could be a nice thing for the check list

### Who can help?

@annakrystalli and @KirstieJane as the ones in charge of checklists (I think) - everyone with ideas on where else to promote it.

**Comment by pherterich** [comment]
Probably links to #450

**Comment by harisood** [comment]
Hello from September 2022 @pherterich! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by pherterich** [comment]
Thanks @harisood - this can be closed as it's linked to an issue and the links can still be picked up if anyone wants to tackle this.
