### ISSUE TITLE
[BUG] yamllint doesn't run on PRs

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#3180]
Hi folks (especially @sgibson91 since she implemented it!), 

Just wondering if there's a logic as to why `yamllint` [only runs on pushes](https://github.com/alan-turing-institute/the-turing-way/blob/main/.github/workflows/yamllint.yaml#L3-L7), whereas [other actions run on PRs to main](https://github.com/alan-turing-institute/the-turing-way/blob/main/.github/workflows/lorem-ipsums.yml#L8-L18) as well?

It means we end up with follow-up PRs like these:
- https://github.com/alan-turing-institute/the-turing-way/pull/3179
- https://github.com/alan-turing-institute/the-turing-way/pull/3162

**Comment by sgibson91** [comment]
I commented on the linked PR! I can't remember my reasoning exactly but it's probably along the lines of "yaml formatting is weird and probably many people, especially those new to GitHub, may not know how to resolve the failed test"

**Comment by da5nsy** [comment]
Fair! I think that since failing CI doesn't actually block merging currently it's reasonable to put it in and then folks can just ignore that test if they're desperate to merge.
For me it just means that we have a chance to see it failing earlier and sneak in and fix it before the original PR is merged rather than having to go in afterwards and do a follow up PR

**Comment by sgibson91** [comment]
Yeah, I'm happy with the PR, it is not a strong opinion from me :)
