### ISSUE TITLE
Incorrect/unitended link on `/afterword/contributors-record.html`?

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#3219]
![a screenshot showing the section of text which I think is showing the wrong link](https://github.com/alan-turing-institute/the-turing-way/assets/3739866/f384aa3d-e138-4dc7-81e2-48ee48427b2b)

https://github.com/alan-turing-institute/the-turing-way/contributors.md (which redirects to https://github.com/alan-turing-institute/the-turing-way/graphs/contributors)
vs.
https://github.com/alan-turing-institute/the-turing-way/blob/main/contributors.md 

---

Tagging you @JimMadge because:
- Is this intentional or no?
- If no, do we actually _also_ want a link to `the-turing-way/graphs/contributors`?
- Does the same issue exist in https://the-turing-way.netlify.app/community-handbook/infrastructure/infrastructure-contributors.html

**Comment by da5nsy** [comment]
Nice. I was just testing you alt-text bot! 🤦 
Thank you for letting me know, I'll fix that right now! 😘

**Comment by JimMadge** [comment]
I don't think I wrote that but it does seem to me that it is pointing to the wrong place.

(It seems like https://github.com/<org>/<repo>/contributors.* redirects to the contributors graph).

**Comment by da5nsy** [comment]
Closed by #3221

**Comment by da5nsy** [comment]
> I don't think I wrote that but it does seem to me that it is pointing to the wrong place.

Ooh yeah you're totally right! This was a sleeper that'd been in there for years! (Since https://github.com/alan-turing-institute/the-turing-way/commit/059c258ffd18ae0f817b170a8ba6cd00251b8e1f)
_Though_, it does seem plausible that it may have been correctly directed at some point, and that that direction has just stopped working at some point in the intervening time.
