### ISSUE TITLE
Update Turing webpage

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/the-turing-way#322]
### Summary

Update [our page](https://www.turing.ac.uk/research/research-projects/turing-way-handbook-reproducible-data-science) on the Turing website.

### What needs to be done?

- [x] Add newsletter links to the "Recent updates" section
- [x] Add link to Becky's blog post to the "Recent updates" section
- [x] Shorten the workshop descriptions now that the workshops have taken place (_to be done after the Sheffield workshop_)
- [x] Add information about book dashes
- [x] Add @rainsworth to the list of researchers

### Who can help?

I should be able to make the changes to the website, but if anyone else wants to suggest other things to include, please add them to the list above.

---

### Updates

**Comment by KirstieJane** [comment]
Fantastic @LouiseABowler!

It would be great to add a link to @r-j-arnold's blog too 😄

**Comment by r-j-arnold** [comment]
Link to said blog: https://software.ac.uk/blog/2019-03-05-turing-way-open-source-resource-promoting-best-practice-reproducible-research

**Comment by LouiseABowler** [comment]
All done. I've now got edit rights on the website, so do let me know if there are any announcements/updates you'd like to see on the page.
