### ISSUE TITLE
How to retire Azure Group/Cluster

### ISSUE THREAD

**Issue by rgaiacs** [alan-turing-institute/the-turing-way#335]
### Summary

What users should do when they decide to close the group/cluster?

### What needs to be done?

Add instructions to https://github.com/alan-turing-institute/the-turing-way/blob/SG/binderhub-workshop/workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md

### Who can help?

- Tania

**Comment by arm61** [comment]
Are those not covered in https://github.com/alan-turing-institute/the-turing-way/blob/SG/binderhub-workshop/workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md#tearing-down-your-binderhub-deployment ?

**Comment by rgaiacs** [comment]
@arm61 Thanks for point me to it. Yes, it is covered. Can I keep this open to send a pull request during Collaborations Workshop adding a note on the begin? Cheers.

**Comment by sgibson91** [comment]
I've added a Table of Contents in PR #412 so future users should be aware that the resource for retiring the BinderHub and cluster are there.
