### ISSUE TITLE
Are SSH keys necessary for builda-binderhub?

### ISSUE THREAD

**Issue by drj11** [alan-turing-institute/the-turing-way#339]
### Summary

In the [zero to binder hub tutorial](https://github.com/alan-turing-institute/the-turing-way/blob/SG/binderhub-workshop/workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md) there are instructions to [create an SSH key](https://github.com/alan-turing-institute/the-turing-way/blob/SG/binderhub-workshop/workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md#5-create-an-ssh-key) and [create the `aks` service with that key](https://github.com/alan-turing-institute/the-turing-way/blob/SG/binderhub-workshop/workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md#6-create-an-azure-container-service-aks-cluster).

I've read around a bit, and I don't think this step is necessary (for building a binderhub in the context of this workshop).
The SSH key is used to [SSH into the AKS cluster nodes](https://docs.microsoft.com/en-us/azure/aks/ssh);
we never did that, and probably wouldn't have had time to demonstrate it or explain why that was useful.
Even if it is later useful, it turns out that [you can add your SSH key after the fact](https://docs.microsoft.com/en-us/azure/aks/ssh#add-your-public-ssh-key).

### What needs to be done?

That means we can:

- delete the create an SSH key step; and,
- use the `--no-ssh-key` option to `az aks create` to avoid using SSH keys.

This makes the instructions slightly simpler and results in less secret material lying around.

### Who can help?

@sgibson91 @arm61

### Updates

[none yet]

**Comment by sgibson91** [comment]
Thank you @drj11 This is really useful to know!

**Comment by sgibson91** [comment]
I'm going to say the answer to this question "Are SSH keys necessary for Build-a-BinderHub?" is "No, but they can be useful for logging into/debugging the Kubernetes cluster if something goes really wrong". 🙂
