### ISSUE TITLE
Issue template for a project spanning multiple repos

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#340]
### Summary

We are discussing splitting The Turing Way repo into smaller repos relating to the handbook, the Zero to Binder workshop, and the Zero to BinderHub workshop. This raises some concerns about where contributors/users would raise issues. The Binder team have an issue template asking contributors to consider exactly where their issues needs to be raised, copied below:

>Welcome!
>Help us stay on top of issues by submitting them to the right repository. For
issues related to:
>* ... "my repository isn't building properly": https://github.com/jupyterhub/binder/issues/new
>* ... https://mybinder.org site downtime or inaccessible pages: https://github.com/jupyterhub/mybinder.org-deploy/issues/new
>* ... the software powering all this (binderhub) in general: https://github.com/jupyterhub/binderhub/issues/new
>If you aren't sure where to go use https://github.com/jupyterhub/binder/issues/new.
>Thank you for being awesome!

We could modify this template to be something like:

>Welcome!
>Help us stay on top of issues by submitting them to the right repository. For
issues related to:
>* ... The Turing Way Handbook: [link to repo /issues/new]
>* ... the Zero to Binder workshop: [link to repo /issues/new]
>* ... the Zero to BinderHub workshop: [link to repo /issues/new]
>If you aren't sure where to go use https://github.com/alan-turing-institute/the-turing-way/issues/new.
>Thank you for being awesome!

### What needs to be done?

- [ ] Decide if we want to split the repo into smaller, specialist repos
- [ ] Implement a new issue template including something like the above

### Who can help?

---

**Comment by KirstieJane** [comment]
I love this 😍

**Comment by sgibson91** [comment]
Closing this since we archived the-turing-way-book repo.
