### ISSUE TITLE
Coordinate May Book Dashes

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#341]
### Summary

I'd really like to run two Turing Way "book dash"es in May.

### What needs to be done?

- [x] Set some dates: 
  * University of Manchester: 16th & 17th May
  * Alan Turing Institute, London: 27th & 28th May
- [x] Set two locations for the events
  * London and Manchester seem like the easiest to host at?
- [x] Make an agenda for the event (See below)
- [x] Figure out a selection process. Who do we want to attend? How will we select for those people? (See discussion below)
- [x] Set the timeline
  * Open applications at the Collaborations Workshop Monday 1 April
  * Close at 11:59pm on 18 April
  * Selection process, communicated by Friday 26 April, invited folks fill in Eventbrite form
  * Deadline for eventbrite confirmations on Sunday 28 April (11:59pm)
- [x] Promote the application
  * Be clear about what folks get through attending, and why they would want to come :heart:
- [x] Prepare eventbrite registrations and additional communications

### Suggested Agenda

| Day | Time | Activity |
| ---- | ----- | -------- |
| Day 1 | 6:30pm | Arrive at dinner venue :wave: |
|           | 7:00pm | Dinner :yum: |
|           | 8:30pm | Lightning talks :zap: |
|           | 9:00pm | Drinks and networking 🥤:cocktail::beers: |
|           | 10:30pm | Go home (get some sleep :sleeping:) | 
| Day 2 | 8:30am | Arrive at dashing venue :wave: |
|           | 9:00am | Intro to the book dash :books::dash: |
|           | 9:30am | Team forming and brain storming 🧠 | 
|           | 10:30am | Coffee break :coffee: |
|           | 11:00am | Group working 👨🏾‍💻👩🏼‍💻 |
|           | 12:30pm | Lunch :yum: |
|           | 1:30pm | Group working, coffee available at 3pm 👨🏾‍💻👩🏼‍💻 |
|           | 4:00pm | Celebrate successes (group share outs) :raised_hands: |
|           | 5:00pm | Close :wave: |

### Selection process

This is hard!

We're looking for people who have expertise that the Turing Way can benefit from. This includes, but is not limited to:

* sci comm skills: skills in writing, editing and/or exciting interactive communications
* great examples and case studies of reproducible research 
* writing new chapters (either from the wish list or beyond)
* editing the current chapters
* updating how the book looks online (css, logos, layout etc)

Two questions that could work are:

1. What could you contribute to the Turing Way community
2. What would you gain from being part of the Turing Way book dash

I think we'd also need to know:

* gender
* career stage (participation not limited to academic positions)
* ethnicity

### Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates
* we will send out the announcement on the newsletter tomorrow
* applications will close on 18 April
* we will let people know by 26 April the latest

### Lessons learned [@pherterich 17/04/2019]
The application form should have asked for: email address, name, location of attendee (where they would need travel from), a question what people would need funds for (child care, accommodation, travel) to help us cost things. I think we thought we's ask for all the detail after inviting people - turns out it would be really helpful to know at point of selection. I guess some clear criteria for selection at the same time as we put the application form together would have been good.
*Don't rush this while you're at a super interesting and intense conference.*

**Comment by pherterich** [comment]
Can't make the 15th, 23rd isn't great either - all other dates should work for me.

**Comment by rosiehigman** [comment]
At the moment all of those work for me

**Comment by rosiehigman** [comment]
Just catching up on this and it looks awesome! A couple of minor suggestions:
* Could we change career stage to role/position to make it more inclusive of non-academic positions? Alternatively we will need to phrase the options quite carefully to avoid excluding people, probably also be explicit that we are asking to ensure diversity and not to exclude a particular group
* Under scicomm skills could we also include something around flow/overall structure of the book as working out the pathways for different groups and making these coherent is potentially a nice chunk of work someone could address.

**Comment by KirstieJane** [comment]
💯💯 it isn’t clear from the issue that I got distracted half way through and didn’t finish that list. Great suggestions!!

**Comment by rainsworth** [comment]
I can do Thurs 16, Fri 17, Thurs 23, Fri 24, Tue 28, Wed 29!

**Comment by pherterich** [comment]
Cool, that should give us some options! My meeting on the 23 is morning only, so I could be in any location in time for day 1 action.

**Comment by rainsworth** [comment]
Brilliant, should we aim for 
* London: Thurs 16/Fri 17
* Manchester: Thurs 23/Fri 24

(or vice versa) so that there is time after the book dashes to reflect and incorporate before the current funding period ends?

**Comment by pherterich** [comment]
Sounds great to me. Can you check room availability for Manchester @rainsworth and @KirstieJane or maybe @LouiseABowler can check availability at the Turing or suggest other locations in London?

**Comment by LouiseABowler** [comment]
I've had a look for rooms at the Turing for the dates @rainsworth suggested above. Our largest seminar room has something in the calendar on all four dates so I don't think we'll be able to get that space, but would that room be too large for us anyway? Do we have an estimate for how many people we want for each event?

The Lovelace suite (where we held the Binder workshop) might be available on the 16th and 23rd if we can persuade people to move seminars to alternative locations, and Mary Shelley (the room on the second floor where we had some of our sprint meetings) is free on all four dates. We can combine Mary Shelley with the small adjoining room if we need something slightly larger.

**Comment by rainsworth** [comment]
I've booked the room that we had for the Manchester Binder workshop for both May 17 and 24, so let me know if one date works better for London!

@LouiseABowler we'll need the rooms for the 17th and 24th, as the 16th and 23rd will just be for dinner :) is anything available those days?

**Comment by rosiehigman** [comment]
I think we were looking at 10-15 people and the core team (I guess 5 of us?), so 20 max, does that help @LouiseABowler?

**Comment by LouiseABowler** [comment]
I was wondering whether you'd meant those dates as all options or whether they were dinner+dash - at least this way narrows down the dates more :)

We can definitely get the rooms on the second floor (Mary Shelley and Isaac Asimov) on either Friday, but I don't know if they're big enough for the event. Those two rooms are good in that you can split or combine them as you want, but I'd think they'd feel crowded if you had 15+ people in them - which is pretty much how many we'd need (thanks @rosiehigman!). I'll go up there and count chairs :)

**Comment by LouiseABowler** [comment]
I think we are going to need one of the larger rooms - the second floor rooms only have 14 chairs, and any more would be too cosy for a whole day.

The 17th and 24th aren't looking great for rooms here - there are workshops happening on both days which mean we won't be able to get the Lovelace suite, and our largest room already has some internal events in the calendar. The reception team aren't in at the moment, but I'll go ask on Monday morning to double-check.

**Comment by pherterich** [comment]
Birmingham doesn't have super pretty rooms available, but there are options for both dates just in case.

**Comment by LouiseABowler** [comment]
That's good to know @pherterich, thanks for checking! I went over to reception and it initially looked like there wouldn't be availability at the Turing for any of the possible dates, but the events team are taking a closer look at the calendar for us.

I've asked about all five of the dates from the summary (Thurs 16, Fri 17, Fri 24, Tue 28 and Wed 29), but I'll check in here again before confirming anything as it looks like the Friday dates would be preferable. I'll be away from the 25th May which is inconvenient for the last two dates, but having the event here at the Turing should still be fine as @KirstieJane will be around.

**Comment by pherterich** [comment]
First crappy draft for an application form is available at : https://docs.google.com/forms/d/e/1FAIpQLSd-HTay3kRowSAPIqslSIeDXpvFWptOjmO9m1uEcUf0YElcqw/viewform 
Comments please here or sit with me for a bit at CollabW on Monday to finish this up ready to promote on Tuesday!

**Comment by LouiseABowler** [comment]
We now have a room booked at the Turing! We've got the Lovelace suite on Tuesday 28th May - a slightly later date that we'd like, but that room gives us plenty of space and it looks like everyone apart from me will be able to make the date.

**Comment by KirstieJane** [comment]
Hey folks! That room at the Turing is the day after a bank holiday - which is not a great day to have folks come down and go out for drinks the night before 😞 

What about 2 May? Can anyone make that date?

**Comment by rainsworth** [comment]
I cannot :(

**Comment by KirstieJane** [comment]
Ok - never mind - lets just stick with the date that @LouiseABowler found (28 May) and we'll be more flexible for the evening before 😄

**Comment by KirstieJane** [comment]
Hey folks! What do you think - 17 or 24 for the Manchester event? I think I'd prefer 17 because 24 and then 28 is very close together and quite overwhelming....but happy to go with either!

**Comment by rainsworth** [comment]
I am happy with either the 17th or 24th!

**Comment by KirstieJane** [comment]
@biostew - if you have any links at the BL please let us know!

**Comment by Biostew** [comment]
Hi Everyone - There is a possibility that I can book the Foyle suite, for the 28th, which is a large room seating up to 35 people, if this would be helpful? Please let me know whether this might work, as rooms at the BL are surprisingly in short supply!

**Comment by pherterich** [comment]
Adding this here as a potentially useful resource after I closed the old issue this was in ( #9 )  https://blogs.tib.eu/wp/tib/2018/11/13/how-to-book-sprint-in-sixteen-steps/

**Comment by pherterich** [comment]
Are we okay to close this? I think this is all sorted or picked up in other issues.

**Comment by rainsworth** [comment]
@pherterich This looks good to close to me.
