### ISSUE TITLE
Solo learning version of Zero-to-BinderHub workshop and Instructor Guidelines

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#343]
### Summary

Create a version of the Zero-to-BinderHub workshop for solo learners with screen-capture resources. https://asciinema.org/

Create instructor guidelines for others who wish to run a Build A BinderHub workshop.

### What needs to be done?

- [ ] Create `zero-to-binderhub-solo.md`
- [ ] Create `instructor-guidelines_zero-to-binderhub.md`

### Who can help?

---

**Comment by KirstieJane** [comment]
I love the idea of these @sgibson91.

What's the difference between instructor guidelines and solo learning?

If they serve the same purpose then can we call them the same thing?

**Comment by sgibson91** [comment]
So, what I call "solo learning" is just one person sitting down and going through the document that is even more in-depth than the original one with screenshots and stuff. The instructor guidelines for me were more like, here's how we ran this and what you'll need to ask your attendees to prepare but feel free to do it differently if you'd like.

**Comment by KirstieJane** [comment]
Gotcha. Thanks @sgibson91 - suuuper useful resource.

So I suppose a next question is: do we want to make a solo learning version of the BinderHub workshop and a instructor guide for the boost your research workshop?

I feel like the latter might be nice and easy? Do you think a solo learning version of the BinderHub workshop would work?

**Comment by sgibson91** [comment]
I'm still meditating on what needs to be different for a solo BinderHub doc, probably not much more than what we have now. But I think an instructor guide for the BinderHub stuff is possibly even more critical given how technical and unpredictable it can be. A resource for Windows users is desperately needed.

**Comment by KirstieJane** [comment]
Cool! Definitely sounds like the right priorities ✅✅

**Comment by dingaaling** [comment]
Hello from October 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
