### ISSUE TITLE
Amount of original research?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/the-turing-way#345]
### Summary

Another thing I've noticed while reading the current chapters: much seems derived from the cited references, but I've started to wonder how much of what is written is genuinely original research. 
(this is assuming that we all agree with the obvious, namely that research about research is research)

In case the work includes original research: should that maybe made explicit, i.e., what the novelties are, what prior ideas this is dependent on, etc, as you would do in any academic manuscript?

There is at least the novelty that content is presented in a novel form - which even in the case that this is all there is, would be a statement to make.

It wouldn't have to interrupt the reading flow, since it can be done, for example, directly preceding the list of references, in small-script, say.

### What needs to be done?

Probably you've already thought about this.
But generally, thou shalt give all ideas due credit (for yourself, and for others).

### Who can help?

This is for discussion.

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by KirstieJane** [comment]
Thanks @fkiraly - we discussed this in the team sprint yesterday in Sheffield and built a release plan for a collection on Zenodo that will give the different chapters citable and versionable DOIs.

Sorry I'm on my phone and don't have time to write up the details - as yesterday I'm still zooming around a bunch of meetings & events - but yes: making sure we both a) cite the references that we've reused (yay open licences) and b) make ourselves citable is important.

We're aiming for a first release at the Collaborations Workshop on 1 April so definitely will have the (first version of the) plan implemented by then :rocket:

**Comment by harisood** [comment]
Hello from autumn 2022 @fkiraly!  Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
