### ISSUE TITLE
Plan next sprint in London

### ISSUE THREAD

**Issue by alexmorley** [alan-turing-institute/the-turing-way#35]
- [x] Complete doodle poll by Wed 5 Dec

Decision made: ~24 & 25~ **15 & 16 January**.

(Updated on 12 Dec because @KirstieJane realised *she* wasn't available on 24 Jan 🤦‍♀️)

- [x] Book a room
* 15: 9 - 13: David Blackwell (1st floor) then 14 -17: Turingery (4th floor)
* 16: 9 - 17: Mary Shelly (2nd floor)
- [x] Let reception know who's coming

DONE!

- [x] Book travel
- [x] Create agenda
  * @rosiehigman can only make the 15th - so lets make this day mostly focused on workshops, communications around building the community of contributors, and data management
  * @annakrystalli can only make the 16th - so lets make this day more focused on binder and software

**Comment by KirstieJane** [comment]
Agenda:

**Tue 15**

| Time | Plan | 
| ---- | ----- |
| 9:00 | arrive and grab coffee | 
| 9:30 | Project triage, review and community engagement planning |
| 12:30 | Lunch |
| 14:00 | Workshop planning |
| 16:00 | Set up pizza party |
| 16:30 | Pizza party |
|18:00 | End |

**Wed 16**

| Time | Plan | 
| ---- | ----- |
| 9:00 | arrive and grab coffee | 
| 9:30 | Continuous integration: discussion and planning |
| 12:30 | Lunch |
| 14:00 | Binderhub: intro and demo |
| 17:00 | End |

**Comment by pherterich** [comment]
Closing this and opening a new issue to plan the Feb meeting
