### ISSUE TITLE
Add continuous integration test to this repository to prevent large files from being added

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#351]
### Summary

We've just re-written history (#350) because our git repository was getting really big! 

It would be great if we could have travis test to see if there are any files larger than 5 MB in a pull request and have the tests fail if there are. (@KirstieJane can always use her master administrator powers to merge them in if they're really necessary).

### What needs to be done?

- [ ] Set up CI for this repository
- [ ] Write a test for file size in the PR. Fail if there is a file larger than 5 MB.

### Who can help?

* Anyone!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by A-Fisk** [comment]
This sounds interesting and I'm keen to help! First issue so help would be super useful. 

Main questions. 
1. Best way to write tests? 
I've played about with writing some test in one of my python repos with a defined environment file and then created the environment on travis using that and run the tests in python. 
Would that work for this or am I missing a simpler way to do this? 

2. Not sure how to look at the file size in the PR. 
I'm thinking of recursively globbing all files in the repo then sorting them by size, then throw an exception/error if the top value is >5mb. Does this sound like it would work? 

I hope that makes sense!

**Comment by KirstieJane** [comment]
Hi @A-Fisk! Thank you for swinging by!!

I'm in meetings for the next few hours, so not super helpful in the near future. But feel free to ask questions as you go and the team will help out as best we can.

As a starter for 10 I think your suggestions sound great! 🚀

**Comment by annakrystalli** [comment]
Hello @A-Fisk! Many apologies but we started work on solving this already! Sorry I only just saw your message. The current solution we've developed is in [this branch](https://github.com/annakrystalli/the-turing-way/tree/filesize-test) if you want to have a look? These files especially:

- [`test bash script`](https://github.com/annakrystalli/the-turing-way/blob/filesize-test/scripts/test-file-size.sh)
- [`.travis.yml`](https://github.com/annakrystalli/the-turing-way/blob/filesize-test/.travis.yml)

Test is queued on Travis atm (seems super busy). Please feel free to add any feedback/further suggestions!

**Comment by KirstieJane** [comment]
Really sorry for causing a mix up here @annakrystalli and @A-Fisk - we’d talked about this task but there wasn’t an issue. I didn’t realise Anna had already started on it 😭 Sorry for making things confusing with my enthusiastic tweeting.

Stay tuned @A-Fisk! I’m sure there will be more fun issues soon 💖

**Comment by alexmorley** [comment]
Hey @A-Fisk (or anyone else) if you can work out what's going on it'd be super useful to add something to the contributing file that notes that large files shouldn't be added (and how to add them if you really need to). https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md

**Comment by A-Fisk** [comment]
No problems, I always appreciated some enthusiastic tweeting, and I'm glad you got something together for it! Good idea @alexmorley I'll have a look at the contribution file and see if I can put something in there.
