### ISSUE TITLE
Include an opinionated discussion on pinning dependencies

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#352]
### Summary

Pinning dependencies is a place that gets us into some stronger opinions than The Turing Way is planning to address.....but we can easily have some interesting interviews in the book with folks arguing both sides of an issue 😄 

There's a discussion happening with @betatim and @choldgraf at https://github.com/jupyterhub/binder/issues/161 so we should figure out what we want to write there, and then incorporate it into the Turing Way Book after that 🚀 

### What needs to be done?

- [ ] Figure out what we (Binder, Turing Way) want to recommend regarding pinning dependencies
- [ ] Draft up a little guide that explains the justification of the recommendations
- [ ] Write up as a conversation w @betatim & @choldgraf (or others if that makes more sense)

### Who can help?

* Anyone! Particularly people w opinions about pinning dependencies 😉 

---

### Updates

* Nice (pseudo)quote from @minrk: Need to choose between a "reproducible environment" and a "living environment" (paraphrased from a conversation in gitter)

**Comment by drj11** [comment]
The spaCy 2.1 blog has, in its second half, a lovely summary of their internal struggle with this. I tweeted it earlier: https://explosion.ai/blog/spacy-v2-1

**Comment by harisood** [comment]
Hello from autumn 2022 @KirstieJane! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
