### ISSUE TITLE
Upgrade Rachael's permission

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#355]
### Summary

@rainsworth doesn't have write access to the repo yet, @KirstieJane could you fix that for her?

### What needs to be done?

- [ ] @KirstieJane to get @rainsworth all the permissions needed
- [ ] following #353 add @rainsworth also to the contributors via #274

### Who can help?

I think only @KirstieJane has master rights

**Comment by KirstieJane** [comment]
Invite sent! Feel free to close this issue once you have access @rainsworth!

**Comment by rainsworth** [comment]
Thank you @KirstieJane & @pherterich!
