### ISSUE TITLE
Broken links to figures in the-turing-way-book 

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#370]
### Summary

In transfering over some of the chapers, the folder structure was re-ordered and now links to figures don't work terribly well.

### What needs to be done?

- [ ] Find the broken figures.....
- [ ] .....and fix them!

### Who can help?

* @longr is going to have a bash at this during the CollabW19 hackday 🚀 

---

### Updates

- [ ] The figure in the [the turing way definition of reproducibility](https://the-turing-way.netlify.com/reproducibility/reproducibility.html#the-turing-way-definition-of-reproducibility) section is broken.
  * Note (from @KirstieJane) that this figure should actually be updated too - it should say "analysis" rather than "code" on the Y axis.

**Comment by longr** [comment]
Fixed in PR: https://github.com/alan-turing-institute/the-turing-way-book/pull/10

**Comment by KirstieJane** [comment]
Fantastic!! Way to go! 💪
