### ISSUE TITLE
Testing vs review

### ISSUE THREAD

**Issue by SiccarPoint** [alan-turing-institute/the-turing-way#372]
### Summary

I'm taking a look at the testing section. For me, review practices (https://the-turing-way.netlify.com/testing/testing.html#code-review) are a distinct issue from testing. At the same time, I think the book could make significantly more of them.

### What needs to be done?

I would propose:
- [ ] Remove the Code Review subsection entirely from under the Testing section.
- [ ] Create new, expanded text to talk a bit more about reviewing.
- [ ] Put this text in... somewhere else? IMO this could stand as a high level (but nonetheless, short?) section in its own right.

### Who can help?

* SiccarPoint (Dan) will attack (1) and (2) as part of our code dash at the SSI collaborations workshop, 3/4/19.
* SiccarPoint will boldly add a new section for this.
* Someone else will need to expand and review the - likely quite slapdash - new material.
* Someone with a bit more oversight on the project as a whole will likely need to restructure!

---

**Comment by illushka** [comment]
Quick background: I spoke to Kirstie on how I think code reviews are super helpful and it is sometimes the one thing that stops me from sharing code, the fear of releasing bad code that hasn't been looked over by anyone else. 

She mentioned this section is being written. I reviewed the new review section and it is great! I think it might be helpful to add just a few notes on how to avoid code reviews becoming too subjective as this is where conflicts are likely to arise which stops people from asking for code reviews (something I noticed in the commercial world but I bet it happens in academia too). And this can potentially create a bias where only confident coders share their code. Am I okay to fork off and add to the chapter?

**Comment by SiccarPoint** [comment]
This sounds like an awesome plan! Have at it!

**Comment by SiccarPoint** [comment]
From my perspective I think this is now 95% complete, content-wise. However, I've really been struggling to find appropriate open-license references for this material (so those sections remain lorem ipsum-ed). This might be a good time for a better established editor to step in, who knows where the good quality open resources for this kind of thing can be found...

This of course neglects current progress by @illushka ...

**Comment by rainsworth** [comment]
Hi @illushka - just want to let you know that we aim to incorporate the [book repo](https://github.com/alan-turing-institute/the-turing-way-book) back into this main repo (hopefully by Monday 🤞 ), so we have merged the Reviewing chapter into the book. Just want to give you the heads up and we will keep you up to date so as not to be too confusing 🙈 

Thanks both for your contributions!

**Comment by illushka** [comment]
Okay, I made a pull request too https://github.com/alan-turing-institute/the-turing-way-book/pull/27 which I hope was okay, but if you need me to change anything, let me know. Thanks.

**Comment by dingaaling** [comment]
Hello from October 2022 @illushka! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way - https://github.com/alan-turing-institute/the-turing-way/pull/449. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
