### ISSUE TITLE
scrolling "on this page" TOC netlify build

### ISSUE THREAD

**Issue by SiccarPoint** [alan-turing-institute/the-turing-way#373]
### Summary

In the rightmost "On this page" column, the ToC stretches below the bottom of the screen on my laptop. However, I don't appear to be able to scroll down to see the rest of this (super useful) content overview. Tested on Mac Safari (12.1) and Firefox (43.0.4).

### What needs to be done?

- [ ] Enable scrolling

### Who can help?

* Someone with knowledge of netlify.

---

**Comment by alexmorley** [comment]
Hey thanks for the feedback :tada:. I think this is more likely to be an issue with [jupyter-book](https://github.com/jupyter/jupyter-book) than on our end but I'll leave this open for now while we make sure.

**Comment by arm61** [comment]
I am also fairly sure this is a jupyter-book issue, as it stands the only thing that could be done would be to have less heading formatted items (or a pull request to jupyter-book with a fix)

**Comment by alexmorley** [comment]
> (or a pull request to jupyter-book with a fix)
@SiccarPoint if you could open an issue on their repo, ideally with a screenshot if you could get one, and tag me in it we'll see if we can get it fixed :) Should just be a couple of lines of css but ... things don't always work like I think they should.

**Comment by SiccarPoint** [comment]
OK, this is now jupiter book issue [173](https://github.com/jupyter/jupyter-book/issues/173).

**Comment by KirstieJane** [comment]
Wonderful! Glad we can contribute back 🌺🌸🙌🚀

**Comment by inwaves** [comment]
Looks like this is resolved in [Jupyter-book's #176](https://github.com/executablebooks/jupyter-book/pull/176)

**Comment by KirstieJane** [comment]
Reopening just incase we haven't updated to the latest version of jupyter book yet -
