### ISSUE TITLE
Render images in GitHub and JupyterBook

### ISSUE THREAD

**Issue by longr** [alan-turing-institute/the-turing-way#375]
### Summary

Images can either be rendered in Github, and be a broken link in JupyterBook, or be a broken link in GitHub and work in JupyterBook.  For the image to display in the JupyerBook, the link need to be of the form:

```
![Kirstie's definition of reproducible research](/assets/figures/reproducibility/ReproducibleMatrix.jpg)
```

For this to render in Github it would need to be

```
![Kirstie's definition of reproducible research](../../website/assets/figures/reproducibility/ReproducibleMatrix.jpg)
```

### What needs to be done?

I suspect there is a way to add or remove a prefix to image urls so that they work.  However it way be that the layout of the project needs changing.  I would not normally have put the images to be included in the book in website/assets.   I thought this is for static images unrelated to content of the book?

@alexmorley edit:
Explicitly I think the change we want here is:  
-  at the moment the figures are in book/website/assets/figures
- we should put them in book/content/chapter/... (the book folder is part of a soon-to-be-merged PR)

### Who can help?

@alexmorley  Do you have any thoughts on this?

---

**Comment by alexmorley** [comment]
Agreed. We should definitely move the images to the content directories.

The worst (but still viable) option is then that we just copy them over to assets using the `build` option in the Makefile. Better would be to use some config as part of jupyter-book (which probably exists but I haven't had time to check yet).

**Comment by longr** [comment]
Looking at the example book in https://github.com/jupyter/jupyter-book
They use relative links and have a directory call images in contents.  I suspect we could replicate this without an issue.

02/2/snow-s-grand-experiment.md:![Snow’s Other Map](../../../images/snow_map2.jpg)

**Comment by alexmorley** [comment]
Just copying in from @KirstieJane conversation on gitter:
Explicitly I think the change we want here is.
At the moment the figures are in `book/website/assets/figures` but in the future we should put them in `book/content/chapter/...` (the book folder is part of a soon-to-be-merged PR).

**Comment by dingaaling** [comment]
Hello from October 2022 @longr + @alexmorley! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
