### ISSUE TITLE
Left alignment of tables

### ISSUE THREAD

**Issue by longr** [alan-turing-institute/the-turing-way#376]
### Summary

Tables are right aligned by default.  This is not great for table layout.  This can be done in markdown on each table one by one, or I *believe* it can be done in the css by changing:

```
table td,
table th {
  padding: $spacing-unit-tiny $spacing-unit-small;
  border: 1px solid $color-dark-gray;
  text-align: right;
}
```
in
```
the-turing-way-book/website/_sass/elements/_elements.tables.scss
```

However, all figures are placed in tables, and right aligned captions are nicer.  This means that the captions will need to be overridden if the change is made.

### What needs to be done?

- [ ] * See if the fix to the css will correct the tables
- [ ] * Decided whether it is better to modify tables one-by-one or all in on go.

### Who can help?

@KirstieJane 
@alexmorley 

---

**Comment by dingaaling** [comment]
Hello from October 2022 @longr! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
