### ISSUE TITLE
Coordinate weekly meetings for April/May

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#387]
### Summary

The core team meet every Wednesday from 2pm to 4pm. This issue is to coordinate whether the meetings are via slack or zoom.

### Proposed schedule

| Date | Meeting type |
| ----- | ------------- |
| 10 Apr | Slack 💻 (no @KirstieJane, maybe no @rainsworth, no @rosiehigman before 15:00, no @LouiseABowler 14:40-15:10) |
| 17 Apr | Zoom 🚀 | 
| 24 Apr | Slack 💻 (no @rosiehigman)|
| 1 May | Zoom 🚀  (no @pherterich, no @rainsworth after 15:00)|
| 8 May | Slack 💻 (no @KirstieJane) |
| 15 May | Slack 💻 (maybe no @pherterich ) |
| 22 May | Slack 💻 (no @pherterich, no @sgibson91 ) |
| 29 May | Zoom 🚀 (no @LouiseABowler) |

### Who can help?

* Edit the table above if you are not able to join any of the meetings
* Request a change to the schedule if you'd prefer

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by pherterich** [comment]
Closing this as we have wrapped up on Wednesday :sob:
