### ISSUE TITLE
The Softer Challenges of Data Science in Practice

### ISSUE THREAD

**Issue by triangle-man** [alan-turing-institute/the-turing-way#391]
### Add a chapter on the problems of data science that aren't machine learning

There are many challenges in data science that aren't the "hard" problems of machine learning, but arise instead from people and their relationships (to each other and to their jobs). These can be just as hard to overcome -- and is some cases make or break the project -- as the challenges of model selection etc. 

For example:

- There is only on IT person with access to the data and everyone has to go through them.

- The "client" thinks that testing and evaluation (eg, by a randomised controlled trial) is unnecessary.

- The client has no good idea of how the result will be used in practice but wants to charge ahead anyway.

### What needs to be done?

- [ ] Decide whether this feature request should be a feature
- [ ] If so, start a new chapter?

### Who can help?

* James Geddes
* Anyone else who's ever done a data science project!

---

**Comment by harisood** [comment]
Hello from autumn 2022 @triangle-man! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
