### ISSUE TITLE
Bookdash comms

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#397]
### Summary

Separating this out so #341 doesn't go to bad

### What needs to be done?

- [x] 25/26 April - send out confirmation emails, @rosiehigman / @pherterich to draft something and do consistent spamming from the Turing inbox. To include:
* Confirmation of attendance, and if attending for both days
* Travel details and accommodation requests if we're booking these direct/info on getting reimbursed if not
* Dietary requirements
* Explaining process/when we will send out more info
- [x] early May - send out an email to prepare participants: providing info on lightning talks, motivating video from @KirstieJane if it's available, pointing to the collaborating on Github chapter, asking people to prepare their content and join in the Gitter channel etc. @pherterich / @rosiehigman / @rainsworth 
- [x] schedule call early May between @pherterich @rosiehigman @rainsworth maybe @KirstieJane to sort out content/facilitation on the day in more detail

**Comment by rosiehigman** [comment]
@pherterich I've done a bit of a brain dump above of what needs to go out in the email next week. I'm out of the office until Thursday so will need to do slightly last minute drafting but hopefully that helps us get started!

**Comment by pherterich** [comment]
Thank you @rosiehigman Officially out of the office till Thursday, too, but it's good to have a starting point on what needs doing when we're both back.

**Comment by rosiehigman** [comment]
@pherterich I've added a couple of extra things to the email to go out next week based on our meeting today, shout if you'd like a hand drafting etc 😃

**Comment by pherterich** [comment]
All pre book dash comms done, I will close this one as a good chance that we will create separate issues for any follow up comms tasks.
