### ISSUE TITLE
Bookdash Manchester - logistics

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#398]
### Summary

Date: 16 & 17 May 2019
Dash location: Bell-Burnell Lecture theatre, Schuster Annexe, University of Manchester, Upper Brook St, Manchester M13 0HR
Networking location: tbd

Turing Way facilitators: @rainsworth @rosiehigman @pherterich @KirstieJane 

### What needs to be done?

- [x] find suitable networking location
- [x] book catering for the day
- [x] book facilitator travel
- [x] book facilitator accommodation
- [x] book/re-imburse attendee travel
- [x] book/re-imburse attendee accommodation
- [x] any coordination with the sketch person?
- [x] follow up on catering fiasco

### Related issues
#341 Coordinate May Book Dashes
#397 Bookdash comms

**Comment by rosiehigman** [comment]
This list might help us get started on networking location: https://www.manchestereveningnews.co.uk/whats-on/food-drink-news/best-private-dining-rooms-manchester-11078780 - Jamie's Italian has a vegan/veggie menu so might be an easy option

**Comment by rainsworth** [comment]
My personal favourite is the Refuge which is halfway between campus and city centre, we could look into costs (hopefully lack thereof) and availability of their den? 

https://www.refugemcr.co.uk/spaces/

**Comment by rainsworth** [comment]
Catering has been ordered, Jamie's Italian has been reserved.

**Comment by KirstieJane** [comment]
Awesome! And I've had a zoom through all the travel and hotel requests and they should all be complete now 🚂 💨 💨 💨  🏨

**Comment by pherterich** [comment]
@rainsworth do you want a task to chase the catering people in here or are you happy to close this one and pick the other stuff up else where. Are there any leftover tasks from last week that I'm missing?

**Comment by rainsworth** [comment]
Oh gosh, I'll add it because I keep getting distracted. I'll email now, tick it off and close it. Thanks for the reminder!

**Comment by rainsworth** [comment]
ok, email sent and closing this issue.
