### ISSUE TITLE
Bookdash London - logistics

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#399]
# Summary
Date: 27 & 28 May 2019
Dash location: Turing Institute, Lovelace suite
Networking location: tbd

Turing Way facilitators: @rainsworth @rosiehigman @pherterich @KirstieJane @alexmorley 

## What needs to be done?
- [x] find suitable networking location
- [x] book catering for the day (with help from @LouiseABowler ?)
- [x] book facilitator travel
- [x] book facilitator accommodation
- [x] book/re-imburse attendee travel
- [x] book/re-imburse attendee accommodation
- [x] any coordination with the sketch person?

### Related issues
#341 Coordinate May Book Dashes
#397 Bookdash comms

**Comment by pherterich** [comment]
London Pint of Science locations: https://pintofscience.co.uk/events/london

**Comment by LouiseABowler** [comment]
Yep, I can help out with the catering order at the Turing again. The catering company need to have the order two weeks beforehand, so shall we aim to decide what we need in our meeting on 8th May?

**Comment by pherterich** [comment]
That should be fine @LouiseABowler - we'll try to get comms right which hopefully means we get answers from attendees soon and can finalize everything by 8th May.

**Comment by pherterich** [comment]
As we will start super early, we might need to ask people to come in via staff entrance, so instructions for that will be needed.

**Comment by LouiseABowler** [comment]
Catering order and request for passes to the BL sent! I can write up some instructions for getting into the staff entrance - where would be a useful place to put them @pherterich? Do you have a document for pre-dash emails?

**Comment by pherterich** [comment]
Thanks @LouiseABowler - I would copy instructions across from here https://whitakerlab.github.io/visit/ - if you think anything else needs adding, there's no dash comms document yet, so feel free to start one and I build the rest around it later.

**Comment by LouiseABowler** [comment]
The instructions on Kirstie's page look good to me! There's one difference from those instructions - reception have asked for one person from our team (they'd like to know who, but we can sort that out later) to be downstairs to check people off the list and bring them up to the Institute. I think there are too many people coming for the staff downstairs to bring them all up to the Turing entrance.

**Comment by pherterich** [comment]
That makes sense @LouiseABowler - I'll add something in to cover that.

**Comment by KirstieJane** [comment]
Hey folks! The set menu for the dinner and networking venue (https://www.themegaro.co.uk) is attached to this comment. @pherterich - are you able to send out a request for selections. We aren't going to make everyone eat the same (what a ridiculous idea) so the £5 is entirely authorised from me!

They've also been rather confusing about the folks with dietary requirements. I _think_ that they'll offer some other options if these don't work. There are vegan and GF options on the menus, but I'm happy to get them to provide more than 1 option for each.

Deadline for reply to the venue: Tuesday 21 🤦‍♀ 

[SET MENU (1).pdf](https://github.com/alan-turing-institute/the-turing-way/files/3187847/SET.MENU.1.pdf)

**Comment by rainsworth** [comment]
I've made a HackMD: http://bit.ly/book-dash-ldn

Potential feedback form and Pluses and Deltas templates ready for review in #528
