### ISSUE TITLE
Case Studies require more resources than mybinder.org permits

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#401]
### Summary

Preparing the following repo for Binder: https://github.com/kochkinaelena/branchLSTM

The data requires 3 data sets to be downloaded (one of which is 1.5 GB) then, during `preprocessing.py`, a model is downloaded which means we very quickly run out of the 2 GB allocation that mybinder.org provides.

### What needs to be done?

- [x] Build a BinderHub for hosting Turing Way case studies that provides greater computational allocations than mybinder.org

### Who can help?

* @sgibson91 

---

### Updates

* 2019-04-23 - 1st Champion project running in a Binder instance

**Comment by KirstieJane** [comment]
😍😍😍 Awesome!! Thank you!

**Comment by sgibson91** [comment]
TuringWayHub will probably need to be built on a high-mem VM as I'm struggling to allocate enough compute resources such that the BinderHub pods can be scheduled and the image can be pulled.

**Comment by sgibson91** [comment]
I've got SERIOUS problems with getting [this line](https://github.com/kochkinaelena/branchLSTM/blob/c88010415e99b55ee836a0ab82436f2cb991574f/preprocessing.py#L271) to work in Binder. The data file is there and unzipped. No issues with file paths. The `preprocessing.py` just exits with no output messages whatsoever, but I can still run other programs after that. So the Binder instance isn't timing out or running out of memory.

Running on a D8 v3 VM with 4GB and 1 CPU per instance.

**Comment by sgibson91** [comment]
Then after a while, this is what I get.

![image](https://user-images.githubusercontent.com/44771837/56365477-e263a980-61e8-11e9-9084-1e61544a9945.png)

:sob: :sob: :sob:

**Comment by sgibson91** [comment]
Branch of the fork I'm running: https://github.com/sgibson91/branchLSTM/tree/sgibson91python-runtime-patch

**Comment by sgibson91** [comment]
Tried a different way of running it

![image](https://user-images.githubusercontent.com/44771837/56365942-eb08af80-61e9-11e9-864d-0a76ff431b13.png)

**Comment by sgibson91** [comment]
Upping to user scheduled resource of 4 CPUs and 16GB.

**Comment by betatim** [comment]
I think what is happening is that that one line uses more memory than is allowed for the pod (check the [`limits` key](https://github.com/jupyterhub/mybinder.org-deploy/blob/08e83b4eb95e67d5ded834447531922a97d864ee/config/prod.yaml#L44-L46) for the single user pods).

The way the memory limit is enforced is that kubernetes watches all the processes in your pod and when one of them (actually when the sum of all of them) goes over the limit then the OOMKiller comes and removes one process (usually the one using the most memory) to restore order.

**Comment by sgibson91** [comment]
Thanks @betatim What's worrying me is that I've allocated a 16GB limit in the config and it's still getting killed, but this script runs fine on a laptop with the same memory. I think I'm just going to have to play with the amount of memory I allocate until I find a balance between the script running and there still being enough left over for the binder pods on the node. I tried allocating an entire node but I think there still needs to be enough space for the image puller and cleaner.

**Comment by betatim** [comment]
What does `kubectl describe pod <nameofthepod>` tell you?

**Comment by sgibson91** [comment]
Current config:
```
singleuser:
  memory:
    limit: 24G
    guarantee: 20G
  cpu:
    limit: 2
    guarantee: 1
```

Describe pod output after first instance of `Server Connection Error: Invalid response: 403 Forbidden`:
<details><summary>Click to expand</summary>
```
$ kubectl describe pod jupyter-sgibson91-2dbranchlstm-2dtu38bw4v -n twhub
Name:               jupyter-sgibson91-2dbranchlstm-2dtu38bw4v
Namespace:          twhub
Priority:           0
PriorityClassName:  twhub-default-priority
Node:               aks-nodepool1-56980770-vmss000000/10.240.0.4
Start Time:         Tue, 23 Apr 2019 09:24:20 +0100
Labels:             app=jupyterhub
                    chart=jupyterhub-0.9-03215dd
                    component=singleuser-server
                    heritage=jupyterhub
                    hub.jupyter.org/network-access-hub=true
                    release=twhub
Annotations:        hub.jupyter.org/username: sgibson91-branchlstm-tu38bw4v
Status:             Running
IP:                 10.244.2.29
Init Containers:
  block-cloud-metadata:
    Container ID:  docker://5216482e89edeccdbf3951c84bf254301cca2f7234f6f03c73886dbbb2931fc3
    Image:         jupyterhub/k8s-network-tools:0.9-1d2e51b
    Image ID:      docker-pullable://jupyterhub/k8s-network-tools@sha256:e89061539b18c940ddb41a18853f52ee98607614cf97e7d69bf0ec78779b6b76
    Port:          <none>
    Host Port:     <none>
    Command:
      iptables
      -A
      OUTPUT
      -d
      169.254.169.254
      -j
      DROP
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 23 Apr 2019 09:24:22 +0100
      Finished:     Tue, 23 Apr 2019 09:24:22 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
Containers:
  notebook:
    Container ID:  docker://70b5b554385a48796e27b42d3dc88dbb690f74434028303bcef2a0c66d8bd0ff
    Image:         turingwayhuborg/binder-prod-sgibson91-2dbranchlstm-07c2e6:486c7981bcc58329595d93655eb57fb3af61fd6f
    Image ID:      docker-pullable://turingwayhuborg/binder-prod-sgibson91-2dbranchlstm-07c2e6@sha256:686b8dc46dc05b8b5ab254e7ae6ee459a00aa60522048fce74665016b7b218a0
    Port:          8888/TCP
    Host Port:     0/TCP
    Args:
      jupyter-notebook
      --ip=0.0.0.0
      --port=8888
      --NotebookApp.base_url=/user/sgibson91-branchlstm-tu38bw4v/
      --NotebookApp.token=<redacted>
      --NotebookApp.trust_xheaders=True
    State:          Running
      Started:      Tue, 23 Apr 2019 09:24:23 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  25769803776
    Requests:
      cpu:     1
      memory:  21474836480
    Environment:
      JUPYTERHUB_API_TOKEN:           <redacted>
      JPY_API_TOKEN:                  <redacted>
      JUPYTERHUB_ADMIN_ACCESS:        1
      JUPYTERHUB_CLIENT_ID:           jupyterhub-user-sgibson91-branchlstm-tu38bw4v
      JUPYTERHUB_HOST:                
      JUPYTERHUB_OAUTH_CALLBACK_URL:  /user/sgibson91-branchlstm-tu38bw4v/oauth_callback
      JUPYTERHUB_USER:                sgibson91-branchlstm-tu38bw4v
      JUPYTERHUB_SERVER_NAME:         
      JUPYTERHUB_API_URL:             http://10.0.188.169:8081/hub/api
      JUPYTERHUB_ACTIVITY_URL:        http://10.0.188.169:8081/hub/api/users/sgibson91-branchlstm-tu38bw4v/activity
      JUPYTERHUB_BASE_URL:            /
      JUPYTERHUB_SERVICE_PREFIX:      /user/sgibson91-branchlstm-tu38bw4v/
      MEM_LIMIT:                      25769803776
      MEM_GUARANTEE:                  21474836480
      CPU_LIMIT:                      2.0
      CPU_GUARANTEE:                  1.0
      JUPYTER_IMAGE_SPEC:             turingwayhuborg/binder-prod-sgibson91-2dbranchlstm-07c2e6:486c7981bcc58329595d93655eb57fb3af61fd6f
      JUPYTER_IMAGE:                  turingwayhuborg/binder-prod-sgibson91-2dbranchlstm-07c2e6:486c7981bcc58329595d93655eb57fb3af61fd6f
      KUBERNETES_PORT_443_TCP_ADDR:   twhubclust-hub23-a42bf8-2018ce8b.hcp.westeurope.azmk8s.io
      KUBERNETES_PORT:                tcp://twhubclust-hub23-a42bf8-2018ce8b.hcp.westeurope.azmk8s.io:443
      KUBERNETES_PORT_443_TCP:        tcp://twhubclust-hub23-a42bf8-2018ce8b.hcp.westeurope.azmk8s.io:443
      KUBERNETES_SERVICE_HOST:        twhubclust-hub23-a42bf8-2018ce8b.hcp.westeurope.azmk8s.io
    Mounts:                           <none>
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:            <none>
QoS Class:          Burstable
Node-Selectors:     <none>
Tolerations:        hub.jupyter.org/dedicated=user:NoSchedule
                    hub.jupyter.org_dedicated=user:NoSchedule
                    node.kubernetes.io/not-ready:NoExecute for 300s
                    node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                From                                        Message
  ----     ------            ----               ----                                        -------
  Warning  FailedScheduling  14m (x2 over 14m)  twhub-user-scheduler                        0/3 nodes are available: 3 Insufficient memory.
  Normal   Scheduled         14m                twhub-user-scheduler                        Successfully assigned twhub/jupyter-sgibson91-2dbranchlstm-2dtu38bw4v to aks-nodepool1-56980770-vmss000000
  Normal   Pulled            14m                kubelet, aks-nodepool1-56980770-vmss000000  Container image "jupyterhub/k8s-network-tools:0.9-1d2e51b" already present on machine
  Normal   Created           14m                kubelet, aks-nodepool1-56980770-vmss000000  Created container
  Normal   Started           14m                kubelet, aks-nodepool1-56980770-vmss000000  Started container
  Normal   Pulled            14m                kubelet, aks-nodepool1-56980770-vmss000000  Container image "turingwayhuborg/binder-prod-sgibson91-2dbranchlstm-07c2e6:486c7981bcc58329595d93655eb57fb3af61fd6f" already present on machine
  Normal   Created           14m                kubelet, aks-nodepool1-56980770-vmss000000  Created container
  Normal   Started           14m                kubelet, aks-nodepool1-56980770-vmss000000  Started container
```
</details>

Code still seems to be running though even with multiple occurrences of the Invalid Server Error?

**Comment by sgibson91** [comment]
@LouiseABowler Does `outer.py` do anything where it would have access on a laptop but wouldn't have on a JupyterHub?

**Comment by sgibson91** [comment]
Ok, now the pod has disappeared so I assume the culler judged it to be inactive.

Culler config:
```
cull:
  every: 300 # 5 mins
  timeout: 240
  maxAge: 600 # 10 mins
```

**Comment by sgibson91** [comment]
`outer.py` completed, just takes a long time, order ~45 mins.

**Comment by sgibson91** [comment]
First Champions project successfully running in a Binder! 🎉 https://github.com/kochkinaelena/branchLSTM/pull/15

I will leave this issue open in case any other tweaks come up while working through the other projects

**Comment by sgibson91** [comment]
Upgraded to 4 CPUs and `outer.py` now runs in roughly 20mins

**Comment by sgibson91** [comment]
Closing this and will start to think about "Providing a specified BinderHub as a service for projects with funding".
