### ISSUE TITLE
Add internal links to Collaborating on GitHub/GitLab Chapter

### ISSUE THREAD

**Issue by rainsworth** [alan-turing-institute/the-turing-way#402]
### Summary

Internal links between the Table of Contents and Sections in the [Collaborating on GitHub/GitLab](https://github.com/alan-turing-institute/the-turing-way-book/blob/2101bcba1711ab9883cf56adcbc8d4a65dd6d6f5/content/collaborating_github.md) chapter in the book can be added as a good first issue.

See, for example, how it is done in the raw markdown of the [Research Data Management](https://github.com/alan-turing-institute/the-turing-way-book/blob/cc93e21411fd65807d0277dad2250bffa14033b0/content/rdm/rdm.md) chapter.

### What needs to be done?

- [ ] Add links to sections in Table of Contents
- [ ] Check other links and for typos
- [ ] Add any other content that you think is relevant!

### Who can help?

This is a good first issue.

---

**Comment by rosiehigman** [comment]
I think this is superseded by #468
