### ISSUE TITLE
Add personas & pathways for users and contributors

### ISSUE THREAD

**Issue by rainsworth** [alan-turing-institute/the-turing-way#403]
### Summary

Create personas and pathways for contributors and users to guide the development of the Turing Way following [Mozilla Open Leadership training](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/).

### What needs to be done?

- [x] Create personas.md for the repo (like done here: https://github.com/mozilla/open-leadership-framework/blob/master/personas.md) 
- [x] Adjust CONTRIBUTING.md and README.md accordingly to overcome any obstacles we foresee for our personas and make contributing as easy as possible

### Who can help?

Anyone! If you do not relate to any of the personas described and are struggling to figure out how to get involved or use this resource, please leave a comment on this issue letting us know what the barriers are!

---

### Updates

Types of personas to describe:

- [x] Contributor persona with limited/no Git/GitHub experience
- [x] Contributor persona with Git/GitHub experience and book topic expertise
- [ ] User persona: early career researcher
- [ ] User persona: supervisor / PI
- [ ] User persona: funder / publisher / admin
- [x] Use gender-neutral names/pronouns

**Comment by oforrest** [comment]
@rainsworth an issue that came up when using personas in the past is that they brought up some unconscious biases, one way of mitigating this risk is to make the names gender-neutral and use they pronouns, what do you think?

**Comment by rainsworth** [comment]
Hi @oforrest, would love to hear your suggestions here!
