### ISSUE TITLE
Netlify build for the book.

### ISSUE THREAD

**Issue by alexmorley** [alan-turing-institute/the-turing-way#404]
### What needs to be done?

- [ ] Document the build process, note what netlify has in common with github-pages (serves static files) and different (the build settings are more flexible).
- [ ] Fix the issue that currently when the build is cached the preview deployments fail.

### Who can help?

Anyone who has used netlify before, or someone who has used github pages a lot and wants to spend a little time digging.

If you want to help then reply to this issue first 

### Details
- [the turing way book](https://github.com/alan-turing-institute/the-turing-way) repo
- Build logs here: https://app.netlify.com/sites/the-turing-way/deploys

**Comment by alexmorley** [comment]
Report: One particular PR is failing to deploy previews any more (although it worked when it was first made?) #482

Here is the deploy history https://app.netlify.com/sites/the-turing-way/deploys I cleared the cache in case that helps. I also removed the requirement for the deploy to succeed in order to merge the branch. Those kind of tests should be in Travis anyway I think... I'd like netlify to make a comment on the PR if there is a preview ready instead. I'll try that and people can let me know if that's more / less convenient than before.

**Comment by pherterich** [comment]
Thank you @alexmorley - maybe something for us to look at at the London dash :smile:

**Comment by dingaaling** [comment]
Hello from October 2022 @alexmorley ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍 this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
