### ISSUE TITLE
Contribution Section - unclear how to contribute edits to the book

### ISSUE THREAD

**Issue by illushka** [alan-turing-institute/the-turing-way#405]
### Summary

The instructions on https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md seem to be outdated and it isn't clear how someone should contribute edits to book chapters, particularly also as some chapters might be in progress as a Pull Requests which haven't been merged to master yet

### What needs to be done?

- [ ] *Check if steps 1,2,3 are still relevant*
- [ ] *Add specific instructions on how to contribute edits to the book*

### Who can help?

---

**Comment by KirstieJane** [comment]
Thank you @illushka!! @rainsworth, I think you can probably clarify how to update an open PR (use the reviewing one as an example!)

But most importantly, I'd really like us to get the chapters back into this repository. @alexmorley @annakrystalli @LouiseABowler - do any of the three of you know how to bring the git commits from https://github.com/alan-turing-institute/the-turing-way-book back here? Related to #404 (lolz at that issue number!)

I know we have some open PRs but I think we can ask them to individually re-open to this....or merge quickly if there's someone who can review.

**Comment by rainsworth** [comment]
@KirstieJane @illushka This has definitely been on my radar, but would like to tackle CONTRIBUTING.md once we've finalised what we're doing with the book repo 🙈 

My aim is to get the personas & pathways up today  (#403 ) and use them to edit the contributing guidelines when we have the book merged back in to the main repo.

Is this ok? 

Will also include how to update an open PR. 👍

**Comment by KirstieJane** [comment]
Yep - totally fine @rainsworth.

For the record, the decision is made about what we're doing with the book repo. We're bringing it back into this one. And quickly.

I can set aside time tomorrow to try to figure out how if our git mavens are too busy.

**Comment by sgibson91** [comment]
Hi @rainsworth, just wanted to note that the addition we made to the contributing guidelines about restarting Travis builds is only applicable if the person has write access to the repo (so probably isn't relevant in the majority of cases).

**Comment by dingaaling** [comment]
Hello from 2022 @illushka ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
