### ISSUE TITLE
Application for Google Season of Docs

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#406]
### Summary

The team that brought you Google Summer of Code are bringing us [Google Season of Docs](https://developers.google.com/season-of-docs) in which a technical writer can join a project and help to develop tutorials/documentation. ✨ 🙌 🚀 🥇 

The deadline is today to submit a project that might be sponsored by the [INCF](https://www.incf.org/).....so I'm going to have a bash and see where it goes.

### What needs to be done?

- [x] Project proposal (see below)
- [x] Mentor application https://forms.gle/a1x26WQGzURLerv66

### Who can help?

* Anyone....but don't worry if you don't have time!

---

- [x] **Email address:** <Kirstie's email>
- [x] **Open source project name:** The Turing Way
- [x] **Link to the open source project:** https://github.com/alan-turing-institute/the-turing-way
- [x] **Mentor's full name**: Kirstie Whitaker 
- [x] **Mentor's display name**: @KirstieJane 
- [x] **What previous experience have you had creating documentation or collaborating with technical writers?**
  *If you have worked with technical writers before, or have developed documentation, mention this in your answer. Describe the documentation that you produced and the ways in which you worked with the technical writer. For example, describe any review processes that you used, or how the technical writer's skills were useful to your project. Explain how this previous experience may help you to work with a technical writer in Season of Docs.*
  
  The BIDS Starter Kit was a Google Summer of Code project in 2018. I mentored Patrick Park as he worked to make the Brain Imaging Data Structure a little more accessible (https://summerofcode.withgoogle.com/archive/2018/projects/5052346392379392). Although we originally proposed the project as developing interactive tutorials, we realised that what the community really needed was additional - and accessible - documentation. This has developed into a detailed README file (https://github.com/bids-standard/bids-starter-kit/blob/master/README.md), a clear set of contributing guidelines (https://github.com/bids-standard/bids-starter-kit/blob/master/CONTRIBUTING.md) and extensive wiki support (https://github.com/bids-standard/bids-starter-kit/wiki). For contributions to the main repository we (Patrick, myself and the four co-mentors from that summer project) reviewed each other's work in pull requests, for contributions to the wiki we used GitHub issues to track where changes had happened and give feedback.

  The Turing Way is a community lead project that has a core of paid contributors as part of the UK's strategic priority fund investment in AI and Data Science for Engineering, Health, Science and Government (https://www.turing.ac.uk/news/alan-turing-institute-spearhead-new-cutting-edge-data-science-and-artificial-intelligence). It is an interactive handbook for reproducible data science. It is published as a jupyter book at https://the-turing-way.netlify.com. We build the project openly via GitHub (https://github.com/alan-turing-institute/the-turing-way) and put a high focus on welcoming contributions from a broad range of backgrounds. Our goal is not to reinvent the wheel, but rather to curate the implicit knowledge that researchers develop over time. Our prompt at community contribution events (such as the Software Sustainability Institute's Collaborations Workshop, or our upcoming Book Dashes) is "What do you wish you had read, or that your supervisor had read, when you started your most recent project?"

  The Turing Way core team (https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md) were selected because of their training as Software Sustainability Institute fellows (https://www.software.ac.uk/about/fellows) or within the Mozilla Open Leadership programme (https://foundation.mozilla.org/en/opportunity/mozilla-open-leaders/). Both put a high emphasis on clear communication, documentation and interdisiplinary engagement to help build a healthy community. Patrick did an excellent job as GSOC student, and the Turing Way team are doing their best to write accessible guides. But in both case it is clear where the expertise of a technical writer would benefit the project. From asking the right questions, knowing their audience and having the skills to capture implicit knowledge, I am confident that the BIDS project (not just the starter kit) and The Turing Way will be greatly enhanced from their expertise.
  
- [x] **What previous experience have you had mentoring individuals?**
  *If you have taken part in Google Summer of Code or a similar program, mention this in your answer. Describe your achievements in that program. Explain how this experience may influence the way you work in Season of Docs.*
  
  I mentored a GSOC Student (Patrick Park, https://summerofcode.withgoogle.com/archive/2018/projects/5052346392379392/) in 2018 and have been selected as a mentor for two more projects in 2019 (assuming we are successful at being allocated the slots): https://neurostars.org/t/gsoc-project-idea-13-improving-unit-testing-and-test-coverage-for-the-te-dependence-analysis-tedana-toolbox/3372 and https://neurostars.org/t/gsoc-project-idea-14-producing-publication-ready-brain-network-analysis-results-and-visualisations-from-the-command-line/3373. The core contributors to the Turing Way are located around the UK (Sheffield, Manchester, Birmingham and London) and come from a broad range of academic backgrounds.

  I have extensive experience mentoring PhD and MSc students in person and in distributed networks across multiple timezones. I have core collaborators in Canada, the USA, and across five instiutions in the UK. I am confident working and mentoring using GitHub for project management, Slack and Gitter for distributed conversations, and my weekly lab meetings have members "Zoom" in from around the world. As a Mozilla Fellow in 2016/17 I contributed to a global network of open leaders focusing on diversity and inclusion as necessary pathways to harnessing the power of open source to build a better world for all.
  
  The Turing Way is a UK-wide project. The BIDS community itself is spread around the world. I hope the distributed nature of these networks are a benefit to the GSOD technical writer. They will not be the only person connecting remotely. Rather, they will be joining a large and distributed group of people passionate about contributing to open science tools, practices and systems.
  
- [x] **I agree to [this Participant Agreement](https://www.google.com/url?q=https://goo.gl/Ej3rSZ&sa=D&ust=1556017534612000&usg=AFQjCNGWF4o3gfd86vvDuzDfbA6RWIyURA)**

---

Each project idea must include at least the following information:

- [x] **Project name:** The Turing Way: An interactive handbook for reproducible data science
- [x] **Description:**

  *A longer description of the documentation work required. Describe your initial idea in detail. Offer opportunities for any interested technical writers to expand or refine the idea.*
  
  Reproducible research is necessary to ensure that scientific work can be trusted. Funders and publishers are beginning to require that publications include access to the underlying data and the analysis code. The goal is to ensure that all results can be independently verified and built upon in future work. This is sometimes easier said than done. Sharing these research outputs means understanding data management, library sciences, sofware development, and continuous integration techniques: skills that are not widely taught or expected of academic researchers and data scientists.

  The Turing Way is a handbook to support students, their supervisors, funders and journal editors in ensuring that reproducible data science is "too easy not to do". It will include training material on version control, analysis testing, and open and transparent communication with future users, and build on Turing Institute case studies and workshops. This project is openly developed and any and all questions, comments and recommendations are welcome at our github repository: https://github.com/alan-turing-institute/the-turing-way.
  
  We host The Turing Way as a Jupyter Book (https://github.com/jupyter/jupyter-book/) at https://the-turing-way.netlify.com. Jupyter Books can format markdown files and jupyter notebooks as static HTML making them easy to read. When a notebook is included in the book, the static page includes a link to an interactive version of the notebook via Binder (https://mybinder.readthedocs.io). At the moment we are under-utilising this opportunity in the Turing Way.

  For this project, the GSOD technical writer will review the handbook and identify opportunities for enhanced engagement with the resources via interactive tutorials and case studies. Ideally, they will support the project in developing pathways to engagement that work for graduate students, research software engineers, senior investigators and business and administrative teams.

- [x] **Related material:**

  * *Link to the open source project that needs documentation.*
  * *If you're proposing a technical writing project that involves updates to an existing documentation set, link to that documentation set.*
  * *If you're proposing a tutorial or a set of how-to guides, describe the features or use cases that need documenting.*
  * *If you're proposing a contributor's guide, link to any existing README file or other relevant material if present. If there's nothing available yet, it's fine to say that.*
  * *Include links to similar documentation in other projects, if relevant.*
  * https://github.com/alan-turing-institute/the-turing-way
  * https://github.com/alan-turing-institute/the-turing-way-book
  * https://the-turing-way.netlify.com

**Comment by KirstieJane** [comment]
Whoops - I didn’t realise I need a secondary mentor. @martintoreilly, would you mind?

**Comment by martintoreilly** [comment]
@KirstieJane Happy to oblige.

**Comment by malinINCF** [comment]
Excellent, thanks Martin! Please go to this form and register yourself as mentor with INCF

https://forms.gle/a1x26WQGzURLerv66

**Comment by martintoreilly** [comment]
## Martin's mentor application
- [ ] **Email address:** <Martin's email>
- [ ] **Open source project name:** The Turing Way
- [ ] **Link to the open source project:** https://github.com/alan-turing-institute/the-turing-way
- [ ] **Mentor's full name**: Martin O'Reilly 
- [ ] **Mentor's display name**: <Martin's display name>
- [ ] **What previous experience have you had creating documentation or collaborating with technical writers?**
  *If you have worked with technical writers before, or have developed documentation, mention this in your answer. Describe the documentation that you produced and the ways in which you worked with the technical writer. For example, describe any review processes that you used, or how the technical writer's skills were useful to your project. Explain how this previous experience may help you to work with a technical writer in Season of Docs.*
  
  My experience of working with technical writers is limited to a few hours being interviewed to create an impact story for one of the projects I was working on. I was impressed with their ability to make the technical content clear for the general reader and communicate the project's motivation and key challenges.
  
  I've developed a range of documentation myself, both for code I have written and for systems and processes I have been responsible for. My goal is always for someone new to the area to be able to get what they need from the documentation and I generally ask someone unfamiliar with the system to review the documentation and "test drive" it where possible. I also request those using the documentation in production to enhance and revise it based on their experience of using it "in the wild".
  
  I have a keen interest in reproducible research and "good enough" software development and analyses practices and am heavily involved in supporting these practices among researchers at The Alan Turing Institute. Providing clear, easy to follow documentation and guidance is key to supporting researchers in improving their practices. With the Turing Way, we are looking to make such quality documentation and guidance available to both the Institute's researchers and the wider research community.
  
- [ ] **What previous experience have you had mentoring individuals?**
  *If you have taken part in Google Summer of Code or a similar program, mention this in your answer. Describe your achievements in that program. Explain how this experience may influence the way you work in Season of Docs.*
  
  I have extensive experience of mentoring individuals. In my current role as deputy head of the research engineering group at The Alan Turing Institute, I lead a group of 30 data scientists, software engineers, researchers and support staff, including 3 team members on secondment from other organisations and one on an internal secondment. I've provided personal mentorship to about a third of the team at all levels of seniority and support the more senior members of the team in mentoring those they work with. The team has a matrix structure, with mentoring regularly occurring outside formal lines of reporting as people work with more experienced colleagues on projects and service areas.
  
  I've previously provided similar on the job mentoring while running a team of 10 developers and analysts in a vocational education organisation. I have also mentored students at a range of levels and in a range of contexts, providing informal guidance and support to PhD students, semi-formal academic supervision to master's students and formal teaching and support to undergraduate students learning programming as part of a business degree.
  
  My approach to mentoring is to support people in achieving their goals and their potential by providing opportunities and encouragement to stretch themselves and take ownership of their work, while providing them coaching and support to fill the gaps in their expertise and grow their confidence.
  
  
- [ ] **I agree to [this Participant Agreement](https://www.google.com/url?q=https://goo.gl/Ej3rSZ&sa=D&ust=1556017534612000&usg=AFQjCNGWF4o3gfd86vvDuzDfbA6RWIyURA)**

**Comment by KirstieJane** [comment]
Woooo! Thank you @martintoreilly!!

@malinINCF is going to submit the projects on behalf of INCF so I'm closing this issue now.

fingers crossed 🤞
