### ISSUE TITLE
Remaining issues for the Make chapter

### ISSUE THREAD

**Issue by GjjvdBurg** [alan-turing-institute/the-turing-way#409]
### Summary

As requested in alan-turing-institute/the-turing-way-book#21 I'm opening an issue in this repo with the remaining todo items for the Make chapter.

### What needs to be done?

Known to do items:

- [x] 1. Add a glossary
- [x] 2. Add more images (e.g. from the result pdf in the tutorial)
- [x] 3. Move some of the links in the Further Reading to the Bibliography
- [x] 4. Provide proper syntax highlighting (? - not sure how to do this in JupyterBook)
- [x] 5. Finalise/Remove TOC (it's already in the sidebar in Netlify, is it needed?)
- [x] 6. Add paragraph on Snakemake under Alternatives to Make (see alan-turing-institute/the-turing-way-book#25)
- [x] 7. Move the Make tutorial repo GjjvdBurg/IntroToMake to the alan-turing-institute organisation.
- [x] 8. Expand more in the big_data section of the chapter, to increase usefulness as reference
- [x] 9. Add reasons for using make raised in [this comment](https://github.com/alan-turing-institute/the-turing-way-book/pull/25#issuecomment-486149112)
- [x] 10. Add ``sudo`` to installation instructions
- [x] 11. Double-check spelling and writing (see also [this comment](https://github.com/alan-turing-institute/the-turing-way-book/pull/25#issuecomment-486149112))

Finally, while I wrote the tutorial from scratch, I later discovered that there are several blog posts online that also describe the use of Make for reproducibility. It might be useful to include these in the bibliography. These links are:

- https://kbroman.wordpress.com/tag/reproducible-research/
- http://zmjones.com/make/
- https://bsmith89.github.io/make-bml/
- https://kbroman.org/minimal_make/
- http://stat545.com/automation04_make-activity.html

### Who can help?

* Anyone who knows about syntax highlighting in Jupyter Book can help with that issue.
* Anyone who can answer whether or not the TOC is needed
### Updates

* Based on the review in alan-turing-institute/the-turing-way-book#25 todo items 8-11 were added above.
* A bugfix branch is maintained at alan-turing-institute/the-turing-way-book#26. To do items that are fixed in that branch will be marked completed in the above checklist.

**Comment by alexmorley** [comment]
> - Anyone who can answer whether or not the TOC is needed
Don't stress over it. But we are aiming to keep all the chapters as similar as possible stylistically. Also if your window is narrow the jupyterbook toc doesn't show :)

**Comment by alexmorley** [comment]
> Anyone who knows about syntax highlighting in Jupyter Book can help with that issue.
Can you post a screenshot?

**Comment by GjjvdBurg** [comment]
Here's a screenshot, the code blocks of the Makefiles have the ``Makefile`` syntax specified, but there is no highlighting for it, compared to the [same code on Github](https://github.com/alan-turing-institute/the-turing-way-book/blob/master/content/make/make.md)

![screenshot](https://user-images.githubusercontent.com/3286696/56648848-8d55e680-6673-11e9-8ade-7d3b1a6f0ed3.png)

**Comment by GjjvdBurg** [comment]
> Don't stress over it. But we are aiming to keep all the chapters as similar as possible stylistically. Also if your window is narrow the jupyterbook toc doesn't show :)

Understood, I'll update the TOC once the rest is final.

**Comment by rainsworth** [comment]
@all-contributors please add @GjjvdBurg for doc, ideas, question

**Comment by rainsworth** [comment]
@all-contributors please add @sje30 for review

(from https://github.com/alan-turing-institute/the-turing-way-book/pull/25)

**Comment by rainsworth** [comment]
@all-contributors please add @hieuhoang for ideas

**Comment by rainsworth** [comment]
Ok, I made a mess with the contributor bot so starting again. APOLOGIES for all the notifications you may receive, thank you so much for your contributions!

**Comment by rainsworth** [comment]
@all-contributors please add @GjjvdBurg for doc, ideas, question
