### ISSUE TITLE
Dissemination report for Turing 

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#429]
### Summary

Amber has asked for:

> Completed or planned publication or dissemination activities, including papers, conference talks, workshops with dates

By the end of today 😬 

I thought I'd have time but UNSURPRISINGLY my calendar got all blocked up again 😭 (With very cool things....but still!)

### What needs to be done?

- [x] A bullet point list of the different things we've done. Nicely formatted to be sent to Amber by the end of today. (Its the nice formatting that I'm struggling to get doen before my next meeting.....right now).
- [ ] Dates
- [x] Something about impact?

Off the top of my head:

* Binder workshops
* BinderHub workshop
* Book dashes (& number of applicants)
* Newsletters (& number of people on mailing list)
* Talks (readme in that folder is out of date I think)
* The book itself
* Number of contributors
* Contributions to other open source projects?

And anything else you can think of!

### Who can help?

* @rainsworth, do you have any bandwidth? Or @pherterich?

**Comment by pherterich** [comment]
I'm at a conference, sorry 😭

**Comment by pherterich** [comment]
I tried to make a start on an impact report, but that only has an outline so far, sorry...

**Comment by malvikasharan** [comment]
@KirstieJane Patricia's impact story is up, and I am assuming you all sent the report out to Amber. Time to close this PR?

**Comment by dingaaling** [comment]
Hello from 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
