### ISSUE TITLE
Decide on the scope/goals of workshops

### ISSUE THREAD

**Issue by alexmorley** [alan-turing-institute/the-turing-way#43]
## Dates and Locations - see #44 for more information
* General researcher workshop at Turing - 12th March
* General researcher workshop in Manchester - 1st March
* Binder hub maintainer workshop in Sheffield - 18th March

## Timetable for researcher-focused workshop
* 9.30 - 10.00: Coffee and Registration
* 10.00 - 10.30: Introduction to the workshop and The Turing Way
* 10.30 - 12.00: Reproducible computing environment, motivations for using Binder and demonstrations (pull requests showing the consequences of changing a dependency)
* 12.00 - 1.00: Lunch
* 1.00 - 2.00: Zero to Binder
* 2.00 - 2.30: Coffee
* 2.30 - 3.30: Build your own Binder
* 3.30 - 4.00: Demonstrating your Binder, general questions, feedback and close
* 4.00 - 5.00: Optional hangout with instructors

## Costs
Total costs are based on 30 attendees per workshop to help give an approximate estimate.

### Manchester
* £20 pp catering = £600

### Sheffield
* Catering is £20pp = £600

### Turing
* £40 pp catering based on https://www.turing.ac.uk/sites/default/files/event_and_engagement_funding_guidance.pdf 
* Estimated Turing total: £1,200

### Totals
* Estimated total cost for venue and catering ~ £2,200
* Staff travel and accommodation costs (based on 5 people per workshop): £2,000

## General Ideas
* Repo for previous binder workshops: https://github.com/Build-a-binder/build-a-binder.github.io. Website at https://build-a-binder.github.io.
* Possibly check in with Tim Head about lessons learned - particularly around marketing the workshops (what is binder and why would people care).
* Recommend timings 10am to 4pm so that people can attend from quite a lot of places without needing a hotel room.
* Suggested structure of the workshops is a demonstration in the morning and a chance to try it out yourself in the afternoon - need to think about a final activity to encourage people to stay.
* Offer childcare and travel support
* Aim to start promoting by mid January with workshops running from mid February onwards
* Room requirements - 30 people, wifi, plenty of plugs, screen.

- [x] Find rooms & dates
- [x] Price up catering etc
- [x] Scope how many people can come

Question: 

If too many people want to come, will we have a selection process? Or first come first served?

**Comment by pherterich** [comment]
Notes for BinderHub workshop: 
* we can probably cover building a BinderHub on Azure with @alexmorley and @sgibson91 expertise, other setups will be more difficult to teach. 
* @annakrystalli will query with Sheffield RSE team/IT on what they could provide as infrastructure for the day
* @sgibson91 is in contact with BinderHub people to see if anyone is available for the day to teach on other setups
