### ISSUE TITLE
Turing Way proposal for the Open Science Fair

### ISSUE THREAD

**Issue by rainsworth** [alan-turing-institute/the-turing-way#434]
### Summary

Apply to present a poster or demo under Training and skills for Open Science at the [Open Science Fair](https://www.opensciencefair.eu/), September 16-18, 2019 in Porto, Portugal.

The deadline for submissions is May 17, 2019.

### What needs to be done?

Authors are asked to submit a short proposal (300 - 500 words) that describes the main contributions of the Poster / Demo. Proposals should contain a brief abstract, place an emphasis on the motivation for the work, and summarize contributions being presented. For Posters, preliminary results may also be included.

Proposal templates and criteria here: https://www.opensciencefair.eu/call-for-posters-demos-2019

### Who can help?

---

**Comment by pherterich** [comment]
Would you submit this as a poster or a demo of the book and binder?

**Comment by rainsworth** [comment]
@pherterich I was thinking both 😬 

Would prefer to do demo, but wouldn't hurt to also have poster (also as backup)?

**Comment by pherterich** [comment]
@rainsworth ah, cool, my brain hasn't even processed both as an option :thinking: 
Shout if you need help

**Comment by pherterich** [comment]
Deadline extended to the 22nd - yay!
