### ISSUE TITLE
Add links to prerequisites in each chapter

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#435]
### Summary

At the top of each chapter there is a list of prerequisites, many of which relate to other chapters in The Turing Way book. Where there is a chapter for the prerequisite this should be linked to in order to make navigating the book easier. Where familiarity with the command line is a requirement then this tutorial should be linked to: [https://programminghistorian.org/en/lessons/intro-to-bash](https://programminghistorian.org/en/lessons/intro-to-bash)

### What needs to be done?

Add links to the following chapters
- [ ] Open Research
- [ ] Collaborating on GitHub/GitLab
- [ ] Version Control
- [ ] Reproducible environments
- [ ] Testing
- [ ] Reviewing
- [ ] Continuous integration
- [ ] Research Data Management
- [ ] Reproducible Research with Make

### Who can help?

This is a good first issue.

---

**Comment by ClareLiggins** [comment]
I'll work on this one.
