### ISSUE TITLE
Find times and venues for Workshops

### ISSUE THREAD

**Issue by alexmorley** [alan-turing-institute/the-turing-way#44]
This is our issue for collecting planning information for our binder workshops in February and March 2019.

### Build a Binder**Hub** Workshop | Sheffield

* Date: 18 March 2019
* Time: 9am - 5pm
* Location: University of Sheffield
* Address: COM-G12 - Main Lewin, 211 Portobello, Sheffield S1 4DP, United Kingdom
* Local helpers:

### Build a Binder Workshop | Manchester

* Date: 1st March 2019
* Time: 9am - 5pm
* Location: University of Manchester
* Address: Bell-Burnell Lecture theatre, Schuster Annexe, University of Manchester, Upper Brook St, Manchester M13 0HR
* Local helpers:

### Build a Binder Workshop | London

* Date: 12th March 2019
* Time: 9am - 5pm
* Location: Ada Lovelace, Alan Turing Institute
* Address: 96 Euston Rd, Kings Cross, London NW1 2DB, United Kingdom
* Local helpers: 
---

General researcher workshop at Turing - ~~6th March~~ 12th March (TBC)
General researcher workshop in Manchester - 1st March
Binder hub maintainer workshop in Sheffield - 18th March

**Comment by annakrystalli** [comment]
### Room spec

- 30 people, 
- not too far out of town 
- screen and plugs? 
- good wifi
- If we can have catering in the room that would be good too

**Comment by annakrystalli** [comment]
Template for collecting details of Bookings
---

## Workshop Title:
### Date:
### Time: 
### Location:
### Address:

**Comment by annakrystalli** [comment]
## Workshop Title: Binderhub for RSEs
### Date: 18 March 2018
### Time:  9am - 5pm
### Location: University of Sheffield
### Address:

**Comment by LouiseABowler** [comment]
The Turing events spaces are booked out on 6th March, so I've asked about Tuesday 12th March instead. I'll update here once we (hopefully!) have confirmation.

**Comment by trallard** [comment]
@rosiehigman @KirstieJane has the Manchester workshop been decided/planned?
I've just been in a CarpentryConnect organisers/taskforce meeting and we talked about having a binder workshop in ([https://software.ac.uk/ccmcr19](https://software.ac.uk/ccmcr19)) let me know if this sounds of interest.

**Comment by fmaussion** [comment]
Are these workshops open to anyone (i.e. non Sheffield University affiliates)?

Is the binderhub workshop going to be too hardcore for a scientist like me? I'm a researcher at Uni Innsbruck (AT) and would be interested in joining the BinderHub workshop in Sheffield (context: https://github.com/pangeo-data/pangeo/issues/521).

**Comment by rosiehigman** [comment]
@trallard I think it would be great to have a follow up associated with CarpentryConnect, we've got rooms/people lined up for the Manchester workshop now so will hopefully be able to advertise it in the next few days.

**Comment by pherterich** [comment]
@fmaussion Workshops will be open to anyone.
Not sure if the BinderHub workshop will be too hardcore for you, @sgibson91 is building the BinderHub for this project and has just finished her physics PhD before starting on this and the whole idea is that her experience means all the potential pitfalls will be documented so it will be easier for others to set up. If you're available and interested, we would love to see you at one of the workshops!

**Comment by KirstieJane** [comment]
@fmaussion - based on your issue to pangeo (https://github.com/pangeo-data/pangeo/issues/521) I think you'd be a great participant of the BinderHub workshop in Sheffield. It might not be super easy, but to be honest, there aren't many people who DO find it easy to build a BinderHub!! One of our hopes is to bring folks together to help each other figure out "how to know what you need to know".

So, setting expectations: you might not be transformed into a cloud controlling super star by the end of the day, but you will have more information on where to look for answers.

And to reiterate the points above, you're very welcome!

**Comment by rosiehigman** [comment]
Hi @fmaussion the sign up page is now live here: [https://www.eventbrite.co.uk/e/build-a-binderhub-registration-55336756729](https://www.eventbrite.co.uk/e/build-a-binderhub-registration-55336756729). Look forward to seeing you there!

**Comment by trallard** [comment]
I can help for the March one!!!!!!!!

**Comment by r-j-arnold** [comment]
That's awesome @trallard! I'm assuming we can pay for your travel, is that right @KirstieJane?

**Comment by KirstieJane** [comment]
I think @trallard lives in Manchester but yes we can reimburse any costs 👾

**Comment by rgaiacs** [comment]
@KirstieJane Do you need help with the promotion? https://software.ac.uk is available if you need. I just need to receive from someone a draft of the announcement or news item.

**Comment by pherterich** [comment]
@rgaiacs we're just finishing off comms, expect something on major mailing lists and channels tomorrow :wink:
