### ISSUE TITLE
Add all-contributors bot instructions to contributing guidelines

### ISSUE THREAD

**Issue by rainsworth** [alan-turing-institute/the-turing-way#446]
### Summary

Add some instructions on how to add contributors using the [all contributors bot](https://github.com/all-contributors/all-contributors) to the [Contributing Guidelines](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md).

### What needs to be done?

- [ ] Add All Contributors Bot instructions/section in Contributing Guidelines
  - When adding contributors in bulk, add ONE contributor at a time, merge, delete branch then run the command for the next contributor, merge, delete branch, etc. (to avoid merge conflicts)
  - Remind contributors to add themselves to [contributors page](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md)
  - Run command directly on related PR/issue or here: https://github.com/alan-turing-institute/the-turing-way/issues/274
- [ ] Include instructions for when CI fails
  - At the bottom of the PR, where it says whether your build passed or failed, you can click “Details” next to the test, that takes you to the Travis page. There’s a “Restart build” button in the top right
- [ ] Feedback issues to https://github.com/all-contributors/all-contributors

### Who can help?

* @sgibson91 
* @pherterich 
* anyone else with experience using the bot

---

**Comment by sgibson91** [comment]
As @pherterich said, we should make it clear that no more than one PR from the bot should be open at any given time, as this will cause a merge conflict.
