### ISSUE TITLE
Promote tools for reproducibility in the book

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#450]
### Summary

As we come across awesome tools for reproducibility in the wild, we should try to find a place to promote and incorporate them in the Turing Way book. This can either be as part of a related chapter (for example, documentation) or have a separate chapter that could be something like "Further Resources".

Please add any other cool tools!

* https://noamross.github.io/redoc/ - Reversible reproducible documentation. It generates Word documents that can be de-rendered back into R Markdown, retaining edits on the Word document, including tracked changes.

### What needs to be done?

- [ ] Include links to tools/resources in the book

### Who can help?

* Anyone who finds a cool tool/resource!

---

**Comment by dingaaling** [comment]
Hello from 2022 @sgibson91! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍 this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
