### ISSUE TITLE
Check and fix formatting in the RDM chapter

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#459]
### Summary

There are a few formatting errors in the research data management chapter, there are some issues highlighted below, but a general proof-read and check of the formatting would be useful as well.

### What needs to be done?

- [ ] Links to the references/further reading
- [ ] Removing comments
- [ ] Putting glossary definitions on separate lines
- [ ] Sorting out weird indentation on 'sharing and archiving data' heading
- [ ] General typos and formatting check

### Who can help?

Anyone, this is a good first issue for people getting familiar with markdown/github.

---

**Comment by AlfAWolf140** [comment]
Going to have a look at this.

**Comment by pherterich** [comment]
Closing this as @AlfAWolf140 did some wonderful work that was merged in :sparkler:
