### ISSUE TITLE
Add/link to an intro to the GitHub interface to the Collaborating on GitHub/GitLab chapter

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#460]
### Summary

To help people who are new to using GitHub it would be helpful to include an introduction to the GitHub web interface.

### What needs to be done?

Add a link to a resource explaining the GitHub interface, a few possibilities are suggested below:
- [https://www.earthdatascience.org/workshops/intro-version-control-git/navigate-github-repos/](https://www.earthdatascience.org/workshops/intro-version-control-git/navigate-github-repos/)
- [https://www.pluralsight.com/blog/software-development/github-tutorial](https://www.pluralsight.com/blog/software-development/github-tutorial)
- [https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/the-github-interface-and-markdown/#-the-github-interface-abby-cabunoc-mayes](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/the-github-interface-and-markdown/#-the-github-interface-abby-cabunoc-mayes)

### Who can help?

Anyone! This is a good first issue.

---

**Comment by growupboron** [comment]
@rosiehigman I would love to work on this.

**Comment by dingaaling** [comment]
Hello from 2023 @rosiehigman! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
