### ISSUE TITLE
Collate all documentation RE JupyterHub and BinderHubs

### ISSUE THREAD

**Issue by alexmorley** [alan-turing-institute/the-turing-way#47]
Notes on methods and issues in deployment of a BinderHub are being documented in `binderhub-notes.md`

#77

**Comment by sgibson91** [comment]
Link for BinderHub citations: https://mybinder.readthedocs.io/en/latest/index.html#citing

**Comment by sgibson91** [comment]
R package: https://github.com/karthik/holepunch
