### ISSUE TITLE
Introducing the FAIR principles for _tools_?

### ISSUE THREAD

**Issue by gkiar** [alan-turing-institute/the-turing-way#471]
### Summary

The FAIR principles also applies to tools, but (as far as I could find) we only discuss them in the context of data. It would be great to extend this :) 

### What needs to be done?

- [ ] Break FAIR principles out of data section
- [ ] Curate list of resources for how the FAIR principles can be applied to tools
- [ ] Write section :)
- [ ] Review

### Who can help?

* Anyone who knows the FAIR principles
* Anyone who uses tools
* Anyone who cares about reproducible research and transparency/provenance in reporting

---

### Updates

* I've made a poster on how we do this in neuroimaging with a tool called Boutiques, which you can [see here](https://figshare.com/articles/fair-pipelines-poster_pdf/8143241)

**Comment by dingaaling** [comment]
Hello from 2022 @gkiar ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍 this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you in a few weeks we'll mark it as closed - but we are always happy to reopen it! Thank you!
