### ISSUE TITLE
Can we add a search bar?

### ISSUE THREAD

**Issue by gkiar** [alan-turing-institute/the-turing-way#472]
### Summary

"I'm a human who wants to find some content in the book but don't know what chapter to look in"

*IF ONLY there was a search bar!*

Let's look into adding a search bar to the Jupyter book, either natively through that stack, jankily-afterwards, or contributing back to the stack if it doesn't exist and would make sense there.

### What needs to be done?

- [x] Identify what search functionality exists in the Jupyter-Book world currently
- [x] Decide on path forward to get searching in the book
- [x] Update this issue with plan
- [x] Discuss
- [x] Implement searching

### Who can help?

* Anyone familiar with Jupyter-Book
* Anyone who knows Markdown/web programming/Jupyter
* Anyone familiar with data querying / searching
* Anyone who wants to learn any of these things a bit better :)

---

**Comment by gkiar** [comment]
Opened this: https://github.com/jupyter/jupyter-book/pull/196

**Comment by HeidiSeibold** [comment]
Is this still relevant? I can search in the book.

![image](https://user-images.githubusercontent.com/14146757/81958562-77182100-960e-11ea-9b63-82b84f02454f.png)

Sorry if I misunderstand something here :grimacing: :nerd_face:

**Comment by malvikasharan** [comment]
Thanks for bringing this Issue to notice @HeidiSeibold. This issue is solved and you are absolutely right with your screenshot. We should be able to safely close this.
