### ISSUE TITLE
[NEW-CHAPTER] Machine Learning Workflow [RFC]

### ISSUE THREAD

**Issue by tallamjr** [alan-turing-institute/the-turing-way#483]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _Machine Learning_.
 * This chapter is being written in #477 
 * This chapter is being developed on the `machine_learning` branch.

This new chapter will guide readers through the common workflow of a machine learning pipeline and discuss gotchas one may come across.

### Table of contents
..._so far_ :
1. Introduction to Machine Learning 
2. Popular Resources
3. Retrieving and versioning input data
4. Tracking input parameters
5. Pipeline diagnostics, visualisation and deployment

## Current status
If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by trallard** [comment]
Count me in folks 🙋🏻‍♀️

**Comment by tallamjr** [comment]
@trallard Awesome! We are working in [this forked repo](https://github.com/informationcake/the-turing-way) and specifically on this file on this branch --> https://github.com/informationcake/the-turing-way/blob/machine_learning/book/content/machine_learning/machine_learning.md

We are collaborating in a single markdown file, If you click the link at the top of the markdown file it will open a HackMD pad where we are putting ideas 😃

**Comment by PranavMahajan25** [comment]
I'd love to contribute to this chapter!

**Comment by tallamjr** [comment]
That's great @PranavMahajan25 ! The developments that took place at the Book Dash were merged into `alan-turing-institute/the-turing-way:machine_learning` with [`d27f720`](https://github.com/alan-turing-institute/the-turing-way/commit/d27f7203c13cd4dd78ef6cafbdc758e8ee03fdcc)

So it should be a case that you can fork the `the-turing-way` repo and then open a PR to that branch (`machine_learning`) with your changes/additions 😃

**Comment by PranavMahajan25** [comment]
Great, will do! Thanks

**Comment by dingaaling** [comment]
Hello from 2022 @tallamjr ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍 this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you in a few weeks we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
