### ISSUE TITLE
Add link to citations 

### ISSUE THREAD

**Issue by RostiReadioff** [alan-turing-institute/the-turing-way#495]
### Summary

*Add citation as links in the book. Follow the guideline explained in [Jupiter book guidance](https://jupyter.org/jupyter-book/features/citations.html). This might require a plug in and/or skills in HTML.*

### What needs to be done?

- [ ] *Add citation as links following the [Jupiter book guidance](https://jupyter.org/jupyter-book/features/citations.html).*

### Who can help?

* *Anyone with html coding skills. I am not the best person to do this.*

---

**Comment by dingaaling** [comment]
Hello from 2022 @RostiReadioff! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
