### ISSUE TITLE
Add Patient and Public Involvement section to Open Research/Open scholarship

### ISSUE THREAD

**Issue by jspickering** [alan-turing-institute/the-turing-way#497]
### Summary

Currently the Open scholarship sub-section of the Open Research chapter covers citizen science, but I think a small section on Patient and Public Involvement (PPI) could be a useful addition here. I have quite a lot of experience with PPI so can draft something myself, but contributions from others are welcome here too!

### What needs to be done?

- [ ] Add sub-section "Patient and Public Involvement"
- [ ] Proofread/edit section

### Who can help?

* Anyone with knowledge of PPI!

---

### Updates

**

**Comment by KirstieJane** [comment]
Hi @all-contributors bot! Please add @jspickering for documentation ✨
