### ISSUE TITLE
Open Research chapter - fix content overview

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#504]
### Summary

After a successful restructure of the chapter, the content overview now needs fixing as the links have been moved

### What needs to be done?
- [ ] Fix all the links to match the restructured content (see [contributing guidelines](CONTRIBUTING.md) for instructions on how to add relative links)

### Who can help?

Anyone!

**Comment by PranavMahajan25** [comment]
Hi, I'd like to take this up!
I had a doubt though, once I make changes to the .md files in the content folder, is there a way of seeing a preview of whether the links are working like they would do on the website? 
(before making a pull request). 

Thanks.

**Comment by pherterich** [comment]
Hi @PranavMahajan25 - thanks for offering your help! :sparkles: 
I don't think there's a preview before you make a pull request, but once you have a pull request open (which you can do early on and highlight it as [WIP] while you're still working on it), continuous integration tests will be triggered which include one line called
"netlify deploy/netlify — Deploy preview ready! "
if you click on details on that line, you can see a preview of the book website and can check the links there.
Hope this helps, give us a shout if you need anything else!

**Comment by PranavMahajan25** [comment]
Hi @pherterich , thanks!
I think I've fixed the links, seems right in the netlify deploy.
Should I rename the PR starting with [Ready for review] for it to be merged? Or is there something else I need to complete before that?
Thanks!!

**Comment by pherterich** [comment]
Hi @PranavMahajan25 - many thanks for that. 
Yes, changing the PR to [Ready for review] is the sign for us to give it a look and merge it in. We have a bit of a backlog, but I'm quite sure @rainsworth and I will work through that as quickly as possible.
