### ISSUE TITLE
MCR Book dash - feedback and lessons learnt

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#505]
## Summary

Some notes of things that we have learnt today that we could do better at the London book dash:

* have a dedicated table to git/GitHub newbies and talk them through the hands-on stuff before getting them started to lower the barriers
* bring markdown cheat sheets

Who can help?
Anyone who attended today - all feedback is super helpful!

**Comment by pherterich** [comment]
* shout out to people when they have been added to the GitHub repo making sure they are aware of the email they've received and added functionality that comes with it

**Comment by rosiehigman** [comment]
Adding explicit guidance on putting github handles into the intro presentation and trying to make sure this happens in the initial brain storming session

**Comment by pherterich** [comment]
I'll close this as I think @rainsworth has covered all of this in #528
