### ISSUE TITLE
Add section on using synthetic data

### ISSUE THREAD

**Issue by wjchulme** [alan-turing-institute/the-turing-way#506]
### Summary

Synthetic datasets mimic real datasets in ways that preserve certain desirable properties (eg variable distributions, size) but remove unwanted properties (eg identifiability of data subjects). They are especially useful as a surrogate for real datasets if the real dataset contains sensitive info and can't be shared directly. 

Synthetic data can be used prior to gaining access to real data to assess study feasiblity and write and test code. They can be used to write and refine study designs without succumbing to 'data-dredging' or 'p-hacking'. They can be used after a study is completed to improve scrutiny and usability of shared analysis code. 

Since synthetic data can facilitate open research practices, a section describing it's benefits would be useful, probably in the 

### What needs to be done?

- [ ] Decide where this content should sit - *Open data* section in Open research chapter? Research Data Management chapter? Somewhere else?
- [ ] Define synthetic data
- [ ] Describe how synthetic data can facilitate open research practices and reproducibility
- [ ] Include links to methods for creating synthetic data
- [ ] Include one or two small case-studies?
- [ ] Review

### Who can help?

* Anyone with some knowledge/experience of synthetic data
* Anyone without knowledge of synthetic data, to check it makes sense to fresh eyes

---

**Comment by vhellon** [comment]
Hello from 2022 @wjchulme ! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog. Coincidentally we have someone from the Turing Institute working on this chapter at the moment- let me know if you would like me to connect you up with them?

**Comment by dingaaling** [comment]
Hi @wjchulme! We haven't heard from you, but we still think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
