### ISSUE TITLE
Open source software licenses & data science

### ISSUE THREAD

**Issue by awllee** [alan-turing-institute/the-turing-way#530]
### Summary

Is there scope for discussing open source software license issues that are particularly relevant for data science? That this involves legal issues makes it harder to discuss easily, but also why it is a cause of stress for potential newcomers to open-source software.

My impression is that choosing the appropriate open source software license for a given project can be difficult/confusing/stressful for people and ultimately off-putting. This is particularly confusing in data science applications that involve high-level languages and rely on many external packages/modules with potentially different licenses. So the [choose a license website](https://choosealicense.com/) may not be sufficient.

I can see that making *suggestions* of almost any kind in the book could be problematic as it could be viewed as legal advice, but is it possible to just provide some information and point to examples of what some communities do without commenting on whether they are right?

For example, it appears that there are many MIT-licensed R packages that *use* GPLv2/3 packages, but do not involve copying or modifying GPL code. I *think* the idea is that the MIT license applies only to the code for the R package, which is what is actually released. Any combined program would need to be released under an appropriate GPL. This is consistent with Section 1.5 of the [Rcpp-FAQ](https://cran.r-project.org/web/packages/Rcpp/vignettes/Rcpp-FAQ.pdf), but there appear to be [many differing opinions](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works) on what exactly constitutes a derivative work.

There is also potentially some value in pointing out some non-controversial facts. For example,

- the GitHub terms of service indicate that when contributing to a project with a clear license, and in the absence of a specific arrangement, [the contribution is licensed under the same terms](https://help.github.com/en/articles/github-terms-of-service#6-contributions-under-repository-license). So one does not need to create a CLA for every project, but trying to relicense would still be difficult.
- a non-judgemental summary of what permissive and copyleft licenses are, and perhaps how licenses can be GPL-compatible.

Just for context: I am creating some light course materials (not yet online) for some computational statistics PhD students at Bristol, which includes some information on reproducible research, open source software, packages, etc. The Turing Way has been an excellent reference on many things, and I am linking to it for additional reading, but on this topic there is not much information.

### What needs to be done?

If it is in scope, some helpful information could be added to the [open source software section](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/content/open_research/02/opensourcesoftware.md).

I think it would be good to avoid strong opinions about licenses, etc. as I know discussions can quickly get very heated. I am mainly concerned with whether non-controversial information can be added to the book that acknowledges existing disagreements where relevant.

### Who can help?

I honestly do not know. I suspect there are a number of people involved in the Turing Way that know much more than me about OSS licenses.

---

**Comment by HeidiSeibold** [comment]
Maybe it would even make sense to broaden this. 

Not only licenses for software matter but also licenses for other research products such as text, images and data.

My favorite ressources:

- Software: https://choosealicense.com
- Other: https://creativecommons.org/choose 

This could be an individual chapter or part of:

- open research
- research compendium #834

**Comment by dingaaling** [comment]
Hello from 2022 @awllee + @HeidiSeibold! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
