### ISSUE TITLE
Update CI scope

### ISSUE THREAD

**Issue by trallard** [alan-turing-institute/the-turing-way#533]
### Summary

The CI for the repo was updated during the book dash so now it includes the steps needed to check / test the generated html website. However, this is not needed when files outside `book` are modified. 

The CI needs to be updated so tha the html checks are only done when there are changes to the `book` folder content

### What needs to be done?

- [ ] Update the CI scripts to detect changes in `book` and then check the output
- [ ] Test with changes to the book only
- [ ] Test with changes outside book
- [ ] Test with changes in and out of book

### Who can help?

* @trallard 

---

### Updates

cc' @sgibson91 @KirstieJane

**Comment by KirstieJane** [comment]
Thanks @trallard!! 

I would actually LOVE to check for broken links in the github repository too. It always makes me sad when READMEs and guidelines etc have broken links in them!

So I'm not super sure that we do need to do this work...

**Comment by KirstieJane** [comment]
Just as a quick note - this error that we have for the CI at the moment is not related to any of these points I think: https://travis-ci.org/alan-turing-institute/the-turing-way/builds/535368941#L184

Maybe related to https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs ??

**Comment by trallard** [comment]
hey @KirstieJane, unfortunately, this is not the case as the CI is now using the `general` CI vm (see [https://github.com/alan-turing-institute/the-turing-way/blob/d59ccdd6579d676f94f79d26cb0437eb097673aa/.travis.yml#L3](https://github.com/alan-turing-institute/the-turing-way/blob/d59ccdd6579d676f94f79d26cb0437eb097673aa/.travis.yml#L3) due to it needing both Ruby and Python installed (For Jekyll and the Jupyterbook) so in this case, the virtualenv does need to be activated upon runtime. 

I am unsure why this has stopped working and I just checked the previous PR's and they all passed the CI with the new implementation. I wonder if this is a Travis issue/lack of resources

**Comment by KirstieJane** [comment]
Ah - gotcha. It might be, but it feels like a strange error to get for a lack of resources issue??

```
source ~/virtualenv/python3.6.3/bin/activate
/home/travis/.travis/functions: line 104: /home/travis/virtualenv/python3.6.3/bin/activate: No such file or directory
The command "source ~/virtualenv/python3.6.3/bin/activate" failed and exited with 1 during .
```

If you tell me that it could be though then I will  absolutely defer to your judgement!

**Comment by trallard** [comment]
I am going to try with the Python instance one and install ruby via rvm so that we do not have to rely on  activation of the environment at runtime

**Comment by KirstieJane** [comment]
@trallard - I think some of the PRs are passing because they haven't pulled from master so travis isn't running the most recent version of the CI commands (just the big file check bash script) 😢

**Comment by sgibson91** [comment]
@KirstieJane My branch for PR #531 is up to date with master and is still failing CI

**Comment by sgibson91** [comment]
(Deleted my last comment because I realised I'd read Kirstie's comment incorrectly!)

**Comment by trallard** [comment]
#528 passed and it used the version with the updated CI (this was two days ago)

So definitely need to dig out why this stopped working now

**Comment by KirstieJane** [comment]
Oh YES - you’re right 😬 Good point. I’m back to maybe a travis weirdness?

**Comment by pherterich** [comment]
@alexmorley - @trallard is on holiday now - do you think this is something you can help with before the London dash?

**Comment by alexmorley** [comment]
Should be OK now :)
