### ISSUE TITLE
Prepare Boost your Research Reproducibility folder for submission to JOSE

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#536]
### Summary

Tidy up and add documentation to the [Boost your Research Reproducibility with Binder folder](https://github.com/alan-turing-institute/the-turing-way/tree/master/workshops/boost-research-reproducibility-binder) prior to submission to [JOSE](https://jose.theoj.org/about).

### What needs to be done?

- [x] Add HackMD notes to README
- [x] Add presenter/facilitators guide
- [ ] Write report summarising Manchester and London workshops and feedback
- [x] Add a short Markdown file titled paper.md with title, author names and affiliations, containing a description of the software, statement of need, and key references.

### Who can help?

* @rainsworth and @rosiehigman working on this 23/05
* Anyone who helped at or attended one of the workshops!

---

### Updates

**[What to include in the paper](https://jose.theoj.org/about#author_guidelines)**

JOSE papers should:
- [x] List all authors and affiliations.
- [ ] Describe the submission, and explain its eligibility for JOSE.
- [x] Include a _Statement of Need_, explaining how the submitted artifacts contribute to computationally enabled teaching and learning, and describing how they might be adopted by others.
- [x] For learning modules, describe the learning objectives, content, instructional design, and experience of use in teaching and learning situations.
- [x] Tell us the "story" of the project: how did it come to be?
- [x] List key references including a link to the open archive of the software or the learning module.

**Comment by rainsworth** [comment]
HackMD links:

Boost your research reproducibility with Binder - Manchester: https://bit.ly/TuringWayMCRNotes
Boost your research reproducibility with Binder - London: https://bit.ly/TuringWayLDNnotes
Build your BinderHub - Sheffield: https://bit.ly/BinderHubShef

**Comment by rainsworth** [comment]
I'm starting on the paper.md file with statement of need.

**Comment by rosiehigman** [comment]
I'm starting on instructor_guide.md with an overall guide for running the workshop

**Comment by rainsworth** [comment]
Feedback tweets from MCR event:
* https://twitter.com/Jade_Pickering/status/1101477313814908929
* https://twitter.com/rgaiacs/status/1101491101926604801

Feedback tweets from LDN event:
* https://twitter.com/BioStew/status/1105465193860083713
* https://twitter.com/jezcope/status/1105469883435966465
* https://twitter.com/Gummifot/status/1105502749494599680
* https://twitter.com/MoseGiordano/status/1105543912255614979
* https://twitter.com/tallamjr/status/1105835634684502016

**Comment by rainsworth** [comment]
Once reviewed and ready, split out copy following: https://help.github.com/en/articles/splitting-a-subfolder-out-into-a-new-repository
