### ISSUE TITLE
"Lorem ipsum" not removed from last sections of Reviewing chapter

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#538]
### Summary

The "lorem ipsum" placeholders have not been removed from the Reviewing chapter.

https://the-turing-way.netlify.com/reviewing/reviewing#further-reading

### What needs to be done?

- [ ] Update the Reviewing chapter to remove instances of "lorem ipsum"
- [ ] Add CI test to check for rogue "lorem ipsums"?

### Who can help?

* Anyone for the PR to remove the text!
* Someone interested in CI/testing for an automated test.

---

### Updates

The CI test should be considered as "nice to have" and not a requirement, so please don't be put off taking this issue on 🙂

**Comment by NatalieThurlby** [comment]
Hi. Just to let you know, I'm about to give this one a go 😃. Cheers!

**Comment by NatalieThurlby** [comment]
I've given it a go. I did write a script to check the lorem ipsums (currently only checks the reviewing chapter), but I didn't add it into the travis file (yet - maybe I will do this tomorrow at the book dash).
