### ISSUE TITLE
Workshop lens on Turing Way content

### ISSUE THREAD

**Issue by maalbadri** [alan-turing-institute/the-turing-way#546]
### Summary

I would like to present the Turing Way content as a half-day PhD training workshop. Which chapters/topics would be the most useful for PhD students to learn about? How would these topics be presented in a classroom/workshop environment? 

### What needs to be done?

- [ ] Rank topics by usability/relevance to PhDs,
- [ ] Create an interactive tutorial for use in classroom and examples for the book.

### Who can help?

* Me
* Anybody else who is running this kind of workshop

---

**Comment by KirstieJane** [comment]
This sounds wonderful @maalbadri! Please go ahead and get started. Ping us in gitter or here in the issue if you have any questions or want longer guidance. Our binder workshops (in the workshops folder) have some nice markdown demos that might be a good format to follow 💞

**Comment by dingaaling** [comment]
Hello from 2022 @maalbadri! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
