### ISSUE TITLE
[suggestion] pinning a few meta issues

### ISSUE THREAD

**Issue by kkmann** [alan-turing-institute/the-turing-way#554]
### Summary

With the turing way growing so quickly (congrats!) the issue board is getting a bit overwhelming. I would suggest pinning a few 'meta issues' to make it easier to find things. In particular, I'd find a meta issue for a content wish-list helpful. People could simply reference their [new [chapter|section|etc]] issues in the pinned issue. Advantage over using labels: newomers have a place to ask/discuss first contributions in a unified thread instead of having to understand the labeling system and deciding on one a particular thing upfront (e.g. 'hey I am xyz, interested in yzx - what would be a good starting point for me?').
It might also be helpful to pin a 'contributing issue' (i know there are contributing guidelines, but it doesn't hurt to have it in a more prominent place ;))

### What needs to be done?

- [ ] *discuss whether and what to pin.*
- [ ] *pin it or close this issue.*

### Who can help?

* *Anybody.*
* @KirstieJane?

---

**Comment by kkmann** [comment]
@rainsworth have you given it any further though? I'd rather close it otherwise - you don't want to have too many zombie issues spooking around your issue bord, do you ;)

**Comment by KirstieJane** [comment]
I think this is an interesting point @kkmann. I don’t mind having lots of issues open, so I’d prefer to keep it until I - and whomever takes over from @rainsworth have time to assess and organise. You’re of course welcome to close if you’d like to!
