### ISSUE TITLE
Very Large Datasets and Data Provenance

### ISSUE THREAD

**Issue by taunsquared** [alan-turing-institute/the-turing-way#558]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _Very Large Datasets and Data Provenance_ (this might be 2 sections).
 * I'd like to write about how to share Very Large Datasets (video datasets, neural recordings, etc) online, perhaps build a list of suggested standard metadata to include, and list online platforms that can host huge datasets (Figshare and OSF have dataset size limits on the order of GBs, and when I say "very large" I mean 100s of GBs or several TBs). The only online resource I know about on this topic (and I haven't explored it exhaustively) is https://crcns.org/
 * I'd also like to talk about data provenance (https://en.wikipedia.org/wiki/Provenance), aka the story of a dataset - where did it come from, how was it collected, what tools were used, what operating systems were involved, etc - and perhaps develop another list of suggestions for standard metadata, such as tools used to collect data, date of original data collection, context of dataset, etc. 
 * The data provenance section would also include how to document any pre-processing steps done to the data...is there anyone already talking about data version control?

### Table of contents
How to share Very Large Datasets
 - suggested places to host Very Large Datasets
 - suggested metadata for Very Large Datasets

Data Provenance
 - what is provenance and how does it apply to research data?
 - suggested workflow for documenting and tracking the provenance of your data

### Resources
https://crcns.org/  

### Discussion points/related issues
 - if there are no satisfactory online resources for hosting Very Large Datasets, does anyone know how to go about building one, or asking for one?

## Current status
This chapter is empty. I am happy to write this chapter and collaborate with others interested in this topic. 

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by taunsquared** [comment]
more resources: 
 - https://crcns.org/files/news/crcns-neuroinformatics-article.pdf

**Comment by dingaaling** [comment]
Hello from 2023 @taunsquared!  Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
