### ISSUE TITLE
Broken ToC links in Chapter 3

### ISSUE THREAD

**Issue by mjg211** [alan-turing-institute/the-turing-way#563]
### Summary

Links to different subsections in Chapter 3 broken after switch to multiple pages.

### What needs to be done?

- [ ] *Change to relative links

### Who can help?

* Fixing now

---

### Updates

None

**Comment by masonlr** [comment]
@mjg211 what's your opinion on https://github.com/alan-turing-institute/the-turing-way/issues/581?

**Comment by dingaaling** [comment]
Hello from 2022 @mjg211 ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
