### ISSUE TITLE
Update contributing guidelines to include how to add a new chapter to the book TOC

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#578]
### Summary

At the moment, there's no information in `CONTRIBUTING.md` on how to include a new chapter to be rendered by the Jupyter Book.

### What needs to be done?

- [ ] Add guidelines of what to update so that the Jupyter Book renders a new chapter (either for deployment or preview in PR)

### Who can help?

* @rainsworth 

---

**Comment by sgibson91** [comment]
book -> website -> _data -> toc.yaml

**Comment by pherterich** [comment]
Yeah, https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_data/toc.yml is super hard to find if you don't know where to look, an update to the contributing guidelines is definitely good. Might be an opportunity to review "how to add a new chapter" in general as I don't think we really do the 2 step review any longer.

**Comment by sgibson91** [comment]
I think it'll be a lot more difficult to do the 2 step review if the team is reimagined as one community manager as well.

**Comment by pherterich** [comment]
That and the fact that whoever will be writing the chapter won't get paid for it, so 2-3 major drafts are unrealistic. We're not Nature (yet) :joy:

**Comment by dingaaling** [comment]
Hello from 2022! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
