### ISSUE TITLE
Update contributing guidelines with how to fix broken image links

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#580]
### Summary

Currently I'm not sure how to get the Jupyter Book to render my image in saved to the figures folder.

### What needs to be done?

- [ ] Update contributing guidelines to make this clearer.

### Who can help?

* @rainsworth 
* @alexmorley and his book magic?

---

**Comment by alexmorley** [comment]
currently figures for the book should go into the `book/website/assets/figures` folder. Once #507 is merged they will be in the `book/content` folder.

figures not for the book will stay in the `/figures` folder

**Comment by sgibson91** [comment]
Pre-merge of #507, adding a figure to a chapter looked like this:
```
![cloud_neutral_binderhub](/assets/figures/cloud_neutral_binderhub.png)
```

This needs to be updated in the contributing guidelines so the path now points to `/book/content/figures/`.

**Comment by sgibson91** [comment]
> ```
> ![cloud_neutral_binderhub](/assets/figures/cloud_neutral_binderhub.png)
> ```
This should now just be:
```
![cloud_neutral_binderhub](/figures/cloud_neutral_binderhub.png)
```
