### ISSUE TITLE
Standardise markdown table-of-contents entries

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/the-turing-way#581]
### Summary

From discussing with a few others (@kkmann, @alexmorley), there are a few issues around table-of-contents content:

1. The manual table-of-contents entries take up a lot of space on each chapter page, i.e. there is a lot of text to scroll through before getting to the content.

2. The manual table-of-contents pages become difficult to maintain if content is sourced from multiple subsection files. For example, if we add a new section between `./03/yaml` and `./04/binder` below, then we have to manually go through and update all of the markdown paths.

   ```
   - [YAML files](./03/yaml#YAML_files)
       - [YAML syntax](./03/yaml#YAML_syntax)
           - [Scalars](./03/yaml#Scalars)
           - [Lists and Dictionaries](./03/yaml#Lists_and_Dictionaries)
           - [YAML gotchas](./03/yaml#YAML_gotchas)
       - [How to use YAML to define computational environments](./03/yaml#How_to_use_YAML_to_define_computational_environments)
       - [Security issues](./03/yaml#Security_issues)
   - [Binder](./04/binder#Binder_section)
       - [Disambiguation](./04/binder#Disambiguation)
       - [Creating a Binder for a project](./04/binder#Creating_a_binder_for_a_project)
           - [Step 1: Specify your computational environment](./04/binder#Step_1_Specify_your_computational_environment)
           - [Step 2: Put your code on GitHub](./04/binder#Step_2_Put_your_code_on_GitHub)
           - [Step 3: Generate a link to a Binder of your project](./04/binder#Step_3_Generate_a_link_to_a_Binder_of_your_project)
       - [Including data in a Binder](./04/binder#Including_data_in_a_Binder)
           - [Small public files](./04/binder#Small_public_files)
           - [Medium public files](./04/binder#Medium_public_files)
           - [Large public files](./04/binder#Large_public_files)
   ```
3. A autogenerated table of contents already exists on the right, so there is duplication of information.

![image](https://user-images.githubusercontent.com/5828176/58474612-9723ab80-8143-11e9-897c-6a0980c38ae2.png)

### What needs to be done?

- [ ] Decide whether handwritten TOC information is needed in markdown files. We recognise that this information may be of use when reading the book directly in github.
- [ ] Depending on decision, go through and remove manual table-of-contents markdown

### Who can help?

* @KirstieJane, @sgibson91

---

**Comment by kkmann** [comment]
:+1:

**Comment by mjg211** [comment]
👍 Compromise could be to retain just the first level contents if there's a strong desire not to delete them all together

**Comment by dingaaling** [comment]
Hello from 2022 @masonlr ! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
