### ISSUE TITLE
Policy document on cloud permissions for BinderHub

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#593]
### Summary

A nice accompaniment to the BinderHub chapter I'm writing might be a policy document on gaining permissions from IT Services to deploy a BinderHub to a cloud platform.

Some resources:
* https://github.com/research-software-reactor/cyclecloud/tree/master/Crib%20Sheet
* https://github.com/research-software-reactor/azure-terminology-cheatsheet

### What needs to be done?

- [ ] What kind of permissions do you need on different platforms? I only have knowledge of Azure.
- [ ] Create a policy document assuaging IT fears against Role Based Access Control and apps acting independently.

### Who can help?

* @sgibson91 
* @trallard 
* Anyone else who's had experience deploying BinderHubs on the cloud!

---

**Comment by sgibson91** [comment]
https://github.com/research-software-reactor/azure-terminology-cheatsheet

The above repo may be a good place to start.

/cc: @KirstieJane

**Comment by dingaaling** [comment]
Hello from 2022 @sgibson91! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍 this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you in a few weeks we'll mark it as closed - but we are always happy to reopen it! Thank you!

**Comment by dingaaling** [comment]
Hello from again from 2022! This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
