### ISSUE TITLE
Updating the "Reproducibility" Chapter

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#596]
### Summary

Updating the Reproducibility Chapter with new sections and updating wordings

### What needs to be done?

- [X] *Changing order of the sections as listed below 
- [X] *Point 1: Make "Definitions of reproducibility" - Currently Point - 3
- [X] *Point 2: Why is reproducibility important for science *and scientific communities*?
- [X] *Point 3: ~Why you should care about reproducibility~ -> What are the benefits of doing reproducible science?
- [X] *Point 4: What are the values and rewards of doing reproducible science?
- [WIP] *Point 5: How can we incentivize people to do reproducible science?
- [WIP] *Point 6: Case studies and examples
- [WIP] *Point 7: Resources

### Old issues:

Closed - https://github.com/alan-turing-institute/the-turing-way/issues/101

### Who can help?

- Anyone can contribute to this issue by commenting, editing, voting, emailing me (malvikasharan@gmail.com) or the core members of Turing Way.

---

### Updates

2019-05-28: Created new issues and checked the completed tasks. Point 6 and 7 in progress.

**Comment by dingaaling** [comment]
Hello from 2022 @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
