### ISSUE TITLE
Create Glossary chapter

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/the-turing-way#598]
## Detailed description
This chapter will provide a single point for new contributors to access jargon free explanations of all the technical terms used in the book. The first version of the chapter may compile glossaries from existing chapters, and it should be continually updated as the book grows (maybe add updating glossary as an an action on the contributor guide?). 

Below is a dump of some thoughts I've collected so far:
- [x] Open a glossary chapter issue...!
- [ ] Use a tool such as The Up-Goer Six Text Editor (https://splasho.com/upgoer6/) to config that glossary descriptions are using most accessible language. 
- [ ] Consider how to distinguish internal glossary links from external page redirects. Formatting italics?
- [ ] See if there is a Jupyter book plugin for more formatting options, for example making use of reStructured text in admonition blocks 
- [ ] Create continuous integration script to search for instances of glossary terms in the book content and cross reference to the glossary chapter and apply appropriate formatting (see issue #616).

**Terms to make sure are included (collated from README.md and CONTIBUTING.md)**

- [ ] pull request
- [ ] ping
- [ ] git 
- [ ] version control
- [ ] Markdown
- [ ] Issue
- [ ] rendered
- [ ] Lorem ipsum
- [ ] bug
- [ ] Jupyter
- [ ] Binder, BinderHub
- [ ] review (in this context)

### Table of contents
Alphabetical list of glossary items

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by cassgvp** [comment]
I've started compiling this and will continue to work on it. Creating the issue as a place holder for now.

**Comment by mjg211** [comment]
Shall we move current glossaries (for example the one at the end of Version Control chapter) over to this chapter?

**Comment by cassgvp** [comment]
> Shall we move current glossaries (for example the one at the end of Version Control chapter) over to this chapter?

Makes perfect sense! Feel free to dump them in and I'll tidy.

**Comment by mjg211** [comment]
Will do now 👍

**Comment by cassgvp** [comment]
Going to create a chapter using the contributor guide.

**Comment by da5nsy** [comment]
Closing this issue as we now have a very lovely glossary here: https://the-turing-way.netlify.app/afterword/glossary.html
