### ISSUE TITLE
feat: Singularity content for "Reproducible Environments"

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/the-turing-way#607]
### Summary

* Adds content for [Singularity](https://www.sylabs.io/docs/).

### What needs to be done?

- [x] Worked examples for getting started with Singularity

### Who can help?

* @kkmann, @masonlr

**Comment by kkmann** [comment]
I am still trying to figure out how to put together a singularity container based on https://hub.docker.com/r/emdupre/jupyter-book
We need to call bundle install to get the required ruby gems, that complains about being run as root though x)

**Comment by masonlr** [comment]
@kkmann I'll close this issue as you got the main singularity content into the book. We also have the temporary docker based method #592 for now.

If you do go down the route of creating a new singularity container for book editing, can you please open a new dedicated issue?  😄
