### ISSUE TITLE
Update figure/image instructions

### ISSUE THREAD

**Issue by masonlr** [alan-turing-institute/the-turing-way#640]
### Summary

#375 proposed placing images in the `book/content` directory and using relative paths to images within our markdown files.  The `book/README.md` file currently has

> All the text for each chapter lives inside its own folder in the `content/` directory.
>
> Everything else is in the `website/`. Importantly this includes the figures, which are in the `website/assets/figures/` directory.

https://github.com/alan-turing-institute/the-turing-way/blame/master/book/README.md#L4-L6

### What needs to be done?

- [ ] Change the instructions to state that figures are now to go within the `book/content` directory

### Who can help?

* @alexmorley

---

**Comment by alexmorley** [comment]
Sorry I lost track of this issue. @masonlr I think we can deleted the second line (re web/assets etc) and just add an example directory structure and figure path?

**Comment by masonlr** [comment]
Yep. Sounds good.

**Comment by da5nsy** [comment]
Closing as this is now out of date.
Instructions for including images can be found here: https://the-turing-way.netlify.app/community-handbook/style/style-figures.html#image-type-file-name-size-and-location
