### ISSUE TITLE
Chapter on research practices and decision making

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#650]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on how organisations onboard people to know what good research practices look like.
 * This chapter is being written in (no open PR yet)
 * This chapter is being developed on the (no open branch yet) branch.

### Table of contents

(Not there yet)

### Resources

* https://twitter.com/rachelcoldicutt/status/1146678686843854848 -- tweet from DotEveryone CEO about resource that they're developing
* https://theodi.org/article/check-out-our-rd-open-research-tools/ -- similar resource from ODI that already exists

### Discussion points/related issues

* Need to get in touch with the folks who have written these chapters and see if they're up for having them included/linked within the Turing Way.
* This chapter is also lightly blocked because its an extension from reproducibility and we haven't scoped that as a community yet.

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by malvikasharan** [comment]
Do we know who can help in the initial stage?

- [ ] A possible list of people who can contribute to designing the outline

**Comment by harisood** [comment]
Hey @KirstieJane! We (the Reviewers & Editors team) believe this content is being covered by #2945 & #2948, and so will be closing this issue for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
