### ISSUE TITLE
New Chapter Proposal: Reproducible Workflows/Pipelines

### ISSUE THREAD

**Issue by mr-c** [alan-turing-institute/the-turing-way#651]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on "Reproducible Batch Data Analysis Workflows", as part of the existing "Reproducible environments" section.
 * This chapter is being written in https://github.com/alan-turing-institute/the-turing-way/pull/652
 * This chapter is being developed on the https://github.com/mr-c/the-turing-way/tree/adv_workflows branch.

Will use the platform/vendor-neutral [Common Workflow Language](https://www.commonwl.org) standards to teach automated data analysis workflow concepts. 

[![Image of an example workflow](https://view.commonwl.org/graph/svg/github.com/hacchy1983/CWL-workflows/blob/master/Workflows/test-workflow.cwl)](https://w3id.org/cwl/view/git/81f0de7c39c54830ce7ed3dec8d747b9a05bb09e/Workflows/test-workflow.cwl)

Will be multi-licensed for easy sharing of material to and from the [official CWL user guide](https://www.commonwl.org/user_guide) (adding CC BY 4.0 for the prose and Apache 2.0 for any code snippets; alongside the MIT license already used for the rest of "The Turing Way".

Could also go after chapter "12 Reproducible Research with Make" as "13 Advanced Reproducible Batch Data Analysis Workflows with CWL". I (@mr-c) am open to suggestions.

if the term "workflow(s)" is too overloaded in this context, we can use "pipeline" everywhere with a footnote explaining that a "pipeline" is being used for the concept of "an automated computational data analysis workflow" as opposed to a real world process.

### Table of contents

- [ ] Why workflows? 
- [ ] When to switch to a structured workflow?
- [ ] Finding an existing tool description for someone else's tool
- [ ] Including your own script as a step in a workflow
- [ ] Connecting steps into a workflow using YAML
- [ ] Connecting steps into a workflow using a GUI (probably the F/OSS Rabix Composer)
- [ ] Adding Tool & Workflow description Metadata: authorship, license, and more
- [ ] Giving credit: not just listing the underlying tool's conda name or container URL, but including an identifier that can used to extract citation information later
- [ ] Visualizing workflows (paste GitHub/GitLab URL into https://view.commonwl.org)
- [ ] Testing Workflows (use small data!) (maybe put under section "9 Testing"?)
- [ ] Personal story: team with a big mess of scripts to a standards-based workflow (Probably [MGnify](https://github.com/EBI-Metagenomics))
- [ ] Personal story: individual or small group wanting to publish their multi-step research workflow (TBD)

### Resources

The CWL user guide: https://www.commonwl.org/user_guide/

### Discussion points/related issues

Will defer foundational concepts (YAML, conda, containers, ) to the existing material

- [ ] add a new intro section between "3.5 Open notebooks" and "3.6 Open scholarship" for "Open Automated Workflows"

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [x] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by mr-c** [comment]
@KirstieJane [wrote](https://gitter.im/alan-turing-institute/the-turing-way?at=5d285ae1f4fe943971f423df)
> I'd recommend writing it as a new chapter rather than fitting it into the reproducible environments one - but - if you have time - looking for places to add links to your chapter from the reproducible environments one

> The other thing I’m trying to push is that chapters can be short: 3 paragraphs is enough. So the most most useful thing you can do is get something written in the time/energy you have, and we can merge that and add to it as we go.

**Comment by KirstieJane** [comment]
I love this @mr-c!! Thank you!

I don’t have opinions about “workflow” vs “pipeline” but I LOVE the idea of having a section that explains the two words and how they’re sometimes (confusingly?) used, and just picks one for the rest of the chapter. That kind of explanation is SO valuable and really helps demystify words that can mean many things in many contexts 💗💗💗

The rest of the ideas look great, please shout if you have any questions.

One of the things that a Jupyter book can do is render a Jupyter notebook as static html with an accompanying binder link. If that works for any of the ideas you have I’d be DELIGHTED to get more interactivity into the Turing Way 🚀 

As I said in the Gitter chat: aim for shorter rather than longer so we can get your chapter reviewed and merged and then extended as needed.

**Comment by mr-c** [comment]
Hello @vhellon ; you may be interested in our "Workflow thinking for novices" Carpentry-style tutorial at https://carpentries-incubator.github.io/cwl-novice-tutorial/

**Comment by vhellon** [comment]
Thanks Michael- will definitely be a good resource for anyone who picks up this chapter :)
