### ISSUE TITLE
workshop "Before You Start" section under title

### ISSUE THREAD

**Issue by JoannaLeng** [alan-turing-institute/the-turing-way#659]
To make it absolutely clear that the student will need a free trail subscription to Microsoft Azure and a Docker Hub account to complete the workshop I would put this in a small section just under the title and author called "Before You Start". This means the student can see this as soon as possible and so can take corrective action if needed. I would format this as a bullet list with one bullet per thing needed which is ideally less than a line in length and as links to other parts of the workshop or external links as necessary.

**Comment by sgibson91** [comment]
Thank you @JoannaLeng!!
