### ISSUE TITLE
Coordinate sprint to discuss and develop extension plan in October 2019

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#678]
### Summary

This issue is for coordinating the Turing Way extension sprint at The Turing Institute on Thursday 10 & Friday 11 October 2019.

### What needs to be done?

- [x] Invite core team members & identified extension stakeholders
- [x] Book room - David Blackwell
- [x] Build schedule according to availability - https://hackmd.io/@KirstieJane/TuringWaySprint_Oct2019#Agenda
- [x] Travel for team members who need it (@malvikasharan so far I think)

### Who can help?

* Anyone with eagle eyes. Have I missed anyone out from the list below? I'm writing this from Heathrow airport and it's SO LIKELY that I've made a terrible mistake!
* There's a section in the hackmd to capture [questions and topics for discussion](https://hackmd.io/13UyCKpKQqS3nfhyjrEOzA?both#Questions-and-topics-for-discussion) - please add any and all comments there!

---

#### Email sent on 3 October

> Hi everyone!
> 
> I've created an agenda [https://hackmd.io/@KirstieJane/TuringWaySprint_Oct2019#Agenda](https://hackmd.io/@KirstieJane/TuringWaySprint_Oct2019#Agenda) for the Turing Way sprint next week.
> 
> Please add or edit your names for the sessions you're able to attend by clicking on the pen button in the top right corner of the page.
> 
> You can add in parentheses if you're only available for part of the session, although please note that leaving early will be much less disruptive than arriving late to a session.
> 
> I've decided to shelve the ethics discussion because none of the public policy team are available. I'll send a separate email to schedule a discussion on a different day with Josh, Christina and David (et al).
> 
> There's a section for Questions and Topics for discussion too ([https://hackmd.io/@KirstieJane/TuringWaySprint_Oct2019#Questions-and-topics-for-discussion](https://hackmd.io/@KirstieJane/TuringWaySprint_Oct2019#Questions-and-topics-for-discussion)) so please also populate that section with any hopes and dreams for the sprint.
> 
> Thank you!
> Kx
> 

#### Email sent on 3 Sept 2019

> Hi Rachael, Rosie, Patricia, Malvika, Louise, Sarah, Anna, Becky, Martin, James G, James H, Catherine, Tania, Tim, Chris H, David B, David L, Christina, Josh, Emily, Amber, Gerrit and Alex,
> 
> You are all friends of the Turing Way. Thank you for all the work and support you've put into the project so far.
> 
> This summer we received funding for an 18 month extension of the Turing Way. We're going to expand from "just" reproducibility to include ethics, how to choose the right statistical model, communicating your research, and how to collaborate. You can read the approved application at https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/tps-funding-application-20190429.md.
> 
> I'd love for you to attend (all or part of) a two day sprint (remotely or in person) on 10 & 11 October.
> 
> The goal of the sprint will be to brainstorm how we extend The Turing Way and - ideally - come up with a list of desired chapters that could be written.
> 
> I've made a hackmd to build up the agenda. The first thing that I need is to know your availability. If you can complete the table there (or just email me the information if you're not sure about hackmd!) that would be amazing.
> 
> You're also welcome to please suggest other folks to invite by adding their names in the hackmd or by sending me a slack/gitter message/email etc. The hackmd is a public document, so if you have any information that you'd prefer to keep a little more confidential, please send me a private message :)
> 
> I'm sorry if the dates don't work for you, I know they won't work for everyone. This is definitely not the only time you can input on the future direction of the project. I'd love to hear your thoughts as we start to have these conversations.
> 
> Ping me if you have any questions! There will be more information to come once we know who can make it, but for now please save as much of the date as you'd like! The Turing Way will pay for travel and accommodation as necessary.
> 
> Kx
> 
> PS: If you can make the first Collaboration Cafe tomorrow that would be so cool!
> 
> * https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/online-collaboration-cafe.md
> * https://hackmd.io/@KirstieJane/CollabCafe20190904
> * https://turing-uk.zoom.us/my/kirstiezoom

**Comment by malvikasharan** [comment]
This event is finished and a report has been added in this PR #812
