### ISSUE TITLE
Add an Australia-friendly Collaboration Cafe session

### ISSUE THREAD

**Issue by orchid00** [alan-turing-institute/the-turing-way#684]
Hi @KirstieJane 

### Summary

https://twitter.com/kirstie_j/status/1171657515316240385

### What needs to be done?

May  I suggest an early UK session for the Collaboration Cafe
Either:
25 September, 8AM UK time
of
30 October, 8 AM UK time
https://arewemeetingyet.com/London/2019-10-30/08:00/TuringWay-CollaborationCafe

### Who can help?

anyone in South East Asia / Australia / New Zealand

**Comment by KirstieJane** [comment]
Heya! @orchid00!! Thank you so much for suggesting this!

25 September I'm actually giving a big overview of the Turing Way to the new PhD students at the Turing Institute so that's a bit of a difficult time for me.

But 30 October is great! I have a call already scheduled for 10am. If we started at 8am we'd just have to finish a little early so I can schoosh across to that other call. Do you think that would be ok?

**Comment by orchid00** [comment]
it should work!, let's do it! @KirstieJane :)
can anyone join?
how should I prepare?

**Comment by malvikasharan** [comment]
@orchid00 did you have a chance to discuss? Would you like me to help reach out to more people in Australian Time Zone to get involved with you? 

I am drafting a Newsletter, and thought maybe that's a good place to add this?

**Comment by orchid00** [comment]
Sure @MalvikaSharan, I'm actually not sure if this is confirmed

**Comment by KirstieJane** [comment]
So sorry @orchid00 for not replying! I'd [added the sesson on 30 October to the guide](https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/online-collaboration-cafe.md#dates-and-start-times) and forgotten to reply here!

Any ideas on promoting it - eg including in the newsletter or promoting on other mailing lists - are super valuable!!

**Comment by orchid00** [comment]
Invite them with "cheers hacktoberfest" 🍻 I'm sure that will call the attention :)

**Comment by EstherPlomp** [comment]
Hello from 2023 @orchid00, @malvikasharan, @aleesteele! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
