### ISSUE TITLE
Reflections on Build A BinderHub workshop

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#694]
### Summary

This issue is reflecting on the feedback I got from the Build a BinderHub session I ran at RSE Con UK 2019, which was captured in the following hackmd: [bit.ly/RSEConBinderHub](https://bit.ly/RSEConBinderHub).

I'm not certain how "closable" this issue is as it stands since a lot of this stuff will serve a reminder for the next time this workshop is run (by me or someone else). Maybe I should rekindle my idea of an "instructor guide" for this workshop.

### Open Questions

These are some questions that I don't think are actionable _yet_ because I'm on the fence as to the least painful solution. Opinions welcome! :sparkles:

- **Using the Azure Portal/Cloud Shell.** This time round, I used the Azure Cloud Shell rather than a local terminal to run the workshop. Should I continue this workflow or go back to a local terminal?
  - _Pros_: All the command line tools are preinstalled in the Cloud Shell so the prerequisites for the workshop are fewer and Windows users have fewer issues/can fully participate.
  - _Cons_: The Cloud Shell times out after 20 mins of inactivity meaning that some output is lost. Especially since the workshop broke for a 25min coffee break after deploying the cluster, and sometimes I did more speaking than typing. This is particularly problematic if the k8s deployment was unsuccessful for whatever reason.
  - _Consensus_: Stick with Cloud Shell. 
- **Using an Azure Pass myself.** When running this with Azure passes, should I register for one myself?
  - _Pros_: Reduces friction and I don't have to explain why my commands are different.
  - _Cons_: Issue is not solved if I run the session with Free Trials as I've already used mine up. Also, I lose the opportunity to explain why I am so adamant about not using an ".ac.uk" or organisational email address during sign up.
  - _Consensus_: Me not using a pass is probably not that disruptive.
- There was a request for **approximate timings** of stages to be added to the workshop instructions. These can be very difficult to predict as I've found it to be different every time I've ran it. What do the people who participated think?

### What needs to be done?

- [ ] When using Azure Passes, make the set-up of the account clearer. Users have to have a registered account to apply the Pass to. This could be a separate markdown doc so as not to confuse the main workshop instructions.
- [x] Add instructions for if the Cloud Shell doesn't automatically log a user in. The inline instructions are pretty clear, but adding a warning that this could happen would be best. (This may become redundant if we go back to using a local terminal.)
- [x] Add a note on nano editor for editing `setup.sh`. Stress that nano doesn't have to be used but it's the one I'll be demonstrating with.
- [x] Make it clearer that templates of what `config.yaml` and `secret.yaml` should/will look like are available at the end of the document. Do the same for `setup.sh`.
- [x] Use separate sections for Pluses and Deltas in a HackMD to nudge people into giving both kinds of feedback.
  - Create a HackMD template?!
- [ ] Workshop leader (me!) to make better use of the assistants in the room.
  - Talk to them about what I feel unsure about and ask that they feedback positive vibes about this
  - Ask them to sit and have a quiet chat with someone if they're not participating in the traffic lights. Questions to ask would be: what would you like out of this workshop?... (And others I'm sure!)
- [x] Add instructions for retrieving k8s deployment logs for if the Cloud Shell has timed out

### Who can help?

* Helpers: @annakrystalli @trallard, any feedback from you that you feel you didn't give me at the time would be great to hear!
* Attendees: @DavidBeavan @nbarlowATI @crangelsmith @teapowell @tallamjr, I know you already gave your feedback in the hackmd, but if you'd like to weigh in on anything here (particularly the open questions!) that would be greatly appreciated!
* @KirstieJane has already given me some offline advice which I've tried to capture here but if anything else occurs to you I always value your opinion!

---

**Comment by DavidBeavan** [comment]
+1 for Cloud shell, it saves tech support, different OS issues, firewalls, you name it. Plus, terminals time out if you shut laptop lids, or are on battery and go away for a bit.

**Comment by sgibson91** [comment]
> +1 for Cloud shell, it saves tech support, different OS issues, firewalls, you name it. Plus, regular ssh terminals time out if you shut laptop lids, or are on battery and go away for a bit. Unless you use screen/tmux

Thanks for the feedback @DavidBeavan! Though using a local terminal does not mean using SSH, as we'd just configure our local terminal to talk to `kubectl` and `helm` using the ` az aks get-credentials...` and `helm init` commands the same way we did in the Cloud Shell 🙂

**Comment by DavidBeavan** [comment]
@sgibson91 that sounds like a lot of apt-get or brew install for a dipping your toes in session. Windows users might be fun to support too ;)

**Comment by sgibson91** [comment]
Yes, that was my initial thought! Should I also include a script that keeps your Cloud Shell session active? 😄

**Comment by EstherPlomp** [comment]
Hello from 2023 @sgibson91! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

It looks like this issue is no longer being actioned, so we'll be closing it for now - however, please feel free to re-open it to continue working on it at any point! If you have any questions or concerns, please comment below ✨ Thank you!
