### ISSUE TITLE
Add section to reproducibility chapter on barriers to reproducibility

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#696]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the section about barriers to reproducibility in the already existing chapter on reproducibility.
 * This chapter is being written in #695 
 * This addition is being developed on the [`barriers-reproresearch`](https://github.com/alan-turing-institute/the-turing-way/tree/barriers-reproresearch) branch, specifically in the [`reproducibility/04/barriers.md`](https://github.com/alan-turing-institute/the-turing-way/blob/barriers-reproresearch/book/content/reproducibility/04/barriers.md) file.

## Assigning barriers

![image](https://user-images.githubusercontent.com/3626306/65597213-81f34800-df90-11e9-99c2-3ca57a31ddab.png)

@KirstieJane has been giving talks for years that cover 7 barriers to reproducible research, and as there are 9 groups at the Turing doctoral and enrichment student induction, she's added two more so that each group has one each.

1. Plead the 5th
2. Publication bias towards novel findings
3. Held to higher standards than others
4. Is not considered for promotion
5. Requires additional skills
6. Takes time
7. Support additional users
8. Big data and complex computational infrastructure
9. Being reproducible doesn't mean the answer is right

In this issue we will assign each of these barriers to a group (table) in the doctoral and enrichment student training, put the barriers in a list, and they will then submit a pull request to update just that barrier.

Here's hoping it works 🤞 😬 🤞

**Comment by JAEarly** [comment]
**Big data and complex computational infrastructure**
_JAEarly, georgiatomova, giuliaok, swalkoAI_
🐔 🐴 🌮 💁

**Comment by blue-moon22** [comment]
@blue-moon22 @mcaseySoton @domdanks Is not considered for promotion

**Comment by daniguariso** [comment]
@alessandroragano @lauracarter @kgrieman @daniguariso -Publication bias towards novel findings

**Comment by l-gorman** [comment]
Being reproducible doesn't mean the answer is right:
@l-gorman @PeterC-ATI @obisargoni @defaultobject

**Comment by fgh95** [comment]
**Takes time**
@ppintosilva @sethsh7 @fgh95

**Comment by ashenvi10** [comment]
@acork25, @tugceoruc, @ceciledebezenac, @vasilisstav, @ashenvi10
Requires additional skills

**Comment by martyn1fyles** [comment]
@martyn1fyles @mooniean @linkpark @LorenzoRimella @vitaly-zankin Plead the Fifth

**Comment by sallyob123** [comment]
@sallyob123 @akira-endo @solonkarapa @saramasa22 @risaueno
Held to higher standards than others

**Comment by DerienFe** [comment]
My table will take Support additional users. @augustinas1 @DerienFe @xc308 @takuover

**Comment by malvikasharan** [comment]
## Add these contributors to the contributor's table

#700 
All contributors were added.

#701
@all-contributors please add @blue-moon22 for ideas. 
@all-contributors please add Michael Casey Soton for ideas. (No GitHub)
@all-contributors please add Dominic Danks for ideas. (No GitHub)

#702 
@all-contributors please add @ashenvi10 for ideas. 
@all-contributors please add @ceciledebezenac for ideas. 
@all-contributors please add @tugceoruc for ideas. 
@all-contributors please add @vasilisstav for ideas. 
@all-contributors please add @acork25 for ideas. 

#703
@all-contributors please add @JAEarly for ideas. 
@all-contributors please add @georgiatomova for ideas.  
@all-contributors please add @swalkoAI for ideas.  
@all-contributors please add @giuliaok for ideas.  

#704
@all-contributors please add @ppintosilva for ideas.  
@all-contributors please add @sethsh7 for ideas.  
@all-contributors please add @fgh95 for ideas.  

#705 
@all-contributors please add @alessandroragano for ideas
@all-contributors please add @LauraCarter for ideas
@all-contributors please add @kgrieman for ideas
@all-contributors please add @daniguariso for ideas

#706 
@all-contributors please add @sallyob123  for ideas
@all-contributors please add @akira-endo  for ideas
@all-contributors please add @solonkarapa  for ideas
@all-contributors please add @saramasa22  for ideas
@all-contributors please add @risaueno  for ideas

#707 
@all-contributors please add @l-gorman   for ideas
@all-contributors please add @PeterC-ATI   for ideas
@all-contributors please add @obisargoni   for ideas
@all-contributors please add @defaultobject  for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @blue-moon22 for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @mjcasy for ideas and content.

**Comment by malvikasharan** [comment]
@all-contributors please add @ashenvi10 for ideas for #702

**Comment by malvikasharan** [comment]
@all-contributors please add @ceciledebezenac for ideas for #702

**Comment by malvikasharan** [comment]
@all-contributors please add @tugceoruc for ideas for #702

**Comment by malvikasharan** [comment]
@all-contributors please add @vasilisstav for ideas for #702

**Comment by malvikasharan** [comment]
@all-contributors please add @acork25 for ideas for #702

**Comment by malvikasharan** [comment]
@all-contributors please add @JAEarly for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @georgiatomova for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @swalkoAI for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @giuliaok for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @ppintosilva for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @sethsh7 for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @fgh95 for ideas.

**Comment by malvikasharan** [comment]
@all-contributors please add @alessandroragano for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @LauraCarter for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @kgrieman for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @daniguariso for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @sallyob123 for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @akira-endo for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @solonkarapa for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @saramasa22 for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @risaueno for ideas

**Comment by malvikasharan** [comment]
@all-contributors please add @l-gorman  for ideas in #707

**Comment by malvikasharan** [comment]
@all-contributors please add @PeterC-ATI   for ideas in #707

**Comment by malvikasharan** [comment]
@all-contributors please add @obisargoni   for ideas in #707

**Comment by malvikasharan** [comment]
@all-contributors please add @defaultobject  for ideas  in #707

**Comment by KirstieJane** [comment]
WOAH - I am 18 months late returning to this issue 😭 

Going to see if I can get this work merged to the book this afternoon / evening (Collaboration Cafe FTW!)

@malvikasharan - thank you so much for adding all these folks to the Contributors Table! AMAZING - do we need to do anything more for them if I do manage to merge their contributions?
