### ISSUE TITLE
Feedback on Collaboration Cafe format, schedule and Time Zones

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#711]
### Summary

You can 

Stemmed by the conversation started by Paula Andrea Martinez - @orcid00 on Twitter, we want to test if the online collaboration cafe can be run on time zones different from UTC/GMT.

### What needs to be done?

- [ ] Collect feedback on the [current format](https://github.com/alan-turing-institute/the-turing-way/blob/master/communications/collaboration-cafe/collaboration-cafe-template.md).
- [ ] Check interest from the community if they would like to see more collaboration cafes.
- [ ] Look for possible hosts in different time zones, starting from Australia - potentially led by @orcid00.

### Who can help?

* Members who want to participate or host in collab cafe at different time zones.
* Members who have ideas to help us plan this effectively.

---

### Updates

This issue link will be posted on an upcoming newsletter.

**Comment by KirstieJane** [comment]
@malvikasharan - do you mind if I make this issue broader? Feedback on Collaboration Cafes more generally? And then keep different time zones as a specific question?

**Comment by npscience** [comment]
Hello @malvikasharan @KirstieJane – I've been itching to get involved with a Collab Cafe, and I'm wondering when the next one might be planned for, please? May I come? 🙏

**Comment by malvikasharan** [comment]
Ooh, hey Naomi, so lovely to see you here. The next one is 1st July at 15:00 BST. If you wanna catch up on other days, we do have some low key coworking calls at 11:00, info here https://hackmd.io/@malvikasharan/TW-coworking

**Comment by npscience** [comment]
Thanks @malvikasharan – I'm going to head in for today's one (I can only stay for first hour, but excited to get started)

**Comment by EstherPlomp** [comment]
Hello from 2023 @malvikasharan! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

This concern has been brought up before (#684) and is included in our catch all issue (#2936) so that it can hopefully be actioned in the future!
