### ISSUE TITLE
lightning talk @ Open Science Community Nijmegen kick-off

### ISSUE THREAD

**Issue by KristijanArmeni** [alan-turing-institute/the-turing-way#717]
### Summary

A lightning talk on October 9, 15.00 (UK time), on the occassion of the [Open Science Community Nijmegen](www.openscience-nijmegen.nl) launch event. The final schedule and details are published [here](https://openscience-nijmegen.nl/events/01_oscn_launch/).

### What needs to be done?

- [x] *test call via Zoom (optional).* (@KirstieJane)

### Who can help?

---

### Updates

Zoom available on site for video call. Test call can be done anytime between 11.00 and 15.00 (UK time) on Oct 9.

**Comment by KirstieJane** [comment]
Sounds great! Thanks @KristijanArmeni! Can I do a video check at 14:30 UK (15:30 Netherlands)?

**Comment by KristijanArmeni** [comment]
Yes, @KirstieJane that sounds perfect. Noted for test call 14:30 (UK). I will create a Zoom meeting called `OSCN kick-off`. Will share the meeting url with you. I guess that's all you need. 

I'm new to Zoom, so if I need to know anything else from your end (e-mails, usernames etc.), just let me know the details.
