### ISSUE TITLE
(How) Does MIT license apply to book contents?

### ISSUE THREAD

**Issue by effigies** [alan-turing-institute/the-turing-way#718]
### Summary

Hi all, I'm putting together a talk on reproducibility, and in particular I want to use the graphic [here](https://the-turing-way.netlify.com/reproducibility/03/definitions.html#the-turing-way-definition-of-reproducibility) and appropriately cite it. The only license I can find quickly (admittedly a 5 minute search) is the [MIT License](https://github.com/alan-turing-institute/the-turing-way/blob/master/LICENSE), which is a software license, which I'm not sure how to interpret in the context of what is mostly non-executable content.

Is there guidance on reusing the contents of The Turing Way in other contexts? My inclination is simply to say something like:

> From [The Turing Way, Ch. 2](https://the-turing-way.netlify.com/reproducibility/03/definitions.html#the-turing-way-definition-of-reproducibility). License: [MIT](https://github.com/alan-turing-institute/the-turing-way/blob/master/LICENSE). Accessed 15 October 2019.

If the guidance exists, it would be nice if it were more prominent in the document itself, e.g., in the first or (near) final chapter.

And, assuming that the MIT license does apply to the textual contents and not just the code, I might consider a second, less software-oriented license for the text. (Though I can see that two licenses might induce more confusion than they relieve...)

### What needs to be done?

- [ ] Guidance on citation
- [ ] Optional: Add guidance to document

### Who can help?

* Anybody, likely.

---

**Comment by KirstieJane** [comment]
Heya! Great question! I thought we had a CC-BY licence so I'm glad you pointed this out @effigies!

I've opened https://github.com/alan-turing-institute/the-turing-way/pull/720 to address this - what do you think?

**Comment by KirstieJane** [comment]
Oh - and we do have a DOI on zenodo - I'm waaaay behind on updating different releases (#648 #655 #384 etc 😭), but the generic doi will work for citing: https://doi.org/10.5281/zenodo.3233853 and that is under a CC-BY licence for sure.
