### ISSUE TITLE
Chapter: Project management and contributing with GitHub issues

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#730]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on "Project management and contributing with GitHub issues".
 * This chapter is being written in (PR is not open yet)
 * This chapter is being developed on the (not yet named) branch.

### Resources

* https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f
* https://github.com/jupyter/repo2docker/issues/new/choose
* https://github.com/stevemao/github-issue-templates
* https://guides.github.com/features/issues/
* https://github.blog/changelog/2019-01-18-more-reaction-emojis

### Discussion points/related issues

This issue was opened during a reproducible research lunch on 28 October led by @KirstieJane. The topic was project management with GitHub issues so we'll use this space to capture important points to include in the book.

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [ ] Write chapter outline
 - [ ] Add material to the chapter
 - [ ] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates
To avoid that others have to read through the full thread of comments, update the initial issue with important updates (e.g. decisions taken) regularly so that all the important information is available at one glance.

**Comment by KirstieJane** [comment]
Notes from the discussion:

* Researchers aren't trained to work this way!
* Avoiding merge conflicts - these come from people doing work at the same time in an un-coordinated way! Committing to master causes some level of mayhem, working in totally separate branches means you can't see what others are doing.
* Distinction between using GitHub for version control but not using issue for project management - lots of other ways to do that
* Even if confident with GitHub & project management its easy to be "lazy" about how you write issues! A lot of implicit knowledge.
* Difficult to make an issue in someone else's project - don't know who they are! Don't know what they want 😬 
* It is really hard to manage issues across multiple GitHub repositories
* Issue best practice - updating as you go along
* They're really helpful! And super fun! It feels really good to close an issue.


There might be an issue already open that covers this - for example I think there's one on how to open source (#685)

**Comment by harisood** [comment]
Hello from 2023 @KirstieJane! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
