### ISSUE TITLE
How the book interoperates with other resources?

### ISSUE THREAD

**Issue by mkuzak** [alan-turing-institute/the-turing-way#736]
This issue have been triggered by the discussion around the differences and synergies between The Turing Way and the [Software Development Guide](https://guide.esciencecenter.nl) by the Netherlands eScience Center.

### Summary

Both resources contain similar content, regarding software development best practices. The Turing Way focuses at the moment on open and reproducible research, the eScience Guide on the other hand goes into more detail on software development tools around particular languages use at the Center. We don't wont to duplicate the content or rewrite it in both of the resources. We had a brief internal discussion in the Center about it and we may decide to contribute to the Turing Way on the content that fits in there, that includes migrating some content from the Guide, and keeping the Software Guide more engineering and Center specific.
This process will also help defining the template for resolving similar issue with other resources.

### What needs to be done?

In order to do that we need to:

- [ ] define the mission (focus) of both of the resources
- [ ] define how Guide content can enrich the Turing Way content
- [ ] migrate the the relevant Guide content to Turing Way

### Who can help?

We will need people involved on both sides, the Turing Way and the eScience Center

---

### Updates
- before filing the issue, it has been discussed at the [CollabCafe](https://hackmd.io/@KirstieJane/CollabCafe) on 30 Oct 2019, with @KirstieJane @pherterich @orchid00 present
- the issue have been filed to start the discussion

**Comment by dingaaling** [comment]
Hello from 2022 @mkuzak! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. This issue looks like it has now been incorporated in the Turing Way in some way or is no longer being actioned. Therefore we will now be closing this issue. If you have any questions or concerns, please comment below ✨ Thank you!
