### ISSUE TITLE
Everyone adds their preferred method of communication to Ways of Working document

### ISSUE THREAD

**Issue by r-j-arnold** [alan-turing-institute/the-turing-way#74]
## Description

The ways_of_working.md file has a place for us all to put the way we'd prefer to be contacted. This issue follows on from #69.  

Still missing input from
- [x] @KirstieJane 
- [x] @martintoreilly

**Comment by pherterich** [comment]
Reminder to @KirstieJane and @martintoreilly to add this or let us know if they would prefer to be removed from the list of people contactable.

**Comment by martintoreilly** [comment]
Updated in #153.

**Comment by r-j-arnold** [comment]
All done, closing.
