### ISSUE TITLE
Collect material for December 2019 newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#749]
### Summary

This issue is to capture news and updates to be added to the December 2019 newsletter

### What needs to be done?

- [ ] Add links, pictures and tweets that you'd like to be included in the next Turing Way newlsetter

### Who can help?

* Anyone in the community!

---

### Updates

No updates so far

**Comment by malvikasharan** [comment]
Highlights from the year, i.e. total book dashes, online events, success and failures

**Comment by KirstieJane** [comment]
Open the call for the London book dash in February 2020 😄

**Comment by KirstieJane** [comment]
https://n8cir.org.uk/news/reprohacks/ - lets advertise this from @annakrystalli 🎉

**Comment by pherterich** [comment]
Mention that registration for CollabW20 is open and you can meet many Turing Way collaborators there?

**Comment by annakrystalli** [comment]
> https://n8cir.org.uk/news/reprohacks/ - lets advertise this from @annakrystalli 🎉

That would be awesome! Let me know if you need anything from me

**Comment by pherterich** [comment]
#772 is sent out, so closing this.

**Comment by KirstieJane** [comment]
Thank you @pherterich!
