### ISSUE TITLE
Present Zero-to-Binder at PyCon Namibia? 

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#761]
https://na.pycon.org/call-proposals/

I think the Zero-to-Binder tutorial in its current form (i.e. totally python!) would be a good candidate for a workshop here. 

Deadline for proposals is **27th December**.

**Comment by KirstieJane** [comment]
Ooooooh - I love it! Yes! 

Would you like to lead on this @sgibson91? Do we have any local community members who can be helpers? Tagging @trallard incase she has any suggestions for folks to connect with?

**Comment by sgibson91** [comment]
I might've over booked myself now 😬

**Comment by trallard** [comment]
I'm planning to be there. 
I know a few folks from there.
My main concern is Internet - I have heard from folks that were there that it's such a huuuuuge blocker!

**Comment by sgibson91** [comment]
Awkwardly, when I was observing in Namibia, I was trying to Skype call my mum back home and the connection in _Hull_ was too terrible.

Anyway, back on topic. I've been offered a seminar on 12th Feb and I have personal commitments around the end of Feb, plus a rough costing (£600 flights, £150 visa) and no (obvious) travel bursaries from the conference itself. All in all, I'm not sure I have the time or the Turing have the funds to attend (at least in such a way that I can enjoy Namibia 😄)
