### ISSUE TITLE
[BUG] all-contributors bot may be broken

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#776]
### Summary

I've been trying to add new contributors but keep receiving the message "We had trouble processing your request. Please try again later."

* See this issue on the all-contributors repo: https://github.com/all-contributors/all-contributors-bot/issues/262
* See this PR for example of bug: https://github.com/alan-turing-institute/the-turing-way/pull/763

### What needs to be done?

- [ ] Be aware that this might be an ongoing issue
- [ ] Maybe choose another contribution-tracking service if this one isn't fixed

### Who can help?

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by CSRedRat** [comment]
I have some problem: https://github.com/CSRedRat/topalias/pull/4
will try without .allcontributorsrc and with .allcontributorsrc

**Comment by sgibson91** [comment]
@CSRedRat this will almost definitely be due to a misconfigured .all-contributorsrc file. It may be easier to download the CLI and generate the file that way, unless you can use an editor and JSON prettifier to track down the missing character.
