### ISSUE TITLE
Submission for "Reproducibility, Replicability and Trust in Science"

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#777]
### Summary

09 - 11 September 2020
Wellcome Genome Campus, UK

"This new meeting will bring together an international audience of researchers motivated to improve the robustness of scientific research. It will also involve important stakeholder groups: data and services providers, publishers, institutions and funders that are developing policies and tools.

The overarching theme of this conference is to position the challenge of reproducibility and replicability as a behaviour-change problem that when addressed can lead to culture change within research. The programme will explore how the right incentives can drive positive behaviour, with examples presented from a variety of groups and organisations. We will also focus on the development and implementation of open science tools, which can help researchers produce transparent, trustworthy and therefore potentially better-quality scientific outputs.

The meeting will also stimulate collaboration on practical measures that can improve the quality of scientific enquiry and reporting. We will focus on the evidence base for such measures and tools, and discuss their effectiveness and impact."

https://coursesandconferences.wellcomegenomecampus.org/our-events/reproducibility-replicability-trust-in-science-2020/

### What needs to be done?

Put in a submission **by 14 June 2020**

### Who can help?

* @malvikasharan ?

---

### Updates

No updates yet

**Comment by harisood** [comment]
Hello from autumn 2022 @pherterich! Hope all is well with you, many months later. The TTW Core team is following up on issues in our backlog and wanted to check if we now should close this issue? If so, feel free to comment or 👍  this comment. If not, please leave a comment on how we could revive this thread and how we can support this work.

We'll leave the issue open for now, and if we don't hear from you by mid-November we'll mark it as closed - but we are always happy to reopen it! Thank you!
