### ISSUE TITLE
Collect material for January newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#778]
### Summary

Here's an issue to capture content for the January newsletter.

### What needs to be done?

- [x] Add any content that you'd like to include!
- [x] Should we try to send this _before_ the 16 January deadline for the book dash applications or after? There might not be a huge amount of content before (eg) 13 Jan but it would be good to send a reminder?

### Who can help?

* Anyone! Promote your content!

---

### Updates

No updates so far

**Comment by pherterich** [comment]
@nadiasoliman just used the illustrations in her webinar talk on leadership and colloboration https://twitter.com/PHerterich/status/1206966606397628416 ❤️

**Comment by rainsworth** [comment]
Plug for Collaborations Workshop 2020 please?

> The Software Sustainability Institute's [Collaborations Workshop 2020 (CW20)](http://bit.ly/ssi-cw20) will take place from 31 March - 2 April 2020 at [Queen's University Belfast](http://qub.ac.uk/), Northern Ireland and registration is now open on [Eventbrite](https://www.eventbrite.co.uk/e/collaborations-workshop-2020-cw20-collabw20-tickets-72375437883?aff=TuringWay)! This workshop brings together researchers, developers, innovators, managers, funders, publishers, leaders and educators to explore best practices and the future of research software. The themes of the keynote presentations, demos, discussion groups, panel sessions and more at CW20 are: Open Research, Data Privacy and Software Sustainability. The [call for proposals for mini-workshop and demo sessions](https://www.software.ac.uk/news/call-proposals-mini-workshops-and-demo-sessions-collaborations-workshop-2020) is open until 31 January, and these sessions are unique opportunities for CW20 participants and sponsors to share a particular software product, approach, standard, or other idea relating to the workshop themes, research software and pitches for the Hackday.
> 
> ![GroupArmsCW19 copy](https://user-images.githubusercontent.com/10600877/72159804-1608e400-33b5-11ea-9db6-91705f8cacb8.png)

**Comment by rainsworth** [comment]
Also a congrats to the *Turing Way* members who are 2020 SSI Fellows! 🎉

**Comment by KirstieJane** [comment]
So many cool updates!! 👾

**Comment by KirstieJane** [comment]
Ready to send in #787 🚀
