### ISSUE TITLE
Small typo in Chapter 2.3

### ISSUE THREAD

**Issue by m-rivera** [alan-turing-institute/the-turing-way#784]
### Summary

Hi, I just found a little typo on the word "reporducibility" in:
book/content/reproducibility/03/definitions.md

### What needs to be done?

- [x] Replacing the word "reporducibility" by "reproducibility"

### Who can help?

I would like to submit a pull request if possible 😊

---

**Comment by m-rivera** [comment]
Here is the pull request #785

**Comment by malvikasharan** [comment]
Thank you so much @m-rivera for taking the time to create an issue and a pull request!! 🎉 @KirstieJane will approve it as soon as possible.

**Comment by malvikasharan** [comment]
This has been sorted.
