### ISSUE TITLE
Create guidelines for writing newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#789]
### Summary

We have a great template for writing the monthly newsletter but I don't think those guidelines are captured in the repository somewhere. (Correct me if I'm wrong).

### What needs to be done?

- [x] Get the template into markdown from [this google doc](https://docs.google.com/document/d/1cs1y5GsMM_QC9Y6BADT0AHttoVuap-lL2dshxky2OFA/edit).
- [x] Describe step of reviewing issue to capture materials for this month
- [x] Describe step of opening an issue to capture materials for _next_ month
- [x] Add guidance on naming: `newsletter_[number]_[Month][Year].md
- [x] Describe how to add images to GitHub repository
- [ ] Add guidance on how to log into tinyletter (and what it is)
- [x] Add guidance on converting from markdown to html for tinyletter: https://www.browserling.com/tools/markdown-to-html
- [ ] Describe how to send draft email as test 

### Who can help?

* @KirstieJane & @malvikasharan are currently sending out the newsletters
* But any other team member if not! @pherterich or @rainsworth have both sent them out 😄 

---

### Updates

*No updates at this time.*

**Comment by srishti-nema** [comment]
Hi @KirstieJane , can I help with this? I think I can start with some of the tasks mentioned in that list, but I will need some guidance. Let me know soon. Thanks.

**Comment by malvikasharan** [comment]
Hey @srishti-nema, this is already recorded, however, we do have it missing in the current repository so that's on me. If you are interested, can you instead of newsletter please write a guide on something @KirstieJane has mentioned in our GSoD issue #1075 

> Short chapters on how to write a paper, how to write an abstract (I love [this example from Nature](https://www.nature.com/documents/nature-summary-paragraph.pdf)), how to write a bio (I know someone had a great template for this and I can't remember who now!) would also be great for the Communication series of chapters.
