### ISSUE TITLE
Share your impact statement

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#790]
### Summary

Has _The Turing Way_ made an impact on your life or work? Has it made you more efficient or allowed you to learn a new skill?

We'd love to hear from you about how the project is supporting your work, by adding your name and story to our [impact statements](https://github.com/alan-turing-institute/the-turing-way/tree/master/project_management/impact_statements). They only need to be a few sentences long, short is beautiful and very easily quotable in future impact assessments!

You can see examples from [Patricia](https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/impact_statements/patricia_herterich.md) and [Rachael](https://github.com/alan-turing-institute/the-turing-way/blob/master/project_management/impact_statements/rachael-ainsworth.md) to inspire you!

Thank you, we really appreciate hearing from you 💖 

### What needs to be done?

- [ ] Open a pull request to contribute your story
- [ ] Add more detailed guidance on what an impact story is, via #786

### Who can help?

* YOU!
* (anyone 🤗 )

---

### Updates

*No current updates.*

**Comment by EstherPlomp** [comment]
Hello from 2023 @KirstieJane! Hope all is well with you, many months later. The TTW Core team is currently reviewing issues in our backlog to determine how they can best be taken forward. 

We think this is a great issue for somebody to pick up in the future - we've added it to our catch-all issue (#2936) for someone to browse and pick up. However, we'll close it for now as it looks like it's no longer being actioned, though please feel free to re-open it to continue working on it at any point! If you have any other thoughts on how to continue moving this issue forwards, please comment below ✨ Thank you!
