### ISSUE TITLE
Collect material for February newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#791]
### Summary

Here's an issue to capture content for the February newsletter.

### What needs to be done?

- [ ] Add any content that you'd like to include!

### Who can help?

* Anyone! Promote your content!

---

### Updates

No updates so far

**Comment by KirstieJane** [comment]
### Upcoming events

* csv,conf,v5 -- https://csvconf.com
  * call deadline 7 Feb: https://docs.google.com/forms/d/e/1FAIpQLSe71P3slET9b7FxA429hYLW7LQMUVIFMZEGNzh9c5U1L6-Jdw/viewform
* Neurohackademy -- https://neurohackademy.org
  * application deadline: 1 March: https://neurohackademy.org/apply

### Turing Way presentations
* Kirstie presenting at OpenMR Benelux -- https://openmrbenelux.github.io/page-program

**Comment by pherterich** [comment]
We've inspired a whole new Jupyter book ✨ https://twitter.com/SusannaASansone/status/1222457621019594753

**Comment by KirstieJane** [comment]
SO COOL! Thanks for sharing @pherterich!

Closing so I can open March's issue!
