### ISSUE TITLE
Broken link in CONTRIBUTING.MD

### ISSUE THREAD

**Issue by EstherPlomp** [alan-turing-institute/the-turing-way#794]
### Summary

"If you open a new issue, please follow our basic guidelines laid out in our issue template." 
The link to the issue template in CONTRIBUTING.MD does not work. 
https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md 

### What needs to be done?

- [ ] Update the ISSUE_TEMPLATE.md file?

### Who can help?

* Kirstie/Malvika?
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by IIITM-Jay** [comment]
@malvikasharan , @EstherPlomp fixed this issue at #1091
