### ISSUE TITLE
Present work at Collaborations Workshop 

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#80]
## Detailed description
 - The collaborations workshop is the software sustainability institute's annual (un) conference. It will be held from Apr 1 to 3 2019 in Loughborough. 
 - @KirstieJane is on the programme committee and will plan to launch The Turing Way at their unconference or during the hackathon
 - https://www.software.ac.uk/cw19
 - This is mostly a placeholder issue to make sure that we all know that the project will be represented at CW19 ✨ 

---

* _The Turing Way_ demo is on the CollabW19 agenda: https://software.ac.uk/cw19/mini-workshops-and-demos-sessions
* We have a crew of 7 people attending for all 3 days: @LouiseABowler, @r-j-arnold, @KirstieJane, @sgibson91, @martintoreilly, @annakrystalli, @pherterich
* Hotel request sent to [Link hotel](https://www.linkhotelloughborough.co.uk/) for everyone
* Amber has paid for everyone's registration (THANK YOU! 🙌)

### TO DO

**Check this box when you have registered via the link I sent in your email**

- [ ] @annakrystalli 
- [x] @r-j-arnold 
- [x] @KirstieJane -- Kinda - paid twice so just coordinating re-fund 😬 
- [x] @LouiseABowler 
- [x] @martintoreilly 
- [x] @pherterich 
- [ ] @sgibson91 

**Turing folks, please book travel**

Turing folks - @martintoreilly, @sgibson91 and @LouiseABowler - please book your travel through gray dawes. I think you all have the project codes. Ping me if you need them again 😄 
> We're all currently taking different trains home. Happy to coordinate (via slack) if you'd like to, but also fine to travel separately! 

@pherterich, @annakrystalli and @r-j-arnold I'll book your trains ✨ 

- [ ] @KirstieJane book trains for non-Turing folks
---

### Previous to do notes

- [x] Submit a session (done, see below)
- [x] Find out whether other members of the team can attend (how much funding do we have?)
  * Done - everyone in the core team who wants to can attend
- [ ] Everyone reply to this thread with whether they would like to attend, which days and where they're travelling from.
  * Hotel for night of 31 March: @LouiseABowler, @r-j-arnold, @KirstieJane, @sgibson91, @martintoreilly, @annakrystalli, @pherterich
  * Hotel for night of 1 April: @LouiseABowler, @r-j-arnold, @KirstieJane, @sgibson91, @martintoreilly, @annakrystalli, @pherterich
  * Hotel for night of 2 April: @LouiseABowler, @r-j-arnold, @KirstieJane, @sgibson91, @martintoreilly, @annakrystalli, @pherterich
  * Return train from Sheffield to Loughborough: @r-j-arnold 31 March at 10:24 --> 3 April at 18:45; @annakrystalli 31 March at 16:19 --> 3 April at 20:05
  * Return train from London to Loughborough: @LouiseABowler, 31 March at  :white_medium_square: --> 3 April at :white_medium_square:, @sgibson91 31 March at 15:10 --> 3 April at 18:26
  * Return train from Birmingham to Loughborough: @pherterich 1 April --> 3 April
   1 April 7:52 leaving Birmingham New Street arriving at 9:04, open return will be cheapest and leaves me with flexibility for the return on 3 April
  * Single train from Peterborough to Loughborough: @KirstieJane, 31 March at 17:53
  * Single train from Loughborough to London:  @KirstieJane, 3 April at 18:53
  * Return train from London to Loughborough: @martintoreilly [flexible fares]
      * Outbound: 31 March at 18:40
      * Return: 03 April at 18:53
  * Not attending: @rosiehigman, @alexmorley 
- [x] Pay for registration - Amber 🙏 
- [x] Register via the special link in your email: @LouiseABowler, @r-j-arnold, @KirstieJane, @sgibson91, @martintoreilly, @annakrystalli, @pherterich

---

__Update__

* @KirstieJane submitted a session (and registered herself)

> ***Title:*** The Turing Way: A handbook for reproducible data science
>
> ***Description:*** Reproducible research is necessary to ensure that scientific work can be trusted. Funders and publishers are beginning to require that publications include access to the underlying data and the analysis code. The goal is to ensure that all results can be independently verified and built upon in future work. This is sometimes easier said than done. Sharing these research outputs means understanding data management, library sciences, sofware development, and continuous integration techniques: skills that are not widely taught or expected of academic researchers and data scientists. The Turing Way is a handbook to support students, their supervisors, funders and journal editors in ensuring that reproducible data science is "too easy not to do". It includes training material on version control, analysis testing, and open and transparent communication with future users, and build on Turing Institute case studies and workshops. This project is openly developed and any and all questions, comments and recommendations are welcome at our github repository: https://github.com/alan-turing-institute/the-turing-way. During this session lead developer of the project, Kirstie Whitaker, will lead a collaborative review of the content so far and show CW19 participants how they can contribute their knowledge to make it even better going forwards.

* Approved for all team members to attend ✨ 🙌 @pherterich @martintoreilly @LouiseABowler @alexmorley @rosiehigman @sgibson91 @annakrystalli @r-j-arnold - see the `to do` action above 😸

**Comment by r-j-arnold** [comment]
Maybe come up with a feature we want to add, and run that as a project at the hack day so people can work on the project in some capacity and be more invested in it.

**Comment by LouiseABowler** [comment]
I can do all three days, and travelling up the day before would definitely make things easier - could you book the nights of the 31st, 1st and 2nd for me? Thanks @KirstieJane!

**Comment by sgibson91** [comment]
@KirstieJane same as @LouiseABowler for me too please

**Comment by pherterich** [comment]
I think @rgaiacs tried to convince me to do something social on Sunday, but I don't think I can come up with a nerdy crochet project to teach people, so I will come on Monday morning as travel from Birmingham is short and stay the 3 days. I'll update the top comment accordingly.

**Comment by pherterich** [comment]
@KirstieJane All the trains for you guys currently have 2 April as return date - I assume this should be the 3rd? I don't want to be alone on the hackday :fearful:

**Comment by r-j-arnold** [comment]
Good point @pherterich I'd also like to return on the evening of the 3rd

**Comment by sgibson91** [comment]
I assume @LouiseABowler and I should have return train on the 3rd too, especially since we're down to stay the night on the 2nd

**Comment by rgaiacs** [comment]
> I think @rgaiacs tried to convince me to do something social on Sunday, but I don't think I can come up with a nerdy crochet project to teach people

I did! You can use the hackday to build your crochet project. ;-)

**Comment by pherterich** [comment]
This might be a bit off topic and I might hate myself for the suggestion, but podcasts such as http://www.openscienceradio.org/ are always looking for content and love reports from relevant conferences. I have no podcasting experience but am willing to try, could this be a hackathon project to have us introduce the Turing Way to that audience and get some quotes from attendees on what they think?

**Comment by KirstieJane** [comment]
@pherterich - that sounds like a really fun project! I do think it's pretty likely to be quite a lot of work so might be better to link up with folks we know who have experience podcasting than recording our own? If you want to give it a whirl though, please do take it forwards. 

This leads to a bigger question about whether members of the Turing Way team will be "allowed" to work on other hackathon projects or expected to work on the Turing Way project. **What do you all think?** Would you like to have the option to join whichever projects you'd like, or commit in advance to the Turing Way project?

**Comment by KirstieJane** [comment]
Sorry for the mistake with the train times! Thank you @sgibson91 & @pherterich for fixing! 😬 

@martintoreilly, @alexmorley, @annakrystalli @rosiehigman - would you like to attend the Collaborations workshop? Can you let me know which days you'd like to attend and if you need trains & hotel 😸

**Comment by r-j-arnold** [comment]
Could I get the 10:24 train from Sheffield to Loughborough on 31/03/19 and return on on 18:45 one from Loughbororugh on 03/04/19?

I'd love to have the option to work on other projects is something super interesting comes up, but take the turing project as the default..

**Comment by pherterich** [comment]
@rgaiacs is there a way to ping people ahead of time to ask if anyone has podcasting experience and equipment and would be up for this?

@KirstieJane what exactly have we planned for The Turing Way throughout the hackathon? Always happy to continue working on that, but I'm wondering if joining relevant other groups and trying to link them up could be of value?

**Comment by rgaiacs** [comment]
> is there a way to ping people ahead of time to ask if anyone has podcasting experience and equipment and would be up for this?

@pherterich Yes. By mid-March we will have Slack or another chat live for attendees.

The institute has some equipment that we will bring to CW. We can lend it for the hackthon.

**Comment by sgibson91** [comment]
I'm providing dates/times here for reference but actually it works out cheaper to buy a **Super Off-Peak Return for London St Pancras to/from Leicester** and an **Off-Peak Return for Leicester to/from Loughborough**. I have a 26-30 railcard too.

**Sunday 31st March:**
* 15:10 -> 16:38: London St Pancras to Leicester
* 20:10 -> 20:23: Leicester to Loughborough

**Wednesday 3rd April:**
* 18:26 -> 18:36: Loughborough to Leicester
* 19:03 -> 20:11: Leicester to London St Pancras

**Comment by LouiseABowler** [comment]
Can I go for the following trains please? I've got a 16-25 railcard.
* **Sunday 31st March:** London St Pancras 18:40 - Loughborough 20:23
* **Wednesday 3rd April:** Loughborough  18:53 - London St Pancras 20:11

Those times should work out as a super off-peak return, but could you still book seats?

**Comment by LouiseABowler** [comment]
I'd be interested to see what the other projects are, but also happy to work on The Turing Way during the hackathon. Do any of you know how big the teams usually are? We'll need to make sure there's space for a decent number of people to join in with us, and if we do spread out into different teams we can keep an eye out for possible link-ups, as @pherterich said earlier.

**Comment by r-j-arnold** [comment]
@LouiseABowler I went last year and some groups were just two or even one person. However there was at least one huge group, upwards of 10 if memory serves.

**Comment by sgibson91** [comment]
Could we get a BinderHub hack going during the Hackathon? 😅

**Comment by martintoreilly** [comment]
@KirstieJane Please could I go for the same trains as Louise with a hotel for the Sunday-Tuesday nights? Thanks.

**Comment by martintoreilly** [comment]
@sgibson91 A BinderHub hack would be very cool!!

**Comment by martintoreilly** [comment]
@KirstieJane I realise I missed your organising day yesterday. If it's easier for me to book myself for the conference, trains and hotel then let me know.

**Comment by pherterich** [comment]
Can we close this one or are there any leftover tasks that I'm not aware of?
