### ISSUE TITLE
Expand definitions of reproducibility grid 

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#802]
### Summary

In the ["definitions" section](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/content/reproducibility/03/definitions.md#the-turing-way-definition-of-reproducibility) of the reproducibility chapter we have a _picture_ of the reproducibility matrix but we don't actually _explain_ what the different cells mean.

![](https://raw.githubusercontent.com/alan-turing-institute/the-turing-way/master/book/content/figures/reproducibility/ReproducibleMatrix.jpg)

When @KirstieJane talks about this matrix she (I) always says that this is what *we* mean when we use these terms, not that everyone needs to use the same terms! @emdupre recommended this paper [Reproducibility vs. Replicability: A Brief History of a Confused Terminology](https://doi.org/10.3389/fninf.2017.00076) which would be good to link to to make that doubly clear.

### What needs to be done?

- [ ] Add a few sentences or bullet points to explain the matrix
- [ ] Add reference to "Reproducibility vs. Replicability: A Brief History of a Confused Terminology" (doi: https://doi.org/10.3389/fninf.2017.00076) to clarify that 
- [ ] Open a pull request to update the book 💖 

This could be combined with #765 (adding in a different but very similar matrix schema) if you're feeling motivated. (But doesn't have to!)

### Who can help?

* Anyone who has heard @KirstieJane talk over the last 5 years! The table is quite easy to interpret but there are always [tweets from folks online](https://twitter.com/doujouDC/status/1219994862659014657?s=20) who see it out of context and therefore don't know what they're looking at!

---

### Updates

*No updates so far.*

**Comment by sgibson91** [comment]
🙋🏻‍♀️ I can tackle this at the Book Dash next week 📖💨
