### ISSUE TITLE
Creating Cross Stitch Kits as gifts for Book Dash attendees

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#807]
### Summary

This issue is tracking the creation of some Jupyter/Binder/Turing Way themed cross stitch kits to give as gifts to the attendees of the February 2020 Book Dash. The aim is to create 25 kits for attendees and helpers.

### What needs to be done?

- [x] Create a cross stitch pattern of the Binder logo
- [ ] (Optional) Create a "hub sweet hub" pattern featuring the Jupyter logo
  - Guidance on using the logo can be found here: https://github.com/jupyter/design/blob/master/brandguide/brand_guide.pdf
- [x] Create some "How to Cross Stitch" instructions
- [x] Buy resources
- [x] Package kits up for distribution
- [x] Submit expenses claim for resources

### What needs to be bought?

- [x] Aida fabric
- [x] Coloured thread/floss
  - [x] DMC 335 (red) - 13/26
  - [x] DMC 728 (yellow) - 14/26
  - [x] DMC 996 (blue) - 12/26
- [x] Embroidery hoops - 3 inch - 26/26
- [x] Needles - 24/26
- [x] Something to package the kits in
  - [x] Tissue paper
  - [x] Paper bags

### Who can help?

* Kirstie

---

### Updates

- I decided not to give whole skeins of cotton to each kit. Its a lot of thread for a small design (1 skein = 8m of thread), especially if the materials aren't going to be reused. I have some thread organisers and will portion out the threads for each kit.

**Comment by sgibson91** [comment]
I'm happy to upload the resources I've created (pattern charts, how-to guides) to the repo. Where's best to place them? In the [book dash resources folder](https://github.com/alan-turing-institute/the-turing-way/tree/master/workshops/book-dash) or a new "other/fun" folder?

**Comment by pherterich** [comment]
I want one, too 😭 - can I buy one?

**Comment by sgibson91** [comment]
@pherterich I'll put one aside for you 😊

**Comment by pherterich** [comment]
Thank you - I would totally accept a cross stitch kit and some stickers at CollabW20 😉

**Comment by sgibson91** [comment]
@KirstieJane here's an idea. Do we want to put a selection of stickers inside the goodie bag, or just let people choose?

**Comment by sgibson91** [comment]
Packaged up!

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">And done! <a href="https://t.co/M8D0ugpLwU">pic.twitter.com/M8D0ugpLwU</a></p>&mdash; Sarah Gibson (@drsarahlgibson) <a href="https://twitter.com/drsarahlgibson/status/1229085926363738117?ref_src=twsrc%5Etfw">February 16, 2020</a></blockquote>

**Comment by sgibson91** [comment]
Checklist complete so I'm closing 🚀
