### ISSUE TITLE
Containers page contains some errors and suboptimal advice

### ISSUE THREAD

**Issue by mwoodbri** [alan-turing-institute/the-turing-way#810]
### Summary

I spotted some errors and potential improvements in relation to the [Containers](https://the-turing-way.netlify.com/reproducible_environments/06/containers) page in the  Reproducible Environments chapter.

### What needs to be done?

- [x] Remove redundant/repeated commands in `Dockerfile` example
- [x] Update the Dockerfile to reflect current [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

### Who can help?

* Me: I'll open a PR!

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by KirstieJane** [comment]
That's wonderful @mwoodbri!! Thank you 🚀 🌟
