### ISSUE TITLE
Add new contributors

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#815]
allcontributor bot is broken (see #776), please queue these users as contributors

1. Bug reports
    - @EstherPlomp ✔️ 
    - @nathanbegbie ✔️ 
    - @kir0ul ✔️ 
    - @m-rivera ✔️ 
    - @anilbey ✔️ 

2. Ideas and content
    - @mwoodbri ✔️

**Comment by sgibson91** [comment]
Also the following from PR #763:

- @JimMadge
- @annahadji
- @radka-j
- @nbarlowATI
- @evelinag
- @fedenanni

**Comment by malvikasharan** [comment]
@all-contributors please add @EstherPlomp for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @nathanbegbie for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @radka-j for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @nbarlowATI for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @evelinag for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @fedenanni for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @JimMadge for content.

**Comment by malvikasharan** [comment]
@all-contributors please add  @annahadji  for content.

**Comment by malvikasharan** [comment]
@all-contributors please add  @radka-j  for content.

**Comment by malvikasharan** [comment]
@all-contributors please add  @nbarlowATI  for content.

**Comment by malvikasharan** [comment]
@all-contributors please add  @evelinag  for content.

**Comment by malvikasharan** [comment]
@all-contributors please add  @fedenanni  for content.

**Comment by KirstieJane** [comment]
@all-contributors please add @EstherPlomp for bug fix!

**Comment by LouiseABowler** [comment]
Let's carry on adding!

@all-contributors please add @kir0ul for bug report!

**Comment by LouiseABowler** [comment]
@all-contributors please add @kir0ul for bug report!

**Comment by LouiseABowler** [comment]
@all-contributors please add @m-rivera for bug fixes!

**Comment by malvikasharan** [comment]
@all-contributors please add @annahadji as a contributor for content.

**Comment by KirstieJane** [comment]
@all-contributors please add @annahadji as a contributor for content.

**Comment by KirstieJane** [comment]
@all-contributors please add @kir0ul for bug report!

**Comment by sgibson91** [comment]
@all-contributors please add @anilbey for bug

**Comment by sgibson91** [comment]
@all-contributors please add @anilbey for bug

**Comment by sgibson91** [comment]
@all-contributors please add @mwoodbri for ideas, content
