### ISSUE TITLE
Design an "I want to contribute!" badge for the readme

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#818]
### Summary

I found this "I want to contribute!" button on the BinderHub readme. It links to the contributing guidelines and I think it's a cool way of directing people to the relevant information to getting started.

<img width="766" alt="I want to contribute button in BinderHub readme" src="https://user-images.githubusercontent.com/44771837/73948107-74f84500-48f0-11ea-8300-8668be13ce13.png">

### What needs to be done?

- [ ] Design a _Turing Way_ version

### Who can help?

* Anyone

---

**Comment by erictleung** [comment]
A quick creation 😄 

**Raw:**

```
[![](https://img.shields.io/static/v1?label=TuringWay&message=I%20want%20to%20contribute!&color=green)](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md)
```

**Rendered:**

[![](https://img.shields.io/static/v1?label=TuringWay&message=I%20want%20to%20contribute!&color=green)](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md)

Things to decide on:

- Label (currently it says `TuringWay`)
- Color (currently green)
- Link (currently https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md)

Possible colors:

![image](https://user-images.githubusercontent.com/2754821/74053961-dde3c980-4991-11ea-8079-1d875faa3ce1.png)

**Comment by sgibson91** [comment]
This looks fantastic, thank you! 🎉🙏🏻 I think we'll be getting a logo/favicon made up soon which would look great on this!

**Comment by erictleung** [comment]
@sgibson91 great! Once the logo is created, we can follow [these instructions](https://stackoverflow.com/a/41472017/6873133) to add it to the badge.

**Comment by sgibson91** [comment]
Hi @erictleung 👋 We now have a logo! Actually three versions! They're available in this Zenodo repo: https://zenodo.org/record/3695300#.Xmd4LZP7TOQ

I think we should go with `LogoNoDetailNoText.jpg` since this will be really small 😄

**Comment by erictleung** [comment]
@sgibson91 great!

So I've tried taking the `LogoNoDetailNoText.jpg` file and went through the steps to convert it. But I'm having troubles getting it to work.

As you suggested, the badge will be small. So I've had to do a lot of hacky ways of resizing the image and compressing it to no avail.

Whoever made these, is it possible to create a smaller version? I think these could be nice examples to go off of https://github.com/badges/shields/tree/master/logo. I think a logo of around 40x40 px would be best.

I saw on Zenodo that there is a zip file with SVG files. I thought I could take that and just resize it, but I don't think my graphics skills are good enough to do that.

Hope that all makes sense. If that is too much work, I can always go ahead and create the badge without a logo for now.

**Comment by KirstieJane** [comment]
Hi @erictleung! Thank you for working on this!

I used https://favicon.io/favicon-converter to convert the image into a bunch of different smaller versions. Would you mind experimenting with them to see which works well?! I think the favicon-32x32 should be good although its very small, so maybe the `apple-touch-icon` would be better? I've attached the others zipped together in case you want to play around 👾 

`favicon-32x32` 👉  ![favicon-32x32](https://user-images.githubusercontent.com/3626306/76856469-40f73480-684b-11ea-8052-bd940d0ee039.png)
`apple-touch-icon` 👉![apple-touch-icon](https://user-images.githubusercontent.com/3626306/76856646-92072880-684b-11ea-928f-4d47b169eb44.png)


all the favicons zipped together 👉 [favicon_io.zip](https://github.com/alan-turing-institute/the-turing-way/files/4343434/favicon_io.zip)

**Comment by erictleung** [comment]
@KirstieJane thanks! That helped a lot. 

[![](https://img.shields.io/static/v1?label=TuringWay&message=I%20want%20to%20contribute!&color=blueviolet&logo=data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8%2F9hAAACYklEQVQ4jXXTy09TQRTH8f5VPhI1xoVxYURNAFcmRleaGDdGXQlKAYkLUARNfICoScGKpTyE3t5bkKD2AUQepUXB0gcgLTalD9rema8LKRVrT3I2k%2Fl95kwyY6BMfQiFqHaoVDlUBoJBZJl9hn8XRsIhqh0abd55tnWdrBA8WfBSpakMhUqhXUCJhKl2aLR65%2FEtLeGc%2BYoy5aHf46bX7cThctK%2BAw2HQkVAW41wzqHRMjNNRteR%2BQzGjg5udZtQ47FiO50gdLZ1nVbvPNUOFSUSxnB4sJ%2F0TjCTTjHk%2BoJl%2BRtqPEaL6zMH79Rw0dyDVVURqRgyn0EkN8jkshwZGsBQodgQyQ2kyDPsce859drjdqLRKE0D%2FZhHR5F6DpHc2B3%2FjF3BcFqxARIpBXXmt9ii67vAYDhIr8fNx0UfE3OzzC0sIHIpxNYqSPEHqFBsiFQMkU3h8vs5%2FvABTeNje6BCj%2FxcwzLlIZHYROq5v4EoIr2JyCbJ57Kobjd3u7o41v4I68pyCfTGrhSvUKHYAJD5bcTWGjKbJJdO4A8E6JyexP4rWgK8Vkb2AjK7hcxnmZybxfF9kff%2BhZJQofvXwhg7O4vAfU2l79ME79xOrjY3c9ZYVzZs8nvZf6%2BRQCRCTgiODg1iCK6vc6WtjZM1tzlRW8sNa99%2Fx64fH%2BNAQz0un49nfh%2BVmspAcKX4lKWUbMbjXOg2cf3Vy%2BLIoRWqekxc7nhB6%2FQ0lZqKJRBAyjKfKZFIcKixgVPPn3LTamFfUyPne7qp1Oz0Bn4g5d7vVAIUamJ2FqPZzCW7gvlHabBQvwE2XnlAiFRrOwAAAABJRU5ErkJggg%3D%3D)](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md)
