### ISSUE TITLE
Collect items for March newsletter

### ISSUE THREAD

**Issue by KirstieJane** [alan-turing-institute/the-turing-way#832]
### Summary

Here's an issue to capture content for the March newsletter.

### What needs to be done?

- [ ] Add any content that you'd like to include!

### Who can help?

* Anyone! Promote your content!

---

### Updates

No updates so far

**Comment by pherterich** [comment]
Happy to write something to promote the hidden REF

**Comment by malvikasharan** [comment]
@pherterich Do you have a few lines for the hidden REF?

**Comment by pherterich** [comment]
Sorry, saw this too late @malvikasharan - ping me again for the April edition please ❤️
