### ISSUE TITLE
New chapter idea: research compendia

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#834]
## Detailed description
 * This issue is a place to discuss matters relating to the writing of the chapter on _reasearch_compendia_.
 * This chapter is being written in #840 

https://research-compendium.science

A research compendium accompanies, enhances, or is a scientific publication providing data, code, and documentation for reproducing a scientific workflow.

A research compendium enables reproducible research by packaging data, software, and documentation of a scientific analysis.

### Resources

https://research-compendium.science and the linkst / papers listed there.

## Current status
This chapter is empty. If anyone would like to make a start they are more than welcome to do so.

 - [x] Write chapter outline
 - [x] Add material to the chapter
 - [x] Combine materials into a readable chapter
 - [ ] Proofread
 - [ ] Request reviews
 - [ ] Address reviews
 - [ ] Merge to master branch.

## Updates

Pull request #840

**Comment by bvreede** [comment]
I want to second this proposal & have various ideas on this :)

One thing I have noticed is the wide variety of research compendium setups available, and one thing I always teach is to keep the basics in mind: to separate folders into **read only**, **human generated**, and **project generated** (see also [this slide](https://utrechtuniversity.github.io/workshop-computational-reproducibility/slides/slides_project-setup.html#2)).

**Comment by HeidiSeibold** [comment]
I tried my best to incorporate your idea @bvreede. See c15d87e07ffbbeb9224e06cde5c3a78ac8e1af01

Looking forward to discussing this with you! :tada:
