### ISSUE TITLE
Mention FAIR data principles in open research / open data

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#835]
### Summary

*I think it would make sense to mention the FAIR principles in the open data section.*
https://www.go-fair.org/fair-principles/

### What needs to be done?

- [ ] Add text on FAIR principles to open data section in open research chapter
- [ ] Optional: Add visualisation on FAIR principles to open data section in open research chapter

### Who can help?

* Anyone who knows how to contribute to a chapter

---

### Updates

*Pull request #837 *

**Comment by KirstieJane** [comment]
Thanks @HeidiSeibold!! The FAIR principles already exist in the research data management section - so can we incorporate a link to that section to make sure we aren't duplicating material too much? https://the-turing-way.netlify.com/rdm/rdm.html#the-fair-principles-and-practices

We have lots of visualisations of FAIR and it would be great to incorproate one of them in the open data chapter (and maybe in the RDM chapter!) 🚀 https://doi.org/10.5281/zenodo.3332807

**Comment by HeidiSeibold** [comment]
Ok I created a PR #837 to add links from open data to rdm chapter.
