### ISSUE TITLE
Image idea for research compendium (or collection of research parts)

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#841]
### Summary

An image of a box with all the components of a research project in it: data, code, text, questionnaires, ...

### What needs to be done?

- [x] *Draw image.*
- [x] *Prepare image for online publication.*
- [ ] *Include image in chapter "research compendium". (see PR #840)*
- [ ] *Create pull request.*

### Who can help?

* Anyone who can draw

---

### Updates

*Might make sense to wait for pull request #840 to be accepted first.*

**Comment by HeidiSeibold** [comment]
I discussed this idea with Sam :tada:

**Comment by malvikasharan** [comment]
Love the draft of illustration. I have checked the first two task from your list.
