### ISSUE TITLE
Migrate Continuous Integration tests from Travis to GitHub Actions

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#842]
### Summary

I believe that The Turing Way repo will benefit in terms of accessibility by having some of its CI tests moved to GitHub Actions from Travis. Here's my reasoning:

- The logs from GitHub Actions are located within the GitHub repo - see the "Actions" tab at the top of the page, or the "Checks" tab at the top of any PR. This means that you don't have to navigate away from GitHub to check on the status of the tests and everything is self-contained within the repo.
- Similarly the logs are also split up on a per Action basis, so you don't need to read the full output of all the tests in order to workout what went wrong - you can just focus on the single test that failed.
- Each GitHub Action has it's own YAML file which will reside in the `.github/workflows/` folder. This means that anyone who would like to contribute a new test only needs to create a new YAML file and does not need to worry about interacting with anyone else's code or test environments (Perfect for first time contributors!).

To be clear, I'm not proposing that we move the netlify build from Travis

### What needs to be done?

- [ ] Migrate the following tests to GitHub Actions:
  - `lorem-ipsum.py`
  - `no-bad-latin.py`
  - `test-file-size.sh`
  - prettier (This one may be trickier as it is allowed to fail)
- [ ] Rename `scripts` folder to `tests`?

### Who can help?

* Me! I will tackle this at the Book Dash on Friday 21st Feb 2020

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by sgibson91** [comment]
Hey @trallard 👋 Do you know if GitHub Actions has an "allowed to fail" option like we currently use in the [Travis file](https://github.com/alan-turing-institute/the-turing-way/blob/master/.travis.yml)?

**Comment by alexwlchan** [comment]
@sgibson91 Possibly https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error?

(I haven't tried it, but it sounds like it offers something similar.)

**Comment by sgibson91** [comment]
Hi @alexwlchan! Yes, I had looked into that. I think the problem with this flag is that it forces the UI to look like it's passed, as opposed to failing but that's ok. https://github.community/t5/GitHub-Actions/continue-on-error-allow-failure-UI-indication/td-p/37033

**Comment by alexwlchan** [comment]
Yes, makes sense. Alas!

The old "neutral" exit code was a bit closer to what you wanted, I guess? It would appear as different in the UI, but not fail all the build. If memory serves, that was exit code 78 in the early betas, but I don't think it's supported right now.

**Comment by sgibson91** [comment]
I think what I explicitly want is the branch protection rules on the repo to only apply to some Actions and not others. So for example, I have an action workflow as follows:

```
.github/workflows/
|- prettier.yml
|- check-file-size.yml
|- no-bad-latin.yml
```

If `check-file-size.yml` and `no-bad-latin.yml` fail, then that should block the merge of the PR. But if `prettier.yml` fails - that's cool, we're not strict about that, go ahead and merge!

**Comment by sgibson91** [comment]
I solved the problem!! 🎉 

<img width="716" alt="Screenshot 2020-02-21 at 10 34 24" src="https://user-images.githubusercontent.com/44771837/75027004-c7f7fd80-5495-11ea-8b17-6d2f46411950.png">

**Comment by trallard** [comment]
Sorry I completely missed this yesterday! Glad this is working now
