### ISSUE TITLE
A button to switch between languages

### ISSUE THREAD

**Issue by tonyyzy** [alan-turing-institute/the-turing-way#855]
### Summary

Now we have links to different language versions of the book, we need a switch button on the page so users can select a different language.

The language previews are here (note that no translations are done yet):
English: https://competent-nightingale-4c1d36.netlify.com/introduction/introduction
Chinese: https://competent-nightingale-4c1d36.netlify.com/zh_cn/introduction/introduction
Spanish: https://competent-nightingale-4c1d36.netlify.com/es/introduction/introduction

### What needs to be done?

- [ ] Add a button to the page
- [ ] ideally, the tool is set up to read from `book/content/po/LINGUAS` so we don't need to change it when new languages are added.

### Who can help?

People happy to work on front-end and look into Jekyll, potentially Liquid template language.

---

**Comment by da5nsy** [comment]
Proposing the rolling of this into https://github.com/alan-turing-institute/the-turing-way/issues/3255 since this is a key component of it, but it requires broader infrastructure.
