### ISSUE TITLE
[WIP] Celebration Bot! Auto-comment on PRs opened by first-time contributors to thank them

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#860]
### Summary

Add a GitHub Action to the repository that automatically comments on Pull Requests opened by new/first-time contributors congratulating them and welcoming them to the project.

### What needs to be done?

- [ ] Write the relevant GitHub Action

### Who can help?

* @nathanbegbie 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by nathanbegbie** [comment]
I was also thinking that bots are great, but humans are even better! Maybe as an enhancement, we have a reminder to a channel in Gitter or something to be like 
> hey!, there's someone who just pushed their first PR - say congrats! [http://github.com/foo/bar/pull/11111](#)

**Comment by sgibson91** [comment]
Or tweets?!

**Comment by sgibson91** [comment]
Hey @nathanbegbie, I don't know what you used to develop the celebration bot at the book dash, but I just found this and thought it might be useful: https://github.com/Deborah-Digges/pr-bot

**Comment by nathanbegbie** [comment]
Hey @sgibson91 ! That's super useful :) thanks, could probs just use that instead of a Github action 😄
