### ISSUE TITLE
Adding additional content from Open Research and Research Data Management to Credit chapter

### ISSUE THREAD

**Issue by FrancesMadden** [alan-turing-institute/the-turing-way#885]
### Summary

A lot of the information about gaining credit for sharing data is in the Open Research and Research Data Management chapters. There isn't much mention of citing and gaining credit for software in there and I want to move them all to the credit chapter.

Related to https://github.com/alan-turing-institute/the-turing-way/issues/879
https://github.com/alan-turing-institute/the-turing-way/issues/884

### What needs to be done?

- [ ] Review content of Open Data chapter
- [ ] Review content of research data management chapter
- [ ] Edit and migrate content to credit chapter
- [ ] Update links to credit chapter in Open Data and Research Data management
- [ ] Add links to credit chapter in Open Source software and new documentation chapter

### Who can help?

* Frances Madden
* Esther Plomp
* Reviewers - make sure this isn't a terrible mistake!

---

### Updates

None yet

**Comment by jspickering** [comment]
I was just about to tidy up the "Elements of an open source hardware project" part of this and update the contents page of the Open Research section. I'll update the section I was going to work on and hold off on updating the contents until you've moved things around?
