### ISSUE TITLE
all-contributors bot deletes other badges

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/the-turing-way#892]
### Summary

In recent PRs (e.g. #869), the all-contributors bot has tried to delete other labels from the top of the README.md file, such as CI status. The formatting has also changed - the label is square, rather than rounded to match other labels.

### What needs to be done?

- [x] Edit `README.md` to move the bot's edit markers.
- [x] Transfer any other custom properties from the old version of `.all-contributorsrc` to the current version of the file.
- [x] Make sure that these changes are carried through as we add new contributors today.

### Who can help?

- I should be okay on this one, but thank you @KirstieJane for offering to give me a hand if needed! ✨ 

---

### Updates

Now onto testing that the formatting is retained when we add new contributors using the bot.

**Comment by LouiseABowler** [comment]
Turns out #893 didn't quite close the issue - adding contributors via the bot doesn't always retain the formatting.

**Comment by sgibson91** [comment]
After lots of adding today, seems that the badge number and formatting of the table is being retained now. Unless I'm missing something?

**Comment by LouiseABowler** [comment]
No, you're right - it is fixed now. There was a follow-up to #893 in #905 which solved the problem (that was when we moved the badge to the end of the list) but I forgot to reference the PR here in the busy end of the book dash!

If all's been working well for you, that ticks the final checkbox at the top of this issue and then we're good to close. (I'll do that now as I'm here, but feel free to reopen if you notice anything else.)
