### ISSUE TITLE
Fix overlap between two similar sections in different chapters ("barriers to data sharing")

### ISSUE THREAD

**Issue by jspickering** [alan-turing-institute/the-turing-way#895]
### Summary

There are two sections titled "Barriers to data sharing" which could be combined into one as they discuss very similar points
* Chapter 3. Open Research (https://the-turing-way.netlify.com/open_research/01/opendata.html#barriers-to-data-sharing)
* Chapter 7. Research Data Management (https://the-turing-way.netlify.com/rdm/rdm.html#barriers-to-data-sharing)

### What needs to be done?

- [ ] Decide which chapter of the book this part best belongs to (they're currently in chapters 3 and 7)
- [ ] Combine the two sections into one
- [ ] Proofreading

### Who can help?

- [ ] Anyone

---

### Updates

None yet

**Comment by malvikasharan** [comment]
@jspickering Thank you for raising this. It totally makes sense to have the "Barriers" as a separate chapter and explain barriers associated with different components of research clearly. This can then linked to the chapters that you mentioned.

**Comment by KirstieJane** [comment]
I’m not sure I agree that barriers should be a different chapter - I think it makes sense to have it be a section in research data management and then link to that section from the open data section of open research. Where would the separate chapter go?

**Comment by jspickering** [comment]
Yeah I think I agree with @KirstieJane rather than having it as a new chapter. It could also be worth linking to the newly created Ethics chapter too.

**Comment by EstherPlomp** [comment]
I think it would make most sense to put it under open research, as that is where the barrier lies: do you want to open it up or not? 

I would then rename the barriers for sharing of personal/confidential data to something like 'management' of that data, as it is not only the non-sharing part where the concerns are: these types of data should be managed differently from the start of the project on compared to data that can eventually be shared. Things such as access management are already an issue during the project, if that makes sense. 

I would then propose to move the whole section about sharing data openly to the 'Open Data' section, and there illustrate the steps you can take if you have personal/confidential data, as well as the regular steps that you take when you are able to share your data. 

Repeating myself from issue #909: From my viewpoint Open Data and RDM are not that much overlapping in the sense that you can do data management without opening up your data. If we keep those topics separate, we could add some practical example of how to choose a repository, how to prepare your data, in the open data bit and then just refer to the Open Data section in the RDM chapter.

**Comment by malvikasharan** [comment]
@KirstieJane We could either have a chapter on barriers in reproducibility (at the end of the reproducibility book) where we discuss it all together for different aspects of research or have barrier section in different chapters.

I don't have any strong opinion, I can see that the latter could be better for the readers. In that case then as suggested by you we can have a section in RDM, and as suggested by @EstherPlomp a section in Open Research, and as other chapters appear (i.e. barriers in collaboration, outreach, project plan etc.).
