### ISSUE TITLE
Co-authoring platforms

### ISSUE THREAD

**Issue by pherterich** [alan-turing-institute/the-turing-way#9]
Just putting down a list of options that we could use to write/display the final handbook with a few examples for discussion. This is just some brainstorming to start with, additions and comments on the options listed are welcome! 

- just GitHub like e.g. the [Mozilla Science primers](https://github.com/mozillascience/open-data-primers); might require a separate repository
- GoogleDocs and Gitbooks like the [Foster Open Science Training handbook](https://open-science-training-handbook.gitbook.io/book/): they started the document as a 3 day book sprint on Google, opened it up for a wide audience for review there (GoogleDocs provides a low barrier and thus, a fairly wide range of people commented on the initial draft); once comments were included they moved it to Gitbook (which charges for a larger group of collaborators...)
- there are platforms like authorea, overleaf etc. that can all be integrated with git/GitHub if wanted, but having to interact with yet another platform/service might be too much of a barrier 

Will some audiences prefer more traditional formats for the end product? PDFs for the checklists for example?
- https://www.mkdocs.org/ can do PDF export with some magic?

**Comment by rosiehigman** [comment]
I'm on a call about a different project and someone mentioned this platform which might be an option: https://www.fiduswriter.org/

**Comment by pherterich** [comment]
Closing this as we went with JupyterBooks in the end. If we need standalone PDFs or something, we can cover that in a fresh issue.
