### ISSUE TITLE
UKRI Cloud Computing Workshop

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#91]
@KirstieJane Would this be relevant to the BinderHub?

[https://www.eventbrite.co.uk/e/ukri-cloud-workshop-tickets-53580893896](https://www.eventbrite.co.uk/e/ukri-cloud-workshop-tickets-53580893896)

---

Just adding a couple of bullet points for easy navigation 😸 

* What: UKRI Cloud Workshop
* When: 12 February

---
## Update: Abstract submitted

Word limit was 200, not 250, so I edited to the following:
> We aim to support the research across all fields using cloud computing to provide reproducible, reliable, reusable analyses. We plan to achieve this through capturing computing environments without installation, facilitating access to advanced resources and handling private repositories.

> Binder/BinderHub is a cloud platform that captures the computing environment of a Git repository within a Docker image. It provides an interactive browser where code can be executed in the developer's environment without requiring installation. BinderHubs can be built and hosted anywhere in minimal installation time. Building a locally hosted BinderHub is advantageous for using private repositories and accessing a greater variety of computing resources.

> By harnessing cloud computing and a BinderHub with expanded capabilities, scientific analyses can become more accessible and transparent to the wider community. We can improve reproducibility by making it easy to showcase and re-run analyses, improve reliability by making it easy to review analyses and catch bugs early in the development process without installation, and improve the reusability of the code by capturing the computing environment.

[HackMD link for demo skeleton](https://hackmd.io/bbNuN-_-S_2NWxER7BVzYg)

**Comment by sgibson91** [comment]
@KirstieJane Please see updated issue ☝️☝️☝️

**Comment by KirstieJane** [comment]
Thanks @sgibson91 - looks great. No problem about the shorter word count 😸 

I wonder if it makes sense to add in a few of the other check boxes to the abstract file? I'm thinking that it would be difficult for someone who was reading files in the repository to know exactly what you're going to do without that additional informaiton.

What do you think?

**Comment by sgibson91** [comment]
Closing ✨
