### ISSUE TITLE
Have only one place for templates

### ISSUE THREAD

**Issue by HeidiSeibold** [alan-turing-institute/the-turing-way#914]
### Summary

There are currently two places where content templates are stored:

- `/book/templates`
- `/templates`

I think it would be better if they were both in the same space.

### What needs to be done?

- [ ] Decide where templates should live
- [ ] Move all templates to a single space
- [ ] Mention where templates are stored in `CONTRIBUTING.md`

### Who can help?

* Anyone

---

### Updates

Non yet.

**Comment by EstherPlomp** [comment]
It looks like this has been resolved in the meantime, so I'll close this issue now. Thanks @HeidiSeibold !
