### ISSUE TITLE
Minor bugs in Travis/Netlify book build

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#921]
### Summary

We have just completed a _huge_ upgrade to the book which brings it up to date with the current version of Jupyter Book in #844. This is now successfully deploying.

I did spot a couple of warnings in the Travis output to do with versions. These are not critical (tests still pass 🎉) but they should probably be addressed at some point. The bugs are as follows:

- `You are using pip version 10.0.1, however version 20.0.2 is available.` For some reason, we're getting a really old version of pip, in spite of this line https://github.com/alan-turing-institute/the-turing-way/blob/be82a3e963482a0de4ee7d3bd9f77ca12eccba68/.travis.yml#L11
- `Warning: the running version of Bundler (1.16.2) is older than the version that created the lockfile (1.17.2). We suggest you upgrade to the latest version of Bundler by running 'gem install bundler'.` Need to upgrade bundler that Travis uses.

Don't feel pressured into thinking that you need to solve both of these bugs and close the issue all at once! If you're comfortable bumping pip but not bundler (or vice versa), that's totally fine! Just update this issue with the progress you've made and the Pull Request number 🌟 

### What needs to be done?

- [ ] Upgrade pip on Travis
- [ ] Upgrade bundler on Travis (optional)

### Who can help?

* Anyone comfortable with any of these tools!

---

### Updates

 **2020-05-12:** The Jupyter Book will be upgraded to the new beta version in PR #1073. The beta version uses Sphinx instead of Jekyll and so the bundler dependency will no longer be required.

**Comment by growupboron** [comment]
@sgibson91 I would like work on this.

**Comment by malvikasharan** [comment]
Hi @growupboron, this issue will be on hold for a while as we are upgrading our Jupyter Book. I would recommend you work on issues that would better demo your technical writing skills.

**Comment by growupboron** [comment]
> Hi @growupboron, this issue will be on hold for a while as we are upgrading our Jupyter Book. I would recommend you work on issues that would better demo your technical writing skills.

Thanks for the Input, I am looking into it.

**Comment by sgibson91** [comment]
@martinagvilas @malvikasharan Has this issue been fixed by the upgrade?

**Comment by martinagvilas** [comment]
@sgibson91 I think it has 🚀 There is like a thousand more warning inside the build now though, but I'm pretty sure they are different
