### ISSUE TITLE
Develop guide for hosting collaboration cafe

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#925]
### Summary

We invite people in different time zones to host a separate collaboration cafe, but there is no handbook for that. 

### What needs to be done?

- [ ] Add a how-to guide for hosting collaboration cafe in the project management section
- [ ] Link YouTube video and link to the past call notes

### Who can help?

* Kirstie
* Anyone who has previously attended one call

**Comment by EstherPlomp** [comment]
It looks like this is covered in [Online Collaboration Cafe](https://the-turing-way.netlify.app/community-handbook/coworking/coworking-collabcafe.html) so I'll close this issue for now. Please re-open if it doesn't cover things!
