### ISSUE TITLE
Remote collaboration: Establishing protocols

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#943]
### Summary 

* Protocols (rules, agenda, tools, format etc.) are the most important way to ensure that remote collaborations are successful. Here is a summary of the main aspects of this point.

### What needs to be done?

- [ ] Collact ideas
- [ ] Create bullet points
- [ ] Add a short descriptive list in Turing way

### Who can help?

Team members named below

**Comment by watson-c** [comment]
**Summary**
The main idea is to set a clear protocol at the beginning of study to set guidelines for the collaborative working arrangement around expectations on communication, timelines and tasks.

**What needs to be done?**
*  Establish key tasks and milestones at beginning of project to determine frequency of meetings - split between sub project groups and whole team
    *  By having regular meetings it should reduce loneliness and exclusion from the project while keeping motivation high
*  Consider having a regular timeslot for meetings and be sure to send out calendar invites.
*  Meetings will have clear pre defined agenda with an allocated chair and note taker to prevent informality and loss of focus.
* Establish format of communication within whole group and subgroups, e.g. Zoom, Google Docs, Trello.
* Decide on the most appropriate way to share: data, documents, analysis scripts. Consider shared drives and Dropboxes, GitHub etc. 
* Once a protocol has been established, circulate and review within the team to ensure a common understanding of tasks and goals.

**Who can help?**
Everyone in the team can help with this at the beginning of a project, to ensure everyone is happy and understands what is expected

Authors: Rose Sisk, Sian Bladon, Helen Brierley, Alexia Sampri, Marilena Pagoni & Charlotte Watson

**Comment by malvikasharan** [comment]
Norms for online meeting can be added here.

**Comment by malvikasharan** [comment]
Added in a subchapter in PR #1566
