### ISSUE TITLE
Remote collaboration: Pros and Cons

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#944]
### Summary

* Pros and cons of working remotely or in a distributed environment

### What needs to be done?

- [x] Brainstorm ideas
- [x]  Summary from the discussion

**Pros and Cons (can be transferred under different topics**

==Pros==
* Positive impact on the environment by reducing travel related co2 emissions
* Will work well equally for low resource environment as the cost will be reduced by not having to deal with on site expense
* May lead to innovative way to establish social interactions and social dynamics in general
* Will help us learn about more colleagues from different parts of the world and make us more educated about our cultural differences and how to accommodate in our work environment
* Will make it convenient to have decision making by making sure that every stakeholders will be present, given the meeting is done in a mutually convenient time

==Cons==
* Developing camaraderie - as we are used to doing that in person relationships 
* Separating working hours from life (may blur lines)
* Allocated time might not be enough for arriving to a conclusion and may sometime lead to misinterpretation of decisions made by the team
* Conflict resolution maybe difficult if most interactions happen in an allocated time slot
* Will lack human interactions, i.e body language, and may lose water-cooler-effect and innovative ideas that results in by not having chanced interactions
* May lead to having distractions that can make it difficult for some people to focus and have disciplined work practices
* People will have different working condition, i.e. access to hardware, that can lead to wrong assumptions regarding replication of certain task

### Who can help?

* Anyone who have worked remotely
* Anyone who would want to work remotely
* Anyone with an insight on team working and dynamics

**Comment by PabRod** [comment]
As someone who used to commute **4 hours** per day for 12 years, I have an important _Pro_ to add:

- Remote collaboration **dramatically** improves the life quality of those who cannot afford to live close to their office. In two words: reduces inequality.

**Comment by adswa** [comment]
One aspect to add to keep in mind (quite specific, but I got this from a talk on data feminism at Fosdem 2020 and had never thought of it before):

- certain web-based services are not available in certain countries, for example, GitHub is still banned in Iran and Syria if I am not mistaken, so choice of distributed service could lead to exclusion

**Comment by malvikasharan** [comment]
@PabRod I added your inputs and a quote: 
![image](https://user-images.githubusercontent.com/5370471/77316240-e81f1480-6d00-11ea-821d-f8e23c1e3fe3.png)

@adswa: Thank you for pointing that. We are discussing that in this issue #939, and I will make sure that your example is added there. 🙌

**Comment by malvikasharan** [comment]
Added in a subchapter in the PR #1566
