### ISSUE TITLE
The new version of Jupyter-book is not screen size aware

### ISSUE THREAD

**Issue by tonyyzy** [alan-turing-institute/the-turing-way#946]
### Summary

The site generated by the new version of Jupyter-book is not screen size aware. People with a large screen will suffer xD

Currently:
![Screenshot 2020-03-12 at 16 46 06](https://user-images.githubusercontent.com/38984697/76546381-49cebb80-6483-11ea-8c42-7864e9232d60.png)
*The content is no longer centered*

Before:
![Screenshot 2020-03-12 at 17 04 19](https://user-images.githubusercontent.com/38984697/76546506-8a2e3980-6483-11ea-8777-bb6dd9303273.png)

### What needs to be done?

- [ ] Which part of the jekyll template is no longer screen size aware? css?
- [ ] Fix it!

### Who can help?

@sgibson91 @martinagvilas @choldgraf 

---

**Comment by choldgraf** [comment]
Yeah this has always been a pain to figure out. We are working on a re-write of the backend of Jupyter Book, and I'm hoping these centering issues will be worked out then. Check out progress here: beta.jupyterbook.org, and if you wanna help out then I am more than happy to help show folks around the codebases etc!

**Comment by tonyyzy** [comment]
Ah I didn't realise it's a known issue. Good to know the team's working on it!

**Comment by malvikasharan** [comment]
We have integrated that in our style guide, and aiming to integrate that in our (~100) subchapters through community contribution. Also, this issue and related PRs will ensure future consistencies. #1174.
