### ISSUE TITLE
Collect items for the April Newsletter

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#954]
### Summary

Here's an issue to capture content for the March newsletter.

### What needs to be done?

- [ ] Add any content that you'd like to include!

### Who can help?

* Anyone! Promote your content!

---

### Updates

No updates so far

**Comment by pherterich** [comment]
This is not super inspiring - feel free to adjust @malvikasharan :

The Hidden REF announces new categories

[The Hidden REF](https://hidden-ref.org/), an initiative to celebrate all research outputs and their contributors, just announced new categories under which outputs and people can be submitted. As a complement to the Research Excellence Framework (REF) exercise run in the UK, the Hidden REF will highlight outputs that are not selected or eligible for REF. Until the end of June, the research community can suggest and comment on categories for which submissions should be accepted. [Latest suggestions]9https://www.software.ac.uk/blog/2020-04-06-first-look-new-categories-hidden-ref) include training material such as the Turing Way resources or carpentry lessons, data and metadata standards, colleagues working in professional services and others.

To keep up to date with the Hidden REF, follow the initiative [on Twitter](https://twitter.com/HiddenRef).

**Comment by malvikasharan** [comment]
Here is the hackMD: https://hackmd.io/EunaGFlARk-DVUrL7vK-Qw?both
