### ISSUE TITLE
LIBER Conference submission

### ISSUE THREAD

**Issue by rosiehigman** [alan-turing-institute/the-turing-way#97]
- LIBER is a European conference for research librarians
- https://liberconference.eu/liber-2019-call-for-papers/ 
- Deadline is 14th January, conference is 26th-28th June, Dublin
- @pherterich and @rosiehigman are interested in submitting, possibly on experiences of this project as a new way for librarians to support Open Science/data science.
- HackMD for writing: https://hackmd.io/u05_5YeoQi6WZC1Qlh3skA

**Update**: submitted by PH on 14/01/2019
**Another update**: accepted on 06/03/2019

**Comment by pherterich** [comment]
@KirstieJane good question - I hope our institution would support this but if there is back up money available, I guess that would be helpful

**Comment by KirstieJane** [comment]
:+1: Have a think and let me know if you'd like me to ask for some 💖

**Comment by pherterich** [comment]
Will do, thanks. @rosiehigman any ideas for a snazzy title?

**Comment by rosiehigman** [comment]
I've added a title, not sure if it's snazzy! I've made a couple of small edits but otherwise happy for this to go in on Monday

**Comment by pherterich** [comment]
Amazing, thank you @rosiehigman and @KirstieJane 
Will investigate the conference submission system tomorrow and ping you if that requires anything else weird so we're good to go on Monday :smile:

**Comment by pherterich** [comment]
Anyone knows how to hack ConfTool to get a group author in there? I'm trying to add the project but the best I can manage at the moment is adding it to @rosiehigman or my last names or creating a made up person that covers it somehow (which would need an email address and an affiliation, so I'm not sure I'll get through with it) ... :disappointed:

**Comment by rosiehigman** [comment]
I don't I'm afraid, I'll sign up and have a look around this afternoon

**Comment by rosiehigman** [comment]
Just making a note of this which might be useful for this: Chassanoff, A., AlNoamany, Y., Thornton, K. and Borghi, J., 2018. Software Curation in Research Libraries: Practice and Promise. Journal of Librarianship and Scholarly Communication, 6(1), p.eP2239. DOI: http://doi.org/10.7710/2162-3309.2239

**Comment by pherterich** [comment]
@KirstieJane I made the Turing Way a "person" with your email address to hack the system, so you might get update emails to the submission. I hope that's not too bad

**Comment by KirstieJane** [comment]
Please could someone add this application to the [conferences/abstracts](https://github.com/alan-turing-institute/the-turing-way/tree/master/conferences/abstracts) folder? Thank you!

**Comment by rosiehigman** [comment]
I think I will need some support as well if that's possible @KirstieJane?

**Comment by rainsworth** [comment]
Hi @rosiehigman & @pherterich - congrats on acceptance! 🎉  Can we close this issue now or do you want to keep it open for coordinating?

**Comment by pherterich** [comment]
Happy to close it, I have the feeling that @rosiehigman and me will do most of the coordination on gitter and slack and then just add the final slides to the conferences folder.

**Comment by rosiehigman** [comment]
Agreed, I'll close this now
