### ISSUE TITLE
[BUG] Jupyter Book doesn't cope well with repeated section headers

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#972]
### Summary

I've noticed that when section headers are repeated within a chapter, the Jupyter Book can't separate them.

<img width="1280" alt="repeated_section_headings" src="https://user-images.githubusercontent.com/44771837/77151667-56a86c00-6a8e-11ea-945e-b8115e27b8ec.png">

### What needs to be done?

- [ ] Come up with a process for preventing clashes like this
- [ ] This may be something that will be fixed in the current upgrade of Jupyter Book backend?

### Who can help?

* @choldgraf 

---

**Comment by choldgraf** [comment]
whoah! that is bizarre and kind of cool but in a very helpful way haha.

FWIW, I just tried this out on the new build system, and it should be fixed there :-)  (beta.jupyterbook.org)

**Comment by sgibson91** [comment]
Fantastic, thanks @choldgraf !

**Comment by sgibson91** [comment]
I think this has been fixed by the upgrade to beta 🎉
