### ISSUE TITLE
Chapter titles are duplicated

### ISSUE THREAD

**Issue by sgibson91** [alan-turing-institute/the-turing-way#973]
### Summary

Chapter titles are currently duplicated on the website.

<img width="1280" alt="duplicated_titles" src="https://user-images.githubusercontent.com/44771837/77152058-109fd800-6a8f-11ea-864a-1fa997e1e8ea.png">

I think this is caused by us requiring a chapter title in our [chapter template](https://github.com/alan-turing-institute/the-turing-way/blob/master/templates/CHAPTER_TEMPLATE.md#chapter-title) and also asking for a title in our TOC file: https://github.com/alan-turing-institute/the-turing-way/blob/74408747c41633607f0cb3a5ad6216df27429b12/book/website/_data/toc.yml#L60

### What needs to be done?

- [ ] Decide if this is a problem
- [ ] If it is a problem, edit the chapter template

### Who can help?

* Anyone!

---

**Comment by martinagvilas** [comment]
Hi! I mentioned this in #933  

In my opinion it would look better if we revert to old titles, what do you think?

**Comment by sgibson91** [comment]
Hi @martinagvilas! Sorry, that's on me for not doing a proper issue search before opening one.

I also agree with you that reverting to old titles would be better. I'll close this issue and mention it on yours 😄

**Comment by martinagvilas** [comment]
No problem! I'm glad someone noticed this issue and was bothered by it as well 🚀
