### ISSUE TITLE
all-contributors requests for the book dash, eScience center members, CW20 and more

### ISSUE THREAD

**Issue by malvikasharan** [alan-turing-institute/the-turing-way#992]
### Summary

* Contributors to add:
- [x] @mkuzak for bug, review, content
- [x] @c-martinez for bug, review content
- [x] @bouweandela for content
- [x] @PabRod for content
- [x] @sverhoeven for comtent
- [x] @eirini-zormpa for bug
- [x] @dblana for content
- [x] @orchid00 for review
- [x] @nlharris for review
- [x] @FrancesMadden for content
- [x] @chadsgilbert for bug
- [x] @sdruskat for content
- [x] @fmcooper for content
- [x] @JoannaLeng for content
- [x] @colinsauze for idea
- [x] @Chrisisour for idea
- [x] @kessonovitch for idea (content under prep)
- [x] @ArielleBL (content under prep)
- [x] @kdixey for idea (content under prep)
- [ ] @nalessandroni for idea (content under prep)
- [ ] @alexwlchan for idea (content under prep)
- [ ] @npch  for idea (content under prep)
- [ ] @trotts for idea (Newcastle)
- [ ] @vladoxNCL for idea (Newcastle)
- [ ] @ppintosilva for idea (Newcastle)
- [ ] @SedarOlmez94 for idea (Newcastle)
- [ ] @rosesisk for idea (Newcastle)
- [ ] @mednche for idea (Newcastle)
- [ ] @paulbaniqued for idea (Newcastle)
- [ ] @GeorgiaA for idea (Newcastle)
- [ ] @davehedgehog for idea (Newcastle)
- [ ] @annabelelizabethwhipp for idea (Newcastle)
- [ ] @sianbladon for idea (Newcastle)
- [ ] @watson-c for idea (Newcastle)
- [ ] @philipdarke for idea (Newcastle)

### What needs to be done?

- [ ] Call all-contributors bot
- [ ] Check is everyone has been added

### Who can help?

* all-contributors bot 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

**Comment by malvikasharan** [comment]
@all-contributors please add @mkuzak for bug fix!

**Comment by malvikasharan** [comment]
@all-contributors please add @mkuzak for review!

**Comment by malvikasharan** [comment]
@all-contributors please add @mkuzak for  content.

**Comment by malvikasharan** [comment]
@all-contributors please add @c-martinez for bug fix.

**Comment by malvikasharan** [comment]
@all-contributors please add @c-martinez for review.

**Comment by malvikasharan** [comment]
@all-contributors please add @c-martinez for content

**Comment by malvikasharan** [comment]
@all-contributors please add @bouweandela for content

**Comment by malvikasharan** [comment]
@all-contributors please add @PabRod for content.

**Comment by malvikasharan** [comment]
@all-contributors please add @sverhoeven  for content.

**Comment by malvikasharan** [comment]
@all-contributors please add @FrancesMadden for content.

**Comment by malvikasharan** [comment]
@all-contributors please add @nlharris for review in #971.

**Comment by malvikasharan** [comment]
@all-contributors please add @orchid00 for review in #971.

**Comment by malvikasharan** [comment]
@all-contributors please add @mkuzak for content.

**Comment by KirstieJane** [comment]
Just noting that I'm working on this now. Plan is to kinda bypass the bot and put in one pull request with all these folks 😄 

🤞 😬 🤞 I can tidy it all up 💖

**Comment by KirstieJane** [comment]
Hey @allcontributors! Please can you add @bouweandela for content

**Comment by KirstieJane** [comment]
Hey @all-contributors! Please can you add @bouweandela for content

**Comment by KirstieJane** [comment]
@all-contributors add @bouweandela for content

**Comment by KirstieJane** [comment]
@all-contributors add @bouweandela for content

**Comment by KirstieJane** [comment]
@all-contributors add @chadsgilbert for bug

**Comment by KirstieJane** [comment]
@all-contributors add @fmcooper for content

**Comment by KirstieJane** [comment]
@all-contributors please add @JoannaLeng for content

**Comment by KirstieJane** [comment]
@all-contributors please add @colinsauze for ideas

**Comment by KirstieJane** [comment]
@all-contributors please add @Chrisisour for idea

**Comment by KirstieJane** [comment]
@all-contributors please add @kessonovitch for ideas

**Comment by KirstieJane** [comment]
@all-contributors please add @ArielleBL for ideas

**Comment by KirstieJane** [comment]
@all-contributors please add @kdixey for ideas
